# 构建 src/data.js（仿 tools/build_events.py）
# 从 src/data/*.ev.js 读取模块 + MANIFEST.json（teams 顺序）组装出 src/data.js
import sys, os, json
sys.stdout.reconfigure(encoding='utf-8')
import esprima

BASE = r'D:\football\career-sim'
SRC_DIR = os.path.join(BASE, 'src', 'data')
OUT = os.path.join(BASE, 'src', 'data.js')
NL = chr(10)

manifest = json.load(open(os.path.join(SRC_DIR, 'MANIFEST.json'), encoding='utf-8'))
team_order = manifest['order']

def read(name):
    return open(os.path.join(SRC_DIR, name), encoding='utf-8').read().rstrip()

def var_decl(filename):
    return read(filename)

# 固定模块（a/b 保留原名，结局闭包引用 a）
modules = [var_decl('awards.ev.js'), var_decl('endings.ev.js'),
           var_decl('positions.ev.js'), var_decl('leagues.ev.js'),
           var_decl('config.ev.js')]

team_decls = []
for lg in team_order:
    team_decls.append(var_decl('teams_' + lg + '.ev.js'))
    # 校验文件里声明的变量名与联赛一致
    assert ('var TEAMS_%s =' % lg) in team_decls[-1], 'bad var in teams_%s' % lg

# TEAMS 用 concat 合并（保持 MANIFEST 联赛顺序）
concat = '[].concat(' + ','.join('TEAMS_' + lg for lg in team_order) + ')'

HEADER = NL.join([
    '// AUTO-GENERATED by tools/build_data.py from src/data/*.ev.js — 编辑 src/data/ 后运行该脚本重建，勿手改本文件',
    'function _dat_0a(){',
    '    return [];',
    '}',
    'function _dat_0b(x,x){',
    "    return '';",
    '}',
])

ENDING_VIEW = NL.join([
    "function(c,d){var f=c&&c[\"pos\"]&&c[\"pos\"][d];",
    "return{'id':c['id'],'tier':c[\"tier\"],'title':f&&f[\"title\"]||c[\"title\"],'desc':f&&f[\"desc\"]||c[\"desc\"]};",
    "}",
])

# DATA 顶层键顺序（与拆分前一致:endingView,POSITIONS,LEAGUES,TEAMS,TROPHIES,NATIONAL,AWARDS,ROLES,...）
cfg_keys = ['TROPHIES', 'NATIONAL']
cfg_keys2 = ['ROLES', 'ROLE_ORDER', 'YOUTH_ABROAD_FEE', 'INJURIES', 'GROWTH', 'VALUE_TABLE']
literal_parts = ["'endingView':" + ENDING_VIEW,
                 "'POSITIONS':positions",
                 "'LEAGUES':leagues",
                 "'TEAMS':" + concat]
for k in cfg_keys:
    literal_parts.append("'%s':config['%s']" % (k, k))
literal_parts.append("'AWARDS':a")
for k in cfg_keys2:
    literal_parts.append("'%s':config['%s']" % (k, k))
literal_parts.append("'ENDINGS':b")

body = NL.join(modules + team_decls + ['window["DATA"]={' + ','.join(literal_parts) + '};'])
built = NL.join([
    HEADER,
    "(0x0,!(function(){'use strict';",
    body,
    '}()));',
]) + NL

esprima.parseScript(built)
open(OUT, 'w', encoding='utf-8', newline='').write(built)
import re
print('built -> %s (%d chars)' % (OUT, len(built)))
print('teams order: %d leagues, %d team modules' % (len(team_order), len(team_decls)))
