# -*- coding: utf-8 -*-
# 从 src/data/teams_*.ev.js 生成青训营补丁 src/data/academy_patch.ev.js
# 规则：凡球队对象里没有 academy 字段的，全部补一个 "<队名>青训营"；
#       OVERRIDES 里的 id 用真实青训基地/别称（闻名的那一批）。
# 产物是 JS 对象 ACADEMY_PATCH（id -> 青训营名），由 build_data.py 合入 data.js，
# 加载时遍历 window.DATA.TEAMS 按 id 写入 academy。
import os, re, json, sys
sys.stdout.reconfigure(encoding='utf-8')

BASE = r'D:\football\career-sim'
SRC_DIR = os.path.join(BASE, 'src', 'data')
OUT = os.path.join(SRC_DIR, 'academy_patch.ev.js')

manifest = json.load(open(os.path.join(SRC_DIR, 'MANIFEST.json'), encoding='utf-8'))
team_order = manifest['order']

# 著名青训基地/别称覆盖（只对这些"有名"的用特色名，其余用 队名+青训营）
OVERRIDES = {
    'eve': '芬奇农场',          # Everton Finch Farm
    'whu': '西汉姆学院',        # West Ham "Academy of Football"
    'sou': '斯台普尔伍德',      # Southampton Staplewood
    'avl': '博德莫尔',          # Aston Villa Bodymoor Heath
    'rso': '苏比埃塔',          # Real Sociedad Zubieta
    'emp': '恩波利学院',        # Empoli 著名青训
    'ren': '雷恩青训学院',      # Rennes 法国著名青训大户
    'nts': '若内莱尔',          # Nantes La Jonelière
    'and': '安德莱赫特学院',    # Anderlecht
    'gnk': '亨克学院',          # Genk 著名青训
    's04': '沙尔克矿工学院',    # Schalke "Knappenschmiede"
    'poh': '浦项青训营',        # Pohang 韩国传奇青训
    'ksm': '鹿岛青训学院',      # Kashima
    'boc': '博卡青训营',        # Boca Juniors
    'riv': '河床青训营',        # River Plate
    'fla': '弗拉门戈青训营',    # Flamengo Ninho do Urubu
    'sant': '桑托斯青训营',     # Santos 贝利/内马尔摇篮
    'saop': '圣保罗青训营',     # São Paulo
    'palm': '帕尔梅拉斯青训营',
    'cori': '科林蒂安青训营',
    'gre': '格雷米奥青训营',
    'cru': '克鲁塞罗青训营',
    'hil': '利雅得新月青训营',
}

pat_obj = re.compile(r"\{[^{}]*\}", re.S)
pat_id = re.compile(r"'id':(['\"])(.*?)\1")
pat_name = re.compile(r"'name':(['\"])(.*?)\1")
pat_acad = re.compile(r"'academy'")

out = {}
skipped_has = []
for lg in team_order:
    text = open(os.path.join(SRC_DIR, 'teams_%s.ev.js' % lg), encoding='utf-8').read()
    for obj in pat_obj.findall(text):
        if pat_acad.search(obj):
            continue
        m_id, m_name = pat_id.search(obj), pat_name.search(obj)
        if not m_id or not m_name:
            continue
        tid, tname = m_id.group(2), m_name.group(2)
        label = OVERRIDES.get(tid)
        if label is None:
            label = tname + '青训营'
        out[tid] = label

lines = ['// AUTO-GENERATED by tools/gen_academy.py — 编辑 teams_*.ev.js 或本文件 OVERRIDES 后重跑，勿手改',
         'var ACADEMY_PATCH={']
for tid, label in out.items():
    lines.append("'%s':\"%s\"," % (tid, label.replace('"', '\\"')))
lines.append('};')
open(OUT, 'w', encoding='utf-8', newline='').write('\n'.join(lines) + '\n')
print('wrote %s (%d entries)' % (OUT, len(out)))
