import sys, os, re, json
sys.stdout.reconfigure(encoding='utf-8')
import esprima

BASE = r'D:\football\career-sim'
SRC_DIR = os.path.join(BASE, 'src', 'events')
p = os.path.join(BASE, 'deobf', 'events.deob.js')
src = open(p, encoding='utf-8').read()
NL = chr(10)

# locate the main array: var j=[ ... ];  window["EVENTS"]=j;
ast = esprima.parseScript(src, {'range': True})
# main code lives inside !(function(){ 'use strict'; ... }()) sequence expression
seq = ast.body[2].expression
iife = seq.expressions[1].argument.callee.body
body_stmts = iife.body
arr_node = None
helpers_nodes = []
for node in body_stmts:
    if node.type == 'VariableDeclaration' and node.declarations[0].id.name == 'j':
        arr_node = node
    else:
        helpers_nodes.append(node)
assert arr_node, 'array not found'

elems = arr_node.declarations[0].init.elements
print('elements:', len(elems))

# ---- classify by id prefix ----
GROUPS = [
    ('vet', 'vet'), ('club', 'club'), ('star', 'star'), ('lg', 'league'),
    ('cn', 'cn'), ('kid', 'kid'), ('youth', 'youth'), ('abr', 'abr'),
    ('nat', 'nat'), ('ntcap', 'nat'), ('gk', 'gk'), ('love', 'love'),
    ('att', 'att'), ('mid', 'mid'), ('def', 'def'), ('aca', 'aca'),
]
def group_of(eid):
    for pre, g in GROUPS:
        if eid.startswith(pre + '_') or eid == pre:
            return g
    return 'misc'

# ---- formatter: rebuild an event object text with line structure ----
def fmt_value(node, src):
    return src[node.range[0]:node.range[1]]

def fmt_option(obj, src, indent):
    pad = '    '
    lines = []
    lines.append(indent + '{')
    props = obj.properties
    for i, pr in enumerate(props):
        key = src[pr.key.range[0]:pr.key.range[1]]
        val = fmt_value(pr.value, src)
        tail = ',' if i < len(props) - 1 else ''
        # wrap long values (desc/text) at property boundary only
        if len(val) > 400 and not val.startswith('function'):
            val = val  # keep single-line; JS strings here are already concatenated chunks
        lines.append(indent + pad + key + ': ' + val + tail)
    lines.append(indent + '}' + ',')
    return NL.join(lines)

def fmt_event(obj, src):
    lines = ['{']
    props = obj.properties
    opt_prop = None
    head_props = []
    for pr in props:
        key = src[pr.key.range[0]:pr.key.range[1]]
        if key.strip("'\"") == 'options':
            opt_prop = pr
        else:
            head_props.append(pr)
    for pr in head_props:
        key = src[pr.key.range[0]:pr.key.range[1]]
        val = fmt_value(pr.value, src)
        comma = ','
        lines.append('  ' + key + ': ' + val + comma)
    if opt_prop is not None:
        lines.append("  'options': [")
        opts = opt_prop.value.elements
        for i, el in enumerate(opts):
            block = fmt_option(el, src, '    ')
            block = block[:block.rfind(',')] if i == len(opts) - 1 else block
            lines.append(block)
        lines.append('  ]')
    lines.append('}')
    return NL.join(lines)

# header comment per event
def event_header(ev_src):
    def grab(key):
        m = re.search(chr(39) + key + chr(39) + r':\s*' + chr(34) + r'([^' + chr(34) + r']*)', ev_src)
        return m.group(1) if m else '?'
    return grab('id') + ' | ' + grab('title')

groups = {}
order = []
for gi, el in enumerate(elems):
    ev_src = src[el.range[0]:el.range[1]]
    m = re.search(chr(39) + 'id' + chr(39) + r':\s*"' + r'([a-z0-9_]+)', ev_src)
    eid = m.group(1)
    g = group_of(eid)
    if g not in groups:
        groups[g] = []
        order.append(g)
    body = fmt_event(el, src)
    groups[g].append('// ---- idx:' + str(gi) + ' | ' + event_header(ev_src) + ' ----' + NL + body)

if os.path.exists(SRC_DIR) is False:
    os.makedirs(SRC_DIR)
for g in order:
    content = '// auto-generated by split_events.py - edit events here, then run build_events.py' + NL + NL
    content += 'var EVT_' + g + '=[' + NL + NL
    content += (',' + NL + NL).join(groups[g]) + NL + NL + '];' + NL
    fp = os.path.join(SRC_DIR, g + '.ev.js')
    open(fp, 'w', encoding='utf-8', newline='').write(content)
    print('%-10s %3d events -> %s' % (g, len(groups[g]), fp))

# helpers.js: everything except the j array & the EVENTS assignment
helper_txt = []
for node in helpers_nodes:
    t = src[node.range[0]:node.range[1]]
    if 'window["EVENTS"]=j' in t or re.match(r'window\s*\[\s*["\']EVENTS', t):
        continue
    helper_txt.append(t)
hp = os.path.join(SRC_DIR, 'helpers.js')
open(hp, 'w', encoding='utf-8', newline='').write(
    '// helper functions d/f/g/h and EV_ROLL (shared by all event modules)' + NL +
    NL.join(helper_txt) + NL)
print('helpers ->', hp)

# manifest for build order
mf = os.path.join(SRC_DIR, 'MANIFEST.json')
json.dump({'order': order}, open(mf, 'w'), indent=1)
print('manifest ->', mf)