// auto-generated by split_events.py - edit events here, then run build_events.py

var EVT_abr=[

// ---- idx:205 | abr_boxi | 节礼日 ----
{
  'id': "abr_boxi"+"ng_day",
  'title': "节礼日",
  'icon': '🎄',
  'weight': 0x44,
  'when': function(p){
return!p["inChina"]&&'EN'===p["country"];
},
  'desc': "十天四场。圣诞夜坐大巴赶路，二十六号打客场。队里的英格兰人管这叫一年里最好的日子。",
  'options': [
    {
        'label': '全踢',
        'p': function(p){
return f(0.62,[[p["ovr"],0x48,0.006],[p["age"],0x1b,-0.022]],0.3,0.85);
},
        'hint': function(p,q){
return g(q,"扛下来了","累趴下");
},
        'apply': function(p,q,s){
return d(q,s)?{'ovr':0x2,'fame':0xe,'roleDelta':0x1,'text':"四场全首发，进了两个。当地报纸写道，这个中国人「有一副英式的肺」。"}:{'ovr':-0x3,'roleDelta':-0x1,
'text':"第三场下半场，大腿后侧忽然拉响了。整个一月，你都在恢复。"};
}
    },
    {
        'label': "跟教练说要轮休",
        'hint': "保住身体，位置有"+'风险',
        'apply': function(){
return{'ovr':0x1,'roleDelta':-0x1,'guanxi':-0x6,'text':"他答应了。只是从那以后，「关键场次」四个字里，不再有你。"};
}
    }
  ]
},

// ---- idx:206 | abr_tran | 翻译不干了 ----
{
  'id': "abr_tran"+"slator",
  'title': "翻译不干了",
  'icon': '🗣',
  'weight': 0x42,
  'when': function(p){
return!p["inChina"]&&p["seasonsA"+"broad"]>=0x1;
},
  'desc': "俱乐部精简开支，翻译的合同没续。战术会上教练讲了二十分钟，你只听懂六成。",
  'options': [
    {
        'p': function(p){return f(0.65,[[p["talent"],1,0.4]],0.2,0.9);
},
        'label': "自己啃语言",
        'hint': function(p,q){return g(q,'从此不用别人','半年还在猜');
},
        'apply': function(p,q,s){
return d(q,s)?{'ovr':0x3,'guanxi':0xc,'text':"三个月后，你在更衣室讲了第一个笑话，全队都笑了。那天你才算真的到了这儿。"}:{'ovr':-0x1,'guanxi':0x4,'text':"背了半年单词，战术板上的东西还是靠猜。教练喊你名字的速度，倒是快了一点。"};
}
    },
    {
        'label': "自费请一个",
        'hint': "钱-，训练不掉队",
        'apply': function(){
return{'money':-0x6e,'ovr':0x1,'text':"你按月付钱，请了个留学生。他后来成了你在那座城市唯一的朋友。"};
}
    }
  ]
},

// ---- idx:207 | abr_mark | 亚洲行 ----
{
  'id': "abr_mark"+'et',
  'title': "亚洲行",
  'icon': '✈️',
  'weight': 0x44,
  'when': function(p){
return!p["inChina"]&&p["fame"]>=0x1e;
},
  'desc': "季前赛排了一趟亚洲行。商务部门把话挑明：这趟海报的中间，得是你。",
  'options': [
    {
        'label': "全程配合",
        'hint': "钱和名气都涨，季"+"前备战被吃掉",
        'apply': function(){
return{'money':0xdc,'fame':0x16,'ovr':-0x2,'text':"十天六个城市，三支广告。回基地的第一堂训练课，体脂比走时高了两个点。"};
}
    },
    {
        'p': function(p){return f(0.6,[[p["ovr"],60,0.008]],0.2,0.9);
},
        'label': "只去三天",
        'hint': function(p,q){return g(q,'状态最好','商务部门记账');
},
        'apply': function(p,q,s){
return d(q,s)?{'ovr':0x2,'money':0x3c,'text':"打完两场友谊赛，你就飞回了基地。开赛后，你的状态是全队最好的一档。"}:{'guanxi':-0xa,'money':0x28,'roleDelta':-0x1,
'text':"赞助商在合同里加了一条。转年续约，商务那一栏，给你打了低分。"};
}
    }
  ]
},

// ---- idx:208 | abr_boo | 看台上的那几个人 ----
{
  'id': "abr_boo",
  'title': "看台上的那几个人",
  'icon': '📢',
  'weight': 0x40,
  'when': function(p){
return!p["inChina"]&&p["seasonsA"+"broad"]>=0x1;
},
  'desc': "客场角旗区附近那几个人，每次你拿球，都学着那动静叫。第四官员装作没听见。",
  'options': [
    {
        'label': "当场指给主裁",
        'hint': "事情闹大，你成了"+'话题',
        'apply': function(){
return{'fame':0x18,'guanxi':-0x8,'clean':0x6,'text':"比赛停了六分钟，广播念了三遍警告。有人说你玻璃心，也有人散场后等在球场外，就为跟你握个手。"};
}
    },
    {
        'p': function(p){return f(0.6,[[p["ovr"],60,0.008]],0.2,0.9);
},
        'label': "用球回应",
        'hint': function(p,q){return g(q,'当场回敬','踢得更急');
},
        'apply': function(p,q,s){
return d(q,s)?{'ovr':0x3,'fame':0x10,'text':h(p,{'gk':"你在那个角旗区前"+"面把一个必进球托"+"出了横梁，起身冲"+"那几个位置张开了"+"双臂。",'other':"你在那个角旗区前"+"面助攻了一个球，"+"转身冲那几个位置"+"张开了双臂。"})}:{'ovr':0x1,
'fame':-0x4,'text':"那场你踢得很急，什么都没做成。回酒店，你把手机关了一整晚。"};
}
    }
  ]
},

// ---- idx:209 | abr_wint | 冬歇期 ----
{
  'id': "abr_wint"+"er_break",
  'title': "冬歇期",
  'icon': '❄️',
  'weight': 0x44,
  'when': function(p){
return!p["inChina"];
},
  'desc': "十二月底到一月中，联赛停摆两周，正赶上春节。机票来回三十几个小时。",
  'options': [
    {
        'label': "回家过年",
        'hint': "关系+，状态回落",
        'apply': function(){
return{'guanxi':0xe,'ovr':-0x2,'money':-0x1e,'text':"你在家待了九天，吃胖三斤。你妈把你穿过的每件球衣，都熨过一遍。"};
}
    },
    {
        'label': "留下来加练",
        'hint': "能力+，一个人过"+'节',
        'apply': function(){
return{'ovr':0x3,'fame':0x4,'text':"大年夜的基地，只剩你和两个门将。仨人点了外卖，对着手机看跨年晚会。"};
}
    }
  ]
},

// ---- idx:210 | abr_pape | 驾照和银行卡 ----
{
  'id': "abr_pape"+"rwork",
  'title': "驾照和银行卡",
  'icon': '🪪',
  'weight': 0x3e,
  'when': function(p){
return!p["inChina"]&&p["seasonsA"+"broad"]<=0x3;
},
  'desc': "住了半年，驾照还没办下来，银行卡冻结过两次。俱乐部说，人手不够。",
  'options': [
    {
        'label': "自己一趟趟跑",
        'hint': "耽误时间，但从此"+'自理',
        'apply': function(){
return{'ovr':-0x1,'guanxi':0xa,'text':"你学会了预约、排队，和据理力争。半年后新来的巴西小孩，什么都来问你。"};
}
    },
    {
        'label': "花钱请人代办",
        'hint': "钱-，省心",
        'apply': function(){
return{'money':-0x46,'ovr':0x1,'text':"两周，全办妥了。省下来的时间，你都泡在了训练场。"};
}
    }
  ]
},

// ---- idx:211 | abr_cliq | 更衣室的桌子 ----
{
  'id': "abr_cliq"+'ue',
  'title': "更衣室的桌子",
  'icon': '🍽',
  'weight': 0x42,
  'when': function(p){
return!p["inChina"];
},
  'desc': "餐厅里南美帮一桌，法语区一桌，本地人一桌。你端着盘子，站在中间。",
  'options': [
    {
        'p': function(p){return f(0.6,[[p["guanxi"],45,0.008]],0.2,0.9);
},
        'label': "硬凑过去",
        'hint': function(p,q){return g(q,'真融进去了','白听两个月');
},
        'apply': function(p,q,s){
return d(q,s)?{'guanxi':0x10,'fame':0x6,'text':"三个月后，他们开始用你的中文名叫你，虽然每次都念得很怪。"}:{'guanxi':-0x4,'ovr':0x1,'text':"听了两个月听不懂的笑话，最后你还是端着盘子，回了自己那桌。"};
}
    },
    {
        'label': "自己一桌，专心吃",
        'hint': "能力+，落个孤僻",
        'apply': function(){
return{'ovr':0x2,'guanxi':-0x6,'text':"你吃饭比谁都快，吃完就去健身房。他们叫你「机器」，语气里有敬意，也有距离。"};
}
    }
  ]
},

// ---- idx:212 | abr_thur | 周四踢欧战 ----
{
  'id': "abr_thur"+"sday",
  'title': "周四踢欧战",
  'icon': '🌙',
  'weight': 0x42,
  'when': function(p){
return!p["inChina"]&&p["hasCont"]&&p["roleRank"]>=0x2;
},
  'desc': "周四客场打完欧战，凌晨三点才落地，周日中午还有联赛。教练问你，能不能连着上。",
  'options': [
    {
        'p': function(p){return f(0.58,[[p["ovr"],60,0.008]],0.2,0.9);
},
        'label': "两场都上",
        'hint': function(p,q){return g(q,'跑满两场','直接空了');
},
        'apply': function(p,q,s){
return d(q,s)?{'roleDelta':0x1,'fame':0xa,'mult':{'cont':1.4},'text':"两场下来，你跑了二十三公里。队长在混合区扔下一句：「这家伙不是人。」"}:{'ovr':-0x2,'text':"周日下半场，你彻底跑不动了。数据网站给了你全场最低分。"};
}
    },
    {
        'label': "只打联赛",
        'hint': "状态稳，欧战名单"+'靠后',
        'apply': function(){
return{'ovr':0x1,'mult':{'cont':0.8},'text':"欧战那晚，你在替补席坐了九十分钟。周日，你是全场最佳。"};
}
    }
  ]
},

// ---- idx:213 | abr_nick | 当地媒体给的外号 ----
{
  'id': "abr_nick"+"name",
  'title': "当地媒体给的外号",
  'icon': '📰',
  'weight': 0x40,
  'when': function(p){
return!p["inChina"]&&p["fame"]>=0x19;
},
  'desc': "本地小报给你起了个外号，直译过来叫「长城」。第二天，全城都这么喊你。",
  'options': [
    {
        'label': "接下来",
        'hint': "名气+",
        'apply': function(){
return{'fame':0x10,'guanxi':0x4,'text':"你在采访里说，挺好，长城是我们那儿的东西。球衣定制区，「长城」卖得比你的号码还好。"};
}
    },
    {
        'label': "公开纠正",
        'hint': "少了个梗，多了点"+'尊重',
        'apply': function(){
return{'fame':-0x4,'clean':0x6,'guanxi':0x6,'text':"你说，我有名字。那家小报第二天改了说法，别的媒体也跟着改了。"};
}
    }
  ]
},

// ---- idx:214 | abr_home | 回母队看看 ----
{
  'id': "abr_home"+"coming",
  'title': "回母队看看",
  'icon': '🏠',
  'weight': 0x3e,
  'when': function(p){
return!p["inChina"]&&p["seasonsA"+"broad"]>=0x3;
},
  'desc': "休赛期路过老东家，梯队教练拦住你：能不能给孩子们上一堂课？基地还是当年那个样子。",
  'options': [
    {
        'label': "去上一堂",
        'hint': "名气+，心里有底",
        'apply': function(p){
return{'fame':0xc,'guanxi':0xa,'text':h(p,{'gk':"你把队里六个守门"+"的孩子单拎出来练"+"了一下午倒地。",'other':"你带着四十个孩子"+"练了一下午传接。"})+("走的时候有个小孩"+"问你，出去踢是不"+"是很难。你说是。")};
}
    },
    {
        'label': "捐一批装备就走",
        'hint': "钱-，也是实在的",
        'apply': function(){
return{'money':-0x3c,'fame':0x6,'clean':0x4,'text':"两百双球鞋和十个球门。你没让挂横幅，也没让拍照，卸完就走了。"};
}
    }
  ]
},

// ---- idx:286 | abr_lang | 语言关 ----
{
  'id': "abr_lang",
  'title': "语言关",
  'icon': '\u{1F5E3}\u{FE0F}',
  'weight': 0x36,
  'repeat': 1,
  'stage': "kid",
  'when': function(p){return p["inAcademy"]&&p["youthAbroad"];},
  'desc': "训练里教练喊的葡语/西语你只听懂了一半。战术板上画得再清楚，喊话那一下你还是慢半拍。",
  'options': [
    {
        'label': "报语言班",
        'p': function(p){return f(0.7,[[p["talent"],1,0.2]],0.4,0.9);},
        'hint': function(p,q){return g(q,"语言通了","花了钱还跟不上");},
        'apply': function(p,q,s){return d(q,s)?{'ovr':0x2,'guanxi':0x2,'text':"三个月后你能在更衣室里接上话了。教练开始愿意多讲两句，你听得懂那些「要球」「压上」之外的暗话。"}:{'ovr':-0x1,'text':"课费不便宜，你去了几节就断了。还是只能靠眼神和手势，训练里继续猜。"};}
    },
    {
        'label': "靠训练硬扛",
        'hint': "能力+1，但磨合慢",
        'apply': function(p,q,s){return d(q,s)?{'ovr':0x1,'text':"听不懂就多练。你把每个动作都做到位，队友开始主动指给你看位置。"}:{'ovr':0x0,'text':"你把自己练得很累，但教练喊战术的时候你还是会愣一下。"};}
    }
  ]
},

// ---- idx:287 | abr_tech | 技术流训练 ----
{
  'id': "abr_tech",
  'title': "技术流训练",
  'icon': '\u{1F3AF}',
  'weight': 0x34,
  'repeat': 1,
  'stage': "kid",
  'when': function(p){return p["inAcademy"]&&p["youthAbroad"];},
  'desc': "这里的青训课和你原来踢的不一样：一个人一趟球要过十几次桩，教练不催，只看动作对不对。",
  'options': [
    {
        'label': "跟着磨细节",
        'p': function(p){return f(0.55,[[p["talent"],1,0.3]],0.3,0.85);},
        'hint': function(p,q){return g(q,"脚下功夫见长","动作学歪了");},
        'apply': function(p,q,s){return d(q,s)?{'ovr':0x3,'talent':0.05,'text':"一个夏天下来，你的趟球、触球都变了样。回到队里热身，教练多看了你几眼。"}:{'ovr':-0x1,'text':"你想学他们那种灵巧，结果动作学得四不像。回去还是用自己那套。"};}
    },
    {
        'label': "保持自己的踢法",
        'hint': "能力+1",
        'apply': function(){return{'ovr':0x1,'text':"你有自己的节奏。这里的人起初不习惯，但你几次过人都让他们闭嘴了。"};}
    }
  ]
},

// ---- idx:288 | abr_physical | 异国体能营 ----
{
  'id': "abr_physical",
  'title': "异国体能营",
  'icon': '\u{1F4AA}',
  'weight': 0x2e,
  'repeat': 1,
  'stage': "kid",
  'when': function(p){return p["inAcademy"]&&p["youthAbroad"];},
  'desc': "这儿的体能教练对力量有一套：不是蛮练，是算着肌肉和爆发力来。他看着你的报告摇头：「太瘦了，但能练。」",
  'options': [
    {
        'label': "吃下这套计划",
        'p': function(p){return f(0.6,[[p["ovr"],0x2a,0.02]],0.3,0.85);},
        'hint': function(p,q){return g(q,"身体壮了一圈","加练加伤了");},
        'apply': function(p,q,s){return d(q,s)?{'ovr':0x3,'text':"半年后你的对抗不再是短板。拼抢里你第一次把对方撞开，自己都愣了一下。"}:{'ovr':-0x2,'text':"量太大，你肌肉拉伤歇了两周。回来后体重是上去了，脚步却慢了点。"};}
    },
    {
        'label': "先保证能踢上球",
        'hint': "能力+1",
        'apply': function(){return{'ovr':0x1,'text':"你没贪那点力量，先把每场比赛踢好。教练后来才慢慢给你加量。"};}
    }
  ]
},

// ---- idx:289 | abr_mentor | 外教的单独指点 ----
{
  'id': "abr_mentor",
  'title': "外教的单独指点",
  'icon': '\u{1F4CB}',
  'weight': 0x32,
  'repeat': 0x1,
  'stage': "youth",
  'when': function(p){return p["inAcademy"]&&p["youthAbroad"]&&p["talent"]>1;},
  'desc': "梯队主教练留你下来：「你脚下有东西，但位置感太飘。来，我告诉你这个位置怎么站。」",
  'options': [
    {
        'label': "认真记下来",
        'p': function(p){return f(0.65,[[p["talent"],1,0.25]],0.4,0.9);},
        'hint': function(p,q){return g(q,"开了窍","没听进去");},
        'apply': function(p,q,s){return d(q,s)?{'ovr':0x4,'talent':0.06,'fame':0x1,'text':"那几句话像钥匙。之后你在场上的站位、跑动都有了章法，教练开始让你打更重要的位置。"}:{'ovr':0x1,'text':"他讲了半天，你记住一半。不过那一半也够你用一阵子了。"};}
    },
    {
        'label': "按自己的理解踢",
        'hint': "能力+2",
        'apply': function(){return{'ovr':0x2,'text':"你谢过他，但场上还是按自己的直觉跑。教练皱了皱眉，没再说什么。"};}
    }
  ]
},

// ---- idx:290 | abr_homesick | 想家 ----
{
  'id': "abr_homesick",
  'title': "想家",
  'icon': '\u{1F3E1}',
  'weight': 0x2a,
  'repeat': 1,
  'stage': "kid",
  'when': function(p){return p["inAcademy"]&&p["youthAbroad"];},
  'desc': "半夜醒来看手机，家里那边正是下午。妈妈的语音一条条发来，你躺在宿舍床上，突然不想动了。",
  'options': [
    {
        'label': "把自己练到没力气想",
        'p': function(p){return f(0.35,[[p["fame"],25,0.008],[p["ovr"],60,0.004]],0.15,0.75);},
        'hint': function(p,q){return g(q,"挺过去了","状态下滑");},
        'apply': function(p,q,s){return d(q,s)?{'ovr':0x3,'fame':0x1,'text':"你把思乡变成训练。那阵子你练得比谁都狠，状态不但没掉，反而起来了。"}:{'ovr':-0x2,'text':"想家想得厉害，训练里走神。教练看出来了，问你「要不要回去待几天」。"};}
    },
    {
        'label': "和家里多视频",
        'hint': "状态稳住",
        'apply': function(){return{'ovr':0x1,'text':"跟家里说开了，心里反而踏实。你决定再熬一熬，这条路是自己选的。"};}
    }
  ]
},

// ---- idx:291 | abr_style | 新战术体系 ----
{
  'id': "abr_style",
  'title': "新战术体系",
  'icon': '\u{1F4D0}',
  'weight': 0x2e,
  'repeat': 1,
  'stage': "kid",
  'when': function(p){return p["inAcademy"]&&p["youthAbroad"];},
  'desc': "这里的打法跟你原来完全不一样：从后场就开始倒脚，前场球员要回撤接球。你踢了几天，觉得自己像个多余的人。",
  'options': [
    {
        'label': "花时间吃透",
        'p': function(p){return f(0.5,[[p["talent"],1,0.3]],0.25,0.8);},
        'hint': function(p,q){return g(q,"融入体系","始终对不上");},
        'apply': function(p,q,s){return d(q,s)?{'ovr':0x3,'guanxi':0x1,'text':"两个月后你终于跑顺了那些线路。教练在队内赛上点名表扬你：「这就是我们要的那种跑位。」"}:{'ovr':-0x1,'text':"你还是习惯自己拿球往前冲，和队友总对不上拍。"};}
    },
    {
        'label': "坚持自己的风格",
        'hint': "能力+2",
        'apply': function(){return{'ovr':0x2,'text':"体系是他们的，你是你的。你在有限的机会里用个人能力证明了自己。"};}
    }
  ]
},

// ---- idx:292 | abr_food | 饮食差异 ----
{
  'id': "abr_food",
  'title': "饮食差异",
  'icon': '\u{1F35D}',
  'weight': 0x26,
  'repeat': 0x1,
  'stage': "kid",
  'when': function(p){return p["inAcademy"]&&p["youthAbroad"];},
  'desc': "食堂里全是你不认识的菜。前两周你靠面包和水果撑着，体能教练看不过去：「你这不是在踢球，是在节食。」",
  'options': [
    {
        'label': "学着吃",
        'p': function(p){return f(0.65,[[p["clean"],1,0.1]],0.4,0.85);},
        'hint': function(p,q){return g(q,"营养跟上了","还是吃不惯");},
        'apply': function(p,q,s){return d(q,s)?{'ovr':0x2,'clean':0x1,'text':"你开始习惯这里的吃法，体重和体力都回来了。身体是踢球的底子，这道理你懂晚了但懂了。"}:{'ovr':0x0,'text':"你还是吃得少，训练后腿发软。教练让你多睡一觉，别的也没法帮你。"};}
    },
    {
        'label': "自己开小灶",
        'hint': "花点钱保状态",
        'apply': function(p,q,s){return d(q,s)?{'ovr':0x2,'money':-0x1,'text':"你自己买食材做中餐，吃是吃好了，但钱包瘪得快。"}:{'ovr':0x0,'text':"你试了几次，锅都没找齐。最后还是回食堂将就。"};}
    }
  ]
},

// ---- idx:293 | abr_rival | 本地球员的敌意 ----
{
  'id': "abr_rival",
  'title': "本地球员的敌意",
  'icon': '\u{2694}\u{FE0F}',
  'weight': 0x2c,
  'repeat': 0x1,
  'stage': "kid",
  'when': function(p){return p["inAcademy"]&&p["youthAbroad"];},
  'desc': "青训队里有个本地球员看你不太顺眼，训练里总爱跟你较劲，几次对抗都下狠脚。",
  'options': [
    {
        'label': "用实力回应",
        'p': function(p){return f(0.5,[[p["ovr"],0x32,0.02]],0.25,0.8);},
        'hint': function(p,q){return g(q,"他服了","吃了亏");},
        'apply': function(p,q,s){return d(q,s)?{'ovr':0x3,'fame':0x1,'text':"你在一次队内对抗里把他过了个干净，还进了球。从那以后他对你客气多了——是那种「服了」的客气。"}:{'ovr':-0x2,'text':"你被他几次撞翻在地，教练吹了哨也没用。那天晚上你大腿青了一块。"};}
    },
    {
        'label': "绕着走",
        'hint': "避开冲突",
        'apply': function(){return{'ovr':0x0,'text':"你不想把精力耗在斗气上，训练里尽量绕开他。他倒也没再找茬。"};}
    }
  ]
},

// ---- idx:294 | abr_reputation | 表现被注意到 ----
{
  'id': "abr_reputation",
  'title': "表现被注意到",
  'icon': '\u{1F31F}',
  'weight': 0x2e,
  'repeat': 0x1,
  'stage': "youth",
  'when': function(p){return p["inAcademy"]&&p["youthAbroad"]&&p["ovr"]>55;},
  'desc': "当地球探来看梯队的比赛。赛后有人把你的号码记在本子上，教练拍拍你：「那边的人，想多看看你。」",
  'options': [
    {
        'label': "展示自己",
        'p': function(p){return f(0.35,[[p["ovr"],0x30,0.01],[p["fame"],25,0.006]],0.2,0.8);},
        'hint': function(p,q){return g(q,"被更多人记住","只是看了一眼");},
        'apply': function(p,q,s){return d(q,s)?{'ovr':0x2,'fame':0x6,'text':"那一场你踢得格外卖力。赛后经纪人打电话来说有人问起你，名字第一次出现在别人的笔记本上。"}:{'ovr':0x1,'fame':0x2,'text':"你踢得不算差，但也没到让人眼前一亮。那人看完就走了。"};}
    },
    {
        'label': "低调攒实力",
        'hint': "能力+1",
        'apply': function(){return{'ovr':0x1,'text':"你不想被盯上就乱踢，还是按自己的节奏来。实力到了，名声自然会来。"};}
    }
  ]
},

// ---- idx:295 | abr_teammate | 交到第一个朋友 ----
{
  'id': "abr_teammate",
  'title': "交到第一个朋友",
  'icon': '\u{1F91D}',
  'weight': 0x2a,
  'repeat': 0x1,
  'stage': "kid",
  'when': function(p){return p["inAcademy"]&&p["youthAbroad"];},
  'desc': "更衣室里有个同龄人总爱找你搭话，用蹩脚的英语加手势比划。他约你周末去他家吃饭，说他妈妈想见见「那个中国来的」。",
  'options': [
    {
        'label': "去",
        'p': function(p){return f(0.45,[[p["guanxi"],45,0.008]],0.3,0.85);},
        'hint': function(p,q){return g(q,"多了个兄弟","还是隔了一层");},
        'apply': function(p,q,s){return d(q,s)?{'guanxi':0x4,'ovr':0x1,'text':"那顿饭吃得比训练还累，但你交到了一个能托底的队友。训练里他开始主动帮你说话、给你传球。"}:{'guanxi':0x1,'text':"去了，但语言还是硬伤。你俩点头之交，他说什么你多半靠猜。"};}
    },
    {
        'label': "婉拒",
        'hint': "省事",
        'apply': function(){return{'guanxi':0x0,'text':"你借口训练推掉了。他还是照常跟你打招呼，但关系也就那样了。"};}
    }
  ]
}

,
// ---- idx:333 | abr_nat_es | 拉玛西亚式的抢圈 ----
{'id':"abr_nat_es",'title':"抢圈是这里的一切",'icon':'🔵','weight':0x30,'stage':"youth",'repeat':1,'when':function(p){return p["inAcadem"+'y']&&p["youthAbroad"]&&'ES'===p["country"];},'desc':"每天训练的第一个科目永远是抢圈：六个人围一圈，两个人在中间追。教练说，在这块土地上，抢圈丢球的人不配谈战术。",'options':[{'label':"把两脚出球练到极致",'p':function(p){return f(0.65,[[p["talent"],1,0.3]],0.35,0.92);},'hint':function(p,q){return g(q,"融进了血液","被晾在圈里");},'apply':function(p,q,s){return d(q,s)?{'ovr':0x2,'text':"三个月后，你成了圈里坚持最久的那个人。队友开始学你接球前的那半步移动。教练只说了一句：现在你像个西班牙球员了。"}:{'ovr':-0x1,'text':"你总想多带一步。每次丢球，全组罚跑，你的名字成了口令。晚上你加练对墙传接，墙皮都踢掉了一块。"};}},{'label':"观察他们怎么思考",'hint':"学意识",'apply':function(){return{'ovr':0x1,'text':"你不急着触球，先看：他们的身体永远朝向下一个传球点。这个细节你记了满满一本笔记。"};}}]},

// ---- idx:334 | abr_nat_de | 双轨制的下午 ----
{'id':"abr_nat_de",'title':"双轨制的下午",'icon':'📚','weight':0x30,'stage':"youth",'repeat':1,'when':function(p){return p["inAcadem"+'y']&&p["youthAbroad"]&&p["country"]==='DE';},'desc':"上午在俱乐部训练，下午要去合作中学上课，一门都不能挂。德国人说：青训不是造机器，是要造完整的人——虽然他们说这话时你刚跑完十二分钟折返。",'options':[{'label':"两头都不放松",'p':function(p){return f(0.6,[[p["clean"],60,0.005]],0.3,0.9);},'hint':function(p,q){return g(q,"德式全能","顾此失彼");},'apply':function(p,q,s){return d(q,s)?{'ovr':0x2,'text':"期末考你过了全部科目，体测数据排梯队前三。德国教练在评语里写了一个词：verlässlich——可靠。他说这个词比天赋值钱。"}:{'ovr':-0x1,'text':"德语语法和战术板在你脑子里搅成一团。月考挂了两门，俱乐部约谈了你和你监护人：学业不达标，注册会被暂停。"};}},{'label':"专注训练这一头",'hint':"风险与回报",'apply':function(){return{'ovr':0x2,'text':"你跟文化课老师摊牌：我的人生在球场上。她叹了口气，给你划了最低限度的复习范围。你压线过了——然后把自己扔进了力量房。"};}}]},

// ---- idx:335 | abr_nat_en | 周六的U18联赛 ----
{'id':"abr_nat_en",'title':"看台上的陌生人",'icon':'📋','weight':0x30,'stage':"youth",'repeat':1,'when':function(p){return p["inAcadem"+'y']&&p["youthAbroad"]&&p["country"]==='EN';},'desc':"英甲球队 U18 联赛的周六早晨，场边站满了人：家长、球探、还有一个端着热茶不停做笔记的老头。领队说：这里的每一场青年队比赛，都有二十双职业的眼睛。",'options':[{'label':"把对抗拉满给他们看",'p':function(p){return f(0.58,[[p["ovr"],0x46,0.01]],0.28,0.88);},'hint':function(p,q){return g(q,"名单上有你了","差一口气");},'apply':function(p,q,s){return d(q,s)?{'fame':0x8,'ovr':0x2,'text':"你在雨里赢下了七次一对一，还造了一张红牌。周一，那个做笔记的老头出现在了一线队训练基地的前台。领队冲你扬了扬下巴：有人问你的名字了。"}:{'ovr':-0x1,'text':"英国孩子的身体对抗像橄榄球。你摔了无数次，数据栏一片空白。回程大巴上领队递给你一块巧克力：在这里，硬汉比天才先吃上饭。"};}},{'label':"用技术说话",'hint':"另一条路",'apply':function(){return{'ovr':0x1,'fame':0x4,'text':"你避开了所有硬碰硬，用两次转身过人和一脚贴地斩上了本地报纸的青年版。标题写着：这个东方孩子有点东西。"};}}]},

// ---- idx:336 | abr_nat_jp | 练习后的球场清扫 ----
{'id':"abr_nat_jp",'title':"练习结束之后",'icon':'🧹','weight':0x30,'stage':"youth",'repeat':1,'when':function(p){return p["inAcadem"+'y']&&p["youthAbroad"]&&p["country"]==='JP';},'desc':"训练结束，没有一个人走。全队排成一列捡拾球场上的草屑和落叶，连主力前锋都在弯腰拔草。部长级的前辈路过你身边，轻轻说了一句：球场记得每一个善待它的人。",'options':[{'label':"拿起工具一起干",'p':function(p){return f(0.75,[[p["guanxi"],40,0.008]],0.45,0.94);},'hint':function(p,q){return g(q,"被接纳了","笨手笨脚");},'apply':function(p,q,s){return d(q,s)?{'guanxi':0xa,'text':"你把捡草屑也做出了标准动作，前辈们相视一笑。周末的合宿名单上第一次出现了你的名字。在日本，被邀请参加合宿意味着：你已经是「自己人」了。"}:{'guanxi':-0x2,'text':"你分不清哪种耙子收拾哪种草，越帮越乱。前辈没说什么，只是默默把你那片重新弄了一遍。当晚你对着手机翻译软件查了一小时「球场养护」。"};}},{'label':"主动申请打扫更衣室",'hint':"诚意拉满",'apply':function(){return{'guanxi':0xc,'ovr':0x1,'text':"你承包了更衣室的清洁。一个月后，队长把一个旧臂章放在你的柜子上：这是队里给最认真的人的传统。"};}}]},

// ---- idx:337 | abr_nat_kr | 前辈的背包 ----
{'id':"abr_nat_kr",'title':"队内序列",'icon':'🎒','weight':0x30,'stage':"youth",'repeat':1,'when':function(p){return p["inAcadem"+'y']&&p["youthAbroad"]&&p["country"]==='KR';},'desc':"韩国梯队的规矩写在看不见的地方：吃饭时按年级坐，训练后低年级要帮高年级背包、收拾装备。你是队里唯一的插班生，也是年纪最小的——所有人都等着看你懂不懂事。",'options':[{'label':"入乡随俗",'p':function(p){return f(0.72,[[p["guanxi"],40,0.008]],0.42,0.93);},'hint':function(p,q){return g(q,"序列认可","忍出内伤");},'apply':function(p,q,s){return d(q,s)?{'guanxi':0xa,'text':"你背了一个月的包，帮了两周的水壶。直到某天训练赛，你过了他们的国脚级中卫——从那天起，前辈们改口叫你「弟弟」的时候带了笑。序列还在，但位置变了。"}:{'guanxi':-0x3,'text':"你背着包摔了一跤，装备散了一地。前辈的脸色很不好看。那晚你想家想到失眠——但第二天，你还是第一个到场的。"};}},{'label':"用表现赢得尊重",'hint':"实力说话",'apply':function(){return{'ovr':0x2,'guanxi':-0x3,'text':"你拒绝了所有杂务：我是来踢球的。更衣室安静了几天。然后你在教学赛连过三人打进一球，前辈拍了拍你的头：好，那就用球说话吧。两种规矩，你选了另一种活法。"};}}]},

// ---- idx:338 | abr_nat_fr | 克莱枫丹的更衣室 ----
{'id':"abr_nat_fr",'title':"十种语言的战术板",'icon':'🌍','weight':0x30,'stage':"youth",'repeat':1,'when':function(p){return p["inAcadem"+'y']&&p["youthAbroad"]&&p["country"]==='FR';},'desc':"这支法国梯队的更衣室里，塞内加尔语、葡语、阿拉伯语和法语各占一角。战术讲解要翻译三遍。你说不好这是混乱还是宝藏，只知道这里的每个天才背后都有一段漂泊的故事。",'options':[{'label':"把每种语言都学一句",'p':function(p){return f(0.7,[[p["talent"],1,0.3]],0.4,0.92);},'hint':function(p,q){return g(q,"团宠诞生","闹了笑话");},'apply':function(p,q,s){return d(q,s)?{'guanxi':0xa,'ovr':0x1,'text':"你学会了用四国语言喊「传给我」。训练场上笑声不断，但配合真的变好了。教练说：足球是最简单的世界语，而你是最好的翻译官。"}:{'guanxi':0x3,'text':"你的一句问候让整个更衣室笑翻了——后来才知道那是句玩笑话。不过没关系，笑完之后，大家记住了这个敢开口的东方人。"};}},{'label':"埋头苦练少说话",'hint':"稳",'apply':function(){return{'ovr':0x2,'text':"语言不通没关系，你的跑位就是语言。三场比赛五个进球之后，队友们开始主动找你配合。有些融入不需要开口。"};}}]}
];