// auto-generated by split_events.py - edit events here, then run build_events.py

var EVT_aca=[

// ---- idx:154 | aca_rese | 预备队联赛 ----
{
  'id': "aca_rese"+"rve",
  'title': "预备队联赛",
  'icon': '🪑',
  'weight': 0x3a,
  'stage': "youth",
  'repeat': 0x2,
  'when': function(p){
return p["inAcadem"+'y'];
},
  'desc': "预备队的比赛排在周二下午。看台上坐着二十来个人，一半球探，一半是队友的家人。你踢得很好，只是，没有集锦。",
  'options': [
    {
        'label': "每场都当正赛踢",
        'hint': "能力+3，没人看"+'见',
        'apply': function(p){
return{'ovr':0x3,'clean':0x4,'text':"整个赛季你一场没"+'缺，'+h(p,{'gk':"零封了十一场",'def':"那条防线一共只丢"+"了九个",'other':"进了十四个"})+("。年底俱乐部的官"+"网做了个盘点，没"+"有提到预备队。")};
}
    },
    {
        'label': "把力气留给训练课",
        'hint': "能力+1，一线队"+"教练那边看得见",
        'apply': function(){
return{'ovr':0x1,'guanxi':0x8,'text':"合练那天你拼得最凶。一线队助教在场边多站了十分钟，临走时回头问了一句：你多大了？"};
}
    }
  ]
},

// ---- idx:155 | aca_sign | 同批人签走了一个 ----
{
  'id': "aca_sign"+'ed',
  'title': "同批人签走了一个",
  'icon': '✒️',
  'weight': 0x38,
  'stage': "youth",
  'repeat': 0x2,
  'when': function(p){
return p["inAcadem"+'y'];
},
  'desc': "跟你同一年进队的那个孩子，今天签了职业合同。更衣室里闹哄哄的，全在起哄。你比他，早两年进队。",
  'options': [
    {
        'label': "去恭喜他",
        'hint': "关系+，心里那关"+"自己过",
        'apply': function(){
return{'guanxi':0xa,'clean':0x5,'text':"你是第一个上去抱他的。那天晚上，你一个人在健身房待到很晚，谁也没理。"};
}
    },
    {
        'p': function(p){return f(0.5,[[p["guanxi"],45,0.008]],0.2,0.9);
},
        'label': "去找教练问自己",
        'hint': function(p,q){return g(q,'得了句实话','被记成沉不住气');
},
        'apply': function(p,q,s){
return d(q,s)?{'ovr':0x2,'guanxi':0x6,'text':"他给你看了评估表：三项比他高，两项比他低，低的那两项旁写着「可练」。「所以你还在这儿。」"}:{'guanxi':-0xa,'text':"他说这种事不是你该问的。往后半年，合练名单上再没有你。"};
}
    }
  ]
},

// ---- idx:156 | aca_newc | 教练组换了一茬 ----
{
  'id': "aca_newc"+"oach",
  'title': "教练组换了一茬",
  'icon': '🔁',
  'weight': 0x36,
  'stage': "youth",
  'repeat': 0x2,
  'when': function(p){
return p["inAcadem"+'y'];
},
  'desc': "带了你三年的青训教练走了。新教练第一堂课，把所有人打散重分。他不知道你是谁。",
  'options': [
    {
        'label': "从头证明一次",
        'hint': "能力+2，累",
        'apply': function(){
return{'ovr':0x2,'guanxi':-0x4,'text':"你把三年前做过的事，又做了一遍。两个月后，他第一次在训练课上叫你的名字——念错了姓。"};
}
    },
    {
        'label': "托老教练打个招呼",
        'hint': "关系+，能力-1",
        'apply': function(){
return{'guanxi':0xc,'ovr':-0x1,'clean':-0x4,'text':"老教练真的打了那通电话。新教练很客气，把你放进了第一组，然后整整一个赛季，再没多看你一眼。"};
}
    }
  ]
},

// ---- idx:157 | aca_gym | 力量房的那两年 ----
{
  'id': "aca_gym",
  'title': "力量房的那两年",
  'icon': "🏋️",
  'weight': 0x34,
  'stage': "youth",
  'when': function(p){
return p["inAcadem"+'y'];
},
  'desc': "体能测试的报告出来：技术合格，对抗不合格。体能教练给你排了一份两年的增重计划——「练完，你才踢得了成年队的比赛。」",
  'options': [
    {
        'label': "照着练两年",
        'p': function(p){
return f(0.62,[[p["ovr"],0x30,0.012]],0.3,0.85);
},
        'hint': function(p,q){
return g(q,"身体撑起来了","光长肉没长力量");
},
        'apply': function(p,q,s){
return d(q,s)?{'ovr':0x3,'text':"两年后你重了九公斤，短距离反而更快。第一次跟成年队合练，你没有被撞开。"}:{'ovr':-0x1,'text':"重了七公斤，转身慢了半拍。那半拍，你找了半年才找回来。"};
}
    },
    {
        'label': "先保住灵活",
        'hint': "能力+1，成年队"+"那关往后拖",
        'apply': function(){
return{'ovr':0x1,'text':"你按自己的节奏来。技术教练点头，体能教练在报告上又写下一次「对抗不合格」。"};
}
    }
  ]
},

// ---- idx:158 | aca_demo | 被放回低一档 ----
{
  'id': "aca_demo"+'te',
  'title': "被放回低一档",
  'icon': '⬇️',
  'weight': 0x32,
  'stage': "youth",
  'when': function(p){
return p["inAcadem"+'y'];
},
  'desc': "U21 名单贴出来，没有你。你被放回低一个年龄段，同组的都比你小两岁，对你客气得像在招待客人。",
  'options': [
    {
        'label': "在那儿当最好的那"+'个',
        'hint': "能力+2，位置低",
        'apply': function(p){
return{'ovr':0x2,'fame':0x4,'text':h(p,{'gk':"半个赛季你只丢了"+"三个球。所有人都"+"说这不算数，但把"+"你叫回 U21 "+"的那份名单上写的"+"就是这个三。",'def':"半个赛季那条防线"+"只丢了三个球。所"+"有人都说这不算数"+"，但把你叫回 U"+"21 的那份名单"+"上写的就是这个三"+'。','other':"半个赛季你进了十"+"九个球。所有人都"+"说这不算数，但把"+"你叫回 U21 "+"的那份名单上写的"+"就是这十九个。"})};
}
    },
    {
        'p': function(p){return f(0.5,[[p["guanxi"],45,0.008]],0.2,0.9);
},
        'label': "申请跟一线队练",
        'hint': function(p,q){return g(q,'被留下','被当成不懂事');
},
        'apply': function(p,q,s){
return d(q,s)?{'ovr':0x3,'guanxi':0x6,'text':"他们让你去当了三周陪练。三周里你没碰到几个球，可你终于知道，那个速度是什么样。"}:{'guanxi':-0x8,'ovr':-0x1,'text':"回复只有一句：「先把该踢的踢好。」那句话贴在你脑子里，两年没揭下来。"};
}
    }
  ]
},

// ---- idx:159 | aca_benc | 一线队的替补名单 ----
{
  'id': "aca_benc"+"h_firstt"+"eam",
  'title': "一线队的替补名单",
  'icon': '📝',
  'weight': 0x30,
  'stage': "youth",
  'when': function(p){
return p["inAcadem"+'y'];
},
  'desc': "杯赛轮换，一线队缺人，你进了替补名单。整场坐到第 91 分钟，热身衣脱了又穿上，穿了又脱，三次。",
  'options': [
    {
        'p': function(p){return f(0.5,[[p["guanxi"],45,0.008]],0.2,0.9);
},
        'label': "赛后去找主帅要一"+'句话',
        'hint': function(p,q){return g(q,'记住了你','什么也没发生');
},
        'apply': function(p,q,s){
return d(q,s)?{'guanxi':0xc,'ovr':0x2,'text':"他只说了句「下次」。那两个字你嚼了一整个夏天。第二年，它真的兑现了。"}:{'guanxi':-0x4,'text':"他正被记者围着，经过你身边时，点了一下头。你不确定，那一下是不是点给你看的。"};
}
    },
    {
        'label': "什么也不说，回去"+'练',
        'hint': "能力+2",
        'apply': function(){
return{'ovr':0x2,'clean':0x4,'text':"第二天，你第一个到基地。没有人看见，但那一年，你的体能数据是全梯队第一。"};
}
    }
  ]
},

// ---- idx:160 | aca_fami | 家里问什么时候签 ----
{
  'id': "aca_fami"+"ly_call",
  'title': "家里问什么时候签",
  'icon': '📱',
  'weight': 0x2e,
  'stage': "youth",
  'when': function(p){
return p["inAcadem"+'y'];
},
  'desc': "又一年过去。电话里，家里没直说，只问一句「今年有消息吗」。你说快了。挂断之后，你在楼道里站了很久。",
  'options': [
    {
        'label': "再给自己一年",
        'hint': "能力+2，家里那"+"头先扛着",
        'apply': function(){
return{'ovr':0x2,'money':-0xc,'text':"你没说，自己已经是队里年纪最大的一档。第二年，你把每一堂训练课，都当成最后一堂来练。"};
}
    },
    {
        'label': "开始联系别的出路",
        'hint': "关系+，心散了一"+'点',
        'apply': function(){
return{'guanxi':0xa,'ovr':-0x1,'text':"你托人问了几家低级别球队。消息还没回来，那几个礼拜，你训练时总在走神。"};
}
    }
  ]
},

// ---- idx:161 | aca_abr_ | 宿舍楼空了 ----
{
  'id': "aca_abr_"+"alone",
  'title': "宿舍楼空了",
  'icon': '🌃',
  'weight': 0x34,
  'stage': "youth",
  'repeat': 0x2,
  'when': function(p){
return p["inAcadem"+'y']&&!p["inChina"];
},
  'desc': "赛季间歇，本地孩子都回家了。整栋青训公寓，只剩你和一个尼日利亚人。食堂只开一个窗口。",
  'options': [
    {
        'label': "两个人一起加练",
        'hint': "能力+3，关系+",
        'apply': function(){
return{'ovr':0x3,'guanxi':0x6,'text':"你们自己打开训练场的灯，一直练到管理员来赶人。很多年后他在另一个联赛踢球，还会给你发消息。"};
}
    },
    {
        'label': "把这几天用来休息",
        'hint': "能力+1，身体缓"+'过来',
        'apply': function(){
return{'ovr':0x1,'clean':0x4,'text':"你睡了三天。然后一个人坐火车去看海。回来的那天，你觉得还能再熬一年。"};
}
    }
  ]
},

// ---- idx:162 | aca_abr_ | 满十八岁那道关 ----
{
  'id': "aca_abr_"+"visa",
  'title': "满十八岁那道关",
  'icon': '🛂',
  'weight': 0x32,
  'stage': "youth",
  'when': function(p){
return p["inAcadem"+'y']&&!p["inChina"];
},
  'desc': "满十八岁那年，要重新办工作许可。条件里有一条：国家队出场纪录——而你一场都没有。俱乐部的法务说，只能走特殊人才那条路，材料摞得很厚。",
  'options': [
    {
        'label': "俱乐部替你申请",
        'hint': "关系+，欠了人情",
        'apply': function(){
return{'guanxi':0xa,'ovr':0x1,'clean':-0x4,'text':"他们真的替你办了，代价是合同年限又延了两年。签合同的时候，你身边没有律师。"};
}
    },
    {
        'label': "先去邻国那支合作"+'球会',
        'hint': "能力+2，绕了一"+'圈',
        'apply': function(){
return{'ovr':0x2,'guanxi':-0x4,'text':"你去了邻国的二级联赛，那边不卡这条。一年后回来，身份问题解决了，人也大了一岁。"};
}
    }
  ]
},

// ---- idx:163 | aca_cn_s | 梯队里的老队员 ----
{
  'id': "aca_cn_s"+"tuck",
  'title': "梯队里的老队员",
  'icon': '🧊',
  'weight': 0x34,
  'stage': "youth",
  'repeat': 0x2,
  'when': function(p){
return p["inAcadem"+'y']&&p["inChina"];
},
  'cn': !0x0,
  'desc': "梯队里比你小三岁的孩子，已经去跟一线队合练了，而你还在这儿。队里人管你叫「老人」——那不是好话。",
  'options': [
    {
        'label': "找人问问能不能走",
        'hint': "关系+，可能走成",
        'apply': function(){
return{'guanxi':0xc,'ovr':-0x1,'money':-0xf,'text':"托的人说会留意。半年里来了两回消息：一回是中乙，一回是没了下文。"};
}
    },
    {
        'label': "闷头再练一年",
        'hint': "能力+3",
        'apply': function(){
return{'ovr':0x3,'clean':0x5,'text':"你把那句「老人」当成每天起床的理由。那一年你的数据是梯队里最好的，名单上，依然没有你。"};
}
    }
  ]
},

// ---- idx:164 | aca_cn_s | 回去读书还来得及 ----
{
  'id': "aca_cn_s"+"chool",
  'title': "回去读书还来得及",
  'icon': '🎓',
  'weight': 0x30,
  'stage': "youth",
  'when': function(p){
return p["inAcadem"+'y']&&p["inChina"];
},
  'cn': !0x0,
  'desc': "同批被刷掉的几个都回了学校，其中一人考上了体育院校。家里把那条消息转给你，后面附了一句：「你自己想想。」",
  'options': [
    {
        'label': "白天练，晚上补课",
        'hint': "能力+1，多一条"+'退路',
        'apply': function(){
return{'ovr':0x1,'degree':!0x0,'money':-0x14,'text':"你两头都占着，两头都不够好。可很多年后，你庆幸自己留了那条路。"};
}
    },
    {
        'label': "只走这一条路",
        'hint': "能力+3，没有别"+"的可想",
        'apply': function(){
return{'ovr':0x3,'clean':0x4,'text':"你把课本收进箱子，塞到床底。那之后，训练场上没人比你到得更早。"};
}
    }
  ]
}

];
