// auto-generated by split_events.py - edit events here, then run build_events.py

var EVT_att=[

// ---- idx:119 | att_offb | 无球跑动 ----
{
  'id': "att_offb"+"all",
  'title': "无球跑动",
  'icon': '👟',
  'weight': 0x37,
  'when': function(p){
return "att"===p["posGroup"];
},
  'desc': "外教说，球在你脚下时你什么都会，球不在时，你什么都不做。",
  'options': [
    {
        'label': "从头练跑位",
        'hint': "能力+5，前半年"+"不进球",
        'apply': function(){
return{'ovr':0x3,'fame':-0x6,'text':"他让你每场只做一件事：在球到之前，先到。半个赛季没进球，之后进了十一个。"};
}
    },
    {
        'p': function(p){return f(0.5,[[p["ovr"],60,0.008]],0.2,0.9);
},
        'label': "等球来",
        'hint': function(p,q){return g(q,'还是那个样','被换位置');
},
        'apply': function(p,q,s){
return d(q,s)?{'fame':0x5,'text':"你还是那种拿球才踢的前锋。在国内够用，出去就不够。"}:{'roleDelta':-0x2,'ovr':-0x1,'text':"教练把你挪到边路，说那儿跑得少一点。"};
}
    }
  ]
},

// ---- idx:120 | att_drou | 十场不进球 ----
{
  'id': "att_drou"+"ght",
  'title': "十场不进球",
  'icon': '🥀',
  'weight': 0x37,
  'when': function(p){
return "att"===p["posGroup"];
},
  'desc': "十场了。你每次拿球，看台上都有人叹气。",
  'options': [
    {
        'p': function(p){return f(0.7,[[p["talent"],1,0.4]],0.2,0.9);
},
        'label': "加练射门",
        'hint': function(p,q){return g(q,'破荒','越练越死');
},
        'apply': function(p,q,s){
return d(q,s)?{'ovr':0x3,'fame':0xc,'text':"第十一场，你打进一个不算漂亮的球，跪在草地上，很久没起来。"}:{'ovr':-0x3,'roleDelta':-0x1,'text':"训练里你能进一百个，比赛里一个都进不了。教练换了首发。"};
}
    },
    {
        'label': "去干别的",
        'hint': "能力+2，进球更"+'少',
        'apply': function(){
return{'ovr':0x2,'fame':-0x6,'text':"你开始回撤接球，把球做给别人。助攻多了三次，进球还是零。"};
}
    }
  ]
},

// ---- idx:121 | att_dive | 禁区里那一下 ----
{
  'id': "att_dive",
  'title': "禁区里那一下",
  'icon': '🎭',
  'weight': 0x32,
  'when': function(p){
return "att"===p["posGroup"];
},
  'desc': "后卫的手确实碰到了你，但还不至于倒。你在空中有半秒，可以决定。",
  'options': [
    {
        'p': function(p){return f(0.6,[[p["clean"],70,0.008]],0.2,0.9);
},
        'label': "倒下去",
        'hint': function(p,q){return g(q,'判点','假摔被罚');
},
        'apply': function(p,q,s){
return d(q,s)?{'clean':-0x8,'fame':0x8,'mult':{'league':1.2},'text':"点球。你罚进了。慢镜头放出来以后，对方球迷给你起了个外号。"}:{'clean':-0x8,'fame':-0xe,
'banGames':0x1,'text':"主裁掏了黄牌，假摔。这张牌，让你在关键战停赛。"};
}
    },
    {
        'label': '站住',
        'hint': "清白+，机会没了",
        'apply': function(){
return{'clean':0x6,'fame':0x4,'text':"你踉跄两步，没倒，球也没了。解说说了句：「这球要是倒了，就是点球。」"};
}
    }
  ]
},

// ---- idx:122 | att_pena | 点球归谁 ----
{
  'id': "att_pena"+"lty_take"+'r',
  'title': "点球归谁",
  'icon': '⚪',
  'weight': 0x30,
  'when': function(p){
return "att"===p["posGroup"];
},
  'desc': "队里的点球一直归队长。这赛季他罚丢两个，更衣室里开始有人议论。",
  'options': [
    {
        'p': function(p){return f(0.6,[[p["guanxi"],45,0.008]],0.2,0.9);
},
        'label': '去要',
        'hint': function(p,q){return g(q,'拿到主罚权','他翻脸');
},
        'apply': function(p,q,s){
return d(q,s)?{'fame':0xc,'ovr':0x2,'text':"接下来五个点球，你全部罚进。金靴榜上，你第一次进了前三。"}:{'guanxi':-0xa,'roleDelta':-0x1,'text':"他当着全队的面，把球从你手里拿走。那场之后，你们再没说过话。"};
}
    },
    {
        'label': '不争',
        'hint': "关系+",
        'apply': function(){
return{'guanxi':0xa,'text':"你说谁罚都行，进了就好。更衣室里，没人跟你红过脸。"};
}
    }
  ]
},

// ---- idx:123 | att_numb | 九号球衣 ----
{
  'id': "att_numb"+"er9",
  'title': "九号球衣",
  'icon': "9️⃣",
  'weight': 0x2d,
  'when': function(p){
return "att"===p["posGroup"];
},
  'desc': "队里的九号退役了。这件球衣在这家俱乐部意味着什么，不用人说。",
  'options': [
    {
        'p': function(p){return f(0.6,[[p["fame"],25,0.01]],0.2,0.9);
},
        'label': '穿上',
        'hint': "名气大涨，压力也"+'大',
        'odds': ["扛住了","压垮了"],
        'apply': function(p,q,s){
return d(q,s)?{'fame':0x16,'ovr':0x2,'text':"你穿着它进了二十个。已经有小孩，在球衣背后印你的名字。"}:{'fame':-0xc,'ovr':-0x2,'roleDelta':-0x1,'text':"半个赛季，七个球。看台上开始有人喊：「把九号还回来。」"};
}
    },
    {
        'label': "留着自己的号",
        'hint': "无变化",
        'apply': function(){
return{'text':"你说号码不重要。那件九号，在队里空了三年，没人敢要。"};
}
    }
  ]
},

// ---- idx:124 | att_drop | 回撤拿球 ----
{
  'id': "att_drop"+"deep",
  'title': "回撤拿球",
  'icon': '🔄',
  'weight': 0x2d,
  'when': function(p){
return "att"===p["posGroup"];
},
  'desc': "球队的进攻打不上来。教练想让你退到中场接球，再自己带上去。",
  'options': [
    {
        'label': "退到中场",
        'hint': "能力+4，进球少"+'一半',
        'apply': function(){
return{'ovr':0x4,'fame':-0x8,'text':"你成了球队的出球点，也成了不进球的中锋。教练很满意，记者不满意。"};
}
    },
    {
        'p': function(p){return f(0.5,[[p["ovr"],60,0.008]],0.2,0.9);
},
        'label': "守着禁区",
        'hint': function(p,q){return g(q,'等到了机会','一场碰不到球');
},
        'apply': function(p,q,s){
return d(q,s)?{'fame':0xa,'ovr':0x1,'text':"你一场只碰九次球，进了两个。有人管这个叫效率。"}:{'ovr':-0x1,'roleDelta':-0x1,'text':"整场比赛你触球十一次，其中六次，是开球。"};
}
    }
  ]
},

// ---- idx:125 | att_head | 站桩中锋 ----
{
  'id': "att_head"+"er_targe"+'t',
  'title': "站桩中锋",
  'icon': '🗼',
  'weight': 0x2d,
  'when': function(p){
return "att"===p["posGroup"];
},
  'desc': "教练想把你练成支点：背身拿球，头球做球，牺牲你自己的机会。",
  'options': [
    {
        'label': "干这个脏活",
        'hint': "能力+4，队友受"+'益',
        'apply': function(){
return{'ovr':0x4,'guanxi':0xa,'fame':-0x5,'text':"一个赛季，你头球做球四十次，进球只有六个。边锋拿了金靴，赛后第一个来谢你。"};
}
    },
    {
        'p': function(p){return f(0.55,[[p["ovr"],60,0.008]],0.2,0.9);
},
        'label': "我要进球",
        'hint': function(p,q){return g(q,'进球更多','被弃用');
},
        'apply': function(p,q,s){
return d(q,s)?{'fame':0xe,'ovr':0x2,'text':"你进了十五个。教练承认，那套支点战术不适合你。"}:{'roleDelta':-0x2,'text':"你既没做球，也没进球。教练买了个真正的支点。"};
}
    }
  ]
},

// ---- idx:126 | att_big_ | 大场面 ----
{
  'id': "att_big_"+"game",
  'title': "大场面",
  'icon': '🎪',
  'weight': 0x30,
  'when': function(p){
return "att"===p["posGroup"]&&p["roleRank"]>=0x2;
},
  'desc': "有个说法跟了你几年：小场面你什么都行，大场面就找不到你。这次是决赛。",
  'options': [
    {
        'p': function(p){return f(0.55,[[p["ovr"],60,0.008]],0.2,0.9);
},
        'label': "自己扛",
        'hint': function(p,q){return g(q,'一战成名','坐实说法');
},
        'apply': function(p,q,s){
return d(q,s)?{'ovr':0x3,'fame':0x1e,'mult':{'cup':0x3,'league':1.5},'text':"你进了两个。赛后记者提起那个说法，你说你不记得了。"}:{'fame':-0x12,'ovr':-0x2,
'text':"你被换下时是第 63 分钟。那个说法，从此变成了事实。"};
}
    },
    {
        'label': "踢简单点",
        'hint': "名气小涨，稳",
        'apply': function(){
return{'fame':0x6,'guanxi':0x6,'text':"你没做任何冒险动作，也没犯错。球队赢了，庆祝照片里，你站在最边上。"};
}
    }
  ]
}

];
