// auto-generated by split_events.py - edit events here, then run build_events.py
// 属性差分事件（名气/关系/清白/队内地位）：按 国内/国外 × 青训/成年/老将 × 年龄/OVR 分档。
// 每条 when 做档位门；概率选项用 f(base,[[p[attr],阈值,每点]]) 让高/低档位产生可感知分叉；
// apply 成功给属性正反馈、失败给惩罚，并按档位软失败兜底。
// 引擎侧已让四项产生后果：关系→角色/工资(aI)；名气→工资议价(_wageOf)；
//   清白→丑闻/代言(_cleanSettle)；地位→大场面参与(_bmPlayerProb)。

var EVT_attr=[

// ---- idx:454 | gx_cn_invite | 一个电话 ----
{
  'id': "gx_cn_inv"+'ite',
  'title': "一个电话",
  'icon': '📞',
  'weight': 0x28,
  'stage': "prime",
  'cn': !0x0,
  'desc': function(p){return p["guanxi"]>=0x3c
    ?"老领队退休前把一个号码塞给你：「有事找他，就说我让的。」你把纸条攥了两条街，纸边被汗浸软了。"
    :"同批的人陆续都有人往里递话，只有你，电话簿上没有一个能拨的号。";},
  'options': [
    {'label': "打这个电话", 'hint': function(p,q){return g(q,'那边答应递个话','对面只是客气两句');},
     'p': function(p){return f(0.42,[[p["guanxi"],0x32,0.012]],0.15,0.9);},
     'apply': function(p,q,s){return d(q,s)
       ?{'roleDelta':0x1,'guanxi':0x4,'ovr':0x2,'text':"名单比预想早了两周。教练组开会时，有人提了你的名字。"}
       :{'guanxi':-0x8,'clean':-0x4,'text':"话递到了，对面只是客气。你欠了个人情，还被人记在了本子上。"};}},
    {'label': "把号码收起来，自己加练", 'hint': "能力+，地位+", 'apply': function(){return{'ovr':0x3,'roleDelta':0x1,'guanxi':-0x2,'text':"你把纸条夹进训练日记。两个月后，体测数据替你说了话。"};}}
  ]
},

// ---- idx:455 | gx_cn_youth_coach | 教练的偏爱 ----
{
  'id': "gx_cn_youth"+'_coach',
  'title': "教练的偏爱",
  'icon': '🧑‍🏫',
  'weight': 0x28,
  'stage': "youth",
  'cn': !0x0,
  'desc': "梯队教练把加练的钥匙给了几个人，没给你。他说这不叫偏心，叫「看谁顺眼」。",
  'options': [
    {'label': "主动去蹭加练", 'hint': function(p,q){return g(q,'教练点了头','被赶了回来');},
     'p': function(p){return f(0.4,[[p["guanxi"],0x28,0.01]],0.15,0.88);},
     'apply': function(p,q,s){return d(q,s)
       ?{'ovr':0x3,'guanxi':0x6,'text':"你连着去了两周，教练把钥匙配了一把给你。「别到处说。」"}
       :{'guanxi':-0x2,'ovr':0x1,'text':"你去了几次，都被门卫拦在外面。你改成在操场外的路灯下练球感。"};}},
    {'label': "跟教练把话挑明", 'hint': "关系+或-，地位+", 'apply': function(p){return p["guanxi"]>=0x32
       ?{'guanxi':0x4,'roleDelta':0x1,'text':"你把话说得直。教练愣了愣，笑了：「有点意思。」第二天你进了主力组。"}
       :{'guanxi':-0x6,'ovr':0x2,'text':"你话说急了。教练记了你一个「不好带」。你只能踢得更狠。"};}}
  ]
},

// ---- idx:456 | gx_abr_locker | 更衣室 ----
{
  'id': "gx_abr_lock"+'er',
  'title': "更衣室",
  'icon': '🚪',
  'weight': 0x28,
  'stage': "prime",
  'when': function(p){return !p["inChina"];},
  'desc': function(p){return p["guanxi"]>=0x3c
    ?"队友开始用你的外号叫你，训练里愿意把球交到你脚下。你终于听懂了更衣室里一半的笑话。"
    :"战术板上的东西你靠猜，队友的笑话你只能跟着笑。你在自己的更衣室里，像个客人。";},
  'options': [
    {'label': "张罗一次全队聚餐", 'hint': function(p,q){return g(q,'这下算自己人了','花了不少，还是很生');},
     'p': function(p){return f(0.45,[[p["guanxi"],0x32,0.012]],0.15,0.9);},
     'apply': function(p,q,s){return d(q,s)
       ?{'guanxi':0xa,'money':-0x28,'text':"你请了全队。有人教你说当地的干杯，你学得很认真，发音很烂，全桌都在鼓掌。"}
       :{'guanxi':0x2,'money':-0x3c,'clean':0x2,'text':"你请了全队。他们来了，吃得很快，走得也早。第二天照旧。"};}},
    {'label': "把精力全放训练上", 'hint': "能力+，关系-", 'apply': function(){return{'ovr':0x3,'guanxi':-0x4,'text':"你成了队里最早到、最晚走的人。他们叫你「机器」，语气里有敬意，也有距离。"};}}
  ]
},

// ---- idx:457 | gx_abr_youth_host | 寄宿家庭 ----
{
  'id': "gx_abr_youth"+'_host',
  'title': "寄宿家庭",
  'icon': '🏠',
  'weight': 0x28,
  'stage': "youth",
  'when': function(p){return !p["inChina"]&&p["_liveChain"]==="host";},
  'desc': "青训营把你安排在一对老夫妇家里。房东太太每天给你留一盏灯和一碗热汤，也每天问你「今天有没有交到朋友」。",
  'options': [
    {'label': "把队友请到家里", 'hint': function(p,q){return g(q,'生日会来了半支梯队','只有房东夫妇');},
     'p': function(p){return f(0.45,[[p["guanxi"],0x28,0.012]],0.15,0.9);},
     'apply': function(p,q,s){return d(q,s)
       ?{'guanxi':0xa,'clean':0x4,'text':"你过生日那天，房东太太烤了蛋糕。来了半个梯队的人，队长把奶油抹了你一脸。"}
       :{'guanxi':0x2,'clean':0x4,'text':"没人来。房东太太把蛋糕切了一半放进冰箱，说，明天带给队友也行。"};}},
    {'label': "一个人待着，练语言", 'hint': "能力+，关系-", 'apply': function(){return{'ovr':0x2,'guanxi':-0x2,'talent':0.02,'text':"你认识了超市里的每一个单词。半年后，你能听懂教练的整段战术布置了。"};}}
  ]
},

// ---- idx:458 | gx_cn_vet_media | 名宿的分量 ----
{
  'id': "gx_cn_vet_me"+'dia',
  'title': "名宿的分量",
  'icon': '🎙️',
  'weight': 0x28,
  'stage': "vet",
  'cn': !0x0,
  'when': function(p){return p["guanxi"]>=0x28;},
  'desc': "一档足球节目请你做嘉宾。主持人是个老名宿，开口第一句就是：「这孩子，我认识。」",
  'options': [
    {'label': "顺着他的话往下说", 'hint': function(p,q){return g(q,'节目火了，你也成了自己人','被说成蹭热度');},
     'p': function(p){return f(0.5,[[p["guanxi"],0x32,0.01],[p["fame"],0x32,0.006]],0.2,0.9);},
     'apply': function(p,q,s){return d(q,s)
       ?{'guanxi':0x8,'fame':0x8,'text':"老名宿在节目里替你说了很多好话。第二天，那段视频在球迷群里转疯了。"}
       :{'fame':-0x4,'clean':-0x2,'text':"有人截图说你套近乎。老名宿没接话，你坐在那儿，笑得很勉强。"};}},
    {'label': "只谈战术，不攀交情", 'hint': "地位+，名气+", 'apply': function(){return{'roleDelta':0x1,'fame':0x4,'ovr':0x1,'text':"你把一段战术讲得清楚。老名宿愣了一下：「这孩子，是真懂球。」"};}}
  ]
},

// ---- idx:459 | gx_abr_prime_agent | 换条门路 ----
{
  'id': "gx_abr_prime"+'_agent',
  'title': "换条门路",
  'icon': '💼',
  'weight': 0x28,
  'stage': "prime",
  'when': function(p){return !p["inChina"];},
  'desc': "有人给你介绍一个「很有办法」的经纪人：他能把电话打到主管办公室，也能把电话打到不该打的地方。",
  'options': [
    {'label': "换他来运作", 'hint': function(p,q){return g(q,'门路真宽','被带进沟里');},
     'p': function(p){return f(0.4,[[p["guanxi"],0x32,0.011]],0.15,0.88);},
     'apply': function(p,q,s){return d(q,s)
       ?{'guanxi':0xc,'money':0x3c,'fame':0x4,'text':"两周内，两份报价摆到了桌上。你第一次觉得，有些门是要靠人推开的。"}
       :{'guanxi':-0xa,'clean':-0x6,'money':-0x1e,'text':"他收了佣金就没影了。后来你才知道，他同时也在替你的对手办事。"};}},
    {'label': "留在原经纪人身边", 'hint': "清白+，名气-", 'apply': function(){return{'clean':0x4,'fame':-0x2,'guanxi':0x2,'text':"你留下了。原经纪人话不多，但每个条款都替你抠。你睡得踏实。"};}}
  ]
},

// ---- idx:460 | gx_cn_prime_captain | 队长之争 ----
{
  'id': "gx_cn_prime"+'_captain',
  'title': "队长之争",
  'icon': '🅲',
  'weight': 0x28,
  'stage': "prime",
  'cn': !0x0,
  'when': function(p){return p["roleRank"]>=0x2;},
  'desc': "老队长要走。更衣室里分成两拨，一拨等着你说话，一拨等着看你怎么收场。",
  'options': [
    {'label': "挨个找队友谈", 'hint': function(p,q){return g(q,'队友都点了头','有人当面翻了脸');},
     'p': function(p){return f(0.45,[[p["guanxi"],0x32,0.012]],0.15,0.9);},
     'apply': function(p,q,s){return d(q,s)
       ?{'guanxi':0xa,'roleDelta':0x1,'text':"你把每个人的心思都聊了一遍。投票那天，几乎没人反对。"}
       :{'guanxi':-0x8,'roleDelta':-0x1,'text':"有人把你找他谈话的事捅了出去，说你拉帮结派。你解释不清。"};}},
    {'label': "让教练直接宣布", 'hint': "地位+，关系-", 'apply': function(){return{'roleDelta':0x1,'guanxi':-0x4,'text':"教练在战术会上直接点名。袖标戴上了，可你总觉得背后有眼睛。"};}}
  ]
},

// ---- idx:461 | gx_abr_young_lang | 语言课 ----
{
  'id': "gx_abr_young_"+'lang',
  'title': "语言课",
  'icon': '🗣️',
  'weight': 0x28,
  'stage': "youth",
  'when': function(p){return !p["inChina"];},
  'desc': "俱乐部给你排了语言课，一周三次。老师说，你要么把舌头练顺，要么把板凳坐穿。",
  'options': [
    {'label': "每天多加一小时", 'hint': function(p,q){return g(q,'能跟队友开玩笑了','还是只会点头');},
     'p': function(p){return f(0.5,[[p["guanxi"],0x28,0.012]],0.2,0.9);},
     'apply': function(p,q,s){return d(q,s)
       ?{'guanxi':0x8,'ovr':0x1,'text':"三个月后，你在更衣室讲出了第一个让人发笑的笑话。那天你才算真的到了这儿。"}
       :{'ovr':0x2,'guanxi':0x2,'text':"你还是习惯用脚说话。教练喊你名字的速度，倒是快了一点。"};}},
    {'label': "把时间用来练身体", 'hint': "能力+，关系-", 'apply': function(){return{'ovr':0x3,'guanxi':-0x2,'text':"你把语言课请了假。身体是练出来了，可战术会上你还是只能猜。"};}}
  ]
},

// ---- idx:462 | gx_cn_favor | 人情到期 ----
{
  'id': "gx_cn_fav"+'or',
  'title': "人情到期",
  'icon': '🤝',
  'weight': 0x28,
  'stage': "prime",
  'cn': !0x0,
  'when': function(p){return p["guanxi"]>=0x3c;},
  'desc': "当年帮过你的那位，如今找上门了。他要你在媒体上替一个后辈说句话——那后辈，抢的正是你的位置。",
  'options': [
    {'label': "还这个人情", 'hint': function(p,q){return g(q,'对方记你一辈子','被后辈顶了位置');},
     'p': function(p){return f(0.5,[[p["guanxi"],0x3c,0.011]],0.2,0.9);},
     'apply': function(p,q,s){return d(q,s)
       ?{'guanxi':0xa,'clean':0x2,'text':"你说那句话时没犹豫。后来那后辈每次见面都叫你一声哥，是真心的。"}
       :{'guanxi':0x2,'roleDelta':-0x1,'clean':0x2,'text':"话你说了，位置也丢了。你没后悔，只是那天回家开了很久的车。"};}},
    {'label': "婉拒，说自己不方便", 'hint': "地位+，关系-", 'apply': function(){return{'roleDelta':0x1,'guanxi':-0x6,'text':"你说自己状态不好，不方便开口。对方说「理解」，语气你懂。"};}}
  ]
},

// ---- idx:463 | gx_abr_community | 街坊 ----
{
  'id': "gx_abr_community",
  'title': "街坊",
  'icon': '🏙️',
  'weight': 0x28,
  'stage': "prime",
  'when': function(p){return !p["inChina"];},
  'desc': "训练基地旁边的小店老板认得你了，每次都多给你一份。他说，这条街的人都在看你踢球。",
  'options': [
    {'label': "常去社区活动", 'hint': function(p,q){return g(q,'成了这条街的熟人','去了几次就没再去');},
     'p': function(p){return f(0.5,[[p["guanxi"],0x28,0.012]],0.2,0.9);},
     'apply': function(p,q,s){return d(q,s)
       ?{'guanxi':0x8,'fame':0x6,'clean':0x2,'text':"你陪着孩子们踢了一下午。第二天，整条街的窗户上都贴了你的海报。"}
       :{'guanxi':0x2,'text':"你去了几次。语言不通，孩子们围着你要签名，你只知道笑。"};}},
    {'label': "少抛头露面", 'hint': "能力+，名气-", 'apply': function(){return{'ovr':0x2,'fame':-0x4,'text':"你把周末都留给了恢复训练。球探的报告上写着：专注。"};}}
  ]
},

// ---- idx:464 | gx_cn_suspicion | 口风 ----
{
  'id': "gx_cn_suspic"+'ion',
  'title': "口风",
  'icon': '🤫',
  'weight': 0x28,
  'stage': "prime",
  'cn': !0x0,
  'desc': "赛前有人拍着你的肩膀，说了句「今天天气不错」。你懂这句话的意思，也知道听懂这句话意味着什么。",
  'options': [
    {'label': "接话，探他的底", 'hint': function(p,q){return g(q,'套出了名字','被反将一军');},
     'p': function(p){return f(0.4,[[p["guanxi"],0x28,0.011]],0.15,0.85);},
     'apply': function(p,q,s){return d(q,s)
       ?{'guanxi':0x8,'clean':-0x4,'text':"你顺着话往下聊，记住了那两个名字。你知道了一些不该知道的事。"}
       :{'clean':-0x6,'guanxi':-0x6,'text':"你的试探太生。对方笑笑走了，赛前的更衣室里，气氛怪了一整年。"};}},
    {'label': "装没听见", 'hint': "清白+，关系-", 'apply': function(){return{'clean':0x4,'guanxi':-0x4,'ovr':0x1,'text':"你戴上耳机走开了。那场球你踢得很干净，也很闷。"};}}
  ]
},

// ---- idx:465 | gx_abr_network | 华裔社区 ----
{
  'id': "gx_abr_netw"+'ork',
  'title': "华裔社区",
  'icon': '🏮',
  'weight': 0x28,
  'stage': "vet",
  'when': function(p){return !p["inChina"]&&p["guanxi"]>=0x28;},
  'desc': "当地华裔社区要办一场义赛，请你当队长。邀请函上写着：让这里的孩子看看，我们也能踢出来。",
  'options': [
    {'label': "去，当这个队长", 'hint': function(p,q){return g(q,'满场都是你的名字','雨里踢了九十分钟');},
     'p': function(p){return f(0.5,[[p["guanxi"],0x28,0.012]],0.2,0.9);},
     'apply': function(p,q,s){return d(q,s)
       ?{'guanxi':0xa,'fame':0x6,'clean':0x4,'text':"看台被国旗铺满。有个孩子举着牌子：我也要出国踢球。"}
       :{'guanxi':0x4,'clean':0x4,'text':"那天下大雨，来的不到一百人。你把球衣挨个签完才走。"};}},
    {'label': "婉拒，腿要保养", 'hint': "能力+，关系-", 'apply': function(){return{'ovr':0x2,'guanxi':-0x4,'text':"你让队医开了张单子。邀请函被你压在了抽屉最下面。"};}}
  ]
},

// ---- idx:466 | fm_cn_sponsor | 本地广告 ----
{
  'id': "fm_cn_spons"+'or',
  'title': "本地广告",
  'icon': '📣',
  'weight': 0x2a,
  'stage': "prime",
  'cn': !0x0,
  'desc': "一家本地食品厂想找你拍广告。钱不多，但那是你第一次被印在包装袋上。",
  'options': [
    {'label': "接，认真拍", 'hint': function(p,q){return g(q,'包装袋卖断货','被队友笑了半年');},
     'p': function(p){return f(0.5,[[p["fame"],0x1e,0.01]],0.2,0.9);},
     'apply': function(p,q,s){return d(q,s)
       ?{'money':0x28,'fame':0x6,'text':"包装袋上你的名字被印得比产品名还大。你妈买了一箱，分给整条街。"}
       :{'money':0x14,'fame':0x2,'text':"广告拍得很土，队友笑了你半年。但钱到账那天，你给家里打了电话。"};}},
    {'label': "先专注踢球", 'hint': "能力+，名气-", 'apply': function(){return{'ovr':0x2,'fame':-0x2,'text':"你把合同推了。教练知道后，多看了你两眼。"};}}
  ]
},

// ---- idx:467 | fm_cn_brand | 国民品牌 ----
{
  'id': "fm_cn_br"+'and',
  'title': "国民品牌",
  'icon': '🥤',
  'weight': 0x30,
  'stage': "prime",
  'cn': !0x0,
  'when': function(p){return p["fame"]>=0x46;},
  'desc': "一线品牌找上门，价钱后面带着一串零。合同很厚，其中一页写着：不得出现任何负面新闻。",
  'options': [
    {'label': "签，把形象也当成工作", 'hint': function(p,q){return g(q,'成了国民面孔','一次失言全砸了');},
     'p': function(p){return f(0.55,[[p["fame"],0x46,0.008],[p["clean"],0x46,0.006]],0.2,0.92);},
     'apply': function(p,q,s){return d(q,s)
       ?{'money':0x64,'fame':0xc,'clean':0x2,'text':"你成了广告里的熟脸。你不知道，从此在球场上每一次失态都会被放大十倍。"}
       :{'money':0x32,'fame':-0x6,'text':"一年后你的一次争执上了热搜。品牌方撤了海报，赔偿条款扣的钱比代言费还多。"};}},
    {'label': "只签一年，先看看", 'hint': "名气+，钱少", 'apply': function(){return{'money':0x1e,'fame':0x4,'clean':0x2,'text':"你把长约换成了短约。经纪人说你傻，可你觉得，脚底下的东西更实在。"};}}
  ]
},

// ---- idx:468 | fm_abr_brand | 国际品牌 ----
{
  'id': "fm_abr_br"+'and',
  'title': "国际品牌",
  'icon': '👟',
  'weight': 0x30,
  'stage': "prime",
  'when': function(p){return !p["inChina"]&&p["fame"]>=0x3c;},
  'desc': "某个运动品牌想签你做区域代言。海报会挂在几条街的橱窗里，旁边是他们的头牌。",
  'options': [
    {'label': "接下，把自己当品牌经营", 'hint': function(p,q){return g(q,'上了全球广告','被当成陪衬');},
     'p': function(p){return f(0.5,[[p["fame"],0x3c,0.009]],0.2,0.9);},
     'apply': function(p,q,s){return d(q,s)
       ?{'money':0x50,'fame':0xa,'text':"你的海报挂上了橱窗。有中国游客在下面拍照，你隔着玻璃看了很久。"}
       :{'money':0x28,'fame':0x4,'text':"你被安排在了海报最角落。但那张海报，你妈一直留着。"};}},
    {'label': "不接，专心恢复", 'hint': "能力+", 'apply': function(){return{'ovr':0x2,'fame':-0x4,'text':"你把档期推了，把夏天留给了健身房。新赛季，你的冲刺次数全队第一。"};}}
  ]
},

// ---- idx:469 | fm_cn_media | 舆论放大 ----
{
  'id': "fm_cn_me"+'dia',
  'title': "舆论放大",
  'icon': '📰',
  'weight': 0x2a,
  'stage': "prime",
  'cn': !0x0,
  'when': function(p){return p["fame"]>=0x32;},
  'desc': "你只是训练里摔了一跤，第二天的标题却是《核心球员伤退，球队前景成疑》。你盯着手机看了很久。",
  'options': [
    {'label': "发一条动态，把话说清", 'hint': function(p,q){return g(q,'把火压下去了','越描越黑');},
     'p': function(p){return f(0.5,[[p["fame"],0x32,0.008]],0.2,0.9);},
     'apply': function(p,q,s){return d(q,s)
       ?{'fame':0x4,'clean':0x2,'text':"你拍了自己的训练视频，配文两个字：没事。评论区安静了下去。"}
       :{'fame':-0x6,'clean':-0x2,'text':"你的回应被解读成傲慢。热搜挂了两天，队里让你以后少说话。"};}},
    {'label': "一个字都不回", 'hint': "能力+，地位+", 'apply': function(){return{'ovr':0x2,'roleDelta':0x1,'fame':-0x2,'text':"你关了手机，一头扎进训练。两天后，那条新闻没人再提。"};}}
  ]
},

// ---- idx:470 | fm_abr_press | 发布会 ----
{
  'id': "fm_abr_pre"+'ss',
  'title': "发布会",
  'icon': '🎤',
  'weight': 0x2a,
  'stage': "prime",
  'when': function(p){return !p["inChina"];},
  'desc': "输了球，记者把话筒塞到你面前。第一个问题是关于那次没传出去的单刀。",
  'options': [
    {'label': "把责任揽下来", 'hint': function(p,q){return g(q,'赢得尊重','被写成认怂');},
     'p': function(p){return f(0.5,[[p["fame"],0x28,0.008],[p["clean"],0x32,0.006]],0.2,0.9);},
     'apply': function(p,q,s){return d(q,s)
       ?{'fame':0x6,'guanxi':0x4,'clean':0x2,'text':"你说「那个球是我的」。第二天，队长在群里发了你这句话。"}
       :{'fame':-0x6,'guanxi':-0x2,'text':"你认了错，标题却写成《他承认自己不行了》。你捏紧了拳头。"};}},
    {'label': "把话题引向下一场", 'hint': "地位+，名气-", 'apply': function(){return{'roleDelta':0x1,'fame':-0x2,'text':"你只谈下一场。记者觉得无趣，教练觉得你稳。"};}}
  ]
},

// ---- idx:471 | fm_cn_fanclub | 球迷会 ----
{
  'id': "fm_cn_fan"+'club',
  'title': "球迷会",
  'icon': '🧣',
  'weight': 0x28,
  'stage': "prime",
  'cn': !0x0,
  'when': function(p){return p["fame"]>=0x28;},
  'desc': "客队球迷看台上有人举着你的名字。他坐了一千多公里，就为了看你一场球。",
  'options': [
    {'label': "赛后把球衣送过去", 'hint': function(p,q){return g(q,'那人哭了','球衣被转卖了');},
     'p': function(p){return f(0.55,[[p["fame"],0x28,0.008]],0.2,0.92);},
     'apply': function(p,q,s){return d(q,s)
       ?{'fame':0x6,'guanxi':0x4,'clean':0x2,'text':"你把球衣从头上脱下来递过去。周围全在鼓掌，你很累，但站得笔直。"}
       :{'fame':-0x4,'clean':-0x2,'text':"第二天你的球衣出现在网上，标价出售。举牌的人说那不是他。"};}},
    {'label': "冲看台鞠个躬就走", 'hint': "能力+，名气+", 'apply': function(){return{'ovr':0x2,'fame':0x2,'text':"你朝看台鞠了一躬。回到更衣室，你把这场球的技术统计看了三遍。"};}}
  ]
},

// ---- idx:472 | fm_abr_tabloid | 小报 ----
{
  'id': "fm_abr_tabl"+'oid',
  'title': "小报",
  'icon': '📸',
  'weight': 0x28,
  'stage': "prime",
  'when': function(p){return !p["inChina"]&&p["fame"]>=0x3c;},
  'desc': "狗仔拍到你和人吃饭的照片，配的标题很难听。照片里那人是你的队医。",
  'options': [
    {'label': "让俱乐部发律师函", 'hint': function(p,q){return g(q,'小报道歉了','被说成心虚');},
     'p': function(p){return f(0.5,[[p["fame"],0x3c,0.008],[p["clean"],0x46,0.006]],0.2,0.9);},
     'apply': function(p,q,s){return d(q,s)
       ?{'fame':0x4,'clean':0x3,'text':"小报删了稿并致歉。队友开玩笑说，你现在是有律师的人了。"}
       :{'fame':-0x6,'clean':-0x2,'text':"律师函发出去，围观的人更多了。那顿饭，后来被讲了整整一年。"};}},
    {'label': "不理会，训练场上见", 'hint': "地位+，能力+", 'apply': function(){return{'ovr':0x2,'roleDelta':0x1,'fame':-0x2,'text':"你一个字没回。周末你进了两个球，赛后只说了句「下一个」。"};}}
  ]
},

// ---- idx:473 | fm_cn_youth_hype | 被捧杀 ----
{
  'id': "fm_cn_youth_h"+'ype',
  'title': "被捧杀",
  'icon': '🌟',
  'weight': 0x28,
  'stage': "youth",
  'cn': !0x0,
  'desc': "一篇报道把你写成「十年一遇」。队友看你的眼神变了，教练在训练里却对你更凶了。",
  'options': [
    {'label': "把报道剪下来贴床头", 'hint': function(p,q){return g(q,'越踢越自信','被自己吓住');},
     'p': function(p){return f(0.5,[[p["fame"],0x1e,0.01],[p["talent"],1,0.3]],0.2,0.9);},
     'apply': function(p,q,s){return d(q,s)
       ?{'ovr':0x3,'fame':0x4,'text':"你把那句话当成了目标。半年后，你踢进了梯队一队。"}
       :{'ovr':-0x2,'fame':-0x4,'roleDelta':-0x1,'text':"你开始害怕踢不好。越怕越紧，教练把你放回了替补席。"};}},
    {'label': "把报道扔进垃圾桶", 'hint': "能力+，名气-", 'apply': function(){return{'ovr':0x3,'fame':-0x2,'clean':0x2,'text':"你只记住教练那三个字：还不够。你把加练时间又拉长了一小时。"};}}
  ]
},

// ---- idx:474 | fm_abr_youth_scout | 球探 ----
{
  'id': "fm_abr_youth_"+'scout',
  'title': "球探",
  'icon': '🔭',
  'weight': 0x28,
  'stage': "youth",
  'when': function(p){return !p["inChina"];},
  'desc': "看台角落里坐着几个穿风衣的人，笔记本从头翻到尾。你知道他们在看谁，也希望他们是在看你。",
  'options': [
    {'label': "把这场当成面试", 'hint': function(p,q){return g(q,'名字进了笔记本','太想表现，踢乱了');},
     'p': function(p){return f(0.48,[[p["ovr"],0x3c,0.008],[p["fame"],0x1e,0.006]],0.15,0.9);},
     'apply': function(p,q,s){return d(q,s)
       ?{'fame':0x8,'ovr':0x2,'text':"赛后有个风衣男在通道口等你，递了张名片。你攥着它,一路都没敢折。"}
       :{'ovr':-0x2,'fame':-0x2,'text':"你太想表现，几次该传的球自己打了。终场哨响，看台已经空了。"};}},
    {'label': "照常踢，不看他们", 'hint': "能力+，稳定", 'apply': function(){return{'ovr':0x3,'roleDelta':0x1,'text':"你把注意力全放在了比赛上。教练说，这是他见过你踢得最像样的一场。"};}}
  ]
},

// ---- idx:475 | fm_cn_vet_legend | 名宿 ----
{
  'id': "fm_cn_vet_le"+'gend',
  'title': "名宿",
  'icon': '🏛️',
  'weight': 0x2c,
  'stage': "vet",
  'cn': !0x0,
  'when': function(p){return p["fame"]>=0x3c;},
  'desc': "俱乐部想给你办一场纪念赛。海报上写着「传奇」两个字，你看着觉得，那两个字有点重。",
  'options': [
    {'label': "办，让球迷好好告别", 'hint': function(p,q){return g(q,'满场都是为你来的','办得冷冷清清');},
     'p': function(p){return f(0.55,[[p["fame"],0x3c,0.008]],0.2,0.92);},
     'apply': function(p,q,s){return d(q,s)
       ?{'fame':0xa,'guanxi':0x8,'money':0x28,'text':"看台拼出了你的名字和号码。你绕场一圈，把每一步都走得很慢。"}
       :{'guanxi':0x4,'fame':0x2,'text':"来的人不多。你在空荡荡的看台前鞠了一躬，心里反而踏实。"};}},
    {'label': "不办，比赛还没结束", 'hint': "能力+，地位+", 'apply': function(){return{'ovr':0x2,'roleDelta':0x1,'text':"你把纪念赛推了。「等我真跑不动了再说。」队友听完，看你的眼神不一样了。"};}}
  ]
},

// ---- idx:476 | fm_abr_prime_award | 奖项提名 ----
{
  'id': "fm_abr_prime"+'_award',
  'title': "奖项提名",
  'icon': '🏅',
  'weight': 0x30,
  'stage': "prime",
  'when': function(p){return !p["inChina"]&&p["fame"]>=0x46;},
  'desc': "年度最佳提名名单出来了，你在里面。这是亚洲球员很少能站进去的名单。",
  'options': [
    {'label': "去，穿上最好的西装", 'hint': function(p,q){return g(q,'上台领奖','被念错了名字');},
     'p': function(p){return f(0.45,[[p["fame"],0x46,0.008],[p["ovr"],0x50,0.006]],0.15,0.88);},
     'apply': function(p,q,s){return d(q,s)
       ?{'fame':0x10,'ovr':0x2,'text':"你上台时话筒高度是错的。你踮了踮脚，台下笑了，然后鼓了很久的掌。"}
       :{'fame':0x4,'ovr':0x1,'text':"你没上台。坐在第三排，镜头扫过你的时候，你笑了笑。第二天训练照旧。"};}},
    {'label': "不去，留在基地训练", 'hint': "能力+，名气-", 'apply': function(){return{'ovr':0x3,'fame':-0x4,'roleDelta':0x1,'text':"你留在了基地。颁奖那晚，你一个人在健身房练到十二点。"};}}
  ]
},

// ---- idx:477 | fm_cn_social | 自媒体 ----
{
  'id': "fm_cn_soc"+'ial',
  'title': "自媒体",
  'icon': '📱',
  'weight': 0x28,
  'stage': "prime",
  'cn': !0x0,
  'desc': "团队劝你多运营账号：「现在踢得好不够，得让人看见你踢得好。」",
  'options': [
    {'label': "认真做内容", 'hint': function(p,q){return g(q,'涨粉几十万','被说成不务正业');},
     'p': function(p){return f(0.5,[[p["fame"],0x28,0.009]],0.2,0.9);},
     'apply': function(p,q,s){return d(q,s)
       ?{'fame':0xa,'money':0x1e,'text':"你的一条训练幕后涨粉几十万。评论区第一次出现：原来球员这么练。"}
       :{'fame':-0x4,'ovr':-0x1,'text':"视频拍得生硬，还被扒出摆拍。你把账号交给了团队，再也不看评论。"};}},
    {'label': "关掉账号", 'hint': "能力+，清白+", 'apply': function(){return{'ovr':0x3,'clean':0x2,'fame':-0x2,'text':"你把账号注销了。屏幕黑下去的那一刻，你觉得轻了很多。"};}}
  ]
},

// ---- idx:478 | cl_cn_youth_age | 年龄那栏 ----
{
  'id': "cl_cn_youth_"+'age',
  'title': "年龄那栏",
  'icon': '🗂️',
  'weight': 0x2c,
  'stage': "youth",
  'cn': !0x0,
  'desc': "有人告诉你，只要把出生年份改小一岁，就能挤进那批「小年龄」的名单。表格就摊在你面前。",
  'options': [
    {'label': "改", 'hint': function(p,q){return g(q,'混进了名单','被查了出来');},
     'p': function(p){return f(0.45,[[p["clean"],0x46,0.008]],0.15,0.85);},
     'apply': function(p,q,s){return d(q,s)
       ?{'ovr':0x2,'roleDelta':0x1,'clean':-0xc,'money':0x14,'text':"你混进了那批名单，多踢了两年「小年龄」。你总觉得有人在你背后算年纪。"}
       :{'clean':-0x10,'fame':-0x6,'roleDelta':-0x1,'text':"事情被翻了出来。你被禁了半年赛，名字后面跟着一串小字。"};}},
    {'label': "把表格推回去", 'hint': "清白+，能力+", 'apply': function(){return{'clean':0x8,'ovr':0x2,'roleDelta':0x1,'text':"你按真实年龄踢，别人投来的怀疑眼神，你当成加练的理由。"};}}
  ]
},

// ---- idx:479 | cl_abr_youth_agent | 提前签约 ----
{
  'id': "cl_abr_youth_"+'agent',
  'title': "提前签约",
  'icon': '✍️',
  'weight': 0x2c,
  'stage': "youth",
  'when': function(p){return !p["inChina"];},
  'desc': "有经纪人悄悄找到你，说能帮你绕过监护人直接签职业合同，条件是抽成很高。",
  'options': [
    {'label': "偷偷签了", 'hint': function(p,q){return g(q,'拿到签字费','合同成了把柄');},
     'p': function(p){return f(0.45,[[p["clean"],0x46,0.008]],0.15,0.85);},
     'apply': function(p,q,s){return d(q,s)
       ?{'money':0x3c,'fame':0x4,'clean':-0x8,'text':"签字费到账那天，你给家里换了台冰箱。那张纸，你没敢给父母看。"}
       :{'clean':-0xc,'money':-0x14,'fame':-0x4,'text':"合同被俱乐部发现了。你补了一堆手续，还被罚了一笔。经纪人早换了号码。"};}},
    {'label': "告诉父母和教练", 'hint': "清白+，关系+", 'apply': function(){return{'clean':0x8,'guanxi':0x4,'text':"你把事情原原本本说了。教练拍了拍你：「以后这种事，第一个告诉我。」"};}}
  ]
},

// ---- idx:480 | cl_cn_prime_fix | 一个球 ----
{
  'id': "cl_cn_prime_"+'fix',
  'title': "一个球",
  'icon': '⚽',
  'weight': 0x2c,
  'stage': "prime",
  'cn': !0x0,
  'when': function(p){return p["clean"]<0x50;},
  'desc': "有人开价，只要你在一场无关紧要的联赛里「刚好」漏掉一次回追，下半程的难点全给你解决。",
  'options': [
    {'label': "答应", 'hint': function(p,q){return g(q,'钱到手，没人知道','东窗事发');},
     'p': function(p){return f(0.4,[[p["clean"],0x32,0.006]],0.12,0.75);},
     'apply': function(p,q,s){return d(q,s)
       ?{'money':0x96,'clean':-0x12,'fame':0x2,'text':"那次回追你放慢了半步，没人看出来。钱是现金，你回家数了很久。"}
       :{'money':0x32,'clean':-0x14,'fame':-0x8,'banGames':0x4,'text':"一个赛季后被翻了出来。你被停赛，名字上了通报。那笔钱，早花完了。"};}},
    {'label': "拒绝并举报", 'hint': "清白+，名气+", 'apply': function(){return{'clean':0xa,'fame':0x6,'guanxi':-0x4,'text':"你把录音交给了俱乐部。几个人被带走，你在队里成了「话多的人」，睡得却很安稳。"};}}
  ]
},

// ---- idx:481 | cl_abr_prime_dive | 假摔 ----
{
  'id': "cl_abr_prime"+'_dive',
  'title': "假摔",
  'icon': '🎭',
  'weight': 0x28,
  'stage': "prime",
  'when': function(p){return !p["inChina"];},
  'desc': "补时最后一攻，防守队员的腿伸过来了。你只要顺势倒在禁区里，可能就是这一分的胜负。",
  'options': [
    {'label': "倒", 'hint': function(p,q){return g(q,'点球，三分','被吹假摔吃牌');},
     'p': function(p){return f(0.5,[[p["clean"],0x32,0.007]],0.2,0.85);},
     'apply': function(p,q,s){return d(q,s)
       ?{'fame':0x6,'clean':-0x6,'ovr':0x1,'text':"裁判指向十二码。你没敢看倒在地上那人的眼睛。"}
       :{'clean':-0x4,'fame':-0x4,'text':"裁判看穿了，第二张黄牌。你早早洗了澡，坐在更衣室里听着全场的嘘声。"};}},
    {'label': "站住，把球传出去", 'hint': "清白+，地位+", 'apply': function(){return{'clean':0x6,'roleDelta':0x1,'ovr':0x1,'text':"你站住了，一脚横传。虽然那场没赢，但队里没人再说你「软」。"};}}
  ]
},

// ---- idx:482 | cl_cn_vet_bribe | 最后一份人情 ----
{
  'id': "cl_cn_vet_br"+'ibe',
  'title': "最后一份人情",
  'icon': '💰',
  'weight': 0x2c,
  'stage': "vet",
  'cn': !0x0,
  'desc': "生涯快到尾声，有人递来一个信封：「退役前，帮兄弟们一次。」信封很厚，厚得你不敢拆。",
  'options': [
    {'label': "收下", 'hint': function(p,q){return g(q,'无人知晓','晚节不保');},
     'p': function(p){return f(0.42,[[p["clean"],0x32,0.006]],0.12,0.8);},
     'apply': function(p,q,s){return d(q,s)
       ?{'money':0x96,'clean':-0x10,'fame':0x2,'text':"那个赛季结束，你退役了，账上多了一笔说不清的钱。"}
       :{'money':0x28,'clean':-0x12,'fame':-0xa,'banned':!0x0,'text':"事情在你退役前爆了。通报上写着终身禁足——你用最后一场球，换掉了所有的告别赛。"};}},
    {'label': "退回，并提前退役", 'hint': "清白+，名气+", 'apply': function(){return{'clean':0xc,'fame':0x8,'guanxi':-0x4,'text':"你把信封退回去，第二天宣布退役。发布会很短，退场时全场起立。"};}}
  ]
},

// ---- idx:483 | cl_abr_vet_supp | 补剂 ----
{
  'id': "cl_abr_vet_su"+'pp',
  'title': "补剂",
  'icon': '💊',
  'weight': 0x2c,
  'stage': "vet",
  'when': function(p){return !p["inChina"];},
  'desc': "队医的抽屉里有一支「康复神药」，见效快，说明书上却写着禁用的字样。你的膝盖一直在响。",
  'options': [
    {'label': "打一针，先上场", 'hint': function(p,q){return g(q,'撑完这个赛季','药检不过');},
     'p': function(p){return f(0.45,[[p["clean"],0x3c,0.006]],0.15,0.8);},
     'apply': function(p,q,s){return d(q,s)
       ?{'ovr':0x4,'clean':-0xa,'text':"膝盖不响了，你撑完了一整个赛季。每次抽检，你的手心都是湿的。"}
       :{'ovr':-0x2,'clean':-0x10,'fame':-0x8,'banGames':0x6,'text':"药检没通过。你被禁赛，赞助商连夜撤了合同。退役比计划早了一年。"};}},
    {'label': "按规程做康复", 'hint': "清白+，能力-", 'apply': function(){return{'clean':0x8,'ovr':-0x2,'roleDelta':0x1,'text':"你老老实实做康复，错过大半个赛季。回来时，教练说：「你还站得住，就好。」"};}}
  ]
},

// ---- idx:484 | cl_cn_charity | 回家 ----
{
  'id': "cl_cn_char"+'ity',
  'title': "回家",
  'icon': '🎗️',
  'weight': 0x28,
  'stage': "prime",
  'cn': !0x0,
  'when': function(p){return p["clean"]>=0x46;},
  'desc': "市里想请你挂个名，给青少年足球基金募款。没人提辛苦费，只说「这是好事」。",
  'options': [
    {'label': "去，自己再捐一笔", 'hint': function(p,q){return g(q,'募款超额完成','被人说作秀');},
     'p': function(p){return f(0.55,[[p["fame"],0x32,0.007],[p["clean"],0x4b,0.006]],0.2,0.92);},
     'apply': function(p,q,s){return d(q,s)
       ?{'clean':0x8,'fame':0x8,'money':-0x1e,'text':"募款超了目标。有个孩子在台上说，他也要当球员。你坐在台下，眼睛有点酸。"}
       :{'clean':0x4,'goodName':!0x0,'text':"有人说你做秀。你没解释，只是把那笔钱又加了一点。"};}},
    {'label': "挂个名，不露面", 'hint': "清白+，名气-", 'apply': function(){return{'clean':0x4,'fame':-0x2,'text':"你出了钱，没出席。基金会的名单上，你的名字排在最后一行。"};}}
  ]
},

// ---- idx:485 | cl_abr_charity | 医院 ----
{
  'id': "cl_abr_char"+'ity',
  'title': "医院",
  'icon': '🏥',
  'weight': 0x28,
  'stage': "prime",
  'when': function(p){return !p["inChina"];},
  'desc': "俱乐部安排你去儿童医院探访。护士说，有个小球迷坚持要来，因为他「想见踢球最努力的那个人」。",
  'options': [
    {'label': "去，待到探访时间结束", 'hint': function(p,q){return g(q,'孩子笑了一下午','走得太急，被写了一条');},
     'p': function(p){return f(0.55,[[p["clean"],0x46,0.007]],0.2,0.92);},
     'apply': function(p,q,s){return d(q,s)
       ?{'clean':0x8,'fame':0x6,'guanxi':0x4,'text':"你陪孩子玩了两个小时的桌上足球，故意输了两局。离开时，他把贴纸贴在了你手背上。"}
       :{'fame':-0x4,'clean':0x2,'text':"你只待了二十分钟。有人把你快步离开的照片发到了网上，配文：作秀。"};}},
    {'label': "捐钱，让俱乐部发新闻", 'hint': "名气+，清白-", 'apply': function(){return{'money':-0x1e,'fame':0x6,'clean':-0x2,'text':"新闻稿发得很快。护士发来消息说，孩子的家长一直在道谢。你看着那条消息，没回。"};}}
  ]
},

// ---- idx:486 | cl_cn_tax | 账 ----
{
  'id': "cl_cn_tax"+'_cn',
  'title': "账面",
  'icon': '🧾',
  'weight': 0x2a,
  'stage': "prime",
  'cn': !0x0,
  'when': function(p){return p["money"]>=0x12c;},
  'desc': "会计说，有几笔代言费可以「处理一下」。数字不小，风险写着「一般不会有人查」。",
  'options': [
    {'label': "按规矩全额报", 'hint': function(p,q){return g(q,'干干净净','白白多交了钱');},
     'p': function(p){return f(0.6,[[p["clean"],0x3c,0.006]],0.25,0.92);},
     'apply': function(p,q,s){return d(q,s)
       ?{'clean':0x8,'money':-0x1e,'text':"你把账一笔笔报清。会计摇头说你傻，你说，睡得着就行。"}
       :{'clean':0x8,'money':-0x3c,'text':"你多交了一笔。那年你少买了一样想要很久的东西，但心里踏实。"};}},
    {'label': "让他「处理一下」", 'hint': function(p,q){return g(q,'省了一大笔','被查出来');},
     'p': function(p){return f(0.4,[[p["clean"],0x32,0.006]],0.12,0.8);},
     'apply': function(p,q,s){return d(q,s)
       ?{'money':0x50,'clean':-0xa,'text':"账面上看不出问题。你把省下的钱投进了房产，晚上偶尔会失眠。"}
       :{'money':-0x96,'clean':-0x14,'fame':-0x6,'text':"几年后倒查。你补缴加罚款，数字比省下来的多得多，还被通报批评。"};}}
  ]
},

// ---- idx:487 | cl_abr_tax | 税务 ----
{
  'id': "cl_abr_tax"+'_abr',
  'title': "税务居所",
  'icon': '🌍',
  'weight': 0x2a,
  'stage': "prime",
  'when': function(p){return !p["inChina"]&&p["money"]>=0x12c;},
  'desc': "财务顾问给你出了个方案：把税务居所挪到一个税率很低的小岛。合法，但经不起审问。",
  'options': [
    {'label': "照他说的办", 'hint': function(p,q){return g(q,'省下大笔税金','被媒体挖出来');},
     'p': function(p){return f(0.5,[[p["clean"],0x32,0.006]],0.18,0.85);},
     'apply': function(p,q,s){return d(q,s)
       ?{'money':0x64,'clean':-0x8,'text':"税省下来一大笔。你在那座小岛上有了一间从没住过的房子。"}
       :{'fame':-0xa,'clean':-0x6,'text':"媒体把「避税天堂」四个字印在你脸上。你补了税，也补不回人心。"};}},
    {'label': "老老实实在当地交", 'hint': "清白+，钱少", 'apply': function(){return{'clean':0x8,'money':-0x1e,'fame':0x2,'text':"你按最高档交了税。顾问说你亏了，你说，我在哪儿踢球，就在哪儿交钱。"};}}
  ]
},

// ---- idx:488 | cl_youth_bully | 新来的 ----
{
  'id': "cl_youth_b"+'ully',
  'title': "新来的",
  'icon': '😔',
  'weight': 0x28,
  'stage': "youth",
  'desc': "梯队里有个新人被高年级堵在器材室门口。你正好路过，他抬起头看了你一眼。",
  'options': [
    {'label': "站出来", 'hint': function(p,q){return g(q,'没人再敢动他','被一起收拾了');},
     'p': function(p){return f(0.5,[[p["clean"],0x32,0.007],[p["ovr"],0x3c,0.006]],0.2,0.88);},
     'apply': function(p,q,s){return d(q,s)
       ?{'clean':0x8,'guanxi':0x6,'roleDelta':0x1,'text':"你把器材室的门推开。从那以后，那个新人每次训练都站在你旁边。"}
       :{'clean':0x6,'ovr':-0x2,'guanxi':0x2,'text':"你也被推了一把，膝盖擦破了。但你挡在他前面，直到教练来。"};}},
    {'label': "装作没看见", 'hint': "清白-，关系-", 'apply': function(){return{'clean':-0x4,'guanxi':-0x2,'ovr':0x1,'text':"你低头走开了。那个新生后来退了队，你偶尔还会想起他抬头看你的那一眼。"};}}
  ]
},

// ---- idx:489 | cl_abr_racism | 看台 ----
{
  'id': "cl_abr_raci"+'sm',
  'title': "看台",
  'icon': '🚫',
  'weight': 0x2a,
  'stage': "prime",
  'when': function(p){return !p["inChina"];},
  'desc': "客场看台上传来针对你的叫声。队友看着你，裁判也看着你——比赛还在继续。",
  'options': [
    {'label': "停下比赛，示意裁判", 'hint': function(p,q){return g(q,'裁判中断了比赛','被说成小题大做');},
     'p': function(p){return f(0.5,[[p["clean"],0x32,0.007],[p["fame"],0x32,0.006]],0.2,0.9);},
     'apply': function(p,q,s){return d(q,s)
       ?{'clean':0x6,'fame':0x8,'guanxi':0x4,'text':"裁判中断了比赛，广播念了三遍警告。散场后有人等在通道口，只为跟你握个手。"}
       :{'fame':-0x4,'clean':0x2,'text':"比赛照常。你咬了咬牙，把那股劲全用在了跑动上，最后跑抽了筋。"};}},
    {'label': "不说话，用进球回击", 'hint': "能力+，地位+", 'apply': function(){return{'ovr':0x3,'roleDelta':0x1,'fame':0x2,'text':"你一句话没说，进了两个球。谢场时你只是把手放在队徽上，看了那片看台很久。"};}}
  ]
},

// ---- idx:490 | rl_cn_prime_captain | 袖标 ----
{
  'id': "rl_cn_prime"+'_captain',
  'title': "该不该戴",
  'icon': '🎽',
  'weight': 0x2a,
  'stage': "prime",
  'cn': !0x0,
  'desc': "老队长伤了半个赛季，教练把袖标放在更衣室中间的桌上，没点名，只说了句「谁想戴，自己拿」。",
  'options': [
    {'label': "第一个拿起来", 'hint': function(p,q){return g(q,'全队认了这个队长','有人不服，闹了一季');},
     'p': function(p){return f(0.45,[[p["guanxi"],0x32,0.011],[p["roleRank"],2,0.12]],0.15,0.9);},
     'apply': function(p,q,s){return d(q,s)
       ?{'roleDelta':0x2,'guanxi':0x6,'fame':0x4,'text':"你把袖标绑上，第一个走进球场。那半年，你连替补席上谁的情绪都要管。"}
       :{'roleDelta':0x1,'guanxi':-0x6,'text':"袖标戴上了，可更衣室里总有几句话绕着你走。你练得更狠，话说得更少。"};}},
    {'label': "让给更资深的人", 'hint': "关系+，地位-", 'apply': function(){return{'guanxi':0x8,'roleDelta':-0x1,'ovr':0x2,'text':"你把袖标推给了旁边的老将。他说了句谢谢，之后的直塞球多了不少。"};}}
  ]
},

// ---- idx:491 | rl_abr_prime_clash | 头牌 ----
{
  'id': "rl_abr_prime"+'_clash',
  'title': "头牌",
  'icon': '⚔️',
  'weight': 0x2a,
  'stage': "prime",
  'when': function(p){return !p["inChina"]&&p["roleRank"]>=0x2;},
  'desc': "队里的头牌公开说，球应该先交到他脚下。你刚用两场最佳回应了这件事。",
  'options': [
    {'label': "当着全队把话说开", 'hint': function(p,q){return g(q,'他服了','关系闹僵');},
     'p': function(p){return f(0.45,[[p["ovr"],0x46,0.008],[p["guanxi"],0x28,0.008]],0.15,0.88);},
     'apply': function(p,q,s){return d(q,s)
       ?{'roleDelta':0x2,'guanxi':0x4,'ovr':0x2,'text':"你说，谁状态好球给谁。他愣了愣，伸手跟你碰了一下。那赛季你们配合进了很多球。"}
       :{'roleDelta':-0x1,'guanxi':-0x8,'fame':0x2,'text':"话谈崩了。之后的比赛，你在禁区里举手，球总是从另一边过去。"};}},
    {'label': "继续用表现说话", 'hint': "能力+，地位+", 'apply': function(){return{'ovr':0x3,'roleDelta':0x1,'text':"你一个字没回，连着五场进球。数据面前，更衣室安静了。"};}}
  ]
},

// ---- idx:492 | rl_cn_youth_number | 号码 ----
{
  'id': "rl_cn_youth_"+'number',
  'title': "号码",
  'icon': '🔢',
  'weight': 0x26,
  'stage': "youth",
  'cn': !0x0,
  'desc': "梯队要报号码，10 号空着。教练说：「想穿就自己去挣，别伸手要。」",
  'options': [
    {'label': "去争这个 10 号", 'hint': function(p,q){return g(q,'10 号归你','被换回了边角号');},
     'p': function(p){return f(0.45,[[p["ovr"],0x3c,0.008],[p["roleRank"],2,0.1]],0.15,0.88);},
     'apply': function(p,q,s){return d(q,s)
       ?{'roleDelta':0x1,'ovr':0x2,'fame':0x2,'number':0xa,'text':"队内对抗赛你一场造了三个球。教练把 10 号递给你：「别辱没了它。」"}
       :{'roleDelta':-0x1,'number':0x1e,'text':"10 号给了别人。你领了个大号，把它当成每天早起加练的理由。"};}},
    {'label': "随便给个号就行", 'hint': "关系+，能力+", 'apply': function(){return{'guanxi':0x4,'ovr':0x2,'text':"你随便挑了个号码。「号码是印在背上的，球是踢在脚下的。」教练听完点了点头。"};}}
  ]
},

// ---- idx:493 | rl_abr_youth_promo | 提拔 ----
{
  'id': "rl_abr_youth_"+'promo',
  'title': "提拔",
  'icon': '⬆️',
  'weight': 0x2a,
  'stage': "youth",
  'when': function(p){return !p["inChina"];},
  'desc': "一线队缺人，教练想在梯队里临时提一个上来。名单上写了三个名字，你在最后一个。",
  'options': [
    {'label': "毛遂自荐", 'hint': function(p,q){return g(q,'当场被提上去','被认为太急');},
     'p': function(p){return f(0.45,[[p["ovr"],0x3c,0.009],[p["guanxi"],0x28,0.008]],0.15,0.88);},
     'apply': function(p,q,s){return d(q,s)
       ?{'roleDelta':0x2,'ovr':0x2,'fame':0x4,'text':"你直接敲了主教练的门。他看了你两秒，说：「明天跟着一队跑。」"}
       :{'guanxi':-0x4,'roleDelta':-0x1,'text':"主教练皱了皱眉：「先把你自己的比赛踢好。」你在门口站了很久。"};}},
    {'label': "等他们先看完另外两个", 'hint': "能力+，关系+", 'apply': function(){return{'ovr':0x3,'guanxi':0x4,'text':"你在U队又踢了两场好球。第三场，一队的教练自己下来看你了。"};}}
  ]
},

// ---- idx:494 | rl_cn_vet_mentor | 带新人 ----
{
  'id': "rl_cn_vet_me"+'ntor',
  'title': "带一带",
  'icon': '🧭',
  'weight': 0x28,
  'stage': "vet",
  'cn': !0x0,
  'when': function(p){return p["roleRank"]>=0x2;},
  'desc': "教练把一个十八岁的新人塞到你旁边：「你带带他，把自己会的那点都给他。」",
  'options': [
    {'label': "真教，不留一手", 'hint': function(p,q){return g(q,'新人成了你的继承人','教会徒弟，饿死师傅');},
     'p': function(p){return f(0.5,[[p["clean"],0x3c,0.007],[p["guanxi"],0x28,0.008]],0.2,0.9);},
     'apply': function(p,q,s){return d(q,s)
       ?{'guanxi':0xa,'clean':0x4,'fame':0x4,'text':"你把跑位、站位、什么时候该倒地都教了。半年后，他第一次首发，跑来抱了你。"}
       :{'roleDelta':-0x2,'ovr':0x1,'clean':0x2,'text':"不到一个赛季，新人顶了你的位置。你没怨他，可你确实更早地坐上了替补席。"};}},
    {'label': "应付两句就完", 'hint': "地位+，关系-", 'apply': function(){return{'roleDelta':0x1,'guanxi':-0x4,'clean':-0x2,'text':"你只教了他几个基础动作。新人很快不再来问你，你保住了位置，也更孤单了。"};}}
  ]
},

// ---- idx:495 | rl_abr_vet_bench | 替补席 ----
{
  'id': "rl_abr_vet_be"+'nch',
  'title': "替补席",
  'icon': '🪑',
  'weight': 0x2a,
  'stage': "vet",
  'when': function(p){return !p["inChina"]&&p["roleRank"]<=0x2;},
  'desc': "你连着五场坐在替补席。年轻的边锋在你面前热身、冲刺、抬头看大屏幕。",
  'options': [
    {'label': "找主教练要个定位", 'hint': function(p,q){return g(q,'拿到了轮换承诺','被明确告知是第三选择');},
     'p': function(p){return f(0.45,[[p["ovr"],0x46,0.007],[p["guanxi"],0x32,0.009]],0.15,0.88);},
     'apply': function(p,q,s){return d(q,s)
       ?{'roleDelta':0x2,'guanxi':0x4,'ovr':0x1,'text':"他给了你明确的轮换位置。你不再等全队伤一半才上场，反而踢得更放得开。"}
       :{'roleDelta':-0x1,'guanxi':-0x2,'ovr':0x1,'text':"他很客气地告诉你：你是第三选择。你回去把这句话写在了训练本第一页。"};}},
    {'label': "把每一分钟都当最后一分钟", 'hint': "能力+，地位+", 'apply': function(){return{'ovr':0x3,'roleDelta':0x1,'text':"从那天起，你连热身都当成决赛。一次替补登场，你用一脚远射把位置抢了回来。"};}}
  ]
},

// ---- idx:496 | rl_cn_prime_penalty | 点球权 ----
{
  'id': "rl_cn_prime"+'_penalty',
  'title': "点球权",
  'icon': '🎯',
  'weight': 0x28,
  'stage': "prime",
  'cn': !0x0,
  'when': function(p){return p["roleRank"]>=0x2&&p["posGroup"]!=="gk";},
  'desc': "队里的点球手转走了。教练看着你：「你敢罚吗？」",
  'options': [
    {'label': "敢，我来", 'hint': function(p,q){return g(q,'成了第一点球手','罚丢了两个，被拿下');},
     'p': function(p){return f(0.5,[[p["ovr"],0x46,0.007],[p["roleRank"],2,0.1]],0.2,0.9);},
     'apply': function(p,q,s){return d(q,s)
       ?{'roleDelta':0x1,'fame':0x4,'ovr':0x2,'text':"接下来五个点球你全部罚进。主罚名单上，你的名字被排在了第一个。"}
       :{'roleDelta':-0x1,'fame':-0x4,'ovr':-0x1,'text':"你连着罚丢两个。主场球迷叹气的那一刻，你听见了。点球权又交了出去。"};}},
    {'label': "让给更稳的人", 'hint': "关系+", 'apply': function(){return{'guanxi':0x6,'roleDelta':0x1,'text':"你把机会让给了队里的老射手。他进了球，第一个跑来抱你。"};}}
  ]
},

// ---- idx:497 | rl_abr_prime_clause | 定位条款 ----
{
  'id': "rl_abr_prime"+'_clause',
  'title': "定位条款",
  'icon': '📄',
  'weight': 0x28,
  'stage': "prime",
  'when': function(p){return !p["inChina"]&&p["contractLeft"]<=0x2;},
  'desc': "续约谈判桌上，你的经纪人想让合同里写上一句：非伤病情况下保证首发。",
  'options': [
    {'label': "坚持加上这一条", 'hint': function(p,q){return g(q,'俱乐部让步了','谈判僵住');},
     'p': function(p){return f(0.45,[[p["ovr"],0x46,0.007],[p["guanxi"],0x32,0.008]],0.15,0.88);},
     'apply': function(p,q,s){return d(q,s)
       ?{'roleDelta':0x2,'money':0x28,'ovr':0x1,'text':"俱乐部签了。那句条款让你从此每场都必须拿出首发的样子。"}
       :{'guanxi':-0x4,'roleDelta':-0x1,'text':"谈判僵了两周。到最后你什么也没加，签字的时候，心里憋着一口气。"};}},
    {'label': "不写，用表现换", 'hint': "能力+，关系+", 'apply': function(){return{'ovr':0x2,'guanxi':0x4,'roleDelta':0x1,'text':"你把那条划掉了。教练知道后说：「这句话我记下了。」"};}}
  ]
},

// ---- idx:498 | rl_cn_youth_captain | 青年队队长 ----
{
  'id': "rl_cn_youth_"+'captain',
  'title': "青年队队长",
  'icon': '📛',
  'weight': 0x26,
  'stage': "youth",
  'cn': !0x0,
  'desc': "青年队选队长，教练问全队：「谁在你们心里是主心骨？」有人回头看了你一眼。",
  'options': [
    {'label': "举手，我想当", 'hint': function(p,q){return g(q,'票过半，就是你了','票不够，很尴尬');},
     'p': function(p){return f(0.45,[[p["guanxi"],0x32,0.011],[p["roleRank"],2,0.1]],0.15,0.88);},
     'apply': function(p,q,s){return d(q,s)
       ?{'roleDelta':0x1,'guanxi':0x8,'text':"你成了青年队的队长。第一次带队喊话，声音抖了，但没人笑。"}
       :{'guanxi':-0x4,'roleDelta':-0x1,'text':"举手的人不多。你把票投给了自己，看着有点孤单。"};}},
    {'label': "低头，让别人当", 'hint': "关系+，能力+", 'apply': function(){return{'guanxi':0x6,'ovr':0x2,'text':"你没举手。新队长上任后，第一个来找你商量战术。你说这比当队长踏实。"};}}
  ]
},

// ---- idx:499 | rl_abr_prime_formdrop | 状态 ----
{
  'id': "rl_abr_prime"+'_formdrop',
  'title': "状态",
  'icon': '📉',
  'weight': 0x2a,
  'stage': "prime",
  'when': function(p){return !p["inChina"]&&p["ovr"]>=0x50;},
  'desc': "你连着七场没进球。媒体开始讨论「他是不是老了」，你才二十七。",
  'options': [
    {'label': "加练射门到深夜", 'hint': function(p,q){return g(q,'把状态练回来了','越练越僵');},
     'p': function(p){return f(0.48,[[p["ovr"],0x50,0.007],[p["clean"],0x3c,0.005]],0.18,0.9);},
     'apply': function(p,q,s){return d(q,s)
       ?{'ovr':0x4,'roleDelta':0x1,'fame':0x2,'text':"第八场你打进了两个。解说员说：这只是状态，不是年龄。"}
       :{'ovr':-0x2,'roleDelta':-0x2,'fame':-0x4,'text':"你练到膝盖发炎，八场变成十场。教练把你放到了替补席上「歇一歇」。"};}},
    {'label': "接受轮换，先把身体养好", 'hint': "清白+，地位-", 'apply': function(){return{'ovr':0x2,'clean':0x4,'roleDelta':-0x1,'text':"你主动提出轮换。三周后复出，你跑动距离全队第一。"};}}
  ]
},

// ---- idx:500 | rl_cn_prime_newcoach | 换帅 ----
{
  'id': "rl_cn_prime"+'_newcoach',
  'title': "换帅",
  'icon': '🧑‍💼',
  'weight': 0x2a,
  'stage': "prime",
  'cn': !0x0,
  'desc': "新教练上任第一件事，就是把上赛季的首发名单折起来，扔进了抽屉。所有人重新排队。",
  'options': [
    {'label': "第一时间去找他聊", 'hint': function(p,q){return g(q,'他记住了你','被当成求位置');},
     'p': function(p){return f(0.45,[[p["guanxi"],0x32,0.009],[p["roleRank"],2,0.1]],0.15,0.88);},
     'apply': function(p,q,s){return d(q,s)
       ?{'roleDelta':0x2,'guanxi':0x6,'text':"你把上赛季的比赛录像剪了给他看。第二天，你出现在了他的计划里。"}
       :{'roleDelta':-0x1,'guanxi':-0x2,'text':"他说：「先看训练。」你被排在了第二组，整整一个月。"};}},
    {'label': "不说话，训练里见真章", 'hint': "能力+，地位+", 'apply': function(){return{'ovr':0x3,'roleDelta':0x1,'text':"你成了他的队内对抗赛里最难对付的人。两周后，首发名单上有你。"};}}
  ]
},

// ---- idx:501 | rl_abr_prime_derby | 德比名单 ----
{
  'id': "rl_abr_prime"+'_derby',
  'title': "德比名单",
  'icon': '🔥',
  'weight': 0x2c,
  'stage': "prime",
  'when': function(p){return !p["inChina"];},
  'desc': "德比周的名单还没定。你对这座城市还没有那种恨，但看台上的人有。",
  'options': [
    {'label': "主动请战", 'hint': function(p,q){return g(q,'首发，并且进球','首发，但被换下');},
     'p': function(p){return f(0.5,[[p["roleRank"],2,0.1],[p["ovr"],0x46,0.006]],0.2,0.9);},
     'apply': function(p,q,s){return d(q,s)
       ?{'roleDelta':0x2,'fame':0xa,'ovr':0x2,'text':"你在第六十分钟捅进一球，冲向看台的瞬间，你终于听懂了整座球场的恨与爱。"}
       :{'roleDelta':0x1,'ovr':-0x1,'fame':-0x2,'text':"你首发，踢了五十分钟被换下。德比比你想象的更快，也更脏。"};}},
    {'label': "听教练安排", 'hint': "能力+，关系+", 'apply': function(){return{'ovr':0x2,'guanxi':0x4,'roleDelta':0x1,'text':"你把选择权交给教练。他让你替补待命。终场前你上场，把球护在了角旗附近。"};}}
  ]
}

];
