// auto-generated by split_events.py - edit events here, then run build_events.py

var EVT_club=[

// ---- idx:303 | club_5yrs | 五年老臣 ----
{
  'id': "club_5yrs",
  'title': "五年老臣",
  'icon': '📜',
  'weight': 0x30,
  'when': function(p){return p["seasonsAtClub"]>=0x5&&p["seasonsAtClub"]<0x8;},
  'desc': "你在这支球队待了五年，看台上的横幅换了一茬又一茬，你的号码，一次都没换过。",
  'options': [
    {
        'label': "续约，把根扎下来",
        'p': function(p){return f(0.7,[[p["guanxi"],50,0.008]],0.3,0.9);},
        'hint': function(p,q){return g(q,"地位稳固","薪水难谈");},
        'apply': function(p,q,s){return d(q,s)?{'guanxi':0x8,'roleDelta':0x1,'text':"续约谈得很顺利。签字那天，主席说，你是队里「压舱石」——他知道这个词你还得想一下。"}:{'guanxi':0x2,'text':"合同年限卡住了，最后各让一步。你留下，但心里记下了这回事。"};}
    },
    {
        'label': "再看看别的机会",
        'hint': "可能离队",
        'apply': function(){return{'leave':!0x0,'text':"你让经纪人把报价递过来。球迷论坛炸了，有帖子问：连他都想走，这队还有救吗。"};}
    }
  ]
},

// ---- idx:304 | club_10yrs | 十年一诺 ----
{
  'id': "club_10yrs",
  'title': "十年一诺",
  'icon': '🏆',
  'weight': 0x38,
  'when': function(p){return p["seasonsAtClub"]>=0xa&&p["youthTeamId"]===p["teamId"];},
  'desc': "十年。你从青训营一路踢到一线队，如今球衣上的名字底下，印着「十年」两个字。俱乐部说，要给你办个盛大的纪念。",
  'options': [
    {
        'label': "我把最好的十年留在这了",
        'hint': "名气大涨，地位稳",
        'apply': function(){return{'fame':0x14,'roleDelta':0x2,'text':"纪念赛那天，全场人穿你的号码。你举起话筒说，我这辈子最对的决定，就是没离开过这儿。"};}
    },
    {
        'label': "冠军是唯一想要的礼物",
        'p': function(p){return f(0.55,[[p["ovr"],70,0.006]],0.25,0.85);},
        'hint': function(p,q){return g(q,"如愿以偿","差一口气");},
        'apply': function(p,q,s){return d(q,s)?{'fame':0x10,'text':"那赛季你拼下了队史一座重量级奖杯。颁奖时队长把奖杯递给你，说，这是给你十年的。"}:{'fame':0x4,'text':"最后一场功亏一篑。你在更衣室坐了很久，十年，就差这一步。"};}
    }
  ]
},

// ---- idx:305 | club_10yrs_way | 十年之约 ----
{
  'id': "club_10yrs_way",
  'title': "十年之约",
  'icon': '🏆',
  'weight': 0x38,
  'when': function(p){return p["seasonsAtClub"]>=0xa&&p["youthTeamId"]!==p["teamId"];},
  'desc': "十年。你从当初转会而来的那天，到如今球队的名字早已刻进你的履历。球衣上的名字底下，印着「十年」两个字。俱乐部说，要给你办个盛大的纪念。",
  'options': [
    {
        'label': "我把最好的十年留在这了",
        'hint': "名气大涨，地位稳",
        'apply': function(){return{'fame':0x14,'roleDelta':0x2,'text':"纪念赛那天，全场人穿你的号码。你举起话筒说，我这辈子最对的决定，就是没离开过这儿。"};}
    },
    {
        'label': "冠军是唯一想要的礼物",
        'p': function(p){return f(0.55,[[p["ovr"],70,0.006]],0.25,0.85);},
        'hint': function(p,q){return g(q,"如愿以偿","差一口气");},
        'apply': function(p,q,s){return d(q,s)?{'fame':0x10,'text':"那赛季你拼下了队史一座重量级奖杯。颁奖时队长把奖杯递给你，说，这是给你十年的。"}:{'fame':0x4,'text':"最后一场功亏一篑。你在更衣室坐了很久，十年，就差这一步。"};}
    }
  ]
}

];
