// auto-generated by split_events.py - edit events here, then run build_events.py

var EVT_cn=[

// ---- idx:26 | cn_zuxia | 足校的学费 ----
{
  'id': "cn_zuxia"+'o',
  'title': "足校的学费",
  'icon': '🎒',
  'weight': 0x50,
  'cn': !0x0,
  'stage': "youth",
  'when': function(p){
return p["inAcadem"+'y'];
},
  'desc': "全国最好的足校发来了通知书，一年学费，抵得上家里两年的收入。父亲只说：车可以卖，学要上。",
  'options': [
    {
        'label': "就去",
        'hint': "能力+5，家里背"+'上债',
        'apply': function(){
return{'ovr':0x5,'money':-0x19,'text':"你去了。开学第一天你才知道，全宿舍六个人，五个家里都卖过点什么。"};
}
    },
    {
        'label': "留在市队",
        'hint': "能力+1，稳",
        'apply': function(){
return{'ovr':0x1,'text':"你留在了市队。教练很负责，场地是水泥地，一下雨就滑得站不住。"};
}
    }
  ]
},

// ---- idx:27 | cn_age | 年龄这事 ----
{
  'id': "cn_age",
  'title': "年龄这事",
  'icon': '🆔',
  'weight': 0x46,
  'cn': !0x0,
  'stage': "youth",
  'when': function(p){
return p["inAcadem"+'y'];
},
  'desc': "有人劝你父亲：把出生年份往后改两年，能一路踢进国少。「都这么干，你不改就吃亏。」",
  'options': [
    {
        'label': "改位置",
        'hint': "青年队地位大增，"+"清白重创",
        'apply': function(){
return{'roleDelta':0x2,'ovr':0x3,'clean':-0x14,'ageFraud':!0x0,'text':"你以「十五岁」的身份，打了两年十七岁组的比赛，场上没一个人对付得了你。也从没人问过，你胡子为什么那么密。"};
}
    },
    {
        'label': '不改',
        'hint': "关系-，清白+",
        'apply': function(){
return{'clean':0xa,'guanxi':-0x8,'text':"你按真实年龄踢。同组对手个个比你矮半个头，却总快你半步——因为他们也没改。"};
}
    }
  ]
},

// ---- idx:28 | cn_bone | 骨龄检测 ----
{
  'id': "cn_bone",
  'title': "骨龄检测",
  'icon': '🦴',
  'weight': 0x190,
  'cn': !0x0,
  'stage': "youth",
  'when': function(p){
return p["ageFraud"];
},
  'desc': "全国青少年比赛新增了骨龄抽检。你被抽中，第二天一早就得去医院。",
  'options': [
    {
        'p': function(p){return f(0.45,[[p["clean"],70,0.008]],0.2,0.9);
},
        'label': '去查',
        'hint': "查出来就完了",
        'odds': ["查出来","卡边过"],
        'apply': function(p,q,s){
return d(q,s)?{'clean':-0x19,'ban':0x1,'roleDelta':-0x2,'fame':-0xf,'text':"报告显示，你的骨龄超出年龄组两岁以上。通报里没写全名，只写了「某队 X 某」。"}:{'text':"机器给出的区间刚好卡在边缘，判定通过。你在走廊的椅子上坐了很久，才站起来。"};
}
    },
    {
        'label': "托关系换报告",
        'hint': "花钱消灾，清白再"+'降',
        'apply': function(p){
return{'money':-0xc,'clean':-0xf,'guanxi':0x8,'text':"报告顺利通过。那天晚上，你父亲喝了很多酒，一句话也没说。"};
}
    }
  ]
},

// ---- idx:29 | cn_hongb | 教练的暗示 ----
{
  'id': "cn_hongb"+'ao',
  'title': "教练的暗示",
  'icon': '🧧',
  'weight': 0x4b,
  'repeat': 0x2,
  'cn': !0x0,
  'stage': "youth",
  'when': function(p){
return p["inAcadem"+'y'];
},
  'desc': "梯队教练在训练后把你留下，聊了几句家常，末了说了句「你爸最近忙不忙，有空一起坐坐」。",
  'options': [
    {
        'label': "让家里去坐坐",
        'hint': "首发有保障，清白"+"-，花钱",
        'apply': function(){
return{'roleDelta':0x2,'money':-0x8,'clean':-0xc,'guanxi':0xa,'text':"下一场你就首发了。你踢得很好，可每次有人夸你，你都会想起那顿饭。"};
}
    },
    {
        'label': "装没听懂",
        'hint': "长期坐板凳",
        'apply': function(){
return{'roleDelta':-0x2,'clean':0x8,'text':"你装作没听懂。之后半年，你的出场时间加起来，不到九十分钟。"};
}
    }
  ]
},

// ---- idx:30 | cn_guosh | 国少的名额 ----
{
  'id': "cn_guosh"+'ao',
  'title': "国少的名额",
  'icon': '📝',
  'weight': 0x37,
  'cn': !0x0,
  'stage': "youth",
  'when': function(p){
return p["inAcadem"+'y'];
},
  'desc': "国少集训名单快出来了。中间人报了个数，说这个价，能保证你的名字在名单里。",
  'options': [
    {
        'label': '掏钱',
        'hint': "征召+，清白-",
        'apply': function(){
return{'money':-0x14,'clean':-0x12,'guanxi':0xf,'caps':0x3,'text':"你穿上了国字号球衣。集训队里，有几个球性明显不如你的，你没敢多想。"};
}
    },
    {
        'label': "凭实力等",
        'hint': "看能力，可能落选",
        'odds': ["名单有你","名单没你"],
        'apply': function(p,q){
return d(q,Math["min"](0.7,(p["ovr"]-0x32)/0x28))?{'caps':0x3,'clean':0x5,'fame':0x8,'text':"名单出来，有你。你后来才知道，被你顶掉的那个人，交了钱。"}:{'clean':0x5,
'fame':-0x4,'text':"名单出来，没你。教练组的说法是「技术特点不符合体系需要」。"};
}
    }
  ]
},

// ---- idx:31 | cn_liuya | 留洋的岔路 ----
{
  'id': "cn_liuya"+'ng',
  'title': "留洋的岔路",
  'icon': '✈️',
  'weight': 0x55,
  'cn': !0x0,
  'when': function(p){
return p["inChina"]&&p["age"]>=0x12&&p["age"]<=0x1b&&p["ovr"]>=0x3e;
},
  'desc': "一家欧洲二级联赛"+"球队愿意给你一份"+"合同，周薪不到你"+"现在的十分之一。"+"同一天，{clu"+"b}把续约报价翻"+"了一倍。",
  'options': [
    {
        'label': "出去闯",
        'hint': "转会海外，收入大"+"减，成长加速",
        'apply': function(){
return{'goAbroad':!0x0,'money':-0x78,'ovr':0x2,'text':"你走了。第一年，你在替补席上学会了一门外语，也学会了一个人过节。"};
}
    },
    {
        'label': "留下拿钱",
        'hint': "收入大增，能力增"+"长放缓",
        'apply': function(p){
return{'money':0x384,'ovr':-0x1,'roleDelta':0x1,'stagnate':!0x0,'text':"你签了那份合同。数字很好看，好看到之后，再也没有欧洲球队来问过你。"};
}
    }
  ]
},

// ---- idx:32 | cn_jinyu | 天价续约 ----
{
  'id': "cn_jinyu"+'an',
  'title': "天价续约",
  'icon': '💰',
  'weight': 0x3c,
  'cn': !0x0,
  'when': function(p){
return p["inChina"]&&p["ovr"]>=0x44;
},
  'desc': "投资方老板亲自来了。桌上摆着一份年薪高得离谱的合同，其中一条写着：五年内不得转会海外。",
  'options': [
    {
        'label': "签字",
        'hint': "巨额收入，锁死留"+'洋',
        'apply': function(){
return{'money':0x384,'lockAbroad':0x5,'roleDelta':0x1,'ovr':-0x1,'text':"你签了。那一年，你成了亚洲身价最高的中国球员——也是最后一次，有人这么形容你。"};
}
    },
    {
        'label': '不签',
        'hint': "地位受损，保留可"+'能',
        'apply': function(){
return{'roleDelta':-0x1,'fame':0x8,'text':"你拒绝了。老板笑着说「年轻人有想法是好事」，然后半年，没再跟你说过一句话。"};
}
    }
  ]
},

// ---- idx:33 | cn_arrea | 工资停了 ----
{
  'id': "cn_arrea"+'rs',
  'title': "工资停了",
  'icon': '💸',
  'weight': 0x50,
  'repeat': 0x3,
  'cn': !0x0,
  'when': function(p){
return p["inChina"];
},
  'desc': "三个月没发工资了。队委会问大家要不要一起去讨，也有人劝：别闹，闹了更没人接盘。",
  'options': [
    {
        'p': function(p){return f(0.5,[[p["fame"],25,0.01]],0.2,0.9);
},
        'label': "牵头去讨",
        'hint': "名气+，被俱乐部"+'记恨',
        'odds': ["补发六成","一分没有"],
        'apply': function(p,q,s){
return d(q,s)?{'money':0x78,'fame':0x12,'roleDelta':-0x1,'text':"钱补发了六成。俱乐部从此把你列进了「不稳定因素」。"}:{'money':-0x3c,'fame':0xc,'roleDelta':-0x2,
'text':"什么也没要到，反而上了新闻。下一份大名单里，没有你的名字。"};
}
    },
    {
        'label': '忍着',
        'hint': "无变化，钱可能拿"+"不回来",
        'apply': function(){
return{'money':-0xb4,'text':"你忍了一年。后来俱乐部换了投资人，那笔账，再没人提起。"};
}
    }
  ]
},

// ---- idx:34 | cn_disso | 俱乐部要没了 ----
{
  'id': "cn_disso"+"lve",
  'title': "俱乐部要没了",
  'icon': "🏚️",
  'weight': 0x37,
  'cn': !0x0,
  'when': function(p){
return p["inChina"]&&p["clubRep"]<=0x2;
},
  'desc': "投资方的地产项目暴雷，{club}宣布退出职业联赛。一夜之间，全队都成了自由身。",
  'options': [
    {
        'label': "先找下家",
        'hint': "强制转会",
        'apply': function(){
return{'leave':!0x0,'money':-0x5a,'fame':0x5,'text':"解散公告贴出来的那天，你回更衣室收拾东西，发现有人已经把球衣带走当纪念了。"};
}
    },
    {
        'label': "跟队友一起讨薪",
        'hint': "拿回部分欠薪，耽"+"误一期",
        'apply': function(){
return{'leave':!0x0,'money':0x96,'ovr':-0x3,'fame':0xa,'text':"你们在体育局门口站了一整个下午。钱要回来一部分，转会窗也错过了。"};
}
    }
  ]
},

// ---- idx:35 | cn_neutr | ? ----
{
  'id': "cn_neutr"+'al',
  'title': '改名',
  'icon': "🏷️",
  'weight': 0x28,
  'cn': !0x0,
  'when': function(p){
return p["inChina"];
},
  'desc': "政策要求俱乐部改中性名，冠名商当场撤资。队徽换了，训练基地的招牌拆了一半，就再没人管。",
  'options': [
    {
        'label': '接受',
        'hint': "收入下降，夺冠概"+"率下降",
        'apply': function(){
return{'money':-0x3c,'mult':{'league':0.6,'cup':0.6},'text':"改完名之后，球迷论坛最热的帖子是「我们还是不是我们」。这个问题，没人给得出答案。"};
}
    }
  ]
},

// ---- idx:36 | cn_fixed | 有人来找你聊天 ----
{
  'id': "cn_fixed",
  'title': "有人来找你聊天",
  'icon': '✉️',
  'weight': 0x41,
  'repeat': 0x2,
  'cn': !0x0,
  'when': function(p){
return p["inChina"]&&p["roleRank"]>=0x2;
},
  'desc': "赛前有人约你吃饭。饭桌上不提比赛，只说了句「这场输一个球，对谁都好」，然后把一个信封推到你面前。",
  'options': [
    {
        'label': "接下",
        'hint': "巨款，清白重创",
        'apply': function(p){
return{'money':0xb4,'clean':-0x2d,'fixed':!0x0,'text':"那场球，你在禁区里慢了半拍。第二天，信封里的数字变成了银行卡上的数字。那一晚，你没睡好。"};
}
    },
    {
        'label': "推回去",
        'hint': "清白+，得罪人",
        'apply': function(){
return{'clean':0xf,'guanxi':-0xc,'text':"你把信封推了回去，饭没吃完就起身走了。之后半年，裁判的哨子对你格外严厉。"};
}
    },
    {
        'label': '举报',
        'hint': "清白大增，代价惨"+'重',
        'apply': function(){
return{'clean':0x1e,'guanxi':-0x1e,'roleDelta':-0x2,'fame':0x14,'text':"你把录音交了上去。案子办了三年，这三年里你换了四家俱乐部，没有一家愿意让你踢主力。"};
}
    }
  ]
},

// ---- idx:37 | cn_gambl | 赌一把 ----
{
  'id': "cn_gambl"+'e',
  'title': "赌一把",
  'icon': '🎲',
  'weight': 0x32,
  'repeat': 0x2,
  'cn': !0x0,
  'desc': "队友把你拉进一个群，群里押自己队的比赛。「小钱，玩玩而已。」",
  'options': [
    {
        'p': function(p){return f(0.6,[[p["clean"],70,0.008]],0.2,0.9);
},
        'label': "跟着玩",
        'hint': "小赚，清白-",
        'odds': ["先赢一把","输两个月"],
        'apply': function(p,q,s){
return d(q,s)?{'money':0xb4,'clean':-0x1c,'gambled':!0x0,'text':"第一次就赢了。赢"+"钱这件事比"+h(p,{'gk':"扑出一个点球",'other':"进一个球"})+("来得容易，这才是"+"最危险的地方。")}:{'money':-0x15e,
'clean':-0x1c,'gambled':!0x0,'text':"输了两个月工资。你已经开始盘算，下一场怎么捞回来。"};
}
    },
    {
        'label': '退群',
        'hint': "清白+",
        'apply': function(){
return{'clean':0xa,'text':"你退了群。三年后，那个群里的人上了通报，名单很长。"};
}
    }
  ]
},

// ---- idx:38 | cn_antic | ? ----
{
  'id': "cn_antic"+"orruptio"+'n',
  'title': '风暴',
  'icon': '🚨',
  'weight': 0x5f,
  'cn': !0x0,
  'repeat': 0x3,
  'when': function(p){
return p["age"]>=0x16;
},
  'desc': "反腐专项组进驻足协。这两天，陆续有人被带走，其中就有那位一直很照顾你的领导。",
  'options': [
    {
        'label': "配合调查",
        'hint': "清白低的人扛不过"+'去',
        'odds': ["上了通报","扛过去了"],
        'apply': function(p,q){
return d(q,p["clean"]>=0x44?0x0:(0x44-p["clean"])/0x2d)?{'banned':!0x0,'fame':-0x28,'text':"你的名字出现在通报的第二段。终身禁足。所有奖杯合影里的你，都被打了码。"}:p["clean"]<0x44?{'clean':-0x5,
'guanxi':-0x19,'roleDelta':-0x1,'fame':-0xa,'text':"谈话谈了两天。什么也没查出来，可你的国字号名额没了，没人告诉你为什么。"}:{'clean':0x6,'guanxi':-0xf,'fame':0xc,
'text':"你什么问题都没有。风暴过后，队里干净的人不多，你是其中一个。"};
}
    },
    {
        'label': "赶紧撇清",
        'hint': "关系归零",
        'apply': function(){
return{'guanxi':-0x23,'clean':0x5,'fame':-0x5,'text':"你连夜删光了所有聊天记录。之后几年，你确实没事，也确实再没进过任何名单。"};
}
    }
  ]
},

// ---- idx:39 | cn_yinya | 两份合同 ----
{
  'id': "cn_yinya"+'ng',
  'title': "两份合同",
  'icon': '📄',
  'weight': 0x2d,
  'cn': !0x0,
  'when': function(p){
return p["inChina"]&&p["ovr"]>=0x41;
},
  'desc': "俱乐部给了你两份合同，一份报备，一份实际执行。财务说「大家都是这么签的」。",
  'options': [
    {
        'label': "签字",
        'hint': "收入大增，清白-",
        'apply': function(){
return{'money':0x226,'clean':-0x12,'yinyang':!0x0,'text':"到手的钱多了不少。你把那份「实际执行」的复印件，锁进了保险柜。"};
}
    },
    {
        'label': "只签报备那份",
        'hint': "收入低，清白+",
        'apply': function(){
return{'money':-0xb4,'clean':0xc,'text':"财务看了你一眼，说了句「你是第一个」。那语气，听不出是夸还是别的。"};
}
    }
  ]
},

// ---- idx:40 | cn_tax | ? ----
{
  'id': "cn_tax",
  'title': '查税',
  'icon': '🧾',
  'weight': 0x37,
  'cn': !0x0,
  'when': function(p){
return p["yinyang"]||p["money"]>=0xbb8;
},
  'desc': "税务部门开始核查体育行业的收入申报。你那两份合同的事，有人把材料递了上去。",
  'options': [
    {
        'label': "主动补缴",
        'hint': "破财免灾",
        'apply': function(p){
return{'money':-Math["max"](0xfa,0.4*p["money"]|0x0),'clean':0x6,'text':"补缴加滞纳金，一次性划走了你大半积蓄。至少，这事到此为止。"};
}
    },
    {
        'p': function(p){return f(0.4,[[p["clean"],70,0.008]],0.2,0.9);
},
        'label': '扛着',
        'hint': function(p,q){return g(q,'没事','重罚');
},
        'apply': function(p,q,s){
return d(q,s)?{'text':"材料递上去之后没了下文。悬了一年的心，你慢慢也就放下了。"}:{'money':-0x384,'ban':0x1,'fame':-0x19,'clean':-0xa,'text':"通报点了你的名。罚款是补缴额的四倍，外加停赛半年。你成了那年的典型。"};
}
    }
  ]
},

// ---- idx:41 | cn_titi | ? ----
{
  'id': "cn_titi",
  'title': '体测',
  'icon': '⏱️',
  'weight': 0x3c,
  'repeat': 0x3,
  'cn': !0x0,
  'when': function(p){
return p["inChina"];
},
  'desc': "赛季前的体测又改了标准，这次是 12 分钟跑加折返。不达标就不能报名，跟你会不会踢球没关系。",
  'options': [
    {
        'label': "苦练体能",
        'hint': "能力+1，稳过",
        'apply': function(){
return{'ovr':0x1,'text':"你练了一个冬天的长跑。测试那天轻松过关，之后再没跑过那么远。"};
}
    },
    {
        'p': function(p){return f(0.7,[[p["ovr"],60,0.008]],0.2,0.9);
},
        'label': "赌能过",
        'hint': function(p,q){return g(q,'过','整期无法报名');
},
        'apply': function(p,q,s){
return d(q,s)?{'text':"压线过了。你在终点线躺了五分钟，队医过来问你还好吗。"}:{'roleDelta':-0x3,'ovr':-0x2,'text':"差了 40 米。整个前半程，你都在看台上坐着——旁边，是队里技术最好的那个队友。"};
}
    }
  ]
},

// ---- idx:42 | cn_u23 | U23 政策 ----
{
  'id': "cn_u23",
  'title': "U23 政策",
  'icon': '🔢',
  'weight': 0x37,
  'cn': !0x0,
  'when': function(p){
return p["inChina"]&&p["age"]<=0x17;
},
  'desc': "新政要求每场必须有 U23 出场。你被安排首发，开场 15 分钟就被换下——名额，用完了。",
  'options': [
    {
        'label': "接受安排",
        'hint': "出场数虚高，能力"+'停滞',
        'apply': function(){
return{'roleDelta':0x1,'ovr':-0x1,'text':"这个赛季，你的出场次数排进队内前三，总时长却排在第十七。"};
}
    },
    {
        'p': function(p){return f(0.5,[[p["ovr"],60,0.008]],0.2,0.9);
},
        'label': "要求真正的机会",
        'hint': function(p,q){return g(q,'争取到','被弃用');
},
        'apply': function(p,q,s){
return d(q,s)?{'roleDelta':0x1,'ovr':0x3,'text':"你跟教练摊牌了。"+"他给了你一个整场"+"，你用"+h(p,{'gk':"一场零封",'def':"一次门线上的解围",'other':"一次助攻"})+"把位置踢了下来。"}:{'roleDelta':-0x2,
'text':"教练说「那就让别人去当那个 15 分钟」。你连那 15 分钟，也没有了。"};
}
    }
  ]
},

// ---- idx:43 | cn_jixun | 抽调进集训队 ----
{
  'id': "cn_jixun",
  'title': "抽调进集训队",
  'icon': "🏕️",
  'weight': 0x32,
  'cn': !0x0,
  'when': function(p){
return p["inChina"]&&p["age"]<=0x1a&&p["ovr"]>=0x3c;
},
  'desc': "为了备战大赛，成立了一支长期集训队，从各队抽人，一去半年，不踢联赛。",
  'options': [
    {
        'label': "就去",
        'hint': "征召+，联赛地位"+'受损',
        'apply': function(){
return{'caps':0x4,'guanxi':0xc,'roleDelta':-0x2,'ovr':-0x1,'text':"半年里，你踢了二十场友谊赛，赢了十七场。回到联赛，你的位置上已经站着别人。"};
}
    },
    {
        'label': "报伤不去",
        'hint': "地位保住，关系-",
        'apply': function(){
return{'guanxi':-0x14,'roleDelta':0x1,'text':"队医给你开了一张诊断。这张纸保住了你的主力，也让你从此不在任何名单里。"};
}
    }
  ]
},

// ---- idx:44 | cn_leade | 领导来看球 ----
{
  'id': "cn_leade"+'r',
  'title': "领导来看球",
  'icon': '🎩',
  'weight': 0x2d,
  'repeat': 0x2,
  'cn': !0x0,
  'when': function(p){
return p["inChina"];
},
  'desc': "主席台上今天坐了不少人。赛前动员会，教练说这场「不只是三分的问题」。",
  'options': [
    {
        'p': function(p){return f(0.6,[[p["fame"],25,0.01]],0.2,0.9);
},
        'label': "拼命表现",
        'hint': function(p,q){return g(q,'一战成名','用力过猛');
},
        'apply': function(p,q,s){
return d(q,s)?{'fame':0xf,'guanxi':0xc,'roleDelta':0x1,'text':"你踢了全场最漂亮的一脚。散场时，有人把你叫到通道口，握手握了很久。"}:{'ovr':-0x2,'banGames':0x3,
'text':"你太想表现，第 30 分钟，一次莽撞的犯规让你被罚下。主席台上没有人鼓掌。"};
}
    },
    {
        'label': "正常踢",
        'hint': "无变化",
        'apply': function(){
return{'text':"你按平时的踢法，走完了 90 分钟。赛后的总结会上，你的名字没有被提到。"};
}
    }
  ]
},

// ---- idx:45 | cn_weibo | 上了热搜 ----
{
  'id': "cn_weibo",
  'title': "上了热搜",
  'icon': '📱',
  'weight': 0x41,
  'repeat': 0x3,
  'cn': !0x0,
  'when': function(p){
return p["caps"]>=0x1;
},
  'desc': "国家队又输了。那场你踢得不差，热搜第一条却挂着你的名字，配图是你低头走向通道的抓拍。",
  'options': [
    {
        'p': function(p){return f(0.45,[[p["clean"],70,0.008]],0.2,0.9);
},
        'label': "回一条",
        'hint': "名气+，也可能更"+'糟',
        'odds': ["舆论转向","越描越黑"],
        'apply': function(p,q,s){
return d(q,s)?{'fame':0x16,'text':"你写了三百字，该认的认了，该说的也说了。评论区第一次有人打出「加油」。"}:{'fame':-0x12,'ovr':-0x1,'text':"你的回应被截成九宫格逐句嘲讽。你删了微博，可人还在网上，删不掉。"};
}
    },
    {
        'label': "关掉评论",
        'hint': "名气-，心态保住",
        'apply': function(){
return{'fame':-0x6,'ovr':0x1,'text':"你把 App 卸了，第二天照常出现在训练场。听不见的声音，就当它不存在。"};
}
    }
  ]
},

// ---- idx:46 | cn_natur | ? ----
{
  'id': "cn_natur"+"alize",
  'title': '归化',
  'icon': '🛂',
  'weight': 0x2d,
  'cn': !0x0,
  'when': function(p){
return p["inChina"]&&p["roleRank"]<=0x3;
},
  'desc': "队里来了两个归化球员，年薪是你的六倍，踢的正是你的位置。发布会上，他们背了一段现学的中文。",
  'options': [
    {
        'label': "接受现实",
        'hint': "地位下降，能力+"+'2',
        'apply': function(){
return{'roleDelta':-0x2,'ovr':0x2,'text':"你在替补席上看了一整年。他们的技术确实好，这一点，你从未否认过。"};
}
    },
    {
        'label': "要求转会",
        'hint': '离队',
        'apply': function(){
return{'leave':!0x0,'fame':-0x5,'text':"你递了转会申请。走的那天，俱乐部发了条通稿，感谢你「为球队做出的贡献」——不多不少，42 个字。"};
}
    }
  ]
},

// ---- idx:47 | cn_lives | 直播带货 ----
{
  'id': "cn_lives"+"how",
  'title': "直播带货",
  'icon': '📺',
  'weight': 0x28,
  'cn': !0x0,
  'when': function(p){
return p["inChina"]&&p["fame"]>=0x28;
},
  'desc': "MCN 找上门来，说凭你现在的人气，一场直播的坑位费，顶你三个月的工资。",
  'options': [
    {
        'label': '开播',
        'hint': "收入大增，能力-"+"，名气+",
        'apply': function(p){
return{'money':0x1c2+0x4*p["fame"],'ovr':-0x3,'fame':0xf,'text':"你在镜头前喊了三个小时「家人们」。当晚成交额漂亮得吓人，第二天训练，你跑不动了。"};
}
    },
    {
        'label': '拒了',
        'hint': "能力+2",
        'apply': function(){
return{'ovr':0x2,'text':"你说，自己还是球员。MCN 转身签了另一个刚退役的，那人现在已是头部主播。"};
}
    }
  ]
},

// ---- idx:48 | cn_zhoub | 队内酒局 ----
{
  'id': "cn_zhoub"+'ao',
  'title': "队内酒局",
  'icon': '🍻',
  'weight': 0x2d,
  'repeat': 0x2,
  'cn': !0x0,
  'when': function(p){
return p["inChina"];
},
  'desc': "赢球之后，老队员组了个局，名目叫「统一思想」。教练组心知肚明，从不插手。",
  'options': [
    {
        'label': "就去",
        'hint': "队内地位+，能力"+'-',
        'apply': function(){
return{'roleDelta':0x1,'ovr':-0x2,'clean':-0x4,'text':"喝到凌晨三点。第二天训练，所有人都在放水，气氛好得不像话。"};
}
    },
    {
        'label': '不去',
        'hint': "被孤立，能力+",
        'apply': function(p){
return{'ovr':0x2,'roleDelta':-0x1,'text':"你回房间睡了。之"+"后半年，"+h(p,{'gk':"后卫回传球总是又"+"急又高，没人愿意"+"多跑两步给你一个"+"好角度。",'other':"传中球总是很难找"+"到你的位置。"})};
}
    }
  ]
},

// ---- idx:49 | cn_trans | 转会卡在手里 ----
{
  'id': "cn_trans"+"fer_bloc"+'k',
  'title': "转会卡在手里",
  'icon': '🔒',
  'weight': 0x2d,
  'cn': !0x0,
  'when': function(p){
return p["inChina"]&&p["ovr"]>=0x42;
},
  'desc': "海外球队来了报价，俱乐部却开出远超市场的价格——摆明了不放人，也不给你涨一分钱。",
  'options': [
    {
        'p': function(p){return f(0.5,[[p["clean"],70,0.008]],0.2,0.9);
},
        'label': "公开抗议",
        'hint': function(p,q){return g(q,'放行','雪藏');
},
        'apply': function(p,q,s){
return d(q,s)?{'goAbroad':!0x0,'fame':0xf,'text':"你把事情捅给了媒体。舆论压下来，俱乐部终于松了口。"}:{'roleDelta':-0x3,'fame':0x8,'text':"俱乐部把你挂了起来，整整一年，没让你进过一次一线队名单。转会窗一关，人也就废了半年。"};
}
    },
    {
        'label': '认了',
        'hint': "无变化",
        'apply': function(){
return{'ovr':-0x1,'text':"报价过期了。俱乐部通稿里写着「球员本人无意离队」——这句话，你是从新闻上看到的。"};
}
    }
  ]
},

// ---- idx:50 | cn_schoo | ? ----
{
  'id': "cn_schoo"+"l_pick",
  'title': '选择',
  'icon': '🎓',
  'weight': 0x37,
  'cn': !0x0,
  'stage': "youth",
  'when': function(p){
return p["inAcadem"+'y'];
},
  'desc': "高三了。体校教练说，再练两年就有职业合同；班主任说，你的成绩够得上一本。那天晚上，父母吵到很晚。",
  'options': [
    {
        'label': '踢球',
        'hint': "能力+4，退路没"+'了',
        'apply': function(){
return{'ovr':0x4,'text':"志愿表上，你一个学校都没填。那晚，母亲一直在厨房里，没有出来。"};
}
    },
    {
        'label': "先考大学",
        'hint': "能力-3，多一条"+'路',
        'apply': function(){
return{'ovr':-0x3,'clean':0x8,'degree':!0x0,'text':"你考上了，读的是体育教育。四年后你终究回来踢球，只是起点，比同龄人晚了四年。"};
}
    }
  ]
},

// ---- idx:51 | cn_ref | ? ----
{
  'id': "cn_ref",
  'title': '哨子',
  'icon': '📯',
  'weight': 0x32,
  'cn': !0x0,
  'when': function(p){
return p["inChina"]&&p["guanxi"]>=0x2d;
},
  'desc': "关键场次，一个再明显不过的犯规，裁判没吹。你们占了便宜，客队全队围上去讨说法。",
  'options': [
    {
        'label': "什么都不说",
        'hint': "夺冠概率提升，清"+'白-',
        'apply': function(){
return{'mult':{'league':1.6,'cup':1.6},'clean':-0x8,'text':"你什么也没说，转身跑回半场。赛后集锦里，那个镜头被剪掉了。"};
}
    },
    {
        'label': "示意裁判",
        'hint': "名气大增，得罪人",
        'apply': function(){
return{'fame':0x19,'guanxi':-0x12,'mult':{'league':0.7},'text':"你跑过去告诉裁判：那是犯规。新闻上了热搜，你也在某些人那里，彻底挂了号。"};
}
    }
  ]
},

// ---- idx:52 | cn_farew | 退役之后 ----
{
  'id': "cn_farew"+"ell",
  'title': "退役之后",
  'icon': '🧭',
  'weight': 0x28,
  'cn': !0x0,
  'stage': "vet",
  'desc': "你开始想，退役以后做什么。有人劝你去考教练证，有人说搞青训正赶上了风口。",
  'options': [
    {
        'label': "考教练证",
        'hint': "清白+，收入-",
        'apply': function(){
return{'money':-0x3c,'clean':0x5,'coachCert':!0x0,'text':"休赛期，你去上了课。班上一半是退役球员，另一半，是从来没踢过球的投资人。"};
}
    },
    {
        'p': function(p){return f(0.45,[[p["guanxi"],45,0.008]],0.2,0.9);
},
        'label': "投钱做青训",
        'hint': "赌运气",
        'odds': ["招满了","烧光积蓄"],
        'apply': function(p,q,s){
return d(q,s)?{'money':0xb4,'academy':!0x0,'text':"第一批学员招满了。你站在场边看他们跑动，忽然想起自己十六岁那年。"}:{'money':-0x2ee,'text':"场地租金、教练工资，烧光了积蓄，招来的只有十一个孩子。第二年，你把场地退了。"};
}
    }
  ]
},

// ---- idx:62 | cn_donxu | ? ----
{
  'id': "cn_donxu"+'n',
  'title': '冬训',
  'icon': '🏔',
  'weight': 0x3c,
  'cn': !0x0,
  'repeat': 0x3,
  'desc': "又是昆明海埂。一天三练：上午越野，下午对抗，晚上开会看录像，直到十一点。",
  'options': [
    {
        'p': function(p){return f(0.65,[[p["talent"],1,0.4]],0.2,0.9);
},
        'label': '全上',
        'hint': function(p,q){return g(q,'能力+3','练废');
},
        'apply': function(p,q,s){
return d(q,s)?{'ovr':0x3,'text':"一个冬天下来，体测全队第一。赛季前六轮，你像换了个人。"}:{'ovr':-0x4,'roleDelta':-0x1,'text':"第三周，膝盖积液。老队员说，这叫「练死了」，每年都有几个。"};
}
    },
    {
        'label': '留力',
        'hint': "能力+1，被说不"+'刻苦',
        'apply': function(){
return{'ovr':0x1,'guanxi':-0x8,'roleDelta':-0x1,'text':"你按自己的节奏练。总结会上，教练组撂下一句：「有些人心思不在这儿。」"};
}
    }
  ]
},

// ---- idx:63 | cn_xianx | 限薪令 ----
{
  'id': "cn_xianx"+'in',
  'title': "限薪令",
  'icon': '✂️',
  'weight': 0x46,
  'cn': !0x0,
  'repeat': 0x2,
  'when': function(p){
return p["inChina"];
},
  'desc': "足协一纸文件，顶薪一刀切。你刚签的合同，一夜之间要重签，降幅超过一半。",
  'options': [
    {
        'label': "签补充协议",
        'hint': "收入大减",
        'apply': function(p){
return{'money':-Math["max"](0x78,0.3*p["money"]|0x0),'text':"你签了。还是那间会议室，去年吹嘘引援投入的人，一个都没来。"};
}
    },
    {
        'p': function(p){return f(0.5,[[p["guanxi"],45,0.008]],0.2,0.9);
},
        'label': "拒签闹到仲裁",
        'hint': function(p,q){return g(q,'拿回部分','被雪藏');
},
        'apply': function(p,q,s){
return d(q,s)?{'money':0x64,'fame':0xc,'guanxi':-0xf,'text':"仲裁支持了你一部分诉求。俱乐部照付，只是从此，把你当外人。"}:{'roleDelta':-0x3,'money':-0x96,
'fame':0x8,'text':"案子拖了一年多。这一年，你没上过一场比赛，一分工资也没拿到。"};
}
    }
  ]
},

// ---- idx:64 | cn_waiyu | 外援政策 ----
{
  'id': "cn_waiyu"+'an',
  'title': "外援政策",
  'icon': '🛫',
  'weight': 0x3c,
  'cn': !0x0,
  'repeat': 0x2,
  'when': function(p){
return p["inChina"]&&'gk'!==p["posGroup"]&&p["roleRank"]<=0x3;
},
  'desc': "新赛季，外援名额放宽到五个，五个都挤在你的位置上轮番上场。",
  'options': [
    {
        'label': "改踢别的位置",
        'hint': "有球踢，能力-2",
        'apply': function(){
return{'ovr':-0x2,'roleDelta':0x1,'text':"你去踢了边路。两年后才回到原位置，回来时，原来那些动作已经生疏了。"};
}
    },
    {
        'p': function(p){return f(0.5,[[p["ovr"],60,0.008]],0.2,0.9);
},
        'label': "死守位置",
        'hint': function(p,q){return g(q,'争到','一年白费');
},
        'apply': function(p,q,s){
return d(q,s)?{'roleDelta':0x1,'ovr':0x2,'fame':0x8,'text':"热身赛，你把那个八百万欧的外援，按在了替补席上。这种事，一年也就一两次。"}:{'roleDelta':-0x3,'text':"一整年，你只打了四百分钟，全是垃圾时间。"};
}
    }
  ]
},

// ---- idx:65 | cn_yidi | 球队搬走了 ----
{
  'id': "cn_yidi",
  'title': "球队搬走了",
  'icon': '🚚',
  'weight': 0x2d,
  'cn': !0x0,
  'when': function(p){
return p["inChina"];
},
  'desc': "投资方把整支球队迁去两千公里外的另一个省。那晚，球迷在球场外坐了一整夜。",
  'options': [
    {
        'label': "跟着走",
        'hint': "保住合同，名气-",
        'apply': function(){
return{'fame':-0xc,'money':0x3c,'text':"你跟着去了。新主场的第一场，看台上坐了三百人，横幅上，是当地赞助商的广告。"};
}
    },
    {
        'label': "留下换队",
        'hint': '离队',
        'apply': function(){
return{'leave':!0x0,'fame':0xa,'text':"你说，这座城市养了你八年。老球迷把这句话记住了——虽然球队，已经不在。"};
}
    }
  ]
},

// ---- idx:66 | cn_qingx | 青训补偿 ----
{
  'id': "cn_qingx"+'un',
  'title': "青训补偿",
  'icon': '📄',
  'weight': 0x2d,
  'cn': !0x0,
  'when': function(p){
return p["age"]<=0x18;
},
  'desc': "老东家翻出一份你十二岁签的协议，要收一笔天价青训补偿，转会就此卡住。",
  'options': [
    {
        'label': "自掏腰包",
        'hint': "破财但走成",
        'apply': function(p){
return{'money':-Math["max"](0x50,0.35*p["money"]|0x0),'text':"你自己垫了这笔钱。签字那天你才看清，十二岁那年，家里到底签了什么。"};
}
    },
    {
        'p': function(p){return f(0.45,[[p["guanxi"],45,0.008]],0.2,0.9);
},
        'label': "打官司",
        'hint': "拖一年，可能白拖",
        'odds': ["仲裁赢了","白拖一年"],
        'apply': function(p,q,s){
return d(q,s)?{'fame':0x8,'clean':0x5,'text':"仲裁认定协议无效"+"。你赢了，也在场"+"外坐了整整一年。"}:{'roleDelta':-0x2,'ovr':-0x2,'text':"官司拖了一年半，转会窗开了又关，三次。到头来，你什么也没得到。"};
}
    }
  ]
},

// ---- idx:67 | cn_yueta | 被约谈 ----
{
  'id': "cn_yueta"+'n',
  'title': "被约谈",
  'icon': '☕',
  'weight': 0x32,
  'cn': !0x0,
  'repeat': 0x2,
  'when': function(p){
return p["inChina"]&&p["fame"]>=0x1e;
},
  'desc': "赛后，你说了句「这场球大家都看见了」。第二天，纪律委员会请你喝茶。",
  'options': [
    {
        'label': "写检查",
        'hint': "名气-，关系+",
        'apply': function(){
return{'fame':-0xc,'guanxi':0xa,'text':"三千字检查，念了一遍，录了像。此后半年，裁判对你格外温柔。"};
}
    },
    {
        'label': '不写',
        'hint': "重罚，球迷买账",
        'apply': function(){
return{'banGames':0x5,'money':-0x50,'fame':0x14,'guanxi':-0x14,'text':"停赛五场，加罚款。球迷把你那句话做成了表情包，一用就是好几年。"};
}
    }
  ]
},

// ---- idx:68 | cn_saihu | 赛会制 ----
{
  'id': "cn_saihu"+'i',
  'title': "赛会制",
  'icon': '🏨',
  'weight': 0x2d,
  'cn': !0x0,
  'when': function(p){
return p["inChina"];
},
  'desc': "整个赛季，集中到一座城市打完。全封闭，四个月，出不了酒店的门。",
  'options': [
    {
        'label': '熬',
        'hint': "能力+2，心态受"+'损',
        'apply': function(){
return{'ovr':0x2,'fame':-0x4,'text':"四个月，你把酒店走廊走了一万遍。有人在里面，把婚离了。"};
}
    },
    {
        'label': "申请特殊回家",
        'hint': "被拒且记过",
        'apply': function(){
return{'guanxi':-0xc,'roleDelta':-0x1,'text':"申请没批。领队说：「大家都一样。」——可并不是大家都一样。"};
}
    }
  ]
},

// ---- idx:69 | cn_zhuan | 退役以后干什么 ----
{
  'id': "cn_zhuan"+'ye',
  'title': "退役以后干什么",
  'icon': '💼',
  'weight': 0x2d,
  'cn': !0x0,
  'stage': "vet",
  'desc': "队里请来个讲师，讲职业规划。台下二十个人，谁也说不出明年自己会在哪。",
  'options': [
    {
        'label': "考教练证",
        'hint': "花钱，退役有出路",
        'apply': function(){
return{'money':-0x32,'clean':0x4,'coachCert':!0x0,'text':"你报了 C 级班。同期学员里，三个是你当年的对手，如今都在等同一个岗位。"};
}
    },
    {
        'label': "先不想",
        'hint': "专心踢球，能力+"+'2',
        'apply': function(){
return{'ovr':0x2,'text':"你说还能再踢几年。讲师笑了笑，说你这句，每年都有人讲。"};
}
    }
  ]
},

// ---- idx:85 | cn_bianz | 体育局的编制 ----
{
  'id': "cn_bianz"+'hi',
  'title': "体育局的编制",
  'icon': '🧾',
  'weight': 0x30,
  'cn': !0x0,
  'stage': "youth",
  'desc': "省队给了个带编制的名额。工资不高，但一辈子有保障，代价是别再想随便转会。",
  'options': [
    {
        'label': "要编制",
        'hint': "钱稳，能力涨得慢",
        'apply': function(){
return{'money':0x3c,'ovr':-0x2,'guanxi':0xc,'bianzhi':!0x0,'text':"你爸松了一口气，说这下踏实了。你在同一块场地上练了好几年，再没人催你进步。"};
}
    },
    {
        'label': '不要',
        'hint': "能力+3，家里不"+'理解',
        'apply': function(){
return{'ovr':0x3,'guanxi':-0x6,'text':"你说，想去踢真正的比赛。那年过年，亲戚问你「有编制没」，你说没有。"};
}
    }
  ]
},

// ---- idx:86 | cn_shiye | 欠薪冲超 ----
{
  'id': "cn_shiye",
  'title': "欠薪冲超",
  'icon': '🎢',
  'weight': 0x2e,
  'cn': !0x0,
  'when': function(p){
return p["clubRep"]<=0x2;
},
  'desc': "老板说，冲上去，什么都好说。全队三个月没发工资，还在加练。",
  'options': [
    {
        'p': function(p){return f(0.7,[[p["ovr"],60,0.008]],0.2,0.9);
},
        'label': "跟着拼",
        'hint': function(p,q){return g(q,'冲上去了','白干一年');
},
        'apply': function(p,q,s){
return d(q,s)?{'ovr':0x3,'fame':0xc,'money':0x5a,'mult':{'league':2.2},'text':"最后一轮客场绝杀"+"，全队在更衣室里"+"哭。工资是补发了"+"，只补了七成。"}:{'ovr':-0x1,
'money':-0x3c,'roleDelta':-0x1,'text':"差两分。老板当晚就飞去了国外。队里的人，第二天才知道。"};
}
    },
    {
        'label': "先保住自己",
        'hint': "能力+1，被当成"+'刺头',
        'apply': function(){
return{'ovr':0x1,'guanxi':-0xa,'roleDelta':-0x1,'text':"你去劳动仲裁递了材料。队友说你不讲义气，你说，讲义气的人上个月已经走了。"};
}
    }
  ]
},

// ---- idx:167 | cn_youth | 青年赛的默契球 ----
{
  'id': "cn_youth"+"_fix",
  'title': "青年赛的默契球",
  'icon': '🤫',
  'weight': 0x30,
  'cn': !0x0,
  'stage': "youth",
  'when': function(p){
return p["inAcadem"+'y'];
},
  'desc': "最后一轮，两队心里都清楚：踢平，一起出线。赛前，领队把两边的队长叫到了一处。",
  'options': [
    {
        'label': "跟着走",
        'hint': "清白重创，一起出"+'线',
        'apply': function(){
return{'clean':-0x12,'roleDelta':0x1,'fixed':!0x0,'text':"全场没有一次射门。看台上，一位家长站起来骂了一句，被保安请了出去。"};
}
    },
    {
        'p': function(p){return f(0.6,[[p["clean"],70,0.008]],0.2,0.9);
},
        'label': "自己踢自己的",
        'hint': function(p,q){return g(q,'被记住','被孤立');
},
        'apply': function(p,q,s){
return d(q,s)?{'clean':0x8,'ovr':0x3,'fame':0x8,'text':"第 80 分钟，你当着两边所有人的面，拼了一次全力。那场之后，有支职业队的球探记下了你的名字。"}:{'clean':0x8,'guanxi':-0x10,
'roleDelta':-0x2,'text':"球没进，队伍出局。回程的大巴上，没人跟你坐一排。"};
}
    }
  ]
},

// ---- idx:168 | cn_hukou | ? ----
{
  'id': "cn_hukou",
  'title': '户口',
  'icon': "🗂️",
  'weight': 0x2d,
  'cn': !0x0,
  'stage': "youth",
  'when': function(p){
return p["inAcadem"+'y'];
},
  'desc': "外省来的孩子，在这边不能参加注册赛。有人说，可以「办一下」。",
  'options': [
    {
        'label': "办一下",
        'hint': "花钱，能踢比赛",
        'apply': function(){
return{'money':-0x46,'clean':-0xa,'guanxi':0xa,'ovr':0x3,'text':"手续走了半年。材料上那个出生地，不是你真出生的地方。你终于能上场了。"};
}
    },
    {
        'p': function(p){return f(0.5,[[p["guanxi"],45,0.008]],0.2,0.9);
},
        'label': "等政策",
        'hint': function(p,q){return g(q,'等到了','耽误两年');
},
        'apply': function(p,q,s){
return d(q,s)?{'ovr':0x1,'clean':0x4,'text':"第二年，注册办法改了。你赶上了末班车。"}:{'ovr':-0x3,'roleDelta':-0x1,'text':"你在场边看了两年球。等到能报名时，同届的早都上一线队了。"};
}
    }
  ]
},

// ---- idx:192 | cn_new_s | 新球场 ----
{
  'id': "cn_new_s"+"tadium",
  'title': "新球场",
  'icon': "🏟️",
  'weight': 0x30,
  'cn': !0x0,
  'desc': "地方上砸下座六万人的新球场。主队搬进去，票价翻了一倍，上座率掉了一半。",
  'options': [
    {
        'label': "公开说老球场好",
        'hint': "球迷买账，上面不"+'高兴',
        'apply': function(){
return{'fame':0x10,'guanxi':-0xe,'text':"你在镜头前说，老球场离球迷近。这句话剪进了当地新闻，紧接着，又被剪掉。"};
}
    },
    {
        'label': "配合宣传",
        'hint': "关系+，钱+",
        'apply': function(){
return{'guanxi':0xc,'money':0x28,'fame':-0x6,'text':"你站在新球场中央拍宣传照，笑得很标准。开幕战，上座一万二。"};
}
    }
  ]
},

// ---- idx:193 | cn_fan_c | 球迷冲突 ----
{
  'id': "cn_fan_c"+"lash",
  'title': "球迷冲突",
  'icon': '🚧',
  'weight': 0x2d,
  'cn': !0x0,
  'desc': "德比刚结束，两边球迷在停车场动起手来。你的车，正好堵在最中间。",
  'options': [
    {
        'p': function(p){return f(0.6,
[[p["fame"],25,0.01]],0.2,0.9);
},
        'label': "下车劝",
        'hint': function(p,q){return g(q,'被记住','挨了一下');
},
        'apply': function(p,q,s){
return d(q,s)?{'fame':0x14,'guanxi':0x8,'text':"你站到两拨人中间，喊了三分钟。视频传开以后，很多人说：这才是职业球员。"}:{'fame':0xa,'ovr':-0x2,'text':"不知谁从背后砸来个瓶子。缝了四针，两个星期没上场。"};
}
    },
    {
        'label': "锁门等警察",
        'hint': "无变化",
        'apply': function(){
return{'text':"你在车里坐了四十分钟。第二天，没人再提这事，俱乐部也是。"};
}
    }
  ]
},

// ---- idx:194 | cn_agent | 经纪人的抽成 ----
{
  'id': "cn_agent"+"_cut",
  'title': "经纪人的抽成",
  'icon': '✂️',
  'weight': 0x30,
  'cn': !0x0,
  'stage': "prime",
  'desc': "转会敲定后你才听说，经纪人从俱乐部那头也抽了一笔，数目比你的签字费还高。",
  'options': [
    {
        'p': function(p){return f(0.6,[[p["guanxi"],45,0.008]],0.2,0.9);
},
        'label': "撕破脸",
        'hint': function(p,q){return g(q,'追回来','转会黄了');
},
        'apply': function(p,q,s){
return d(q,s)?{'money':0x96,'guanxi':-0xc,'clean':0x6,'text':"你换了经纪人，把那笔钱讨了回来。这行里，从此有人背后说你不好带。"}:{'money':-0x3c,'roleDelta':-0x1,
'text':"转会在最后一刻黄了。新东家那边传话：「这孩子，事多。」"};
}
    },
    {
        'label': '忍了',
        'hint': "钱少了，路好走",
        'apply': function(){
return{'money':-0x50,'guanxi':0xa,'text':"你什么都没说。他后来又替你张罗过两次转会，每次，佣金都抽得很干净。"};
}
    }
  ]
},

// ---- idx:195 | cn_team_ | ? ----
{
  'id': "cn_team_"+"doctor",
  'title': '队医',
  'icon': "🧑‍⚕️",
  'weight': 0x30,
  'cn': !0x0,
  'desc': "队医是老板的亲戚。处理伤病只有两招：冰敷，和一句「再练练」。",
  'options': [
    {
        'label': "自费找外面的",
        'hint': "花钱，能力+3",
        'apply': function(){
return{'money':-0x46,'ovr':0x3,'guanxi':-0x6,'text':"你自己联系了运动医学中心。队里说你信不过队医，你说你信得过自己的腿。"};
}
    },
    {
        'p': function(p){return f(0.5,[[p["ovr"],60,0.008]],0.2,0.9);
},
        'label': '忍着',
        'hint': function(p,q){return g(q,'熬过去','拖成大伤');
},
        'apply': function(p,q,s){
return d(q,s)?{'text':"那点伤，后来自己好了。你至今不知道，它当初到底是什么。"}:{'ovr':-0x4,'text':"小伤拖成慢性劳损。三年后再拍片子，医生盯着片子问：当年怎么处理的？"};
}
    }
  ]
},

// ---- idx:196 | cn_forei | 外教来了 ----
{
  'id': "cn_forei"+"gn_coach",
  'title': "外教来了",
  'icon': "🗣️",
  'weight': 0x32,
  'cn': !0x0,
  'desc': "俱乐部请来个欧洲教练。第一堂训练课，他让全队做自己青训里十四岁孩子的传接练习。",
  'options': [
    {
        'p': function(p){return f(0.7,[[p["talent"],1,0.4]],0.2,0.9);
},
        'label': "认真练基本功",
        'hint': function(p,q){return g(q,'能力+5','白练');
},
        'apply': function(p,q,s){
return d(q,s)?{'ovr':0x3,'text':"三个月后，全队失误率掉了一半。你才明白，有些习惯自己错练了十年。"}:{'ovr':-0x1,'guanxi':-0x6,'text':"他撑了半个赛季就被换走，新帅把他那套全推翻。你两头都没落着。"};
}
    },
    {
        'label': "跟着老队员抵触",
        'hint': "关系+，能力-",
        'apply': function(){
return{'guanxi':0xc,'ovr':-0x2,'text':"更衣室里没人听他的。他走那天，只跟翻译握了手。"};
}
    }
  ]
},

// ---- idx:197 | cn_salar | 限薪令 ----
{
  'id': "cn_salar"+"y_cap",
  'title': "限薪令",
  'icon': '📉',
  'weight': 0x32,
  'cn': !0x0,
  'stage': "prime",
  'when': function(p){
return p["ovr"]>=0x44&&p["roleRank"]>=0x2;
},
  'desc': "足协一纸文件，顶薪砍到原来的三分之一，已签的合同「参照执行」。俱乐部把你叫去重签。",
  'options': [
    {
        'label': '签了',
        'hint': "收入大减，队里记"+"你一个人情",
        'apply': function(){
return{'money':-0x104,'guanxi':0x10,'clean':0x6,'text':"你没提条件。后来闹去仲裁的那几个，到头来拿的也不比你多。"};
}
    },
    {
        'p': function(p){return f(0.55,[[p["guanxi"],45,0.008]],0.2,0.9);
},
        'label': "让经纪人想办法",
        'hint': function(p,q){return g(q,'钱保住了','谈崩');
},
        'apply': function(p,q,s){
return d(q,s)?{'money':0xb4,'clean':-0xe,'yinyang':!0x0,'text':"差额，走了一家公司的「形象代言」。合同一式两份，只有一份能见光。"}:{'money':-0x78,'guanxi':-0xe,
'roleDelta':-0x1,'text':"谈崩了。你在替补席坐了半个赛季，再没人提起那份合同。"};
}
    }
  ]
},

// ---- idx:198 | cn_quany | 全运会的名额 ----
{
  'id': "cn_quany"+'un',
  'title': "全运会的名额",
  'icon': '🏟',
  'weight': 0x30,
  'cn': !0x0,
  'when': function(p){
return p["age"]>=0x12&&p["age"]<=0x17;
},
  'desc': "省里点名要你回去打全运会，场次跟联赛撞了。俱乐部的脸色很不好看。",
  'options': [
    {
        'p': function(p){return f(0.5,[[p["ovr"],60,0.008]],0.2,0.9);
},
        'label': "回去打",
        'hint': function(p,q){return g(q,'拿牌两头讨好','位置被顶');
},
        'apply': function(p,q,s){
return d(q,s)?{'guanxi':0x14,'fame':0xa,'text':"你带着队拿了牌。省里记住了你，俱乐部也没把话说死。"}:{'guanxi':0xe,'roleDelta':-0x2,'text':"回来时，你的位置坐了别人。省里那边倒一直念着你的好。"};
}
    },
    {
        'label': "留在俱乐部",
        'hint': "地位保住，得罪省"+'里',
        'apply': function(){
return{'guanxi':-0x12,'roleDelta':0x1,'ovr':0x1,'text':"你说合同在这儿。往后几年，凡是要省里点头的名单，都没有你的名字。"};
}
    }
  ]
},

// ---- idx:199 | cn_winte | ? ----
{
  'id': "cn_winte"+"r_camp",
  'title': '冬训',
  'icon': '🏔',
  'weight': 0x34,
  'cn': !0x0,
  'repeat': 0x2,
  'desc': "昆明海埂，海拔一千九，一天两练，三个月。队医说在这儿练完，回平原能多跑十公里。",
  'options': [
    {
        'label': "顶着练",
        'p': function(p){
return f(0.68,[[p["age"],0x1a,-0.028],[p["ovr"],0x46,0.003]],0.3,0.88);
},
        'hint': function(p,q){
return g(q,"体能脱胎换骨","练废了");
},
        'apply': function(p,q,s){
return d(q,s)?{'ovr':0x4,'text':"开赛前三轮，你的跑动数据全队第一。解说员说，你跟换了个人似的。"}:{'ovr':-0x3,'text':"第七周，膝盖开始积液。余下的冬训，你在健身房看别人跑。"};
}
    },
    {
        'label': "按自己的节奏来",
        'hint': "能力+1，被说不"+'合群',
        'apply': function(){
return{'ovr':0x1,'guanxi':-0x8,'text':"你递给教练组一份自己的计划。他们批了，可那年「刻苦」名单上，没有你。"};
}
    }
  ]
},

// ---- idx:200 | cn_acl_a | 亚冠西亚客场 ----
{
  'id': "cn_acl_a"+"way",
  'title': "亚冠西亚客场",
  'icon': '🛫',
  'weight': 0x2e,
  'cn': !0x0,
  'when': function(p){
return p["clubRep"]>=0x2&&p["roleRank"]>=0x2;
},
  'desc': "飞十一个小时打客场，落地就训练，第三天还有联赛。领队来问你，上不上。",
  'options': [
    {
        'p': function(p){return f(0.55,[[p["ovr"],60,0.008]],0.2,0.9);
},
        'label': "全程跟队",
        'hint': function(p,q){return g(q,'打满全场','透支');
},
        'apply': function(p,q,s){
return d(q,s)?{'roleDelta':0x1,'fame':0x8,'mult':{'cont':1.6},'text':"你在四万人的客场打满全场。回程航班上，全队没人说话。"}:{'ovr':-0x2,'roleDelta':0x1,
'text':"两周三场。第三场下半场，你抽筋被换下。教练记下的，是你上了。"};
}
    },
    {
        'label': "留下备战联赛",
        'hint': "保住状态，被说不"+"顾大局",
        'apply': function(){
return{'ovr':0x2,'guanxi':-0x8,'text':"那场客场丢了三个。赛后发布会上有人放话：「有些人心不在亚冠。」"};
}
    }
  ]
},

// ---- idx:201 | cn_amate | 足协杯打业余队 ----
{
  'id': "cn_amate"+"ur_cup",
  'title': "足协杯打业余队",
  'icon': '🥅',
  'weight': 0x2e,
  'cn': !0x0,
  'when': function(p){
return p["roleRank"]>=0x2;
},
  'desc': "足协杯首轮，对手是支业余队。场地是县城的土场，看台坐满两千人，都是冲你来的。",
  'options': [
    {
        'p': function(p){return f(0.7,[[p["fame"],25,0.01]],0.2,0.9);
},
        'label': "认真踢",
        'hint': function(p,q){return g(q,'名气+','在土坑里崴脚');
},
        'apply': function(p,q,s){
return d(q,s)?{'fame':0xc,'guanxi':0x6,'mult':{'cup':1.4},'text':"赢了四个。散场后你在场边签了四十分钟名，有个孩子递上来一本作业。"}:{'ovr':-0x3,'fame':0x4,
'text':"第 26 分钟，你一脚踩进土场的坑里，脚踝当场肿了。对面那孩子一直道歉，话都说不利索。"};
}
    },
    {
        'label': '留力',
        'hint': "保住身体，球迷失"+'望',
        'apply': function(p){
return{'fame':-0x8,'text':"你踢了半场就被换"+"下。第二天当地论"+"坛的标题是"+h(p,{'gk':"「他连一次扑救都"+"懒得做给我们看」",'other':"「他连一脚射门都"+"不愿意给我们」"})+'。'};
}
    }
  ]
},

// ---- idx:202 | cn_bus_s | 大巴被查封了 ----
{
  'id': "cn_bus_s"+"eized",
  'title': "大巴被查封了",
  'icon': '🚌',
  'weight': 0x2c,
  'cn': !0x0,
  'when': function(p){
return p["clubRep"]<=0x2;
},
  'desc': "欠薪半年，法院给俱乐部大巴贴了封条。下一场客场，全队得自己想办法过去。",
  'options': [
    {
        'label': "带头出面讨薪",
        'hint': "名气大涨，圈子里"+'挂号',
        'apply': function(){
return{'fame':0x16,'guanxi':-0x14,'money':0x3c,'clean':0x6,'text':"你带着队友在基地门口站了一上午。工资补了六成，你的名字也进了另一份名单。"};
}
    },
    {
        'label': "自己垫钱先把球打"+'完',
        'hint': "钱-，队友记你一"+'辈子',
        'apply': function(){
return{'money':-0x5a,'guanxi':0x12,'text':"你订了两辆中巴。那笔钱后来没人提过要还，队友倒是记了很多年。"};
}
    }
  ]
},

// ---- idx:203 | cn_reg_d | 注册截止前四小时 ----
{
  'id': "cn_reg_d"+"eadline",
  'title': "注册截止前四小时",
  'icon': '⏳',
  'weight': 0x2e,
  'cn': !0x0,
  'desc': "转会窗最后一天，注册材料就差俱乐部一个章。办公室的人说，领导在外地。",
  'options': [
    {
        'label': "自己开车去找人签",
        'hint': "钱-，事办成",
        'apply': function(){
return{'money':-0x19,'guanxi':0x8,'text':"你在高速上跑了三"+"百公里，在一个饭"+"局门口等到十一点"+"半。章盖上了，赶"+"上了。"};
}
    },
    {
        'p': function(p){return f(0.5,[[p["guanxi"],45,0.008]],0.2,0.9);
},
        'label': "等他们办",
        'hint': function(p,q){return g(q,'赶上了','空转半个赛季');
},
        'apply': function(p,q,s){
return d(q,s)?{'text':"系统关闭前二十分钟，材料提交成功。中间发生了什么，没人跟你解释过。"}:{'roleDelta':-0x2,'ovr':-0x2,'guanxi':-0x6,'text':"材料卡在系统里。上半赛季，你只能跟着训练，一场正式比赛都没踢上。"};
}
    }
  ]
},

// ---- idx:204 | cn_leade | 领导来看球 ----
{
  'id': "cn_leade"+"r_visit",
  'title': "领导来看球",
  'icon': '🎗',
  'weight': 0x30,
  'cn': !0x0,
  'desc': "地方领导带队来调研，赛前合影，赛后座谈。队里放话：这场球性质不一样。",
  'options': [
    {
        'p': function(p){return f(0.6,[[p["ovr"],60,0.008]],0.2,0.9);
},
        'label': "打起十二分精神",
        'hint': function(p,q){return g(q,'被点名表扬','用力过猛');
},
        'apply': function(p,q,s){
return d(q,s)?{'guanxi':0x10,'mult':{'league':1.3},'text':h(p,{'gk':"你零封了对手，还"+"扑了一个点球。",'other':"你打进一个。"})+("座谈会上领导点了"+"你的名，说这样的"+"球员要多培养。")}:{'guanxi':0x6,
'ovr':-0x1,'text':h(p,{'gk':"你太想表现，几次"+"没必要的出击差点"+"送礼。座谈会上没"+"人提你。",'other':"你太想表现，全场"+"丢了十一次球权。"+"座谈会上没人提你"+'。'})};
}
    },
    {
        'label': "当普通一场踢",
        'hint': "无变化，也没人怪"+'你',
        'apply': function(){
return{'ovr':0x1,'text':"你照常热身，照常拉伸。合影时，你站在最后一排靠边的位置。"};
}
    }
  ]
},

// ---- idx:205 | cn_media | 统一口径 ----
{
  'id': "cn_media"+"_line",
  'title': "统一口径",
  'icon': '🗒',
  'weight': 0x30,
  'cn': !0x0,
  'when': function(p){
return p["fame"]>=0x19;
},
  'desc': "媒体开放日前，俱乐部发来一张纸：上面写着「可以说的三句话」，和「不能提的四件事」。",
  'options': [
    {
        'label': "照着念",
        'hint': "关系+，球迷觉得"+'你假',
        'apply': function(p){
return{'guanxi':0xc,'fame':-0x8,'text':"你一字不差地念完"+"了。那段采访被做"+"成了鬼畜，播放量"+'比你'+h(p,{'gk':"任何一次扑救",'other':"任何一个进球"})+"都高。"};
}
    },
    {
        'label': "说了一句实话",
        'hint': "名气大涨，俱乐部"+'记账',
        'apply': function(){
return{'fame':0x14,'guanxi':-0x10,'clean':0x6,'text':"你说：「欠薪的事，大家心里都有数。」第二天，球队公告说你「言论不代表俱乐部」。"};
}
    }
  ]
},

// ---- idx:206 | cn_banne | 看台上的横幅 ----
{
  'id': "cn_banne"+'r',
  'title': "看台上的横幅",
  'icon': '🧣',
  'weight': 0x2e,
  'cn': !0x0,
  'when': function(p){
return p["clubRep"]<=0x3;
},
  'desc': "南看台拉起一条三十米的横幅，写着「还我球队」。安保去收，球迷不撒手。",
  'options': [
    {
        'label': "赛后走过去鞠躬",
        'hint': "球迷认你，上面不"+'高兴',
        'apply': function(){
return{'fame':0x12,'guanxi':-0xc,'text':"你一个人走到南看台前，鞠了很久的躬。那张照片，如今还挂在球迷会的墙上。"};
}
    },
    {
        'label': "跟着大部队回更衣"+'室',
        'hint': "无变化",
        'apply': function(){
return{'fame':-0x5,'text':"走进球员通道时，你回头看了一眼。横幅还在，看台上的人少了一半。"};
}
    }
  ]
}

];
