// auto-generated by split_events.py - edit events here, then run build_events.py

var EVT_def=[

// ---- idx:103 | def_offs | 造越位 ----
{
  'id': "def_offs"+"ide",
  'title': "造越位",
  'icon': '🚩',
  'weight': 0x37,
  'when': function(p){
return "def"===p["posGroup"];
},
  'desc': "教练要打高位防线。整条线的默契，只能一遍遍练——练错一次，就是单刀。",
  'options': [
    {
        'p': function(p){return f(0.7,[[p["talent"],1,0.4]],0.2,0.9);
},
        'label': "带头练",
        'hint': function(p,q){return g(q,'能力+4','被打穿');
},
        'apply': function(p,q,s){
return d(q,s)?{'ovr':0x3,'roleDelta':0x1,'text':"一个赛季，造越位四十多次。对方前锋赛后说，跟你们踢球，像在猜谜。"}:{'ovr':-0x2,'fame':-0x8,'text':"有一场你慢了半步，全队被单刀了三次。赛后视频会上，暂停键停在你这帧。"};
}
    },
    {
        'label': "各防各的",
        'hint': "无变化",
        'apply': function(){
return{'text':"你按老办法回追。防线没被打穿，可也没人说这条线好。"};
}
    }
  ]
},

// ---- idx:104 | def_aeri | ? ----
{
  'id': "def_aeri"+'al',
  'title': '头球',
  'icon': '🪖',
  'weight': 0x34,
  'when': function(p){
return "def"===p["posGroup"];
},
  'desc': "对手下半场全打高球，专冲你这一侧。想加练头球争顶，就得拿脖子和脑袋去换。",
  'options': [
    {
        'p': function(p){return f(0.75,[[p["talent"],1,0.4]],0.2,0.9);
},
        'label': '加练',
        'hint': function(p,q){return g(q,'能力+4','脑震荡');
},
        'apply': function(p,q,s){
return d(q,s)?{'ovr':0x4,'text':"定位球防守，你一个人管大半个禁区。角球进攻时，你也开始往前插了。"}:{'ovr':-0x3,'text':"一次争顶之后，你在场上站了十秒，才想起自己站在哪儿。队医不让你再上。"};
}
    },
    {
        'label': "让门将出来摘",
        'hint': "地位小降",
        'apply': function(){
return{'roleDelta':-0x1,'text':"门将替你摘了一年高球。后来他在采访里说：要是中卫能顶，他能少跑一半。"};
}
    }
  ]
},

// ---- idx:105 | def_buil | 后场出球 ----
{
  'id': "def_buil"+'d',
  'title': "后场出球",
  'icon': '🧱',
  'weight': 0x34,
  'when': function(p){
return "def"===p["posGroup"];
},
  'desc': "新体系要求中卫从禁区里把球带出来。对方前锋就在你三米外等着。",
  'options': [
    {
        'p': function(p){return f(0.65,[[p["talent"],1,0.4]],0.2,0.9);
},
        'label': "按体系来",
        'hint': function(p,q){return g(q,'能力+5','送大礼');
},
        'apply': function(p,q,s){
return d(q,s)?{'ovr':0x3,'fame':0x6,'text':"你成了球队第一出球点。有解说说，你踢得像个后腰。"}:{'ovr':-0x2,'fame':-0xc,'roleDelta':-0x1,'text':"禁区里被断过两次。那两次，都直接变成了失球。"};
}
    },
    {
        'label': "大脚解围",
        'hint': "稳，教练不满",
        'apply': function(){
return{'roleDelta':-0x1,'text':"你把球全往看台上招呼。安全，可战术板上的箭头，到你这儿就断了。"};
}
    }
  ]
},

// ---- idx:106 | def_tact | 战术犯规 ----
{
  'id': "def_tact"+"ical_fou"+'l',
  'title': "战术犯规",
  'icon': '🟨',
  'weight': 0x32,
  'when': function(p){
return "def"===p["posGroup"];
},
  'desc': "对方反击起势，你身前只剩一片空地。教练在场边做了个「拉住他」的手势。",
  'options': [
    {
        'label': '拉住',
        'hint': "停赛 2 场，教"+"练认可",
        'apply': function(){
return{'banGames':0x2,'roleDelta':0x1,'guanxi':0x6,'fame':-0x4,'text':"你伸手一拽，黄牌。累积停两场，可那次反击，死在了中圈。教练过来，拍了拍你的后脑勺。"};
}
    },
    {
        'p': function(p){return f(0.6,[[p["ovr"],60,0.008]],0.2,0.9);
},
        'label': '回追',
        'hint': function(p,q){return g(q,'追上了','丢球');
},
        'apply': function(p,q,s){
return d(q,s)?{'ovr':0x2,'fame':0x8,'text':"你从三十米外追上去，在禁区前沿把球捅了出去。这个镜头，被放了一晚上。"}:{'fame':-0x6,'roleDelta':-0x1,'text':"你差半步。那球进了。赛后所有人都在说那个手势。"};
}
    }
  ]
},

// ---- idx:107 | def_pace | 追不上了 ----
{
  'id': "def_pace",
  'title': "追不上了",
  'icon': '🐢',
  'weight': 0x32,
  'stage': "vet",
  'when': function(p){
return "def"===p["posGroup"];
},
  'desc': "上一场，对方边锋从你身边过去时，你第一次觉得：那是另一种速度。",
  'options': [
    {
        'label': "改踢拖后中卫",
        'hint': "能力+3，靠脑子"+'吃饭',
        'apply': function(){
return{'ovr':0x3,'text':"你把位置往回撤了五米，用预判补速度。那个赛季，你的抢断数反而是生涯最高。"};
}
    },
    {
        'p': function(p){return f(0.45,[[p["ovr"],60,0.008]],0.2,0.9);
},
        'label': "硬扛速度",
        'hint': function(p,q){return g(q,'还行','被过成筛子');
},
        'apply': function(p,q,s){
return d(q,s)?{'fame':0x8,'ovr':0x1,'text':"你靠着经验和小动作，又扛了两个赛季。裁判没抓到你几次。"}:{'ovr':-0x4,'roleDelta':-0x2,'text':"对手开始专打你这一侧。有一场，你一个人被过了七次。"};
}
    }
  ]
},

// ---- idx:108 | def_mars | 后防线的嘴 ----
{
  'id': "def_mars"+"hal",
  'title': "后防线的嘴",
  'icon': '📣',
  'weight': 0x30,
  'when': function(p){
return "def"===p["posGroup"]&&p["roleRank"]>=0x3;
},
  'desc': "这条防线上，没人说话。教练问你，愿不愿意当那个一直喊的人。",
  'options': [
    {
        'label': "喊起来",
        'hint': "能力+3，得罪人",
        'apply': function(){
return{'ovr':0x3,'roleDelta':0x1,'guanxi':-0x8,'text':"你从开场喊到终场，嗓子哑了半个赛季。有两个人被你这么喊过，再没跟你一起吃过饭。"};
}
    },
    {
        'label': "各扫门前雪",
        'hint': "无变化",
        'apply': function(){
return{'text':"防线还是各踢各的。丢球之后，大家互相看一眼，谁也不说话。"};
}
    }
  ]
},

// ---- idx:109 | def_own_ | 禁区里那只手 ----
{
  'id': "def_own_"+"box",
  'title': "禁区里那只手",
  'icon': '✋',
  'weight': 0x2d,
  'when': function(p){
return "def"===p["posGroup"];
},
  'desc': "角球混战里，球打在你手臂上。主裁没看见，VAR 在这个联赛还时灵时不灵。",
  'options': [
    {
        'p': function(p){return f(0.5,[[p["clean"],70,0.008]],0.2,0.9);
},
        'label': "什么都不说",
        'hint': function(p,q){return g(q,'蒙过去','回放判点');
},
        'apply': function(p,q,s){
return d(q,s)?{'clean':-0x6,'text':"主裁摆手，示意继续。你回防时，没敢回头看大屏幕。"}:{'clean':-0x6,'fame':-0xa,'text':"VAR 叫停了比赛。点球，外加一张黄牌。你成了那晚输球的理由。"};
}
    },
    {
        'label': "自己举手承认",
        'hint': "清白+，球迷骂",
        'apply': function(){
return{'clean':0x8,'fame':-0x8,'guanxi':-0x6,'text':"你举了手。对方球员愣了一下。那场你们输了，球迷聊的全是你的名字。"};
}
    }
  ]
},

// ---- idx:110 | def_full | 边后卫要不要压上 ----
{
  'id': "def_full"+"back_pus"+'h',
  'title': "边后卫要不要压上",
  'icon': '↗️',
  'weight': 0x30,
  'when': function(p){
return "def"===p["posGroup"];
},
  'desc': "现在的边后卫，得跑满全场。教练说，你压上去，身后那块地，他来想办法。",
  'options': [
    {
        'p': function(p){return f(0.7,[[p["talent"],1,0.4]],0.2,0.9);
},
        'label': "压上去",
        'hint': function(p,q){return g(q,'能力+4','身后被打穿');
},
        'apply': function(p,q,s){
return d(q,s)?{'ovr':0x4,'fame':0xa,'text':"一个赛季，你送出九次助攻。有人开始拿你跟欧洲那些边后卫比。"}:{'ovr':-0x2,'roleDelta':-0x1,'text':"你身后那块地，被打了一整年。教练最后把你挪到了另一侧。"};
}
    },
    {
        'label': "守好本职",
        'hint': "稳，能力+1",
        'apply': function(){
return{'ovr':0x1,'text':"你老老实实待在自"+"己那条线上。数据"+"不好看，丢球也确"+"实少。"};
}
    }
  ]
}

];
