// auto-generated by split_events.py - edit events here, then run build_events.py

var EVT_gk=[

// ---- idx:82 | gk_penal | 点球大战 ----
{
  'id': "gk_penal"+'ty',
  'title': "点球大战",
  'icon': '🧤',
  'weight': 0x37,
  'when': function(p){
return'gk'===p["posGroup"];
},
  'desc': "杯赛半决赛拖进点球大战。门将教练递来一张纸条，上面写着对方五个人的习惯方向。",
  'options': [
    {
        'p': function(p){return f(0.55,[[p["ovr"],60,0.008]],0.2,0.9);
},
        'label': "照纸条扑",
        'hint': function(p,q){return g(q,'扑出两个','全被骗了');
},
        'apply': function(p,q,s){
return d(q,s)?{'ovr':0x3,'fame':0x19,'mult':{'cup':0x3},'text':"你连扑两个，第二个还在纸条之外的方向。教练说，那一下是你自己的。"}:{'fame':-0xa,'text':"五个人里，有四个改了主意。那张纸条，你后来收进包里，没扔。"};
}
    },
    {
        'p': function(p){return f(0.45,[[p["ovr"],60,0.008]],0.2,0.9);
},
        'label': "凭感觉",
        'hint': function(p,q){return g(q,'神扑','站着不动');
},
        'apply': function(p,q,s){
return d(q,s)?{'ovr':0x2,'fame':0x16,'mult':{'cup':2.5},'text':"你赌了一个方向，"+"赌对了三次。全场"+"山呼海啸。"}:{'fame':-0x8,'ovr':-0x1,'text':"五个球，你一个方向都没蒙对。回放里的你，像一根木桩。"};
}
    }
  ]
},

// ---- idx:87 | gk_sweep | 出击还是守线 ----
{
  'id': "gk_sweep"+'er',
  'title': "出击还是守线",
  'icon': '🧤',
  'weight': 0x37,
  'when': function(p){
return'gk'===p["posGroup"];
},
  'desc': "新教练要求防线压到中圈。你身后，是三十米无人区。",
  'options': [
    {
        'p': function(p){return f(0.65,[[p["talent"],1,0.4]],0.2,0.9);
},
        'label': "练出击",
        'hint': function(p,q){return g(q,'能力+4','被吊射');
},
        'apply': function(p,q,s){
return d(q,s)?{'ovr':0x4,'fame':0x8,'text':"你把自己练成了半个后卫。解围的次数，比一些中卫还多。"}:{'ovr':-0x2,'fame':-0xa,'text':"有人在中线开始起脚。那个球在你头顶，飞了整整两秒。"};
}
    },
    {
        'label': "守好门线",
        'hint': "稳，地位小降",
        'apply': function(){
return{'roleDelta':-0x1,'ovr':0x1,'text':"你不出来。防线因此往回收了十米。教练在训练课上没点你的名，也没夸你。"};
}
    }
  ]
},

// ---- idx:88 | gk_howle | 黄油手 ----
{
  'id': "gk_howle"+'r',
  'title': "黄油手",
  'icon': '🧴',
  'weight': 0x32,
  'when': function(p){
return'gk'===p["posGroup"];
},
  'desc': "一脚软绵绵的远射，从你手里滑进了球门。全场三万人先是安静，然后笑了。",
  'options': [
    {
        'label': "赛后开发布会认了",
        'hint': "名气-，队内关系"+'+',
        'apply': function(){
return{'fame':-0xc,'guanxi':0xa,'roleDelta':0x1,'text':"你一个人坐在发布会上，说了十分钟。队长后来说，这事到此为止。"};
}
    },
    {
        'p': function(p){return f(0.5,[[p["ovr"],60,0.008]],0.2,0.9);
},
        'label': "什么也不说",
        'hint': function(p,q){return g(q,'下一场找回来','心态崩了');
},
        'apply': function(p,q,s){
return d(q,s)?{'ovr':0x2,'fame':0x6,'text':"下一场，你扑出了两个必进球。没人再提上一场。"}:{'ovr':-0x3,'roleDelta':-0x2,'text':"接下来六场，你出球都不敢用脚。替补门将，开始热身了。"};
}
    }
  ]
},

// ---- idx:89 | gk_distr | 脚下活 ----
{
  'id': "gk_distr"+"ibution",
  'title': "脚下活",
  'icon': '🦵',
  'weight': 0x34,
  'when': function(p){
return'gk'===p["posGroup"];
},
  'desc': "教练把训练里的门"+"球全改成了短传。"+"你这个年纪重学脚"+"下技术，队里有人"+"看笑话。",
  'options': [
    {
        'p': function(p){return f(0.7,[[p["talent"],1,0.4]],0.2,0.9);
},
        'label': "从头学",
        'hint': function(p,q){return g(q,'能力+5','送礼');
},
        'apply': function(p,q,s){
return d(q,s)?{'ovr':0x3,'text':"半年后，你的传球成功率排进了联赛前三。有人开始叫你「第十一个球员」。"}:{'ovr':-0x2,'fame':-0x8,'text':"一次横传，直接送到对方前锋脚下。那球至今还在各种集锦里。"};
}
    },
    {
        'label': "大脚开走",
        'hint': "无变化",
        'apply': function(){
return{'text':"你还是一脚开到中"+"线。教练摇头，但"+"没换你。"};
}
    }
  ]
},

// ---- idx:90 | gk_numbe | 一号位 ----
{
  'id': "gk_numbe"+'r1',
  'title': "一号位",
  'icon': "1️⃣",
  'weight': 0x37,
  'when': function(p){
return'gk'===p["posGroup"]&&p["roleRank"]<=0x2;
},
  'desc': "队里签了个和你同龄的门将。教练说，「你们自己踢出来」。",
  'options': [
    {
        'p': function(p){return f(0.55,[[p["ovr"],60,0.008]],0.2,0.9);
},
        'label': "去抢",
        'hint': function(p,q){return g(q,'抢到主力','彻底出局');
},
        'apply': function(p,q,s){
return d(q,s)?{'roleDelta':0x2,'ovr':0x3,'text':"热身赛你零封三场。名单出来那天，他先跟你握了手。"}:{'roleDelta':-0x2,'ovr':-0x1,'text':"他各方面都比你好一点。整整一年，你只在杯赛里出场。"};
}
    },
    {
        'label': "申请外租",
        'hint': "去小球队当主力",
        'apply': function(){
return{'leave':!0x0,'ovr':0x2,'text':"你去了一支保级队，场场首发。零封不多，但你至少还在踢球。"};
}
    }
  ]
},

// ---- idx:91 | gk_line | 门线上的那半个球 ----
{
  'id': "gk_line",
  'title': "门线上的那半个球",
  'icon': '📏',
  'weight': 0x2d,
  'when': function(p){
return'gk'===p["posGroup"];
},
  'desc': "补时最后一刻，你把球从门线上捞了出来。边裁举旗，说进了。这个联赛没有门线技术，没有第二种答案。",
  'options': [
    {
        'label': "冲上去理论",
        'hint': "被罚，球迷买账",
        'apply': function(){
return{'banGames':0x2,'fame':0x10,'guanxi':-0xc,'text':"你追着边裁跑了三十米。红牌，停两场。你那张咆哮的照片，后来被做成了头像。"};
}
    },
    {
        'label': '认了',
        'hint': "关系+，心里憋着",
        'apply': function(){
return{'guanxi':0x8,'ovr':-0x1,'text':"你什么都没说。慢镜头里，那个球清清楚楚没进。没有人为此道歉。"};
}
    }
  ]
},

// ---- idx:92 | gk_coach | 门将教练走了 ----
{
  'id': "gk_coach"+"_gone",
  'title': "门将教练走了",
  'icon': '🚶',
  'weight': 0x30,
  'when': function(p){
return'gk'===p["posGroup"];
},
  'desc': "带了你六年的门将教练跟着主帅一起下课。新来的那个，只会安排体能。",
  'options': [
    {
        'label': "自费请他继续带",
        'hint': "花钱，能力+4",
        'apply': function(){
return{'money':-0x46,'ovr':0x4,'text':"每周两次，城郊一块租来的场地。他执意不收全款，说那部分算他的。"};
}
    },
    {
        'p': function(p){return f(0.5,[[p["ovr"],60,0.008]],0.2,0.9);
},
        'label': "跟着新教练",
        'hint': function(p,q){return g(q,'也挺好','手感全丢');
},
        'apply': function(p,q,s){
return d(q,s)?{'ovr':0x1,'text':"新方法你居然适应了。身体确实比以前壮了一圈。"}:{'ovr':-0x3,'text':"一整年，没人给你喂过高球。半年后，你连球落下来该在哪儿起跳，都拿不准了。"};
}
    }
  ]
},

// ---- idx:93 | gk_shoot | 门将罚点球 ----
{
  'id': "gk_shoot"+"out_pen",
  'title': "门将罚点球",
  'icon': '🎯',
  'weight': 0x28,
  'when': function(p){
return'gk'===p["posGroup"];
},
  'desc': "点球大战踢到第十一轮，轮到门将了。全场都在等你自己走上去。",
  'options': [
    {
        'p': function(p){return f(0.6,[[p["ovr"],60,0.008]],0.2,0.9);
},
        'label': "自己罚",
        'hint': function(p,q){return g(q,'罚进封神','罚丢背锅');
},
        'apply': function(p,q,s){
return d(q,s)?{'fame':0x1a,'ovr':0x2,'text':"你打了个正中间，对方门将扑向角落。这段画面，进了当年所有的年度盘点。"}:{'fame':-0x12,'roleDelta':-0x1,'text':"球被扑住了。你走回门前的三十米，转播镜头一秒都没离开。"};
}
    },
    {
        'label': "让给别人",
        'hint': "无变化",
        'apply': function(){
return{'text':"你摆摆手，让门将教练去跟主帅说。第十一个走上去的，是队里的后腰。"};
}
    }
  ]
},

// ---- idx:94 | gk_old_k | 三十六岁的门将 ----
{
  'id': "gk_old_k"+"eeper",
  'title': "三十六岁的门将",
  'icon': '⏳',
  'weight': 0x32,
  'stage': "vet",
  'when': function(p){
return'gk'===p["posGroup"];
},
  'desc': "门将比别的位置踢得久，这话你听了十年。今年你头一回觉得，球飞得比以前快了。",
  'options': [
    {
        'label': "再练两年",
        'hint': "花钱保养，能力+"+'3',
        'apply': function(){
return{'money':-0x32,'ovr':0x3,'text':"反应练不回来了，你把站位算得更准。有些球，你根本不需要扑。"};
}
    },
    {
        'label': "带年轻的那个",
        'hint': "地位降，队内关系"+'大涨',
        'apply': function(){
return{'roleDelta':-0x1,'guanxi':0x12,'fame':0x6,'text':"你把二十年攒下的东西，一样一样都给了他。他首发那天，你在替补席上比谁都紧张。"};
}
    }
  ]
},

// ---- idx:95 | gk_corne | 最后一分钟的角球 ----
{
  'id': "gk_corne"+"r_up",
  'title': "最后一分钟的角球",
  'icon': '🙌',
  'weight': 0x2e,
  'when': function(p){
return'gk'===p["posGroup"];
},
  'desc': "补时第三分钟，落后一个球，最后一个角球。队友摆好球，回头朝你这边招了招手，全场三万人跟着一起喊。",
  'options': [
    {
        'label': "冲上去",
        'p': function(p){
return f(0.14,[[p["ovr"],0x4e,0.004]],0.06,0.3);
},
        'hint': function(p,q){
return g(q,"顶进去了","对方打空门");
},
        'apply': function(p,q,s){
return d(q,s)?{'ovr':0x2,'fame':0x28,'mult':{'league':1.2,'cup':0x2},'text':"你顶进去了。你是那种一辈子只进一个球的人——可这个球，往后每一年的今天，都有人翻出来重发一遍。"}:{'ovr':-0x1,
'fame':-0x6,'text':"球被第一点解围，对方一脚长传，打向你身后空着的球门。你转身追了四十米，跑到一半，停了。"};
}
    },
    {
        'label': "留在自己半场",
        'hint': "无变化，也没人怪"+'你',
        'apply': function(){
return{'guanxi':0x4,'text':"你站在中线上看完了那个角球。终场哨响，全队都挤在禁区里，只有你一个人站在那边——也只有你，不用解释什么。"};
}
    }
  ]
},

// ---- idx:96 | gk_last_ | 最后一个人 ----
{
  'id': "gk_last_"+"man",
  'title': "最后一个人",
  'icon': '🟥',
  'weight': 0x32,
  'when': function(p){
return'gk'===p["posGroup"];
},
  'desc': "直塞打穿了整条防线，你已经冲出禁区，球比你想的快了半步。你只有零点几秒，决定用身上哪个部位去挡。",
  'options': [
    {
        'label': "用手把球摁下来",
        'hint': "红牌停一场，但这"+"一分保住了",
        'apply': function(){
return{'banGames':0x1,'guanxi':0xa,'fame':0x6,'text':"红牌。换人名额早用完了，队里那个后腰戴上你的手套，站了最后二十分钟。那场 0-0，你在通道口把全场听完。"};
}
    },
    {
        'label': "收手，赌他打不进",
        'p': function(p){
return f(0.42,[[p["ovr"],0x4c,0.01]],0.15,0.72);
},
        'hint': function(p,q){
return g(q,"他没打进","空门被推进");
},
        'apply': function(p,q,s){
return d(q,s)?{'ovr':0x3,'fame':0xe,'text':"他挑射，球擦着横梁飞出底线。你躺在地上笑出了声，队友一个个过来揉你的头。"}:{'ovr':-0x2,'fame':-0x8,'text':"他从你收回去的那只手边上推进了空门。回放里所有人都在问同一句：为什么不犯规？"};
}
    }
  ]
},

// ---- idx:97 | gk_clean | 不失球的分钟数 ----
{
  'id': "gk_clean"+"_run",
  'title': "不失球的分钟数",
  'icon': '🔒',
  'weight': 0x30,
  'when': function(p){
return'gk'===p["posGroup"]&&p["roleRank"]>=0x3;
},
  'desc': "你已经七百多分钟没丢球，队史纪录是九百零三。下一轮对手是倒数第一，教练问你，要不要趁这场歇一歇。",
  'options': [
    {
        'label': "追这个纪录",
        'p': function(p){
return f(0.5,[[p["ovr"],0x4e,0.01]],0.2,0.8);
},
        'hint': function(p,q){
return g(q,'破了',"第八百分钟丢一个");
},
        'apply': function(p,q,s){
return d(q,s)?{'ovr':0x2,'fame':0x16,'text':"第九百零四分钟，一记软绵绵的传中，你把它抱进怀里，整个看台站了起来。后来那个数字跟你的名字一起，刷在球场内墙上。"}:{'ovr':-0x1,'fame':-0x6,
'text':"第八百一十分钟，一次折射。你趴在地上，没有起来。广播念了比分，没有念那个数字。"};
}
    },
    {
        'label': "听教练的",
        'hint': "能力+1，关系+"+"，纪录停在这儿",
        'apply': function(){
return{'ovr':0x1,'guanxi':0xc,'text':"你在替补席上看完了那场，二号门将也零封了。纪录停在七百多分钟，之后没人再提，包括你自己。"};
}
    }
  ]
},

// ---- idx:98 | gk_capta | 戴袖标的门将 ----
{
  'id': "gk_capta"+'in',
  'title': "戴袖标的门将",
  'icon': "🗣️",
  'weight': 0x2c,
  'when': function(p){
return'gk'===p["posGroup"]&&p["roleRank"]>=0x3&&p["seasonsA"+"tClub"]>=0x3&&p["ovr"]>=0x32+0x4*(p["clubRep"]||0x0)&&(p["capDone"]||[])["indexOf"](p["teamId"])<0x0;
},
  'desc': "老队长转会走了。教练把袖标递到你面前，更衣室里有人小声说：门将离得太远，喊不到人。",
  'options': [
    {
        'label': '戴上',
        'hint': "关系+，名气+，"+"锅也归你",
        'apply': function(){
return{'guanxi':0xe,'fame':0xa,'roleDelta':0x1,'ovr':-0x1,'captain':!0x0,'text':"你成了俱乐部历史上第二个戴袖标的门将。那个赛季，每一场输球后的发布会都是你去开的。能力一分没涨，可更衣室从此是你的。"};
}
    },
    {
        'label': "让给后腰",
        'hint': "能力+2，你只管"+"门里那块",
        'apply': function(){
return{'ovr':0x2,'guanxi':0x6,'capDecline':!0x0,'text':"你说自己在门里喊，比站在场上说管用。那一年，你少开了二十场发布会，多练了二十堂课。"};
}
    }
  ]
},

// ---- idx:99 | gk_var_r | VAR 说重罚 ----
{
  'id': "gk_var_r"+"etake",
  'title': "VAR 说重罚",
  'icon': '📺',
  'weight': 0x2e,
  'when': function(p){
return'gk'===p["posGroup"];
},
  'desc': "你把那个点球扑出去了，全场在喊你的名字。VAR 看了两分钟——你出线早了半只脚，重罚。",
  'options': [
    {
        'label': "还扑同一边",
        'p': function(p){
return f(0.34,[[p["ovr"],0x4e,0.009]],0.12,0.6);
},
        'hint': function(p,q){
return g(q,"又扑出来了","他改了边");
},
        'apply': function(p,q,s){
return d(q,s)?{'ovr':0x3,'fame':0x1e,'mult':{'cup':0x2},'text':"同一个方向，同一个人，你又把球扑了出来。这一次，没有 VAR 再拦。解说喊到破了音。"}:{'ovr':-0x1,'fame':-0x6,
'text':"他换了边，球从你身后滚进去。你跪在草皮上很久，起来时，手套上沾满了白线的灰。"};
}
    },
    {
        'p': function(p){return f(0.5,[[p["fame"],25,0.01]],0.2,0.9);
},
        'label': "先跟主裁磨两分钟",
        'hint': function(p,q){return g(q,'把他磨毛了','先吃张黄牌');
},
        'apply': function(p,q,s){
return d(q,s)?{'ovr':0x1,'fame':0x10,'guanxi':-0x8,'text':"你拉着主裁说了两分钟，又走回去，把点球点的草皮踩了一遍。他罚飞了。有人说你无耻，你说，这是我的工作。"}:{'fame':-0x4,
'guanxi':-0xa,'text':"黄牌。他等你归位，不慌不忙地把球打进了死角。第二天专栏的标题是「小动作没能救他」。"};
}
    }
  ]
},

// ---- idx:100 | gk_charg | 他撞的是人不是球 ----
{
  'id': "gk_charg"+'e',
  'title': "他撞的是人不是球",
  'icon': '💥',
  'weight': 0x30,
  'cn': !0x0,
  'when': function(p){
return'gk'===p["posGroup"];
},
  'desc': "角球。对方那个高中锋助跑起来，整个人撞进你怀里。你倒在门线上，主裁指了指中圈——进球有效。",
  'options': [
    {
        'label': "爬起来接着踢",
        'hint': "能力+2，关系+"+"，这笔账自己记着",
        'apply': function(){
return{'ovr':0x2,'guanxi':0x8,'text':"你什么也没说。那个赛季，这样的球你被撞了九次，判给你的只有一次。从那以后，你的落点判断总比旁人早半步——你得先算好，人是从哪儿来的。"};
}
    },
    {
        'label': "追着主裁问到底",
        'hint': "停赛，但球迷记住"+'了你',
        'apply': function(){
return{'banGames':0x2,'fame':0x10,'guanxi':-0xe,'text':"黄牌，你没停下。红牌。赛后你把倒地的那张照片发了出去，一个字没配，转发过了十万。"};
}
    }
  ]
},

// ---- idx:101 | gk_nt_nu | ? ----
{
  'id': "gk_nt_nu"+"mber1",
  'title': '国门',
  'icon': "🇨🇳",
  'weight': 0x34,
  'when': function(p){
return'gk'===p["posGroup"]&&p["caps"]>=0x5;
},
  'desc': "国家队三个门将里，你不是最年轻的，也不是身价最高的。世预赛前一周，主教练把你们三个叫到一起，说：这个位置，我只信一个人。",
  'options': [
    {
        'label': "去找他谈",
        'p': function(p){
return f(0.45,[[p["guanxi"],0x37,0.006],[p["ovr"],0x4c,0.01]],0.15,0.8);
},
        'hint': function(p,q){
return g(q,"三场都是你","三场都在替补席");
},
        'apply': function(p,q,s){
return d(q,s)?{'caps':0x6,'fame':0x12,'ovr':0x1,'text':"三场你都首发。第三场那次扑救被剪进了片头，整整用了一个周期。"}:{'fame':-0x6,'guanxi':-0x8,'text':"名单上你排第二。三场，你坐满九十分钟。赛后跟着大家去谢场，手套一次都没戴上。"};
}
    },
    {
        'label': "把话咽回去",
        'hint': "能力+3，名气-"+"，慢慢等",
        'apply': function(){
return{'ovr':0x3,'caps':0x1,'fame':-0x4,'text':"你每天比另外两个早到一小时。轮换那场你上了，就再没下来——只是等来那一刻，已经过去了两年。"};
}
    }
  ]
},

// ---- idx:102 | gk_finge | ? ----
{
  'id': "gk_finge"+'rs',
  'title': '手指',
  'icon': '🩹',
  'weight': 0x2e,
  'when': function(p){
return'gk'===p["posGroup"];
},
  'desc': "训练里，一个球打在指尖上，你听见一声响。片子出来，是两根手指的韧带。医生给了两条路。",
  'options': [
    {
        'label': "做手术，歇三个月",
        'hint': "花钱，能力小降，"+"手是好的",
        'apply': function(){
return{'money':-0x3c,'ovr':-0x1,'roleDelta':-0x1,'text':"三个月，你只能用左手吃饭。回来第一堂课，第一个动作，你空手接了个高球——接住了。"};
}
    },
    {
        'p': function(p){return f(0.5,[[p["ovr"],60,0.008]],0.2,0.9);
},
        'label': "用胶布绑起来接着"+'踢',
        'hint': function(p,q){return g(q,'撑过整个赛季','这两根手指废了');
},
        'apply': function(p,q,s){
return d(q,s)?{'ovr':0x2,'fame':0xa,'guanxi':0x8,'text':"整个赛季，你把那两根手指绑在一起。队医每场赛前缠一次，缠到后来，不用问你都知道是哪两根。"}:{'ovr':-0x4,'text':"那两根手指，后来再没完全伸直过。阴天下雨的时候你自己知道，别人看不出来。"};
}
    }
  ]
}

];
