// auto-generated by split_events.py - edit events here, then run build_events.py
// 成长差分事件：按"年度 ovr 变化"(flags._ovrD / flags._ovrPh) 分档强制触发。
//  _ovrD = 刚过去这一年的 ovr 变化（青训年是 youthLog 差值；职业年是 ovrEnd - round(ovr)）
//  _ovrPh = 'y' 青训年(有上一年可比, 且仅 14 岁起) / 'y0' 青训首年(禁用) / 'p' 职业赛季
//  _ovrA = 该年/该季的起始年龄（校验用）
//  两个"停滞"事件额外要求 ovr<90（0x5a）：高能力球员不该被判"停在原地/这一年没长"
// 入队由 sim.js 在两处钩子处调用 b1()（青训 bj() / 职业结算），此处 when 只做兜底校验。

var EVT_grow=[

// ---- idx:398 | youth_surge | 长得比谁都快 ----
{
  'id': "youth_surge",
  'title': "长得比谁都快",
  'icon': '📈',
  'weight': 0x50,
  'stage': "youth",
  'when': function(p){return "y"===p["_ovrPh"]&&p["_ovrA"]>=0xe&&p["_ovrD"]>=0x8;},
  'desc': "这一年你的身体像被谁按了快进。教练捏着你的肩膀说：别停，趁现在。",
  'options': [
    {'label': "顺势加练，能加多少加多少", 'p': function(p){return f(0.6,[[p["talent"],1.1,0.35]],0.3,0.9);}, 'hint': function(p,q){return g(q,"稳步兑现","练过头了");}, 'apply': function(p,q,s){return d(q,s)?{'ovr':0x4,'talent':0.02,'fame':0x4,'text':"别人一年的量，你半年就吃下去了。梯队教练开始拿你的名字去跟一线队的人提。"}:{'ovr':0x1,'health':1.15,'text':"你练得太狠。膝盖在冬天开始响，队医让你停了两周，那两周你自己偷偷加练。"};}},
    {'label': "收着点，别把身体掏空", 'hint': "少长一点，不伤", 'apply': function(){return{'ovr':0x2,'health':0.9,'text':"你把量压下来，长得慢了些，但每天醒来身体都是好的。师傅说，这条路长，急不得。"};}}
  ]
},

// ---- idx:399 | youth_stall | 这一年没长 ----
{
  'id': "youth_stall",
  'title': "这一年没长",
  'icon': '🧊',
  'weight': 0x50,
  'stage': "youth",
  'when': function(p){return "y"===p["_ovrPh"]&&p["_ovrA"]>=0xe&&p["_ovrD"]<=0x1&&p["ovr"]<0x5a;},
  'desc': "一整年过去，你的数据几乎没动。跟你一批的人，已经有人被叫上一队了。",
  'options': [
    {'label': "去找教练要加练", 'p': function(p){return f(0.55,[[p["talent"],1.1,0.3]],0.25,0.85);}, 'hint': function(p,q){return g(q,"开窍了","练岔了");}, 'apply': function(p,q,s){return d(q,s)?{'ovr':0x5,'talent':0.02,'text':"你堵在办公室门口要了个专项计划。三个月后，那个卡了一年的数字终于动了。"}:{'ovr':-0x2,'health':1.1,'roleDelta':-0x1,'text':"你自己加的量没人看着。动作练歪了，改回来花了整个冬天。"};}},
    {'label': "照旧练，别慌", 'hint': "能力+1，关系+", 'apply': function(){return{'ovr':0x1,'guanxi':0x4,'text':"你没跟谁较劲，按部就班地练。教练说你心态稳，队里的老队员愿意带你加练。"};}}
  ]
},

// ---- idx:400 | young_surge | 涨球期 ----
{
  'id': "young_surge",
  'title': "涨球期",
  'icon': '🚀',
  'weight': 0x50,
  'when': function(p){return "p"===p["_ovrPh"]&&p["age"]>=0x10&&p["age"]<=0x18&&p["_ovrD"]>=0x6&&!p["inAcademy"];},
  'desc': "半个赛季不见，队里的人说你像换了一个人。涨球期就这几年。",
  'options': [
    {'label': "趁热多打，什么比赛都上", 'hint': "能力+，磨损大", 'apply': function(){return{'ovr':0x4,'fame':0x6,'health':1.12,'text':"联赛、杯赛、预备队，你什么都踢。一年下来出场四十多次，数据在替你说活。"};}},
    {'label': "挑比赛打，护住身体", 'p': function(p){return f(0.6,[[p["talent"],1.1,0.35]],0.3,0.9);}, 'hint': function(p,q){return g(q,"长得扎实","被抢了机会");}, 'apply': function(p,q,s){return d(q,s)?{'ovr':0x3,'talent':0.02,'health':0.88,'text':"你只挑该打的打。别人一年踢四十场，你踢二十场，却每场都在往上走。"}:{'ovr':0x1,'roleDelta':-0x1,'text':"你推掉了两场关键比赛。位置被别人坐稳了，教练再想起你的时候，赛季已经过半。"};}}
  ]
},

// ---- idx:401 | young_stall | 停在原地 ----
{
  'id': "young_stall",
  'title': "停在原地",
  'icon': '🪨',
  'weight': 0x50,
  'when': function(p){return "p"===p["_ovrPh"]&&p["age"]>=0x10&&p["age"]<=0x18&&p["_ovrD"]<=0x0&&p["ovr"]<0x5a&&!p["inAcademy"];},
  'desc': "这个赛季，你的能力值停在原地。教练嘴上说你年轻，可他手里的名单上，你的名字在往下挪。",
  'options': [
    {'label': "换个踢法，重新给自己找位置", 'p': function(p){return f(0.5,[[p["talent"],1.1,0.3]],0.25,0.85);}, 'hint': function(p,q){return g(q,"换出条路","两头不靠");}, 'apply': function(p,q,s){return d(q,s)?{'posAny':!0x0,'ovr':0x3,'text':"你换了个位置重新学起。刚开始踢得很难看，可半年后，那条被堵死的路通了。"}:{'ovr':-0x1,'roleDelta':-0x1,'text':"你换了位置，又换回来。两边都没练熟，教练在训练里开始不再叫你名字。"};}},
    {'label': "死磕老本行", 'hint': "能力+，上限低", 'apply': function(){return{'ovr':0x3,'fame':-0x2,'text':"你把会的那点东西又磨了一遍，磨得更亮。可别人已经知道该怎么防你了。"};}}
  ]
},

// ---- idx:402 | vet_up | 别人的下滑期 ----
{
  'id': "vet_up",
  'title': "别人的下滑期",
  'icon': '🍷',
  'weight': 0x50,
  'stage': "vet",
  'when': function(p){return "p"===p["_ovrPh"]&&p["age"]>=0x21&&p["_ovrD"]>=0x0;},
  'desc': "同龄人在这个年纪一年掉三四个点。你的数据表上，这条线是平的，甚至往上翘。",
  'options': [
    {'label': "继续加练，把状态焊住", 'p': function(p){return f(0.62,[[p["talent"],1.1,0.35]],0.3,0.9);}, 'hint': function(p,q){return g(q,"再顶一年","伤来了");}, 'apply': function(p,q,s){return d(q,s)?{'ovr':0x2,'fame':0x5,'text':"你比队里最小的那批人来得还早。体测数据出来，教练盯着看了很久，说了句：这不科学。"}:{'ovr':-0x1,'health':1.15,'text':"你把自己练伤了。这一次恢复用了小半个赛季，回来时，队里换了打法。"};}},
    {'label': "把经验传下去，少跑一点", 'hint': "关系+，地位+", 'apply': function(){return{'ovr':0x1,'guanxi':0x6,'roleDelta':0x1,'text':"你开始教年轻人怎么站位、怎么省力。教练把你留在场上，不再是因为你跑得动，是因为你懂。"};}}
  ]
}

];
