// auto-generated by split_events.py - edit events here, then run build_events.py

var EVT_league=[

// ---- idx:308 | lg_epl_dec | 没有冬歇的十二月 ----
{
  'id': "lg_epl_dec",
  'title': "没有冬歇的十二月",
  'icon': '📅',
  'weight': 0x50,
  'when': function(p){return "epl"===p["leagueId"];},
  'desc': "别处的联赛陆续停摆过冬，这里的日程表上只有下一个对手。教练把一沓录像拍在桌上：十二天四场，谁也别想省力。",
  'options': [
    {
        'label': "把轮换当机会踢",
        'p': function(p){return f(0.55,[[p["ovr"],0x4c,0.008]],0.25,0.85);},
        'hint': function(p,q){return g(q,"站稳了","透支了");},
        'apply': function(p,q,s){return d(q,s)?{'ovr':0x2,'roleDelta':0x1,'text':"四场你上了三场，进了两个。英国记者写道：这个东方人比英格兰人更懂圣诞节的意义——就是不停下来。"}:{'ovr':-0x2,'health':1.1,'text':"第四场开始前，你的大腿绷得像根弦。队医摇头：这个月你跑的量，顶别人一个半月的。"};}
    },
    {
        'label': "跟队医要恢复方案",
        'hint': "稳妥，状态缓",
        'apply': function(){return{'ovr':0x1,'guanxi':-0x3,'text':"冰浴、加压裤、睡前两小时不看手机。你把身体当成项目来管理。教练看了眼你的数据表，什么都没说，轮换名单上却少了你的名字。"};}
    }
  ]
},

// ---- idx:309 | lg_epl_mixedzone | 混采区 ----
{
  'id': "lg_epl_mixedzone",
  'title': "混采区",
  'icon': '🎤',
  'weight': 0x50,
  'when': function(p){return "epl"===p["leagueId"];},
  'desc': "英超的规定：赢球的球员必须走混采区。几十个话筒伸过来，问题从战术到你的私生活无所不包。翻译在你耳边小声提醒：说错一个词，明天就是头条。",
  'options': [
    {
        'label': "有问必答",
        'p': function(p){return f(0.6,[[p["fame"],40,0.006]],0.3,0.9);},
        'hint': function(p,q){return g(q,"圈粉无数","被断章取义");},
        'apply': function(p,q,s){return d(q,s)?{'fame':0xc,'guanxi':0x4,'text':"你夸了对手、谢了球迷、还开了个自嘲的玩笑。第二天那段视频被转了几万次，评论区第一次齐刷刷地喊你的名字。"}:{'fame':-0x5,'text':"你说「我们配不上三分」，标题变成《核心炮轰队友》。更衣室里安静了一天，队长拍拍你：下次学学怎么打太极。"};}
    },
    {
        'label': "只回一句：下场见",
        'hint': "清白+，关系少一点",
        'apply': function(){return{'clean':0x4,'guanxi':-0x3,'text':"你说了句「下场见」就上了大巴。有人觉得你敷衍，可你知道，有些话在这里说出来就会变味。"};}
    }
  ]
},

// ---- idx:310 | lg_liga_tiki | 把球传进大门 ----
{
  'id': "lg_liga_tiki",
  'title': "把球传进大门",
  'icon': '🧩',
  'weight': 0x50,
  'when': function(p){return "liga"===p["leagueId"];},
  'desc': "新助教上任第一周，训练场上拉起了绳网：传球路线被限制成只有两条。他说，在这块土地上，控不住球的人连尊严都没有。",
  'options': [
    {
        'label': "苦练一脚出球",
        'p': function(p){return f(0.6,[[p["talent"],1,0.35]],0.3,0.9);},
        'hint': function(p,q){return g(q,"融进体系","水土不服");},
        'apply': function(p,q,s){return d(q,s)?{'ovr':0x2,'roleDelta':0x1,'text':"三周后，你在中场连续一脚传递撕开了模拟防线。助教鼓着掌喊：就是这个节奏！看台上，一线队主教练点了点头。"}:{'ovr':-0x1,'text':"你习惯了带两步再传，绳网却逼你提前出球。失误一次，全队陪跑一圈。第七天晚上，你自己留在场地上，一遍遍练那个两秒内的决定。"};}
    },
    {
        'label': "保持自己的风格",
        'hint': "个性，风险",
        'apply': function(){return{'ovr':0x1,'guanxi':-0x4,'text':"你还是那个爱多带一步的你。助教找你谈了两次话。数据不会说谎：你的丢失球权数，全队第一。"};}
    }
  ]
},

// ---- idx:311 | lg_liga_clasico | 第一次国家德比 ----
{
  'id': "lg_liga_clasico",
  'title': "第一次国家德比",
  'icon': '🔥',
  'weight': 0x52,
  'when': function(p){return "liga"===p["leagueId"]&&p["clubRep"]>=0x4;},
  'desc': "赛前一周，整座城市就变了味道。出租车司机跟你吵该谁罚点球，报纸头版印着你和对方十号的对位图。更衣室里老队长说：这种比赛，一辈子记住一次就够了。",
  'options': [
    {
        'label': "把它当普通比赛",
        'p': function(p){return f(0.45,[[p["ovr"],0x4c,0.012]],0.15,0.8);},
        'hint': function(p,q){return g(q,"一战成名","被情绪吞没");},
        'apply': function(p,q,s){return d(q,s)?{'ovr':0x2,'fame':0x14,'roleDelta':0x1,'text':"第九十分钟，你在两人夹防里把球搓向后点，队友头槌绝平。那晚社交网络上，你的名字和两位金球先生排在同一行。"}:{'ovr':-0x1,'fame':0x4,'text':"你太想证明了。上半场三次丢球，半场就被换下。老队长赛后搂着你：我第一次踢这场，吐了一整夜。你已经很好了。"};}
    },
    {
        'label': "接受替补角色",
        'hint': "平稳",
        'apply': function(){return{'guanxi':0x6,'ovr':0x1,'text':"你坐在替补席看完了全程，第80分钟上去触了七次球。赛后你说：至少，我在场上了。"};}
    }
  ]
},

// ---- idx:312 | lg_bund_press | 从门将开始逼抢 ----
{
  'id': "lg_bund_press",
  'title': "从门将开始逼抢",
  'icon': '🏃',
  'weight': 0x50,
  'when': function(p){return "bund"===p["leagueId"];},
  'desc': "新帅的第一堂训练课，把十一块背心全发出去：从门将开始，所有人都要压上去。他说，在德国，不跑的人连看台都不配坐。",
  'options': [
    {
        'label': "把肺活量押上去",
        'p': function(p){return f(0.6,[[p["ovr"],0x4a,0.01]],0.25,0.85);},
        'hint': function(p,q){return g(q,"跑成体系","跑垮了");},
        'apply': function(p,q,s){return d(q,s)?{'ovr':0x2,'roleDelta':0x1,'text':"体测数据出来，你的高强度跑排进前五。教练在战术板上把你的名字往前挪了一格：逼抢的第一线，就是你的第二生命。"}:{'ovr':-0x2,'health':1.1,'text':"第三周，你的内收肌罢工了。理疗床上你看着天花板想：这套打法是台绞肉机，而我是最新的那块肉。"};}
    },
    {
        'label': "找教练谈定位",
        'hint': "关系+，强度降",
        'apply': function(){return{'guanxi':0x6,'ovr':0x1,'text':"你跟教练聊了自己的特点：与其满场飞，不如卡死关键三十米。他听完沉默半天，训练里给你划了块专属区域。"};}
    }
  ]
},

// ---- idx:313 | lg_bund_kid | 十六岁的队友 ----
{
  'id': "lg_bund_kid",
  'title': "十六岁的队友",
  'icon': '🧒',
  'weight': 0x50,
  'when': function(p){return "bund"===p["leagueId"]&&p["age"]>=0x17;},
  'desc': "梯队里又提上来一个孩子，十六岁，训练赛把你过了两次。更衣室里他管你叫哥。教练说：在这里，没人等你长大，也没人等你变老。",
  'options': [
    {
        'label': "带他，也学他",
        'p': function(p){return f(0.65,[[p["guanxi"],50,0.008]],0.35,0.9);},
        'hint': function(p,q){return g(q,"教学相长","位置被他顶了");},
        'apply': function(p,q,s){return d(q,s)?{'ovr':0x2,'guanxi':0x8,'text':"你把自己十年踩过的坑讲给他听，也偷偷学他那下变向。季末你们同时入选月度最佳阵容——一老一少，照片里笑得一样坏。"}:{'ovr':-0x1,'roleDelta':-0x1,'text':"你教他的东西他三天就会了，而他那些天生的爆发力，你练不来。首发名单公布那天，你在替补席系了很久的鞋带。"};}
    },
    {
        'label': "只管踢好自己的",
        'hint': "稳",
        'apply': function(){return{'ovr':0x1,'text':"竞争就竞争。你加练了两组力量，把焦虑压进了杠铃里。赛季很长，笑到最后的才有资格说话。"};}
    }
  ]
},

// ---- idx:314 | lg_seri_defense | 防守是一门功课 ----
{
  'id': "lg_seri_defense",
  'title': "防守是一门功课",
  'icon': '🛡',
  'weight': 0x50,
  'when': function(p){return "seri"===p["leagueId"]&&p["posGroup"]!=='gk';},
  'desc': "防守教练把你拉到录像室，一帧一帧放你的回防路线。他说：在意甲，前锋也得懂造越位，边锋也得会卡位。这里的数据榜上，抢断和进球一样值钱。",
  'options': [
    {
        'label': "从头学防守",
        'p': function(p){return f(0.6,[[p["clean"],60,0.005]],0.3,0.9);},
        'hint': function(p,q){return g(q,"攻防一体","顾此失彼");},
        'apply': function(p,q,s){return d(q,s)?{'ovr':0x2,'text':"六周后，对方反击时你已经站在了肋部的必经之路上。解说员说：这个中国人，用脑子的方式很意大利。"}:{'ovr':-0x1,'text':"你把太多精力花在了站位上，进攻端的灵感却断了电。两场比赛颗粒无收后，教练让你二选一。"};}
    },
    {
        'label': "只打磨进攻",
        'hint': "扬长避短",
        'apply': function(){return{'ovr':0x1,'roleDelta':-0x1,'text':"你把心思全放在了禁区前沿。防守数据惨不忍睹，但你的进球数撑住了首发位置。意甲的生存法则之一：有绝活的人总有饭吃。"};}
    }
  ]
},

// ---- idx:315 | lg_seri_slow | 领先之后的九十分钟 ----
{
  'id': "lg_seri_slow",
  'title': "领先之后的九十分钟",
  'icon': '⏱',
  'weight': 0x50,
  'when': function(p){return "seri"===p["leagueId"];},
  'desc': "二比零之后，全队开始在中圈附近倒脚。对手不逼抢，只是跟在你身后走。看台上嘘声四起。老中卫说：在这联赛，领先的一方才有权定义时间。",
  'options': [
    {
        'label': "学会控节奏",
        'p': function(p){return f(0.62,[[p["ovr"],0x48,0.008]],0.3,0.9);},
        'hint': function(p,q){return g(q,"大师课","丢了好局");},
        'apply': function(p,q,s){return d(q,s)?{'ovr':0x2,'guanxi':0x6,'text':"你把球权攥在脚下，四十多脚传递耗完了最后十分钟。终场哨响，客队教练冲裁判咆哮，你的队友们笑着抱成一团。这就是三分的艺术。"}:{'ovr':-0x2,'text':"第八十七分钟，你想多带一步消耗时间，球被断了。一分钟后，比分变成了二比二。大巴上没人说话，你盯着窗外的夜路看了一路。"};}
    },
    {
        'label': "继续进攻扩大比分",
        'hint': "高风险高回报",
        'apply': function(){return{'ovr':0x1,'fame':0x4,'text':"你不肯演，第七十分钟打进第三球。看台的嘘声变成了掌声。教练赛后说：好看，但下次先学着别丢球。"};}
    }
  ]
},

// ---- idx:316 | lg_l1_scouts | 看台上的陌生人 ----
{
  'id': "lg_l1_scouts",
  'title': "看台上的陌生人",
  'icon': '🔭',
  'weight': 0x50,
  'when': function(p){return 'l1'===p["leagueId"];},
  'desc': "连续三场首发后，包厢里多了几张生面孔。经纪人打来电话：都是豪门的人。这里是欧洲最大的球星超市，橱窗里永远摆着下一个天才。",
  'options': [
    {
        'label': "让表现说话",
        'p': function(p){return f(0.55,[[p["ovr"],0x4b,0.009]],0.25,0.85);},
        'hint': function(p,q){return g(q,"豪门报价","暂时无人问津");},
        'apply': function(p,q,s){return d(q,s)?{'fame':0xa,'money':0x32,'text':"月底，俱乐部收到了正式询价。主席把你叫进办公室：他们给的数字，是你身价的四倍。你第一次感觉到，自己是一件被标价的商品——还是抢手货。"}:{'ovr':0x1,'text':"生面孔们看完三场，没再出现。经纪人安慰你：他们还会来的。你耸耸肩，继续在训练场上加练。这里留不住人，但能锻造人。"};}
    },
    {
        'label': "公开表态留队",
        'hint': "关系大增",
        'apply': function(){return{'guanxi':0xc,'fame':-0x3,'text':"你在采访里说：我合同还有两年，脑子里只有这件球衣。俱乐部官网转发了这句话，球迷看台上多了条给你的横幅。"};}
    }
  ]
},

// ---- idx:317 | lg_l1_tower | 巴别塔更衣室 ----
{
  'id': "lg_l1_tower",
  'title': "巴别塔更衣室",
  'icon': '🌍',
  'weight': 0x50,
  'when': function(p){return 'l1'===p["leagueId"];},
  'desc': "更衣室里，塞内加尔语、葡萄牙语、阿拉伯语和法语混在一起。战术板上的标注要翻译三遍。你说不好这算混乱还是包容，只知道这里的足球和这里的人一样杂糅。",
  'options': [
    {
        'label': "学语言，交朋友",
        'p': function(p){return f(0.7,[[p["talent"],1,0.3]],0.4,0.92);},
        'hint': function(p,q){return g(q,"成为枢纽","闹了笑话");},
        'apply': function(p,q,s){return d(q,s)?{'guanxi':0xa,'ovr':0x2,'text':"三个月后，你能用法语喊战术、用葡语开玩笑。非洲帮拉你去家里吃饭，法国本土派带你去了老城区的馆子。你成了更衣室的翻译器，也是所有人的自己人。"}:{'guanxi':0x3,'text':"你把「传中」说成了另一个尴尬的词，全队笑了十分钟。不过笑声之后，大家反而记住了这个敢开口的东方人。"};}
    },
    {
        'label': "用脚说话",
        'hint': "稳",
        'apply': function(){return{'ovr':0x1,'text':"语言不通没关系，好传球是世界语。两个助攻之后，队里的语言天才们抢着教你各自的方言。"};}
    }
  ]
},

// ---- idx:318 | lg_ere_price | 下一个标价 ----
{
  'id': "lg_ere_price",
  'title': "下一个标价",
  'icon': '🏷',
  'weight': 0x50,
  'when': function(p){return "ere"===p["leagueId"];},
  'desc': "财务总监把一张纸推到你面前：俱乐部上赛季卖人赚的钱，比门票和转播加起来还多。他笑着说：你现在的合同里，有百分之十五的二次转会分成——好好踢，我们都发财。",
  'options': [
    {
        'label': "接受这套生意逻辑",
        'p': function(p){return f(0.6,[[p["ovr"],0x4a,0.009]],0.3,0.9);},
        'hint': function(p,q){return g(q,"身价暴涨","状态起伏");},
        'apply': function(p,q,s){return d(q,s)?{'fame':0x8,'money':0x28,'ovr':0x2,'text':"半年后，转会市场给你标了新价。主席在发布会上说：我们不着急卖，但他值得更好的舞台。你知道这是明码标价的告别预告。"}:{'ovr':-0x1,'text':"你太想涨身价了，场上反而放不开。两场低迷后，总监的笑脸淡了几分：生意归生意，孩子，先把球踢好。"};}
    },
    {
        'label': "只关心上场时间",
        'hint': "纯粹",
        'apply': function(){return{'guanxi':0x6,'text':"你说：我只管踢球，卖不卖你们定。总监愣了一下，然后笑出声。那天之后，训练场上你的名字总被第一个念到。"};}
    }
  ]
},

// ---- idx:319 | lg_pri_sea | 南美的孩子们 ----
{
  'id': "lg_pri_sea",
  'title': "南美的孩子们",
  'icon': '🌊',
  'weight': 0x50,
  'when': function(p){return "pri"===p["leagueId"];},
  'desc': "一月窗口，俱乐部一口气租来了三个南美小将。训练赛上他们盘带如跳舞，也丢球如散沙。老队长搂着你说：欢迎来到葡超，欧洲和南美之间的渡口。",
  'options': [
    {
        'label': "当他们的引路人",
        'p': function(p){return f(0.65,[[p["guanxi"],45,0.008]],0.35,0.9);},
        'hint': function(p,q){return g(q,"更衣室核心","文化冲突");},
        'apply': function(p,q,s){return d(q,s)?{'guanxi':0xa,'ovr':0x2,'text':"你教他们读战术板，他们教你踩单车。三个月后，你们的连线成了联赛集锦的常客。球探报告里写：这支球队的化学反应，是买不来的。"}:{'guanxi':-0x3,'text':"你觉得他们浪，他们觉得你木。一次训练赛的争执后，更衣室分成了两拨。教练把你们叫进办公室谈了很久。"};}
    },
    {
        'label': "保持距离",
        'hint': "稳",
        'apply': function(){return{'ovr':0x1,'text':"你敬而远之，专注自己的节奏。赛季末你的数据稳稳当当，而那些孩子们来来去去，像潮水。"};}
    }
  ]
},

// ---- idx:320 | lg_jup_step | 跳板 ----
{
  'id': "lg_jup_step",
  'title': "跳板",
  'icon': '🪜',
  'weight': 0x50,
  'when': function(p){return "jup"===p["leagueId"];},
  'desc': "又一名主力队友在冬窗被五大联赛挖走了。欢送会上经理举杯说：这就是我们的商业模式。轮到你时他眨眨眼：当然，也包括你。",
  'options': [
    {
        'label': "把跳板踩实",
        'p': function(p){return f(0.55,[[p["ovr"],0x48,0.01]],0.25,0.85);},
        'hint': function(p,q){return g(q,"更大的舞台","原地踏步");},
        'apply': function(p,q,s){return d(q,s)?{'ovr':0x2,'fame':0x8,'text':"半个赛季，你在欧战资格区球队身上连场进球。经纪人的邮件开始多了起来，标题里出现了英超和德甲的名字。"}:{'ovr':-0x1,'text':"你急着表现，越踢越急。冬窗过去了，没有报价。经理拍拍你：别慌，跳板一直都在，先站稳。"};}
    },
    {
        'label': "享受这里的核心位",
        'hint': "关系++",
        'apply': function(){return{'guanxi':0xc,'roleDelta':0x1,'text':"你成了队里的进攻核心，球迷喊你名字的时候，你想起自己曾经也只想把这里当驿站。有些站，待久了就成了家。"};}
    }
  ]
},

// ---- idx:321 | lg_seg_bus | 大巴与人工草皮 ----
{
  'id': "lg_seg_bus",
  'title': "大巴与人工草皮",
  'icon': '🚌',
  'weight': 0x50,
  'when': function(p){return "seg"===p["leagueId"];},
  'desc': "客场大巴开了五个小时，球场是人工草皮，看台离边线只有三米，骂声听得一清二楚。队长吐掉口香糖：习惯这里，你才算真的踢过西班牙足球。",
  'options': [
    {
        'label': "硬碰硬",
        'p': function(p){return f(0.58,[[p["clean"],60,0.005]],0.25,0.88);},
        'hint': function(p,q){return g(q,"客场的男人","吃牌下场");},
        'apply': function(p,q,s){return d(q,s)?{'ovr':0x2,'clean':-0x2,'text':"你在人工草皮上滑铲、拼抢、还进了一个。主队球迷从骂声变成了沉默。回程大巴上，老队员递给你一颗糖：欢迎毕业。"}:{'ovr':-0x1,'clean':-0x5,'text':"对方后卫整场都在你耳边垃圾话。第七十分钟你回了一句，换来两张黄牌和一场禁赛。更衣室里教练没骂你，只是让你看了眼自己的犯规集锦。"};}
    },
    {
        'label': "少惹事，专注踢球",
        'hint': "清白+",
        'apply': function(){return{'clean':0x4,'ovr':0x1,'text':"骂声就当背景音。你用一脚助攻回应了看台。裁判赛后特意走过来握了握手：难得。"};}
    }
  ]
},

// ---- idx:322 | lg_b2_climb | 冲甲积分榜 ----
{
  'id': "lg_b2_climb",
  'title': "冲甲积分榜",
  'icon': '📈',
  'weight': 0x50,
  'when': function(p){return "b2"===p["leagueId"];},
  'desc': "德乙还剩十轮，升级区里挤着四支球队，分差三分。俱乐部食堂挂出了倒计时牌，连清洁阿姨都会跟你说：这周日，必须赢。",
  'options': [
    {
        'label': "扛起冲刺重任",
        'p': function(p){return f(0.52,[[p["ovr"],0x49,0.01]],0.22,0.85);},
        'hint': function(p,q){return g(q,"升级功臣","倒在门口");},
        'apply': function(p,q,s){return d(q,s)?{'ovr':0x2,'fame':0xa,'roleDelta':0x1,'text':"最后三轮你造了四个球。升级确定那天，几千名球迷冲进场内，把你举了起来。香槟的泡沫里，主席凑到你耳边：下赛季，德甲见。"}:{'ovr':-0x2,'text':"倒数第二轮，你们输给了直接竞争对手。更衣室的倒计时牌第二天被摘了下来。主席说：明年再来。可你知道，阵容留不住了。"};}
    },
    {
        'label': "平常心踢完",
        'hint': "心态稳",
        'apply': function(){return{'ovr':0x1,'guanxi':0x4,'text':"你照常训练、恢复、比赛。压力这种东西，你见过太多起落。赛季结束，成绩单不算完美，但你自己的数据，是生涯最佳。"};}
    }
  ]
},

// ---- idx:323 | lg_ch_grind | 四十六轮 ----
{
  'id': "lg_ch_grind",
  'title': "四十六轮",
  'icon': '♻️',
  'weight': 0x50,
  'when': function(p){return "ch"===p["leagueId"];},
  'desc': "英冠四十六轮，外加两项杯赛。周二周六连轴转，队医的按摩床比替补席还忙。老门将咧嘴一笑：想上英超？先在这磨盘里滚一年。",
  'options': [
    {
        'label': "把自己练成铁人",
        'p': function(p){return f(0.55,[[p["age"],27,-0.02],[p["ovr"],0x47,0.008]],0.2,0.85);},
        'hint': function(p,q){return g(q,"全勤铁人","积劳成伤");},
        'apply': function(p,q,s){return d(q,s)?{'ovr':0x2,'health':0.95,'roleDelta':0x1,'text':"你打满了四十四场。季末颁奖礼，队友们把「球员先生」的奖杯塞进你怀里。主教练说：他就是这台机器的心脏。"}:{'ovr':-0x2,'health':1.15,'text':"三月，疲劳性骨折。你打着石膏看完了冲刺阶段，看着球队差两分掉出附加赛区。队医说：年轻人，这不是英超，没人会让你轮休。"};}
    },
    {
        'label': "聪明地分配体力",
        'hint': "养生流",
        'apply': function(){return{'health':0.92,'ovr':0x1,'text':"你跟队医制定了轮换计划，关键战必上，鸡肋杯赛让路。有人质疑你不够拼，直到冲刺期所有人都垮了，只有你还站着。"};}
    }
  ]
},

// ---- idx:324 | lg_jl_detail | 细节即一切 ----
{
  'id': "lg_jl_detail",
  'title': "细节即一切",
  'icon': '📐',
  'weight': 0x50,
  'when': function(p){return "jl"===p["leagueId"];},
  'desc': "训练结束后，全队留下来复盘录像——不是比赛，是上午的训练。每一个传球角度、每一次回防步点都被标了出来。主帅说：在这里，细节就是尊重。",
  'options': [
    {
        'label': "融入这种偏执",
        'p': function(p){return f(0.7,[[p["talent"],1,0.28]],0.4,0.92);},
        'hint': function(p,q){return g(q,"脱胎换骨","消化不良");},
        'apply': function(p,q,s){return d(q,s)?{'ovr':0x2,'text':"两个月后，你的无跑动回合减少了七成。日本媒体写：这个中国球员，踢得比日本人还日本人。你把剪报贴在了储物柜内侧。"}:{'ovr':-0x1,'text':"你被那些细到毫米的要求压得喘不过气，反而丢了即兴的天赋。教练看出你的僵硬，破例让你自由踢了一周。"};}
    },
    {
        'label': "取其精华去其糟粕",
        'hint': "自成一派",
        'apply': function(){return{'ovr':0x1,'guanxi':0x4,'text':"你学他们的恢复流程和录像习惯，但保留了射门前的直觉。主帅评价：他有纪律，也有火花。这是最好的组合。"};}
    }
  ]
},

// ---- idx:325 | lg_kl_service | 兵役倒计时 ----
{
  'id': "lg_kl_service",
  'title': "兵役倒计时",
  'icon': '⏳',
  'weight': 0x50,
  'when': function(p){return "kl"===p["leagueId"];},
  'desc': "你的韩国室友刚过二十五岁生日，桌上多了一份兵役体检通知。他笑着问你：中国是不是没有这个？你说没有。他沉默了一会儿：那我可能只剩两年职业生涯了。",
  'options': [
    {
        'label': "帮他备战体能测试",
        'p': function(p){return f(0.68,[[p["guanxi"],45,0.008]],0.38,0.92);},
        'hint': function(p,q){return g(q,"过线了","差点意思");},
        'apply': function(p,q,s){return d(q,s)?{'guanxi':0xe,'text':"你陪他加练了一个月，替他掐表、递水、喊口令。成绩公布那天他过了线，抱住你哭了一场。他说：等我从军队回来，还要跟你做队友。"}:{'guanxi':0x6,'text':"测试差了一点，要二次复检。他嘴上说没事，那晚却在阳台抽了很久的烟。你能做的，只有陪着。"};}
    },
    {
        'label': "聊聊两种人生",
        'hint': "关系+",
        'apply': function(){return{'guanxi':0x8,'ovr':0x1,'text':"你们聊了很多：关于义务、关于选择、关于两年空白期怎么保持状态。他说：跟你聊天真好，好像我的暂停键没那么可怕了。"};}
    }
  ]
},

// ---- idx:326 | lg_mls_coast | 五个时区 ----
{
  'id': "lg_mls_coast",
  'title': "五个时区",
  'icon': '✈️',
  'weight': 0x50,
  'when': function(p){return "mls"===p["leagueId"];},
  'desc': "这周先飞西海岸，再飞回来打主场，下周又是东海岸。队友们人手一个颈枕，行李箱轮子磨平了。队长说：在这个联盟，旅途本身就是第十二人。",
  'options': [
    {
        'label': "学会在飞机上恢复",
        'p': function(p){return f(0.62,[[p["age"],28,-0.02],[p["ovr"],0x46,0.008]],0.28,0.9);},
        'hint': function(p,q){return g(q,"空中飞人","时差拖垮");},
        'apply': function(p,q,s){return d(q,s)?{'ovr':0x2,'health':0.95,'text':"压缩袜、定时补水、落地即睡。一个月横跨四次时区，你的体测数据不降反升。队医逢人就夸：这家伙把客机住成了理疗中心。"}:{'ovr':-0x2,'health':1.1,'text':"连续五周飞行后，你在训练场上睡着了。不是开玩笑——拉伸做到一半，靠着标志锥就眯了过去。队医强制你休了三天。"};}
    },
    {
        'label': "顺路看看这个国家",
        'hint': "心态+",
        'apply': function(){return{'ovr':0x1,'fame':0x4,'text':"大峡谷、芝加哥的风、纽约的雨夜机场。你把这些都记进了随行笔记。足球之外，这段漂泊成了你人生最特别的部分之一。"};}
    }
  ]
}

];
