// auto-generated by split_events.py - edit events here, then run build_events.py

var EVT_love=[

// ---- idx:256 | love_fir | 有人在等你 ----
{
  'id': "love_fir"+'st',
  'title': "有人在等你",
  'icon': '💬',
  'weight': 0x37,
  'when': function(p){
return!p["hasPartn"+'er'];
},
  'desc': "训练完，手机上有好几条消息，来自不同的人。你在更衣室门口站了很久，没有一条是关于球的。",
  'rndPick': 0x3,
  'pool': [{'label':"老家从小一起踢球的",'hint':"青梅竹马，天赋+",'apply':function(){
return{'partner':"青梅竹马",'ovr':0x1,'talent':0.02,'guanxi':0x4,'text':"你们八岁就认识。那时候她比你还敢往人堆里冲。她说这些年你的比赛，一场都没落。"};
}},{'label':"队里的康复师",'hint':"天天见面的那个人，伤病-15%",'apply':function(){
return{'partner':"队里的康复师",'ovr':0x2,'health':0.85,'text':"她给你处理了两年脚踝，知道你每一处旧伤。第一次约饭，她开口第一句：「今天别喝冰的。」"};
}},{'label':"评论区里那个总在"+'的人','hint':"镜头那头的，伤病少一点",'apply':function(){
return{'partner':"屏幕那头的人",'fame':0xa,'money':-0x14,'health':0.95,'text':"她做美食账号，粉丝比你多。见面那天，她把手机反扣在桌上，说今天不拍。"};
}},{'label':"客场看台上每场都来的那个球迷",'hint':"你一直记得她，激励加练",'apply':function(){
return{'partner':"那个客场球迷",'fame':0x8,'money':-0xa,'talent':0.01,'text':"她跟着你们队去每一个客场，举一块手写的灯牌。第一次搭话，她把灯牌转过来，背面写着你的生日。"};
}},{'label':"写了你三年的跟队记者",'hint':"她比你先知道转会，场上更自律",'apply':function(){
return{'partner':"那位跟队记者",'fame':0x8,'guanxi':0x2,'ovr':0x1,'text':"她写过你从梯队到现在每一篇。约饭那天她说：「你转会的消息，是我第一个写的，那时候你还在国少。」"};
}},{'label':"国家队队友的妹妹",'hint':"更衣室门口见过几次，伤病少一点",'apply':function(){
return{'partner':"队友的妹妹",'guanxi':0x6,'fame':0x3,'health':0.9,'text':"她在国家队看台上看了你三年。介绍人说，她总问「这场他上了吗」。你第一次觉得，有人比你自己还惦记你上不上场。"};
}},{'label':"游戏里经常开黑的那个网友",'hint':"那个抢你位置的辅助，状态更好",'apply':function(){
return{'partner':"那个游戏搭子",'fame':0x5,'money':-0xf,'ovr':0x1,'text':"你们一起打了四年排位，她一直不知道你踢球。面基那天，她盯着你看了半天：「你……不就是那个国家队……」你请她吃了顿火锅，堵住她的嘴。"};
}}],
  'single': {'label':"现在只想踢球",'hint':"能力+3",'apply':function(){
return{'ovr':0x3,'text':"那些消息，你一条都没回。那年冬训你是全队跑得最多的，总结会上教练点了你的名。"};}},
},

// ---- idx:257 | love_lat | 三十岁那年 ----
{
  'id': "love_lat"+'e',
  'title': "三十岁那年",
  'icon': '🍵',
  'weight': 0x46,
  'when': function(p){
return!p["hasPartn"+'er']&&p["age"]>=0x1d;
},
  'desc': "又一年冬歇，家里安排了个饭局。对方是牙医，坐下第一句：「你们踢球的，膝盖是不是都不太好？」",
  'options': [
    {
        'label': "试试看",
        'hint': "有个人了",
        'apply': function(){
return{'partner':"那位牙医",'ovr':0x1,'money':-0x1e,'text':"第二次见面，她把你的旧片子翻了一遍，说不归她管，但她认识人。你笑了很久。"};
}
    },
    {
        'label': "还是算了",
        'hint': "能力+2",
        'apply': function(){
return{'ovr':0x2,'text':"你说自己这几年跑来跑去，怕耽误人家。回去的路上下了雪，你一个人走了两站地。"};
}
    }
  ]
},

// ---- idx:258 | love_onl | 直播间 ----
{
  'id': "love_onl"+"ine",
  'title': "直播间",
  'icon': '📱',
  'weight': 0x46,
  'when': function(p){
return!p["hasPartn"+'er']&&p["fame"]>=0x2d;
},
  'desc': "一个百万粉丝的主播在直播里说你是她的偶像。第二天，她的助理联系了你的经纪人。",
  'options': [
    {
        'label': "见一面",
        'hint': "名气大涨，也会有"+"别的东西跟着来",
        'apply': function(){
return{'partner':"那位主播",'fame':0x16,'money':0x78,'ovr':-0x1,'text':"你们的合照第二天传得到处都是。评论里一半在祝福，一半在算她的粉丝值多少钱。"};
}
    },
    {
        'label': "让经纪人回绝",
        'hint': "清静，名气-",
        'apply': function(){
return{'fame':-0x5,'ovr':0x2,'text':"经纪人说，这种流量不要白不要。你说，你要的不是这种。"};
}
    }
  ]
},

// ---- idx:259 | love_lon | ? ----
{
  'id': "love_lon"+"gdistanc"+'e',
  'title': '时差',
  'icon': "🕰️",
  'weight': 0x34,
  'repeat': 0x2,
  'when': function(p){
return p["hasPartn"+'er']&&!p["inChina"];
},
  'desc': "你这边是训练完的下午，她那边是凌晨三点。这个月的通话记录：四次，最长的一次十一分钟。",
  'options': [
    {
        'label': "让她过来",
        'hint': "花钱，两个人都稳",
        'apply': function(){
return{'money':-0x50,'ovr':0x2,'guanxi':0x5,'text':"她辞了那边的工作搬了过来。头半年，这座城市里她没有半个熟人，每天只等你训练完回家。"};
}
    },
    {
        'p': function(p){return f(0.55,[[p["guanxi"],45,0.008]],0.2,0.9);
},
        'label': "先这样，等赛季结"+'束',
        'hint': "能力+2，感情有"+'风险',
        'odds': ["撑住了","撑不住"],
        'apply': function(p,q,s){
return d(q,s)?{'ovr':0x2,'text':"你们撑过了那个赛季。后来她说，那半年你每场比赛的重播，她一场都没落下。"}:{'split':!0x0,'ovr':-0x2,'fame':-0x4,'text':"最后一次通话，她说：「我不是不理解，我就是累了。」挂断之后，你在阳台上站到天亮。"};
}
    }
  ]
},

// ---- idx:260 | love_pro | ? ----
{
  'id': "love_pro"+"pose",
  'title': '戒指',
  'icon': '💍',
  'weight': 0x82,
  'when': function(p){
return p["hasPartn"+'er']&&!p["married"]&&p["partnerY"+"ears"]>=0x2;
},
  'desc': "在一起几年了，两边家里都在问。冬歇期只有十九天，真要办婚礼，蜜月就得砍掉。",
  'options': [
    {
        'label': "求婚，冬歇期办",
        'hint': "结婚，花钱，心气"+'稳',
        'apply': function(){
return{'marry':!0x0,'money':-0x96,'ovr':0x2,'fame':0xc,'text':"婚礼在老家办，来了三十几桌。队友来了七个，教练发了条语音：别耽误一月八号的集训。"};
}
    },
    {
        'label': "等退役再说",
        'hint': "能力+2，但这话"+"说了好几年了",
        'apply': function(){
return{'ovr':0x2,'text':"你说，等踢完这个合同。她说好。这句「等踢完这个合同」，你后来又说了两次。"};
}
    }
  ]
},

// ---- idx:261 | love_kid | 第一个孩子 ----
{
  'id': "love_kid"+"_first",
  'title': "第一个孩子",
  'icon': '🍼',
  'weight': 0x82,
  'repeat': 0x2,
  'when': function(p){
return p["married"]&&0x0===p["kids"];
},
  'desc': "预产期落在赛季中段，正好撞上客场三连战。俱乐部说，可以特批你回去一趟。",
  'options': [
    {
        'label': "赶回去",
        'hint': "错过一场比赛，但"+"你在场",
        'apply': function(){
return{'kid':!0x0,'roleDelta':-0x1,'fame':0x8,'ovr':0x1,'text':"你落地时，孩子已经出生四十分钟。护士把他递过来，你手一直在抖，没敢用力。"};
}
    },
    {
        'label': "打完再回",
        'hint': "队内地位+，这件"+"事会记很多年",
        'apply': function(){
return{'kid':!0x0,'roleDelta':0x1,'ovr':-0x1,'guanxi':0x5,'text':"那场你打满全场，还助攻了一个。视频里她没生气，只是很累。这件事，她后来只提过一次。"};
}
    },
    {
        'label': "这两年先不要",
        'hint': "能力+3，这事以"+"后再说",
        'apply': function(){
return{'ovr':0x3,'text':"你说，等这份合同踢完。她把体检报告收进抽屉，那个抽屉，后来再没打开过。"};
}
    }
  ]
},

// ---- idx:262 | love_kid | 夜里三点 ----
{
  'id': "love_kid"+"_night",
  'title': "夜里三点",
  'icon': '🌙',
  'weight': 0x32,
  'repeat': 0x2,
  'when': function(p){
return p["kids"]>=0x1;
},
  'desc': "孩子六个月，一晚上要醒三次。第二天有比赛，队医说你的深睡掉到了两个多小时。",
  'options': [
    {
        'label': "请个月嫂",
        'hint': "花钱，睡得着",
        'apply': function(){
return{'money':-0x3c,'ovr':0x2,'text':"那半年，你每天都能睡满八小时。有人说你花钱买觉，你说这是这辈子最值的一笔。"};
}
    },
    {
        'label': "自己扛",
        'hint': "能力-，但那几个"+"月你都在",
        'apply': function(){
return{'ovr':-0x3,'fame':0x5,'text':"有一场你在替补席上睡着了，被队友拍醒。那个赛季，是你出场以来数据最差的一年。"};
}
    }
  ]
},

// ---- idx:263 | love_kid | ? ----
{
  'id': "love_kid"+"_second",
  'title': '老二',
  'icon': '👶',
  'weight': 0x2e,
  'when': function(p){
return p["married"]&&p["kids"]>=0x1&&p["age"]>=0x1c;
},
  'desc': "老大四岁了，家里问，要不要再要一个。你的合同还有两年，下一站在哪儿，谁也不知道。",
  'options': [
    {
        'label': "再要一个",
        'hint': "又一个孩子",
        'apply': function(){
return{'kid':!0x0,'money':-0x32,'fame':0x6,'ovr':0x1,'text':"老二出生那天，你在客场。回来时，老大趴在婴儿床边不肯走，说这是他的。"};
}
    },
    {
        'label': "等安顿下来再说",
        'hint': "能力+2",
        'apply': function(){
return{'ovr':0x2,'text':"你说，等合同定下来。等那份合同签完，你们已经搬了两次家。"};
}
    }
  ]
},

// ---- idx:264 | love_kid | 看台上的那两个 ----
{
  'id': "love_kid"+"_watch",
  'title': "看台上的那两个",
  'icon': "🎟️",
  'weight': 0x30,
  'when': function(p){
return p["kids"]>=0x1;
},
  'desc': "孩子第一次来现场看你踢球。开场十分钟，他睡着了，醒来第一句是「什么时候能吃薯条」。",
  'options': [
    {
        'label': "赛后带他上草皮",
        'hint': "名气+，能力+",
        'apply': function(){
return{'fame':0xa,'ovr':0x2,'text':"他在中圈跑了两圈，摔了一跤，爬起来接着跑。那张照片后来是你手机的锁屏，一直没换。"};
}
    },
    {
        'label': "让他先回家睡",
        'hint': "能力+2",
        'apply': function(){
return{'ovr':0x2,'text':"他在车上睡着了，手里还攥着那张票。后来那张票，被夹进了家里的相册。"};
}
    }
  ]
},

// ---- idx:265 | love_kid | 他也想踢球 ----
{
  'id': "love_kid"+"_ball",
  'title': "他也想踢球",
  'icon': '⚽',
  'weight': 0x32,
  'stage': "vet",
  'when': function(p){
return p["kids"]>=0x1&&p["age"]>=0x21;
},
  'desc': "孩子说想进梯队。那条路有多少人走不到头，你比谁都清楚——你自己就是从那儿爬上来的。",
  'options': [
    {
        'label': "送他去",
        'hint': "名气+，你知道自"+"己在做什么",
        'apply': function(){
return{'fame':0xc,'ovr':0x1,'money':-0x28,'text':"报名表是你填的，教练那一栏，写着你自己的名字。他在队里第一次被换下时哭了，你在车里等他，没下车。"};
}
    },
    {
        'label': "让他先把书念完",
        'hint': "能力+2",
        'apply': function(){
return{'ovr':0x2,'clean':0x4,'text':"你跟他说，先把书念完，真喜欢的话，什么时候都来得及。这话，当年也有人跟你说过，你没听。"};
}
    }
  ]
},

// ---- idx:266 | love_inl | 岳父的意思 ----
{
  'id': "love_inl"+'aw',
  'title': "岳父的意思",
  'icon': '🏠',
  'weight': 0x2c,
  'when': function(p){
return p["married"];
},
  'desc': "回老家吃饭，岳父绕了三圈才说到正题：老家的房子该换了，弟弟结婚也差一笔。",
  'options': [
    {
        'label': "掏这笔钱",
        'hint': "花一大笔，关系+",
        'apply': function(){
return{'money':-0xdc,'guanxi':0xa,'ovr':0x1,'text':"钱转过去的当天，他发了条动态，配图是新房的钥匙。你老婆一句话没说，晚上给你多盛了碗汤。"};
}
    },
    {
        'label': "说清楚",
        'hint': "省下钱，家里几年"+"不太自在",
        'apply': function(){
return{'ovr':0x2,'guanxi':-0xa,'fame':-0x4,'text':"你把这些年的账摊开说了一遍。那顿饭，后来没人再说话，电视一直开着。"};
}
    }
  ]
},

// ---- idx:267 | love_pap | ? ----
{
  'id': "love_pap"+"arazzi",
  'title': '代拍',
  'icon': '📷',
  'weight': 0x2e,
  'repeat': 0x2,
  'when': function(p){
return p["hasPartn"+'er']&&p["fame"]>=0x32;
},
  'desc': "有人在你住处楼下蹲了三天。照片发出来时，配的文字跟照片上的事，没有半点关系。",
  'options': [
    {
        'label': "发律师函",
        'hint': "花钱，名气+",
        'apply': function(){
return{'money':-0x3c,'fame':0xa,'clean':0x5,'text':"对方删了帖，也道了歉。三个月后，另一个号又发了同样的图。你这才知道，这事没有尽头。"};
}
    },
    {
        'label': "带她换个地方住",
        'hint': "花钱，清静",
        'apply': function(){
return{'money':-0xb4,'ovr':0x2,'text':"新家在城郊，通勤多了四十分钟。她说，这四十分钟换来的，是能自己下楼扔垃圾。"};
}
    }
  ]
},

// ---- idx:268 | love_mov | 她的工作 ----
{
  'id': "love_mov"+'e',
  'title': "她的工作",
  'icon': '✈️',
  'weight': 0x30,
  'when': function(p){
return p["hasPartn"+'er']&&p["partnerY"+"ears"]>=0x2;
},
  'desc': "你这边谈着新合同，她那边刚升了职。两座城市之间，隔着两千公里，或者一片海。",
  'options': [
    {
        'label': "让她跟着走",
        'hint': "你的路顺，她的断"+'了',
        'apply': function(){
return{'ovr':0x2,'roleDelta':0x1,'text':"她辞了职，跟你搬了过来。第二年，她在这边重新开始，从助理做起。这件事，你们再没聊过。"};
}
    },
    {
        'label': "你留下",
        'hint': "地位受损，家里稳",
        'apply': function(){
return{'roleDelta':-0x2,'ovr':0x1,'guanxi':0x6,'text':"你续了一份不算好的合同，条件是留下来。那年出场时间少了一半，但每天都能回家吃饭。"};
}
    },
    {
        'p': function(p){return f(0.5,[[p["guanxi"],45,0.008]],0.2,0.9);
},
        'label': "各走各的",
        'hint': function(p,q){return g(q,'撑住','就这么散了');
},
        'apply': function(p,q,s){
return d(q,s)?{'ovr':0x2,'fame':0x4,'text':"你们靠航班表过了两年。她说，这样也挺好，两个人都没停下。"}:{'split':!0x0,'ovr':-0x2,'money':-0x3c,'text':"分开是她先提的，说得很平静。东西分两次搬走，第二次，你没在家。"};
}
    }
  ]
},

// ---- idx:269 | love_ann | 纪念日那天有客场 ----
{
  'id': "love_ann"+'iv',
  'title': "纪念日那天有客场",
  'icon': '🎂',
  'weight': 0x2c,
  'repeat': 0x2,
  'when': function(p){
return p["married"];
},
  'desc': "结婚纪念日撞上客场。上一次撞上，是三年前——那次，你也没在。",
  'options': [
    {
        'label': "让队医报个小伤",
        'hint': "在家，队内地位受"+'损',
        'apply': function(){
return{'roleDelta':-0x1,'ovr':0x1,'guanxi':0x5,'text':"你在家做了顿饭，做糊了。她说，这是这些年最好的一个纪念日。"};
}
    },
    {
        'label': "照常走",
        'hint': "队内地位+，回来"+'补',
        'apply': function(){
return{'roleDelta':0x1,'ovr':0x1,'text':"你在酒店给她订了花，卡片上的字，是队里翻译帮你写的。她收到时，正在加班。"};
}
    }
  ]
},

// ---- idx:270 | love_spl | 说不下去了 ----
{
  'id': "love_spl"+'it',
  'title': "说不下去了",
  'icon': '🥀',
  'weight': 0x2a,
  'when': function(p){
return p["hasPartn"+'er']&&p["partnerY"+"ears"]>=0x4;
},
  'desc': "这半年，你们几乎没吵过架——因为已经没什么可说的了。她把话摊开那天，你正准备去队里报到。",
  'options': [
    {
        'p': function(p){return f(0.45,[[p["guanxi"],45,0.008]],0.2,0.9);
},
        'label': "试着修一修",
        'hint': function(p,q){return g(q,'修回来了','拖着更难看');
},
        'apply': function(p,q,s){
return d(q,s)?{'ovr':0x2,'guanxi':0x5,'text':"你们去做过几次咨询，也一起出去待了两周。回来后她说，那两周是这几年最像样的日子。"}:{'split':!0x0,'ovr':-0x3,'money':-0x12c,
'fame':-0x6,'text':"拖了一年半，最后还是签了字。财产分割那天你迟到了——队里加练。"};
}
    },
    {
        'label': "好好散",
        'hint': "花一笔，各自往前"+'走',
        'apply': function(){
return{'split':!0x0,'money':-0x104,'ovr':-0x1,'fame':0x4,'text':"你们一起吃了顿饭，才去办的手续。她说，以后你的比赛她还是会看。你说，好。"};
}
    }
  ]
},

// ---- idx:271 | love_bac | 退役以后干什么 ----
{
  'id': "love_bac"+"khome",
  'title': "退役以后干什么",
  'icon': "🛋️",
  'weight': 0x2c,
  'stage': "vet",
  'when': function(p){
return p["hasPartn"+'er']&&p["age"]>=0x22;
},
  'desc': "她第一次认真问你，退役以后想干什么。你发现，从十二岁起你就没想过这个问题。",
  'options': [
    {
        'label': "去考教练证",
        'hint': "退役后有出路",
        'apply': function(){
return{'coachCert':!0x0,'ovr':-0x1,'money':-0x28,'text':"你利用赛季间隙上了课。考试那天，你紧张得像是回到十六岁那年的选拔赛。"};
}
    },
    {
        'label': "先把这个赛季踢完",
        'hint': "能力+3",
        'apply': function(){
return{'ovr':0x3,'text':"你说，等踢不动了自然就知道了。她没再问。这个问题，后来是你自己在一个夜里想起来的。"};
}
    }
  ]
}

];
