// auto-generated by split_events.py - edit events here, then run build_events.py

var EVT_mid=[

// ---- idx:109 | mid_engi | 跑动数据 ----
{
  'id': "mid_engi"+'ne',
  'title': "跑动数据",
  'icon': '📈',
  'weight': 0x37,
  'when': function(p){
return "mid"===p["posGroup"];
},
  'desc': "体能教练把全队的跑动图贴在墙上。你那条线，停在中游偏下。",
  'options': [
    {
        'p': function(p){return f(0.7,[[p["ovr"],60,0.008]],0.2,0.9);
},
        'label': "跑到第一",
        'hint': function(p,q){return g(q,'能力+4','跑废了');
},
        'apply': function(p,q,s){
return d(q,s)?{'ovr':0x3,'roleDelta':0x1,'text':"你连续十场，每场跑满十二公里。教练说，有你在，这支队的中场就不会断。"}:{'ovr':-0x3,'text':"第二十七轮，你在一次无对抗的跑动里拉伤了大腿。那张图，后来被撤了下来。"};
}
    },
    {
        'label': "省着点跑",
        'hint': "能力+1，教练不"+'满',
        'apply': function(){
return{'ovr':0x1,'roleDelta':-0x1,'text':"你把力气留给带球那几下。跑动数据难看，可你那几脚传球，很关键。"};
}
    }
  ]
},

// ---- idx:110 | mid_deep | 往后撤一条线 ----
{
  'id': "mid_deep",
  'title': "往后撤一条线",
  'icon': '🔻',
  'weight': 0x34,
  'when': function(p){
return "mid"===p["posGroup"];
},
  'desc': "队里前腰位置人满为患。教练问你，愿不愿意往后撤一步，改踢后腰。",
  'options': [
    {
        'label': "改位置",
        'hint': "能力+4，进球没"+'了',
        'apply': function(){
return{'ovr':0x3,'roleDelta':0x1,'fame':-0x6,'text':"你从进球的人，变成了让别人进球的人。数据难看，出场时间却翻了一倍。"};
}
    },
    {
        'p': function(p){return f(0.5,[[p["ovr"],60,0.008]],0.2,0.9);
},
        'label': '不改',
        'hint': function(p,q){return g(q,'争到位置','板凳');
},
        'apply': function(p,q,s){
return d(q,s)?{'ovr':0x2,'fame':0x8,'text':"你用两个赛季，证明了那个位置本来就该是你的。"}:{'roleDelta':-0x2,'text':"教练用了那个花大价钱买来的前腰。你在替补席上看了一年。"};
}
    }
  ]
},

// ---- idx:111 | mid_setp | 定位球主罚权 ----
{
  'id': "mid_setp"+"iece",
  'title': "定位球主罚权",
  'icon': '🎯',
  'weight': 0x32,
  'when': function(p){
return "mid"===p["posGroup"];
},
  'desc': "队里的定位球一直是队长罚的。这赛季他状态下滑，训练课上，你罚出的每一脚都比他准。",
  'options': [
    {
        'p': function(p){return f(0.65,[[p["guanxi"],45,0.008]],0.2,0.9);
},
        'label': "开口要",
        'hint': function(p,q){return g(q,'拿到','得罪人');
},
        'apply': function(p,q,s){
return d(q,s)?{'ovr':0x3,'fame':0xc,'text':"第一脚任意球就旋进死角。从那以后，角球、任意球，都归了你。"}:{'guanxi':-0xc,'roleDelta':-0x1,'text':"队长当着全队的面说：「你先把传球练准。」这句话你记了很多年。"};
}
    },
    {
        'label': "等他自己让",
        'hint': "无变化",
        'apply': function(){
return{'text':"你等了两年。他退役那天，把角旗区的位置，交给了另一个人。"};
}
    }
  ]
},

// ---- idx:112 | mid_temp | 节拍器 ----
{
  'id': "mid_temp"+'o',
  'title': "节拍器",
  'icon': '🎼',
  'weight': 0x30,
  'when': function(p){
return "mid"===p["posGroup"];
},
  'desc': "外教说，中场球员的通病是快慢不分：该慢的时候急，该快的时候磨。",
  'options': [
    {
        'label': "重学节奏",
        'hint': "能力+4，头半年"+'难看',
        'apply': function(){
return{'ovr':0x4,'fame':-0x5,'text':"他让你每场只做一"+"件事：抬头。半年"+"后你传球少了，但"+"每一脚都往前。"};
}
    },
    {
        'p': function(p){return f(0.5,[[p["talent"],1,0.4]],0.2,0.9);
},
        'label': "按自己的来",
        'hint': function(p,q){return g(q,'也踢出来了','越踢越乱');
},
        'apply': function(p,q,s){
return d(q,s)?{'ovr':0x2,'fame':0x6,'text':"你那套节奏在国内够用。出了国，才发现差着一截。"}:{'ovr':-0x2,'roleDelta':-0x1,'text':"你在中场丢球太多。外教没多说，把你挪去了边路。"};
}
    }
  ]
},

// ---- idx:113 | mid_tack | 抢断还是站位 ----
{
  'id': "mid_tack"+'le',
  'title': "抢断还是站位",
  'icon': '🦿',
  'weight': 0x30,
  'when': function(p){
return "mid"===p["posGroup"];
},
  'desc': "你的抢断数联赛第二，犯规数联赛第一。分析师说，这两件事其实是同一件事。",
  'options': [
    {
        'label': "改成靠站位",
        'hint': "能力+3，观赏性"+'没了',
        'apply': function(){
return{'ovr':0x3,'fame':-0x6,'text':"你不再飞铲，改成提前站到那儿。集锦里没了你，球队少丢了六个球。"};
}
    },
    {
        'p': function(p){return f(0.6,[[p["clean"],70,0.008]],0.2,0.9);
},
        'label': "继续飞",
        'hint': function(p,q){return g(q,'成为狠角色','累积停赛');
},
        'apply': function(p,q,s){
return d(q,s)?{'fame':0xe,'ovr':0x1,'text':"对方前腰赛前会专门研究你。这本身，就是一种战术价值。"}:{'banGames':0x3,'ovr':-0x1,'text':"一个赛季，十二张黄牌，两张红牌。三场关键战，你的名字不在名单上。"};
}
    }
  ]
},

// ---- idx:114 | mid_long | 四十米转移 ----
{
  'id': "mid_long"+"ball",
  'title': "四十米转移",
  'icon': '🏹',
  'weight': 0x2d,
  'when': function(p){
return "mid"===p["posGroup"];
},
  'desc': "你有一脚长传的本事，可教练的体系只要短传渗透，长传在他那儿叫「回避对抗」。",
  'options': [
    {
        'label': "藏起来",
        'hint': "能力+2，符合体"+'系',
        'apply': function(){
return{'ovr':0x2,'roleDelta':0x1,'text':"你把长传收进口袋，一个赛季只用了七次，七次全是机会。"};
}
    },
    {
        'p': function(p){return f(0.5,[[p["ovr"],60,0.008]],0.2,0.9);
},
        'label': "该传就传",
        'hint': function(p,q){return g(q,'被认可','被换下');
},
        'apply': function(p,q,s){
return d(q,s)?{'ovr':0x2,'fame':0xc,'text':"有一脚六十米转移，直接变成进球。教练什么也没说，也没再拦你。"}:{'roleDelta':-0x2,'text':"第三次长传出界，你被换下。第四次，没有机会了。"};
}
    }
  ]
},

// ---- idx:115 | mid_box_ | 两个禁区之间 ----
{
  'id': "mid_box_"+"to_box",
  'title': "两个禁区之间",
  'icon': '↕️',
  'weight': 0x2d,
  'when': function(p){
return "mid"===p["posGroup"];
},
  'desc': "教练要你既能插上，又能回防。这活儿在{league}，没几个人扛得了一整个赛季。",
  'options': [
    {
        'p': function(p){return f(0.75,[[p["ovr"],60,0.008]],0.2,0.9);
},
        'label': "接下来",
        'hint': function(p,q){return g(q,'能力+5','半程报销');
},
        'apply': function(p,q,s){
return d(q,s)?{'ovr':0x3,'fame':0xc,'text':"那个赛季你进了九个，抢断也在前十。队里人都在问，你是怎么练的。"}:{'ovr':-0x3,'text':"第十九轮，你倒在中圈，起不来。诊断写的是：疲劳性骨裂。"};
}
    },
    {
        'label': "只干一头",
        'hint': "能力+2",
        'apply': function(){
return{'ovr':0x2,'text':"你专心做好防守那一半。教练在那个位置上，又买了个人做另一半。"};
}
    }
  ]
},

// ---- idx:116 | mid_crea | 别冒险 ----
{
  'id': "mid_crea"+"tive_lea"+'sh',
  'title': "别冒险",
  'icon': '🔗',
  'weight': 0x2d,
  'when': function(p){
return "mid"===p["posGroup"];
},
  'desc': "录像会上，教练按下暂停：「这个球，横传。」你记得那一脚直塞，差点撕开整条防线。",
  'options': [
    {
        'label': "听他的",
        'hint': "地位+，能力-1",
        'apply': function(){
return{'roleDelta':0x1,'ovr':-0x1,'guanxi':0x6,'text':"你成了传球成功率最高的中场，也成了最不被人记住的那个。"};
}
    },
    {
        'p': function(p){return f(0.55,[[p["talent"],1,0.4]],0.2,0.9);
},
        'label': "继续塞",
        'hint': function(p,q){return g(q,'成了球队大脑','坐板凳');
},
        'apply': function(p,q,s){
return d(q,s)?{'ovr':0x4,'fame':0xe,'text':"一个赛季，十一次助攻。后来教练在发布会上说，有些球，只有他敢传。"}:{'roleDelta':-0x2,'fame':-0x6,'text':"丢球太多。坐在替补席上，你想明白了一件事：这不是技术问题。"};
}
    }
  ]
}

];
