// auto-generated by split_events.py - edit events here, then run build_events.py
// 里程碑结算事件（职业期）：季末在 _promoReleg 末尾由 _milestoneScan() 扫描一次。
// 该处数据全部定稿：_lgFinalRefresh 已写 bz.leaguePos、bAw 已发奖、_promoReleg 已定升降名单。
// 五类：荣誉（首座/横扫/金球）、奖项（联赛金靴/最佳/欧洲金靴/金手套/亚洲足球先生）、
//       纪录（进球/助攻/零封/出场/国家队/奖杯数/收入）、身份（首转会/第三家/突破90）、时代（豪门·死敌降级）。
// 扫描只做条件判断、不掷骰（不打乱随机序列）；命中写"一次锁存"flag 并入 _mileQ，
// 再由 _mileQ 按优先级 drain（每季最多 3 条）到 forceQ —— 队列满时留到以后，赛季性里程碑不会丢。
// 本文件 when 只做兜底（读扫描写的锁存 flag）；desc 需要的具体名字/球队由扫描写进 flags。

var EVT_milestone=[

// ---- idx:407 | mile_ballon | 金球奖 ----
{
  'id': "mile_ballon",
  'title': "金球奖",
  'icon': '👑',
  'weight': 0x50,
  'when': function(p){return p["_mileBallon1"]!=null;},
  'desc': "金球奖。你小时候在电器行的橱窗里见过它的照片，隔着玻璃，旁边是打折的电视机。现在它在你手里，比想象中沉。",
  'options': [
    {'label': "举起来，让家里人看见", 'hint': "名气+，关系+", 'apply': function(){return{'fame':0x8,'guanxi':0x4,'text':"你把奖杯举过头顶。转播镜头扫到看台，你妈在抹眼睛，你爸在鼓掌，鼓得很用力。"};}},
    {'label': "收进柜子，明天照常训练", 'hint': "地位+，名气+", 'apply': function(){return{'fame':0x2,'roleDelta':0x1,'text':"你把奖杯放到柜子最上层，第二天照常第一个到训练场。教练看了你一眼，什么也没说。"};}}
  ]
},

// ---- idx:408 | mile_ballon3 | 第三座金球 ----
{
  'id': "mile_ballon3",
  'title': "第三座金球",
  'icon': '🥇',
  'weight': 0x50,
  'when': function(p){return p["_mileBallon3"]!=null;},
  'desc': "第三座。第一座给了父亲，第二座放进了青训营的展柜。这一座你还没想好放哪——家里能摆奖杯的地方，已经比你能想起的荣誉还多了。",
  'options': [
    {'label': "留在俱乐部更衣室", 'hint': "关系+", 'apply': function(){return{'guanxi':0x8,'text':"你把奖杯留在了更衣室。第二天有人给它擦得发亮，摆在了所有人的柜子正中间。"};}},
    {'label': "带回家，和另外两座摆一起", 'hint': "名气+", 'apply': function(){return{'fame':0x4,'text':"你把三座摆成一排，拍了张照片。照片后来被无数人转发，配文是同一句话：还会不会有第四座。"};}}
  ]
},

// ---- idx:409 | mile_first_trophy | 第一座奖杯 ----
{
  'id': "mile_first_trophy",
  'title': "第一座奖杯",
  'icon': '🎁',
  'weight': 0x50,
  'when': function(p){return p["_mileFirstTr"]!=null;},
  'desc': function(p){return "更衣室的柜子里，从此多了一个"+p["_mileFirstTr"]+"。你把它摆正，退后两步看了看，又伸手把它擦了一遍。";},
  'options': [
    {'label': "拍照发给家里", 'hint': "关系+", 'apply': function(){return{'guanxi':0x4,'text':"你把奖杯照片发到了家里的群里。你爸回了两个字：收到。过了十分钟，他又发来一张截图——他把照片设成了手机壁纸。"};}},
    {'label': "明天照常加练", 'hint': "地位+", 'apply': function(){return{'roleDelta':0x1,'text':"你把奖杯放在柜子最里面，第二天照常第一个到。有人问你为什么不多庆祝一天，你说，一个不够。"};}}
  ]
},

// ---- idx:410 | mile_first_league | 第一座联赛冠军 ----
{
  'id': "mile_first_league",
  'title': "第一座联赛冠军",
  'icon': '🎊',
  'weight': 0x50,
  'when': function(p){return p["_mileFirstLg"]!=null;},
  'desc': function(p){return "联赛冠军。"+p["_mileFirstLg"]+"。三十八轮，最后一场结束的时候，看台上有球迷翻过了围栏。" ;},
  'options': [
    {'label': "跟着球迷一起唱", 'hint': "关系+", 'apply': function(){return{'guanxi':0x6,'text':"你站在看台前，跟着他们唱完了整首歌。跑调的部分，第二天被剪进了俱乐部的官方视频。"};}},
    {'label': "把奖杯先递给队里最老的人", 'hint': "关系+，地位+", 'apply': function(){return{'guanxi':0x4,'roleDelta':0x1,'text':"你把奖杯先递给了队里那个合同即将到期的老队长。他愣了一下，然后把奖杯举得比你还高。"};}}
  ]
},

// ---- idx:411 | mile_first_ucl | 大耳朵杯 ----
{
  'id': "mile_first_ucl",
  'title': "大耳朵杯",
  'icon': '🏆',
  'weight': 0x50,
  'when': function(p){return p["_mileFirstUcl"]!=null;},
  'desc': "欧洲冠军联赛。终场哨响，你站在中圈，看着满场的白色纸屑落下来。你想找个人抱一下，却发现所有人都在跑，只有你站在原地。",
  'options': [
    {'label': "把奖杯举给客队看台", 'hint': "名气+", 'apply': function(){return{'fame':0x6,'text':"你举着奖杯绕场一周，最后停在客队球迷的那一角。他们没有骂你，只是站起来鼓掌——这一夜他们记得的，是你的名字。"};}},
    {'label': "先去找那个传球的队友", 'hint': "关系+", 'apply': function(){return{'guanxi':0x6,'text':"你穿过人群去找那个送出助攻的人。他正蹲在草皮上哭。你把他拉起来，把奖杯塞进他怀里。"};}}
  ]
},

// ---- idx:412 | mile_wc | 世界之巅 ----
{
  'id': "mile_wc",
  'title': "世界之巅",
  'icon': '🌍',
  'weight': 0x50,
  'when': function(p){return p["_mileWC"]!=null;},
  'desc': "世界杯冠军。决赛的最后一个点球罚进的那一刻，你听见的不是欢呼，是一种很闷的声音——像整个国家同时松了一口气。",
  'options': [
    {'label': "披着国旗绕场", 'hint': "名气+，关系+", 'apply': function(){return{'fame':0xa,'guanxi':0x4,'text':"你把国旗披在肩上走了很久。后来那张照片挂在了一家体校的走廊里，一挂就是很多年。"};}},
    {'label': "把金牌挂在父亲脖子上", 'hint': "关系+", 'apply': function(){return{'guanxi':0x8,'text':"你把金牌摘下来挂在父亲脖子上。他一句话没说，只是把手放在你后脑上，按了一下。"};}}
  ]
},

// ---- idx:413 | mile_sweep | 一年全包 ----
{
  'id': "mile_sweep",
  'title': "一年全包",
  'icon': '💎',
  'weight': 0x50,
  'when': function(p){return p["_mileSweep"]!=null;},
  'desc': "这一年你没有给别人留任何东西：联赛冠军、欧洲冠军、金球奖。颁奖典礼结束，有记者问你，还有什么是没拿到的。",
  'options': [
    {'label': "回答：下一个赛季", 'hint': "名气+", 'apply': function(){return{'fame':0x6,'text':"你说：下一个赛季。那句话第二天成了头条，也成了更衣室里所有人都听见的一句话。"};}},
    {'label': "什么也不说，把奖杯搬回家", 'hint': "关系+", 'apply': function(){return{'guanxi':0x4,'text':"你没回答，只是把那三座奖杯一趟一趟搬回了家。搬到最后一座的时候，你妈说，别放客厅了，放不下。"};}}
  ]
},

// ---- idx:414 | mile_euro_boot | 欧洲金靴 ----
{
  'id': "mile_euro_boot",
  'title': "欧洲金靴",
  'icon': '👟',
  'weight': 0x50,
  'when': function(p){return p["_mileBoot"]!=null;},
  'desc': "欧洲金靴。这个奖不看你是谁，只看你进了多少球。整个欧洲五大联赛，没有人比你更多。",
  'options': [
    {'label': "把金靴送给青训教练", 'hint': "关系+", 'apply': function(){return{'guanxi':0x8,'text':"你把金靴寄给了体校那个教你射门的老头。他打电话来，第一句是：鞋盒别扔，能卖钱。"};}},
    {'label': "在社媒上晒出来", 'hint': "名气+", 'apply': function(){return{'fame':0x6,'text':"你发了张照片，配文只有一个数字。第二天，那个数字被所有对手的更衣室打印出来贴在了墙上。"};}}
  ]
},

// ---- idx:415 | mile_afcpoy | 亚洲足球先生 ----
{
  'id': "mile_afcpoy",
  'title': "亚洲足球先生",
  'icon': '🌏',
  'weight': 0x50,
  'when': function(p){return p["_mileAfc"]!=null;},
  'desc': "亚洲足球先生。颁奖礼在另一个国家，台下坐着的很多人你只在电视里见过。主持人念你的名字时，念错了声调。",
  'options': [
    {'label': "用中文讲完获奖感言", 'hint': "关系+", 'apply': function(){return{'guanxi':0x6,'text':"你用中文讲完了整段感言。台下的翻译愣了两秒才开始翻。回国后，这段话被反复播放。"};}},
    {'label': "把奖杯留在足协的展柜里", 'hint': "名气+", 'apply': function(){return{'fame':0x4,'text':"你把奖杯留在了足协的展柜里。工作人员问要不要写个说明牌子，你说写：还早。"};}}
  ]
},

// ---- idx:416 | mile_glove | 金手套 ----
{
  'id': "mile_glove",
  'title': "金手套",
  'icon': '🧤',
  'weight': 0x50,
  'when': function(p){return p["_mileGlove"]!=null;},
  'desc': "金手套。前锋的奖杯是聚光灯，门将的奖杯是那些没被写进新闻的扑救。你戴上它，手套比去年又硬了一点。",
  'options': [
    {'label': "把它收进装备包", 'hint': "地位+", 'apply': function(){return{'roleDelta':0x1,'text':"你把金手套塞进装备包最底层，第二天照常提前一个小时到。守门员教练说，这东西不该放在最下面。"};}},
    {'label': "送给守门员教练", 'hint': "关系+", 'apply': function(){return{'guanxi':0x8,'text':"你把金手套送给了守门员教练。他把它挂在了训练场球门后面的网兜上，说：以后每个来练扑救的都先看它一眼。"};}}
  ]
},

// ---- idx:417 | mile_ucl3 | 欧冠三连 ----
{
  'id': "mile_ucl3",
  'title': "欧冠三连",
  'icon': '🏆',
  'weight': 0x50,
  'when': function(p){return p["_mileUclTeam"]!=null;},
  'desc': function(p){return "三年，三座大耳朵杯。第三次捧杯的夜里，"+p["_mileUclTeam"]+"的更衣室没有人尖叫——大家只是互相看着，像在确认这件事真的发生过。";},
  'options': [
    {'label': "把队长袖标留到下一年", 'hint': "关系+，地位+", 'apply': function(){return{'guanxi':0x6,'roleDelta':0x1,'text':"你没有多说什么。训练第一天，你比所有人都早到，把袖标放在了最年轻那个人的柜子上，又拿了回来。"};}},
    {'label': "对着镜头说还会再来", 'hint': "名气+", 'apply': function(){return{'fame':0x6,'text':"你对着镜头说，第四座也在路上。第二天这句话成了所有对手的赛前标语。"};}}
  ]
},

// ---- idx:418 | mile_lg_weak | 黑马冠军 ----
{
  'id': "mile_lg_weak",
  'title': "黑马冠军",
  'icon': '🐎',
  'weight': 0x50,
  'when': function(p){return p["_mileWeakClub"]!=null;},
  'desc': function(p){return "赛季开始前，没有一家媒体把"+p["_mileWeakClub"]+"写进争冠名单。最后一轮终场哨响，"+p["_mileWeakLg"]+"的冠军是你们。看台上有人哭着喊你的名字。";},
  'options': [
    {'label': "把功劳全推给教练组", 'hint': "关系+", 'apply': function(){return{'guanxi':0x8,'text':"你在采访里把功劳全推给了教练组和那些跑了十二公里的队友。第二天训练，没人再拿你当外人。"};}},
    {'label': "一个人举起奖杯走一圈", 'hint': "名气+", 'apply': function(){return{'fame':0x8,'text':"你独自举着奖杯绕场一周。那一刻你听见的不是欢呼，是很多人同时喊你的名字。"};}}
  ]
},

// ---- idx:419 | mile_promote | 升上去了 ----
{
  'id': "mile_promote",
  'title': "升上去了",
  'icon': '🚀',
  'weight': 0x50,
  'when': function(p){return p["_mileUpLg"]!=null;},
  'desc': function(p){return "升级。下赛季你们要踢"+p["_mileUpLg"]+"了。俱乐部把草皮换了一遍，看台加了两排座位——为了那些明年会来的客队球迷。";},
  'options': [
    {'label': "留下，把它带上去", 'hint': "关系+，地位+", 'apply': function(){return{'guanxi':0x6,'roleDelta':0x1,'text':"经纪人问你走不走。你说不走，这支队的名字是你从最低一级开始写上去的。"};}},
    {'label': "先让经纪人摸摸行情", 'hint': "名气+", 'apply': function(){return{'fame':0x2,'text':"你让经纪人把电话开着。这个夏天，会有很多电话打进来——其中一个是豪门的。"};}}
  ]
},

// ---- idx:420 | mile_releg | 降级之夜 ----
{
  'id': "mile_releg",
  'title': "降级之夜",
  'icon': '📉',
  'weight': 0x50,
  'when': function(p){return p["_mileDownLg"]!=null;},
  'desc': function(p){return "降级。下赛季你们要踢"+p["_mileDownLg"]+"。终场哨响后更衣室里没有人说话，有人把球衣蒙在头上。你坐了很久才起来洗澡。";},
  'options': [
    {'label': "留下，把它踢回来", 'hint': "关系+", 'apply': function(){return{'guanxi':0x8,'text':"你把所有人叫到一起，只说了一句：明年这个时候，我们要在更高级别的更衣室里。没人鼓掌，但第二天训练来了二十八个人。"};}},
    {'label': "让经纪人打开电话", 'hint': "名气+", 'apply': function(){return{'fame':0x2,'text':"你让经纪人开始联系下家。这个降级的夏天，你把行李收得很快。"};}}
  ]
},

// ---- idx:421 | mile_giant_down | 豪门陨落 ----
{
  'id': "mile_giant_down",
  'title': "豪门陨落",
  'icon': '🏚',
  'weight': 0x50,
  'when': function(p){return p["_mileGiant"]!=null;},
  'desc': function(p){return p["_mileGiant"]+"降级了。那家俱乐部拿过的冠军比很多联赛的历史都长，现在它的名字出现在降级名单上。你看了两遍才确认那不是排版错误。";},
  'options': [
    {'label': "在社媒上发一句", 'hint': "名气+", 'apply': function(){return{'fame':0x2,'text':"你只发了一句：足球不会饶过任何人。评论区吵了整整一周。"};}},
    {'label': "什么也不发", 'hint': "关系+", 'apply': function(){return{'guanxi':0x2,'text':"你什么也没发。第二天训练，你比平时多跑了二十分钟。"};}}
  ]
},

// ---- idx:422 | mile_rival_down | 死敌降级 ----
{
  'id': "mile_rival_down",
  'title': "死敌降级",
  'icon': '🔻',
  'weight': 0x50,
  'when': function(p){return p["_mileRival"]!=null;},
  'desc': function(p){return p["_mileRival"]+"降级了。下个赛季，你们的德比不会再有。你在训练场上听见有人吹口哨，吹的是他们主场的歌。";},
  'options': [
    {'label': "把那首歌记下来", 'hint': "关系+", 'apply': function(){return{'guanxi':0x4,'text':"你把那首歌的调子记在了手机备忘录里。你说，等他们回来的时候，要有人在看台上唱出来。"};}},
    {'label': "接受采访时说一句心里话", 'hint': "名气+", 'apply': function(){return{'fame':0x2,'text':"你说：少了他们，这一年会安静很多。这句话被两家球迷同时转发了。"};}}
  ]
},

// ---- idx:423 | mile_transfer1 | 第一次转会 ----
{
  'id': "mile_transfer1",
  'title': "第一次转会",
  'icon': '🧳',
  'weight': 0x50,
  'when': function(p){return p["_mileTrans"]!=null;},
  'desc': "你换了球队。搬家那天只有两个箱子，其中一个是球鞋。新更衣室里的柜子上还没有你的名字，只有一张打印出来的纸条。",
  'options': [
    {'label': "把老东家的队徽贴在柜子里", 'hint': "关系+", 'apply': function(){return{'guanxi':0x4,'text':"你把老东家的队徽贴在了新柜子的内侧。有人看见了，什么也没说，只是在你名字下面加了一行字：从那边来的。"};}},
    {'label': "谁也不联系，先训练", 'hint': "地位+", 'apply': function(){return{'roleDelta':0x1,'text':"你没给任何人打电话。第一堂训练课结束，主教练在名单上把你的名字往前挪了一行。"};}}
  ]
},

// ---- idx:424 | mile_ovr90 | 突破九十 ----
{
  'id': "mile_ovr90",
  'title': "突破九十",
  'icon': '🎯',
  'weight': 0x50,
  'when': function(p){return p["_mileOvr90"]!=null;},
  'desc': "数据部门出的赛季报告上，你的综合评分第一次上到了九十。这个数字很小，但从六十走到它，用了十几年。",
  'options': [
    {'label': "把报告打印出来", 'hint': "关系+", 'apply': function(){return{'guanxi':0x4,'text':"你把那页报告打印出来，寄回了家。你爸把它夹在了相册里，和一张你十二岁的照片放在同一页。"};}},
    {'label': "盯着下一个数字", 'hint': "地位+", 'apply': function(){return{'roleDelta':0x1,'text':"你没有庆祝。第二天你问教练：下一个数字是多少。"};}}
  ]
},

// ---- idx:425 | mile_goals20 | 二十球赛季 ----
{
  'id': "mile_goals20",
  'title': "二十球赛季",
  'icon': '⚽',
  'weight': 0x50,
  'when': function(p){return p["_mileG20"]!=null;},
  'desc': "这个赛季你进了二十个联赛进球。这个数字以前只在别人的名字后面出现过。",
  'options': [
    {'label': "把进球剪成集锦", 'hint': "名气+", 'apply': function(){return{'fame':0x4,'text':"你把二十个进球剪成了一段视频，配了首很吵的歌。发出去当晚，播放量过了百万。"};}},
    {'label': "只记住没进的那些", 'hint': "地位+", 'apply': function(){return{'roleDelta':0x1,'text':"你把没进的球也数了一遍。数到第七个的时候，你关掉视频去睡了。"};}}
  ]
},

// ---- idx:426 | mile_goals30 | 三十球赛季 ----
{
  'id': "mile_goals30",
  'title': "三十球赛季",
  'icon': '⚽',
  'weight': 0x50,
  'when': function(p){return p["_mileG30"]!=null;},
  'desc': "三十个联赛进球。整个赛季，每三场就有一个进球写着你的名字。对手开始用两个人盯你。",
  'options': [
    {'label': "继续，不管对面几个人", 'hint': "名气+", 'apply': function(){return{'fame':0x6,'text':"你没有改变踢法。被两个人盯的那半年，你送出了职业生涯最多的助攻。"};}},
    {'label': "学会为队友做球", 'hint': "关系+", 'apply': function(){return{'guanxi':0x6,'text':"你开始习惯被包夹后的第一脚出球。赛季结束，队友们的进球数一起涨了。"};}}
  ]
},

// ---- idx:427 | mile_goals40 | 四十球赛季 ----
{
  'id': "mile_goals40",
  'title': "四十球赛季",
  'icon': '⚽',
  'weight': 0x50,
  'when': function(p){return p["_mileG40"]!=null;},
  'desc': "四十个联赛进球。到这个数字，你已经被拿去和历史上那些名字放在一起比较了——而那些人，大多已经退役很多年。",
  'options': [
    {'label': "接受那些比较", 'hint': "名气+", 'apply': function(){return{'fame':0x8,'text':"你在采访里接受了那些比较。你说，被拿去和他们比，本身就已经是荣誉。"};}},
    {'label': "关掉所有新闻", 'hint': "地位+", 'apply': function(){return{'roleDelta':0x1,'text':"你把那些新闻全关了。第二个赛季的第一场，你又进了两个。"};}}
  ]
},

// ---- idx:428 | mile_goal50 | 生涯第五十球 ----
{
  'id': "mile_goal50",
  'title': "生涯第五十球",
  'icon': '💫',
  'weight': 0x50,
  'when': function(p){return p["_mileG50"]!=null;},
  'desc': "职业生涯第五十个球。看台上没人知道这是个整数，你自己知道。你把球捡起来，抱了一会儿才交回去。",
  'options': [
    {'label': "把球留下来", 'hint': "关系+", 'apply': function(){return{'guanxi':0x2,'text':"你把球留了下来，让全队在上面签了名。它后来被放在了俱乐部的走廊里。"};}},
    {'label': "谁也不说", 'hint': "地位+", 'apply': function(){return{'roleDelta':0x1,'text':"你什么也没说，比赛照常结束。这个数字只留在了你自己的本子上。"};}}
  ]
},

// ---- idx:429 | mile_goal100 | 生涯第一百球 ----
{
  'id': "mile_goal100",
  'title': "生涯第一百球",
  'icon': '💯',
  'weight': 0x50,
  'when': function(p){return p["_mileG100"]!=null;},
  'desc': "第一百个进球。赛后发布会，有记者翻出了你第一个职业进球的视频——那球进得很丑，你自己都笑了。",
  'options': [
    {'label': "把第一球和第一百球放一起", 'hint': "名气+", 'apply': function(){return{'fame':0x6,'text':"你把两段视频剪在一起发了出去。配文是：十年，两个球。那条动态被转发了很久。"};}},
    {'label': "请全队吃饭", 'hint': "关系+", 'apply': function(){return{'guanxi':0x6,'text':"你请全队吃了饭，包括那个在你第一场把你骂哭的理疗师。他坐在你旁边，喝了很多。"};}}
  ]
},

// ---- idx:430 | mile_goal200 | 生涯第二百球 ----
{
  'id': "mile_goal200",
  'title': "生涯第二百球",
  'icon': '💯',
  'weight': 0x50,
  'when': function(p){return p["_mileG200"]!=null;},
  'desc': "第二百个。你已经不太记得其中很多球是怎么进的，只记得进球之后抬头看见的那些看台。",
  'options': [
    {'label': "开始记一本本子", 'hint': "关系+", 'apply': function(){return{'guanxi':0x4,'text':"你买了一本本子，从第二百个开始记：时间、对手、比分。字写得很难看。"};}},
    {'label': "把这个球送出去", 'hint': "名气+", 'apply': function(){return{'fame':0x4,'text':"你把这个球签了名，寄给了一个正在住院的孩子。他后来把它带进了手术室。"};}}
  ]
},

// ---- idx:431 | mile_goal300 | 生涯第三百球 ----
{
  'id': "mile_goal300",
  'title': "生涯第三百球",
  'icon': '💯',
  'weight': 0x50,
  'when': function(p){return p["_mileG300"]!=null;},
  'desc': "第三百个进球。到这个数字，你的名字已经会被写进一些纪录的后面。你自己只记得那个球进得还算干净。",
  'options': [
    {'label': "把球衣送进博物馆", 'hint': "名气+", 'apply': function(){return{'fame':0x6,'text':"你把那件球衣送进了俱乐部的博物馆。展柜的标签上写着日期，还有一句：还在继续。"};}},
    {'label': "回家睡一觉", 'hint': "地位+", 'apply': function(){return{'roleDelta':0x1,'text':"你没有庆祝，回家睡了很久。第二天醒来，你先看了一眼赛程表。"};}}
  ]
},

// ---- idx:432 | mile_assist15 | 助攻大师 ----
{
  'id': "mile_assist15",
  'title': "助攻大师",
  'icon': '🪄',
  'weight': 0x50,
  'when': function(p){return p["_mileA15"]!=null;},
  'desc': "这个赛季你送出十五次助攻。有些球比你进的球更好看——那种把整条防线一剑剖开的传球。",
  'options': [
    {'label': "把传球做成教学视频", 'hint': "名气+", 'apply': function(){return{'fame':0x4,'text':"你把那些传球剪成了一个系列。后来很多孩子在球场上模仿那个动作，虽然大多数都传丢了。"};}},
    {'label': "感谢那些跑位的人", 'hint': "关系+", 'apply': function(){return{'guanxi':0x6,'text':"你在采访里说，助攻有一半是对面那些人的。跑位的人笑了，说下次你多传两个。"};}}
  ]
},

// ---- idx:433 | mile_assist100 | 第一百次助攻 ----
{
  'id': "mile_assist100",
  'title': "第一百次助攻",
  'icon': '🪄',
  'weight': 0x50,
  'when': function(p){return p["_mileA100"]!=null;},
  'desc': "职业生涯第一百次助攻。进球的人跑去庆祝了，你在中圈把球衣拉正，慢慢往回走。",
  'options': [
    {'label': "记住每一个接球的人", 'hint': "关系+", 'apply': function(){return{'guanxi':0x6,'text':"你能想起其中大部分人的名字，还有他们接球前的那个动作。你把这些写进了那本本子里。"};}},
    {'label': "什么也不说，继续踢", 'hint': "地位+", 'apply': function(){return{'roleDelta':0x1,'text':"你什么也没说。下一场比赛，你又送出了两次。"};}}
  ]
},

// ---- idx:434 | mile_cs100 | 第一百场零封 ----
{
  'id': "mile_cs100",
  'title': "第一百场零封",
  'icon': '🧱',
  'weight': 0x50,
  'when': function(p){return p["_mileCS100"]!=null;},
  'desc': "职业生涯第一百场零封。门前的那块草皮被你踩了十几年，比别人的都要秃一点。",
  'options': [
    {'label': "请后防线吃饭", 'hint': "关系+", 'apply': function(){return{'guanxi':0x8,'text':"你请整条后防线吃了饭。你说，这些零封有一半是他们的，剩下的一半是门柱的。"};}},
    {'label': "把第一个零封的球留下", 'hint': "名气+", 'apply': function(){return{'fame':0x2,'text':"你翻出了很多年前第一场零封时的比赛用球，把它和今天的摆在一起拍了张照。"};}}
  ]
},

// ---- idx:435 | mile_apps300 | 第三百场 ----
{
  'id': "mile_apps300",
  'title': "第三百场",
  'icon': '🧢',
  'weight': 0x50,
  'when': function(p){return p["_mileApps300"]!=null;},
  'desc': "职业生涯第三百次出场。你已经能凭脚步声判断是哪个队友在你身后。",
  'options': [
    {'label': "把每场都记下来", 'hint': "关系+", 'apply': function(){return{'guanxi':0x4,'text':"你翻出旧赛程，一场一场往回数。数到第一百场的时候，你停了很久。"};}},
    {'label': "只看下一场", 'hint': "地位+", 'apply': function(){return{'roleDelta':0x1,'text':"你没有回头看。第二天训练，你照旧第一个到。"};}}
  ]
},

// ---- idx:436 | mile_apps500 | 第五百场 ----
{
  'id': "mile_apps500",
  'title': "第五百场",
  'icon': '🧢',
  'weight': 0x50,
  'when': function(p){return p["_mileApps500"]!=null;},
  'desc': "第五百次出场。赛前热身的时候，你听见看台上有人在喊一个很久以前给你起的外号。",
  'options': [
    {'label': "朝那个看台挥手", 'hint': "关系+", 'apply': function(){return{'guanxi':0x6,'text':"你朝那个角落挥了挥手。喊声更大了，虽然你已经记不清那外号是怎么来的。"};}},
    {'label': "把它当成普通一场", 'hint': "地位+", 'apply': function(){return{'roleDelta':0x1,'text':"你把它当成普通一场。赛后的技术统计里，你跑了全队第二多。"};}}
  ]
},

// ---- idx:437 | mile_caps50 | 国家队五十场 ----
{
  'id': "mile_caps50",
  'title': "国家队五十场",
  'icon': '🧢',
  'weight': 0x50,
  'when': function(p){return p["_mileCap50"]!=null;},
  'desc': "第五十次为国出战。赛前奏国歌的时候，你跟着唱，唱到一半声音有点抖。",
  'options': [
    {'label': "把那件球衣装裱起来", 'hint': "关系+", 'apply': function(){return{'guanxi':0x6,'text':"你把第五十场的球衣装裱好，挂在了家里。你妈说，比奖杯好看。"};}},
    {'label': "把袖标戴紧一点", 'hint': "地位+", 'apply': function(){return{'roleDelta':0x1,'text':"你把袖标戴紧了一点。那场比赛，你在补时阶段还回追了四十米。"};}}
  ]
},

// ---- idx:438 | mile_caps100 | 国家队百场 ----
{
  'id': "mile_caps100",
  'title': "国家队百场",
  'icon': '🧢',
  'weight': 0x50,
  'when': function(p){return p["_mileCap100"]!=null;},
  'desc': "第一百次国家队出场。这个数字意味着你参加了这个国家十几年里几乎所有的正式比赛，包括那些没人愿意回忆的。",
  'options': [
    {'label': "把百场球衣留给国家队", 'hint': "关系+", 'apply': function(){return{'guanxi':0x8,'text':"你把百场球衣留给了国家队的荣誉室。挂上去的那天，你站在门口看了很久才走。"};}},
    {'label': "在赛后把话说重一点", 'hint': "名气+", 'apply': function(){return{'fame':0x4,'text':"你在赛后说，希望下一个一百场不用等这么久。这句话第二天上了所有体育版面。"};}}
  ]
},

// ---- idx:439 | mile_trophy10 | 第十座奖杯 ----
{
  'id': "mile_trophy10",
  'title': "第十座奖杯",
  'icon': '🥂',
  'weight': 0x50,
  'when': function(p){return p["_mileTr10"]!=null;},
  'desc': "职业生涯第十座奖杯。你数了数，有些在父母家，有些在俱乐部，有些你已经想不起放哪了。",
  'options': [
    {'label': "拍一张全家福", 'hint': "关系+", 'apply': function(){return{'guanxi':0x4,'text':"你把能找到的奖杯全摆在一起，拍了张照片。照片里少了两座——你后来找了很久也没找到。"};}},
    {'label': "把第10座送给启蒙教练", 'hint': "名气+", 'apply': function(){return{'fame':0x4,'text':"你把第十座送给了当年在体校门口把你留下的人。他说，早知道你要送我，我就挑个好看的。"};}}
  ]
},

// ---- idx:440 | mile_trophy20 | 第二十座奖杯 ----
{
  'id': "mile_trophy20",
  'title': "第二十座奖杯",
  'icon': '🥂',
  'weight': 0x50,
  'when': function(p){return p["_mileTr20"]!=null;},
  'desc': "第二十座。柜子早就放不下了，家里腾出了一间房。你妈每次擦灰都要抱怨，但每次都擦。",
  'options': [
    {'label': "专门做一面墙", 'hint': "关系+", 'apply': function(){return{'guanxi':0x4,'text':"你在家里做了一面墙，按年份把奖杯排好。排到最上面那层的时候，你发现自己已经要踩凳子了。"};}},
    {'label': "捐出一部分", 'hint': "名气+", 'apply': function(){return{'fame':0x6,'text':"你把早年的几座捐给了体校。校长说要单独开一间屋子放，你说，别开，就放在走廊里，让孩子天天经过。"};}}
  ]
},

// ---- idx:441 | mile_trophy30 | 第三十座奖杯 ----
{
  'id': "mile_trophy30",
  'title': "第三十座奖杯",
  'icon': '🥂',
  'weight': 0x50,
  'when': function(p){return p["_mileTr30"]!=null;},
  'desc': "第三十座。到这个数量，你已经不再一座一座地记了。你只记得那些输了、却没拿到的。",
  'options': [
    {'label': "开始想退役之后的事", 'hint': "关系+", 'apply': function(){return{'guanxi':0x4,'text':"你第一次认真地想了一下退役之后做什么。想了一晚上，没想出来。"};}},
    {'label': "把下一座定为目标", 'hint': "地位+", 'apply': function(){return{'roleDelta':0x1,'text':"你只跟经纪人说了四个字：还要再赢。"};}}
  ]
},

// ---- idx:442 | mile_earn1e8 | 亿元先生 ----
{
  'id': "mile_earn1e8",
  'title': "亿元先生",
  'icon': '💰',
  'weight': 0x50,
  'when': function(p){return p["_mileEarn"]!=null;},
  'desc': "职业生涯总收入过了一亿。你算了一下，从家里拿出那笔报名费算起，刚好够本。",
  'options': [
    {'label': "给家里换套房子", 'hint': "关系+", 'apply': function(){return{'guanxi':0x8,'text':"你给家里换了一套房子。你爸绕着小区走了三圈，最后只问了一句：物业费贵不贵。"};}},
    {'label': "投进青训", 'hint': "名气+", 'apply': function(){return{'fame':0x6,'text':"你拿出一部分钱，在老家的体校建了一块带灯光的小场地。牌子上没写你的名字，只写了一句话：晚上也可以练。"};}}
  ]
},

// ---- idx:443 | mile_streak20 | 三个二十球赛季 ----
{
  'id': "mile_streak20",
  'title': "三个二十球赛季",
  'icon': '🔥',
  'weight': 0x50,
  'when': function(p){return p["_mileStreak20"]!=null;},
  'desc': "连续三个赛季，联赛进球都在二十个以上。稳定性是最难的部分——单季爆发过的人很多，连着三年的人很少。",
  'options': [
    {'label': "把训练计划记下来", 'hint': "地位+", 'apply': function(){return{'roleDelta':0x1,'text':"你把自己的训练和恢复计划写了下来。后来队里很多年轻人来抄这份计划。"};}},
    {'label': "给自己放个假", 'hint': "关系+", 'apply': function(){return{'guanxi':0x4,'text':"赛季结束后你第一次真的放了假，关掉手机去了一个没有球场的地方。第三天你就开始看比赛了。"};}}
  ]
},

// ---- idx:444 | mile_clubs3 | 第三家俱乐部 ----
{
  'id': "mile_clubs3",
  'title': "第三家俱乐部",
  'icon': '🏙',
  'weight': 0x50,
  'when': function(p){return p["_mileClubs3"]!=null;},
  'desc': "第三家俱乐部。搬家公司的师傅已经认识你了，进门第一句话是：还是那些球鞋？",
  'options': [
    {'label': "每换一家就学当地话", 'hint': "关系+", 'apply': function(){return{'guanxi':0x6,'text':"你在新城市学了几句当地话。第一次在更衣室里说出来的时候，全队都笑了，然后有人教了你更难的。"};}},
    {'label': "只带一个箱子", 'hint': "地位+", 'apply': function(){return{'roleDelta':0x1,'text':"你只带了一个箱子来报到，当天下午就开始训练。教练说，就冲这个，你先发。"};}}
  ]
},

// ---- idx:445 | mile_first_cont | 洲际首冠 ----
{
  'id': "mile_first_cont",
  'title': "洲际首冠",
  'icon': '🌐',
  'weight': 0x50,
  'when': function(p){return p["_mileFirstCont"]!=null;},
  'desc': function(p){return "第一座"+p["_mileFirstCont"]+"。跨过整个大陆去打的那项赛事，你终于把它拿回来了。回程的飞机上，奖杯被所有人传着拍了一遍。";},
  'options': [
    {'label': "让奖杯坐在座位上", 'hint': "关系+", 'apply': function(){return{'guanxi':0x6,'text':"你把奖杯系上安全带放在了旁边的座位上，被空乘笑着拍了照。那张照片成了俱乐部那一年的年度图片。"};}},
    {'label': "落地就投入下一场", 'hint': "地位+", 'apply': function(){return{'roleDelta':0x1,'text':"落地当天你就去了训练场。教练问你奖杯呢，你说，在行李架里。"};}}
  ]
},

// ---- idx:446 | mile_first_cup | 第一座杯赛 ----
{
  'id': "mile_first_cup",
  'title': "第一座杯赛",
  'icon': '🏆',
  'weight': 0x50,
  'when': function(p){return p["_mileFirstCup"]!=null;},
  'desc': function(p){return "第一座"+p["_mileFirstCup"]+"。杯赛总是这样：一路磕磕绊绊，最后靠一场比赛定生死。那天你们运气不错。";},
  'options': [
    {'label': "承认运气不错", 'hint': "关系+", 'apply': function(){return{'guanxi':0x4,'text':"你在采访里承认了运气。对手的主教练后来在通道里跟你握了手，说：会这么说的赢家不多。"};}},
    {'label': "举着奖杯绕场", 'hint': "名气+", 'apply': function(){return{'fame':0x4,'text':"你举着奖杯绕场一周。看台上有一半是对方球迷，他们居然也鼓了掌。"};}}
  ]
},

// ---- idx:447 | mile_first_super | 第一座超级杯 ----
{
  'id': "mile_first_super",
  'title': "第一座超级杯",
  'icon': '🥇',
  'weight': 0x50,
  'when': function(p){return p["_mileFirstSuper"]!=null;},
  'desc': function(p){return "第一座"+p["_mileFirstSuper"]+"。新赛季的第一场正式比赛，只有一个冠军和一个亚军，没有平局。";},
  'options': [
    {'label': "把它当作赛季开始", 'hint': "地位+", 'apply': function(){return{'roleDelta':0x1,'text':"你没有多庆祝。你说，真正的赛季从下周开始，这只是一次热身。"};}},
    {'label': "把奖牌给看台上的孩子", 'hint': "关系+", 'apply': function(){return{'guanxi':0x6,'text':"你把奖牌摘下来，递给了看台第一排的一个孩子。他把它举过头顶，一整个下半场都没放下。"};}}
  ]
},

// ---- idx:448 | mile_first_youth | 青年队的冠军 ----
{
  'id': "mile_first_youth",
  'title': "青年队的冠军",
  'icon': '🎓',
  'weight': 0x50,
  'when': function(p){return p["_mileFirstYouth"]!=null;},
  'desc': function(p){return p["_mileFirstYouth"]+"。那时候你还穿大一号的球衣，领奖台上站着都比别人矮半个头。但你记得那天太阳很大。";},
  'options': [
    {'label': "记住那天的感觉", 'hint': "关系+", 'apply': function(){return{'guanxi':0x4,'text':"很多年以后你还记得那天。后来你拿过更大的冠军，却没有一次比那次更紧张。"};}},
    {'label': "从那天开始加倍练", 'hint': "地位+", 'apply': function(){return{'roleDelta':0x1,'text':"从那天起你把训练量加了一倍。教练说你终于像个想踢球的人了。"};}}
  ]
},

// ---- idx:449 | mile_league_boot | 联赛金靴 ----
{
  'id': "mile_league_boot",
  'title': "联赛金靴",
  'icon': '👟',
  'weight': 0x50,
  'when': function(p){return p["_mileLgBoot"]!=null;},
  'desc': function(p){return "第一座"+p["_mileLgBoot"]+"。这个奖不看你效力哪家俱乐部、也不看身价——只看谁把球送进网窝的次数最多。";},
  'options': [
    {'label': "把金靴摆进球鞋柜", 'hint': "关系+", 'apply': function(){return{'guanxi':0x4,'text':"你把金靴摆在了装备间最上层，和那些穿过很多年的球鞋放在一起。有人说那地方不配，你说配。"};}},
    {'label': "明年还要拿", 'hint': "名气+", 'apply': function(){return{'fame':0x4,'text':"你在采访里说，这不会只有一次。第二年的揭幕战，你进了两个。"};}}
  ]
},

// ---- idx:450 | mile_league_mvp | 联赛最佳 ----
{
  'id': "mile_league_mvp",
  'title': "联赛最佳",
  'icon': '🌟',
  'weight': 0x50,
  'when': function(p){return p["_mileLgMvp"]!=null;},
  'desc': function(p){return "第一座"+p["_mileLgMvp"]+"。这个奖是同行和记者投出来的，意思很直白：这个联赛今年最好的球员是你。";},
  'options': [
    {'label': "谢谢那些投你票的人", 'hint': "关系+", 'apply': function(){return{'guanxi':0x6,'text':"你谢了所有投票的人，包括那个一直批评你的记者。他后来写了篇文章说，这一票投得心服。"};}},
    {'label': "把它当成压力", 'hint': "地位+", 'apply': function(){return{'roleDelta':0x1,'text':"你把奖杯放在每天出门都能看见的地方。你说，看着它，就没法偷懒。"};}}
  ]
},

// ---- idx:451 | mile_ucl2 | 第二座欧冠 ----
{
  'id': "mile_ucl2",
  'title': "第二座欧冠",
  'icon': '🏆',
  'weight': 0x50,
  'when': function(p){return p["_mileUcl2"]!=null;},
  'desc': "第二座大耳朵杯。第一次是意外，第二次就不是了——别人开始把你所在的那支球队，当成每个赛季都要被讨论的对象。",
  'options': [
    {'label': "说这还不够", 'hint': "名气+", 'apply': function(){return{'fame':0x4,'text':"你在采访里说，第二座不是终点。这句话在对手的更衣室里贴了一个赛季。"};}},
    {'label': "把奖杯留在更衣室", 'hint': "关系+", 'apply': function(){return{'guanxi':0x6,'text':"你把奖杯留在了更衣室，让每个人轮流带回家一天。轮到清洁工阿姨那天，她发了张照片，配文是：终于摸到了。"};}}
  ]
},

// ---- idx:452 | mile_ucl5 | 第五座欧冠 ----
{
  'id': "mile_ucl5",
  'title': "第五座欧冠",
  'icon': '🏆',
  'weight': 0x50,
  'when': function(p){return p["_mileUcl5"]!=null;},
  'desc': "第五座。你把五座奖杯排成一排，数了两遍。很多球队一个世纪都没有五座。",
  'options': [
    {'label': "把其中一座还给俱乐部", 'hint': "关系+", 'apply': function(){return{'guanxi':0x8,'text':"你把其中一座还给了俱乐部，放在了大厅最显眼的位置。工作人员说，这地方从来只放历史。"};}},
    {'label': "拍一张五连的照片", 'hint': "名气+", 'apply': function(){return{'fame':0x6,'text':"你拍了那张照片。后来它被印在海报上，挂在了这座城市所有的地铁站。"};}}
  ]
},

// ---- idx:453 | mile_dom_treble | 国内三冠王 ----
{
  'id': "mile_dom_treble",
  'title': "国内三冠王",
  'icon': '🔱',
  'weight': 0x50,
  'when': function(p){return p["_mileDomTr"]!=null;},
  'desc': "联赛、杯赛、超级杯，一个赛季全拿了。国内的赛场，那一年没有别人什么事。",
  'options': [
    {'label': "把三座奖杯一次举起来", 'hint': "名气+", 'apply': function(){return{'fame':0x6,'text':"你在庆祝仪式上试着同时举起三座奖杯，举到一半差点掉下来。那张照片比奖杯本身有名。"};}},
    {'label': "把功劳分给所有人", 'hint': "关系+", 'apply': function(){return{'guanxi':0x8,'text':"你把三座奖杯依次递给了队长、门将和那个整个赛季只出场三次的替补。最后一座才轮到自己。"};}}
  ]
}

];
