// auto-generated by split_events.py - edit events here, then run build_events.py

var EVT_misc=[

// ---- idx:0 | extra_tr | ? ----
{
  'id': "extra_tr"+"aining",
  'title': '加练',
  'icon': '🏃',
  'weight': 0x5a,
  'repeat': 0x2,
  'desc': "队里加了一期封闭集训。名单贴出来的第二天，教练在更衣室堵住你，只问了一句话。",
  'options': [
    {
        'p': function(p){return f(0.7,[[p["talent"],1,0.4]],0.2,0.9);
},
        'label': "跟上强度",
        'hint': function(p,q){return g(q,'能力+4','能力-2');
},
        'apply': function(p,q,s){
return d(q,s)?{'ovr':0x4,'text':"一整期下来，体脂降了，触球也稳了。没有掌声，只是战术板上的那个十号位，笔画渐渐成了你的。"}:{'ovr':-0x2,'text':"第三周就练伤了。两个月病床把一切都换掉了——再回来，首发名单上没有你的名字。"};
}
    },
    {
        'label': "按计划来",
        'hint': "无变化",
        'apply': function(){
return{'text':"你按原计划走完了这一期。没有惊喜，也没有意外，一切照旧。"};
}
    }
  ]
},

// ---- idx:1 | nutritio | 营养师 ----
{
  'id': "nutritio"+"nist",
  'title': "营养师",
  'icon': '🥗',
  'weight': 0x46,
  'desc': "队医递来一份很难吃的食谱，说照着吃，能多踢三年。",
  'options': [
    {
        'p': function(p){return f(0.65,
[[p["talent"],1,0.4]],0.2,0.9);
},
        'label': "照着吃",
        'hint': function(p,q){return g(q,'能力+3','能力-1');
},
        'apply': function(p,q,s){
return d(q,s)?{'ovr':0x3,'text':"半年后，体能数据一路往上走。你也终于数得清水煮西兰花有几种做法了。"}:{'ovr':-0x1,'text':"六公斤说掉就掉，对抗也跟着没了。教练拍拍你的肩：先把肉吃回来。"};
}
    },
    {
        'label': "该吃吃",
        'hint': "无变化",
        'apply': function(){
return{'text':"你照旧吃你的。队医摇摇头，那份食谱落到了别人手里。"};
}
    }
  ]
},

// ---- idx:2 | suppleme | 来路不明的补剂 ----
{
  'id': "suppleme"+'nt',
  'title': "来路不明的补剂",
  'icon': '💊',
  'weight': 0x28,
  'desc': "有人塞给你两瓶看不出名堂的胶囊，压低声音：「队里好几个都在吃，查不出来的。」",
  'options': [
    {
        'p': function(p){return f(0.72,
[[p["clean"],70,0.008]],0.2,0.9);
},
        'label': "吃下去",
        'hint': function(p,q){return g(q,'能力+6','禁赛+清白重创');
},
        'apply': function(p,q,s){
return d(q,s)?{'ovr':0x6,'clean':-0xc,'text':"体能确实上了一个台阶。那两瓶东西是什么，你一次也没再问。"}:{'ovr':-0x3,'clean':-0x19,'ban':0x1,'fame':-0x14,
'text':"赛后抽检，阳性。禁赛通告贴出来那天你才明白，「查不出来」是一句安慰话。"};
}
    },
    {
        'label': '扔了',
        'hint': "清白+5",
        'apply': function(){
return{'clean':0x5,'text':"胶囊进了马桶。塞给你的人，后来再没来找过你。"};
}
    }
  ]
},

// ---- idx:3 | load | 赛季负荷 ----
{
  'id': "load",
  'title': "赛季负荷",
  'icon': '📅',
  'weight': 0x41,
  'repeat': 0x2,
  'stage': "prime",
  'desc': "赛程密到一周三赛。队医让你轮休，主教练点名要你场场首发。两个人都在等你表态。",
  'options': [
    {
        'p': function(p){return f(0.68,[[p["ovr"],60,0.008]],0.2,0.9);
},
        'label': "场场都上",
        'hint': function(p,q){return g(q,'地位提升','受伤');
},
        'apply': function(p,q,s){
return d(q,s)?{'roleDelta':0x1,'fame':0x6,'text':"你把这一期全踢满了。更衣室里再没人敢问谁是主力。"}:{'ovr':-0x4,'roleDelta':-0x1,'text':"第 31 轮，没有对抗，你倒了下去。医生写下两个字：积劳。"};
}
    },
    {
        'label': "听队医的",
        'hint': "地位下降，能力+"+'2',
        'apply': function(){
return{'roleDelta':-0x1,'ovr':0x2,'text':"比赛少了一半，身体是保住了。等回来，位置已经不是你的了。"};
}
    }
  ]
},

// ---- idx:4 | position | 位置改造 ----
{
  'id': "position"+"_change",
  'title': "位置改造",
  'icon': '🔄',
  'weight': 0x37,
  'when': function(p){
return'gk'!==p["posGroup"];
},
  'desc': "主教练把你叫到办公室，希望你去踢另一个位置，「那里更需要你」。",
  'options': [
    {
        'label': "改位置",
        'hint': "首发有保障，但能"+"力短期-2",
        'apply': function(){
return{'ovr':-0x2,'roleDelta':0x1,'text':"新位置踢得别扭，可每场都有你的名字。习惯之后你才发现，这位置像是为你留的。"};
}
    },
    {
        'label': '不改',
        'hint': "出场时间下降",
        'apply': function(){
return{'roleDelta':-0x1,'text':"你守住了自己的位置。教练也守住了他的用人。两个人都很硬。"};
}
    }
  ]
},

// ---- idx:5 | competit | 有人来抢位置 ----
{
  'id': "competit"+"ion",
  'title': "有人来抢位置",
  'icon': '⚔️',
  'weight': 0x3c,
  'repeat': 0x2,
  'when': function(p){
return p["roleRank"]<=0x3;
},
  'desc': "{club}花大价钱买下一个跟你同位置的球员。发布会上，他被称作「体系升级的关键一环」。",
  'options': [
    {
        'p': function(p){return f(0.5,[[p["ovr"],60,0.008]],0.2,0.9);
},
        'label': "跟他争",
        'hint': function(p,q){return g(q,'地位提升','沦为轮换');
},
        'apply': function(p,q,s){
return d(q,s)?{'roleDelta':0x1,'ovr':0x2,'fame':0x8,'text':('gk'===p["posGroup"]?"热身赛你零封了两"+"场，他漏了三个":"def"===p["posGroup"]?"热身赛你那一侧一"+"次没被打穿":"热身赛你进了两个"+"，他一个没进")+("。首发名单上还是"+"你的名字。")}:{'roleDelta':-0x2,
'text':"他的转会费是你的十倍，教练没有理由不用他。你开始熟悉替补席的温度。"};
}
    },
    {
        'label': "找机会走人",
        'hint': "本期结束后离队",
        'apply': function(){
return{'leave':!0x0,'text':"你让经纪人放话出去：想踢球，哪里都行，就是不留下。"};
}
    }
  ]
},

// ---- idx:6 | competit | 队里买了替身 ----
{
  'id': "competit"+"ion_star",
  'title': "队里买了替身",
  'icon': '🧩',
  'weight': 0x34,
  'repeat': 0x2,
  'when': function(p){
return p["roleRank"]>=0x4;
},
  'desc': "{club}签下一个和你同位置的年轻人。发布会上，教练把话挑明：「买他，是让核心少踢十场，不是要取代谁。」",
  'options': [
    {
        'label': "让出杯赛和垃圾时"+'间',
        'hint': "少踢一点，保住身"+'体',
        'apply': function(){
return{'ovr':0x2,'roleDelta':-0x1,'fame':0x3,'text':"一个赛季，你少踢了九场，全是输赢已定的那种。三月的密集赛程，队里唯一没拉伤的主力，是你。"};
}
    },
    {
        'p': function(p){return f(0.6,[[p["ovr"],60,0.008]],0.2,0.9);
},
        'label': "一场都不让",
        'hint': "场次拉满，但风险"+"自己扛",
        'odds': ["扛住了","扛不住"],
        'apply': function(p,q,s){
return d(q,s)?{'fame':0xa,'roleDelta':0x1,'text':"那个赛季的每一分钟你都踢满了。四百分钟，是他一年的全部上场时间。赛季结束，他转会走了。"}:{'ovr':-0x3,'roleDelta':-0x1,
'text':"四月，你的大腿后侧终于响了一声。最后八轮你躺着看完，那八轮，全是他踢的。"};
}
    }
  ]
},

// ---- idx:7 | prospect | 小孩上来了 ----
{
  'id': "prospect",
  'title': "小孩上来了",
  'icon': '🌱',
  'weight': 0x2d,
  'stage': "vet",
  'when': function(p){
return p["roleRank"]<=0x3;
},
  'desc': "青训提上来一个 18 岁的孩子，踢你的位置。训练里他压得你抬不起头，记者已经在写他的稿子了。",
  'options': [
    {
        'label': '带他',
        'hint': "球队夺冠概率翻倍"+"，自己地位下降",
        'apply': function(){
return{'roleDelta':-0x1,'mult':{'league':0x2,'cup':0x2},'fame':0x5,'text':"你把自己会的全教给了他。赛季末，最佳新人的获奖感言里，第一个念的是你的名字。"};
}
    },
    {
        'p': function(p){return f(0.5,[[p["ovr"],60,0.008]],0.2,0.9);
},
        'label': "压着他",
        'hint': function(p,q){return g(q,'保住位置','更衣室失分');
},
        'apply': function(p,q,s){
return d(q,s)?{'roleDelta':0x1,'text':"你用状态说话，把他按回替补席。教练说，老将还是靠得住。"}:{'roleDelta':-0x2,'fame':-0x8,'text':"队里传开你排挤新人的说法。教练两个都不用了，先抬出第三个。"};
}
    }
  ]
},

// ---- idx:8 | captain | 队长袖标 ----
{
  'id': "captain",
  'title': "队长袖标",
  'icon': "🎖️",
  'weight': 0x28,
  'stage': "prime",
  'when': function(p){
return p["roleRank"]>=0x3&&p["seasonsA"+"tClub"]>=0x2&&p["ovr"]>=0x32+0x4*(p["clubRep"]||0x0)&&(p["capDone"]||[])["indexOf"](p["teamId"])<0x0;
},
  'desc': "老队长走了。袖标在几个人之间传了一圈，教练单独问你：愿不愿意。",
  'options': [
    {
        'p': function(p){return f(0.65,[[p["guanxi"],45,0.008]],0.2,0.9);
},
        'label': "接下",
        'hint': "名气+，但责任也"+'大',
        'odds': ["带得住","扛不住"],
        'apply': function(p,q,s){
return d(q,s)?{'fame':0xf,'roleDelta':0x1,'captain':!0x0,'text':"袖标戴上了。输球以后，你开始学着自己先走向看台。"}:{'fame':-0x6,'ovr':-0x1,'captain':!0x0,
'text':"带队成绩不好，炮火全冲着袖标来。你这才掂出它的分量。"};
}
    },
    {
        'label': "让给别人",
        'hint': "无变化",
        'apply': function(){
return{'capDecline':!0x0,'text':"你说，还是专心踢球吧。教练点点头，再没提过袖标。"};
}
    }
  ]
},

// ---- idx:9 | coach_ch | ? ----
{
  'id': "coach_ch"+"ange",
  'title': '换帅',
  'icon': '📋',
  'weight': 0x37,
  'repeat': 0x3,
  'desc': "{club}中途换帅。新教练第一堂课，就把所有人的位置重新洗了一遍。",
  'options': [
    {
        'p': function(p){return f(0.55,[[p["ovr"],60,0.008]],0.2,0.9);
},
        'label': "适应他的体系",
        'hint': function(p,q){return g(q,'地位提升','下降');
},
        'apply': function(p,q,s){
return d(q,s)?{'roleDelta':0x1,'ovr':0x1,'text':"新体系反而更适合你。发布会上，新帅当众点了你的名字，夸的是你的跑动。"}:{'roleDelta':-0x1,'text':"你不在他的计划里"+"。他甚至叫不全你"+"的名字。"};
}
    }
  ]
},

// ---- idx:10 | rival_of | 死敌的报价 ----
{
  'id': "rival_of"+"fer",
  'title': "死敌的报价",
  'icon': '🔥',
  'weight': 0x46,
  'stage': "prime",
  'desc': "{rival}想签你。钱和荣誉都更多，代价是穿上这座城里最不该穿的那件球衣。",
  'options': [
    {
        'label': "就去",
        'hint': "转会至{riva"+"l}，夺冠概率提"+"升，名气受损",
        'apply': function(p){
return{'transferTo':p["rivalId"],'fame':-0x12,'mult':{'league':1.8,'cont':1.8},'text':"你走了。老东家的球迷在你家楼下拉起横幅，没有一个脏字，每个字都很脏。"};
}
    },
    {
        'label': '留下',
        'hint': "地位巩固，名气+",
        'apply': function(){
return{'fame':0xe,'roleDelta':0x1,'text':"采访里你说了句「我不会走」。后来，这句话被印上看台的横幅。"};
}
    }
  ]
},

// ---- idx:11 | crisis | 球队掉队了 ----
{
  'id': "crisis",
  'title': "球队掉队了",
  'icon': '📉',
  'weight': 0x32,
  'when': function(p){
return p["clubRep"]<=0x2;
},
  'desc': "{club}半个赛季只赢了两场，保级区就在脚边。已经有别的队来打听你。",
  'options': [
    {
        'label': "留下来打保级",
        'hint': "夺冠概率归零，名"+'气+',
        'apply': function(){
return{'fame':0xc,'mult':{'league':0x0,'cup':0.5},'text':"你留下了，最后一轮打进保级的关键球。这个赛季你什么也没拿到，除了球迷的记性。"};
}
    },
    {
        'label': "离开",
        'hint': "本期结束后离队",
        'apply': function(){
return{'leave':!0x0,'fame':-0x8,'text':"球队最难的时候，你递上了转会申请。这件事，会被人记很久。"};
}
    }
  ]
},

// ---- idx:12 | crisis_b | 掉出争冠圈 ----
{
  'id': "crisis_b"+'ig',
  'title': "掉出争冠圈",
  'icon': '📉',
  'weight': 0x32,
  'when': function(p){
return p["clubRep"]>=0x3;
},
  'desc': "{club}三连败，榜首已经看不见了。主帅下课的消息一天一个版本，更衣室裂成两派。",
  'options': [
    {
        'label': "站出来扛",
        'hint': "夺冠概率减半，名"+'气+',
        'apply': function(){
return{'fame':0xe,'mult':{'league':0.4,'cup':1.2},'text':"发布会上你把话说死：成绩是全队的事。那半个赛季你场场首发。球队终究没追上，但再没人提更衣室。"};
}
    },
    {
        'label': "别掺和",
        'hint': "无变化",
        'apply': function(){
return{'text':"你什么都没说。主帅走的那天，你站在训练场，隔着玻璃看他把东西一件件搬上车。"};
}
    },
    {
        'label': "让经纪人放风",
        'hint': "本期结束后离队，"+"名气-",
        'apply': function(){
return{'leave':!0x0,'fame':-0x8,'text':"「这样的球队配不上他」。这句话见报的第二天，看台有人打出你的名字，是骂的。"};
}
    }
  ]
},

// ---- idx:13 | renew | 续约谈判 ----
{
  'id': "renew",
  'title': "续约谈判",
  'icon': '✍️',
  'weight': 0x32,
  'stage': "prime",
  'when': function(p){
return p["seasonsA"+"tClub"]>=0x3;
},
  'desc': "合同还剩一年。俱乐部给的报价比你预期的低一截，经纪人说，可以耗一耗。",
  'options': [
    {
        'label': "签字",
        'hint': "地位稳固，收入一"+'般',
        'apply': function(p){
return{'money':0x64+0x4*p["ovr"],'roleDelta':0x1,'text':"你签了。数字不好看，但你不用再想住哪儿，孩子上哪所学校。"};
}
    },
    {
        'p': function(p){return f(0.6,[[p["ovr"],60,0.008]],0.2,0.9);
},
        'label': "耗到自由身",
        'hint': function(p,q){return g(q,'大合同','无人问津');
},
        'apply': function(p,q,s){
return d(q,s)?{'money':0x190+0x7*p["ovr"],'leave':!0x0,'text':"自由身换来一份翻倍的合同。经纪人这次赌对了。"}:{'money':-0x3c,'roleDelta':-0x2,'text':"耗到最后没人接盘。俱乐部把你晾在替补席，等你自降身价。"};
}
    }
  ]
},

// ---- idx:14 | return_h | 家里来电话 ----
{
  'id': "return_h"+"ome",
  'title': "家里来电话",
  'icon': '🏠',
  'weight': 0x28,
  'stage': "prime",
  'when': function(p){
return!p["inChina"];
},
  'desc': "父母年纪大了，电话里总问你什么时候回去踢。国内的报价也一直没断过。",
  'options': [
    {
        'label': '回国',
        'hint': "回中超，收入大增"+"，能力停滞",
        'apply': function(){
return{'returnHome':!0x0,'money':0xb4,'ovr':-0x2,'text':"回国的第一场，全场喊你的名字。这种感觉，你很久没有过了。"};
}
    },
    {
        'label': "再撑几年",
        'hint': "能力+2，家庭关"+"系受损",
        'apply': function(){
return{'ovr':0x2,'fame':-0x3,'text':"你留下了。那年春节又没回去，视频里母亲把手机举得很近，想让你看清楚桌上的菜。"};
}
    }
  ]
},

// ---- idx:15 | red_card | 争议红牌 ----
{
  'id': "red_card",
  'title': "争议红牌",
  'icon': '🟥',
  'weight': 0x2d,
  'repeat': 0x2,
  'desc': "中圈，你铲倒了对方核心，主裁掏出红牌。慢镜头回放，那是个五五开的球。",
  'options': [
    {
        'label': '认了',
        'hint': "停赛 2 场",
        'apply': function(){
return{'banGames':0x2,'text':"你没上诉。停赛的两场，你坐在看台，散场了才走。"};
}
    },
    {
        'label': "赛后开炮",
        'hint': "名气+，停赛加到"+" 4 场",
        'apply': function(){
return{'banGames':0x4,'fame':0xf,'guanxi':-0xa,'text':"你在混合区说了句「这哨子该查查」。这句话被全网炒了两天，追加停赛两场。"};
}
    }
  ]
},

// ---- idx:16 | statemen | 话说重了 ----
{
  'id': "statemen"+'t',
  'title': "话说重了",
  'icon': '🎤',
  'weight': 0x2d,
  'repeat': 0x2,
  'desc': "输球后的采访里，你说了句「有些人根本不想赢」。第二天，全网都在猜你说的是谁。",
  'options': [
    {
        'label': '道歉',
        'hint': "地位下降",
        'apply': function(){
return{'roleDelta':-0x1,'fame':-0x5,'text':"俱乐部替你写了一份声明。你照着念完了，没有抬头。"};
}
    },
    {
        'label': "不撤回",
        'hint': "名气+，更衣室关"+"系恶化",
        'apply': function(){
return{'fame':0x14,'roleDelta':-0x2,'guanxi':-0xa,'text':"你一个字都没收回。球迷说你敢讲真话，更衣室说你难相处。两边都对。"};
}
    }
  ]
},

// ---- idx:17 | sponsor | 代言找上门 ----
{
  'id': "sponsor",
  'title': "代言找上门",
  'icon': '💼',
  'weight': 0x2d,
  'stage': "prime",
  'when': function(p){
return p["fame"]>=0x2d;
},
  'desc': "一个运动品牌想签你。合同金额比半年工资还高，条件是拍一支很尬的广告。",
  'options': [
    {
        'label': "签字",
        'hint': "收入大增，名气+",
        'apply': function(p){
return{'money':0xfa+0x5*p["fame"],'fame':0xa,'ovr':-0x1,'text':"广告播出后，你在超市被认出来三次。那句台词，队友学了一整个赛季。"};
}
    },
    {
        'label': '拒了',
        'hint': "专心踢球，能力+"+'2',
        'apply': function(){
return{'ovr':0x2,'text':"你说，时间要留给训练。品牌方找了别人，那支广告后来还挺火。"};
}
    }
  ]
},

// ---- idx:18 | nightlif | 夜里被拍到了 ----
{
  'id': "nightlif"+'e',
  'title': "夜里被拍到了",
  'icon': '🌃',
  'weight': 0x28,
  'stage': "prime",
  'desc': "赛季中，你在酒吧的照片被人挂到网上，配文写着「{club} 的人凌晨三点仍在」。",
  'options': [
    {
        'label': "承认，接受罚款",
        'hint': "收入-，名气小损",
        'apply': function(){
return{'money':-0x5a,'fame':-0x8,'text':"内部罚款的通报贴在更衣室门口。每天进出，你都要看它一眼。"};
}
    },
    {
        'p': function(p){return f(0.5,[[p["clean"],70,0.008]],0.2,0.9);
},
        'label': "说是旧照",
        'hint': function(p,q){return g(q,'蒙混过关','被扒');
},
        'apply': function(p,q,s){
return d(q,s)?{'text':"这事三天就翻篇了。网上永远有下一个该骂的人。"}:{'fame':-0x16,'roleDelta':-0x1,'clean':-0x5,'text':"有人放出带日期的原图。你没洗白，身上多了一张「不诚实」的标签。"};
}
    }
  ]
},

// ---- idx:19 | nt_confl | 俱乐部不放人 ----
{
  'id': "nt_confl"+"ict",
  'title': "俱乐部不放人",
  'icon': '🛫',
  'weight': 0x2d,
  'repeat': 0x2,
  'stage': "prime",
  'when': function(p){
return p["caps"]>=0x1;
},
  'desc': "国家队要集训，俱乐部拿伤病报告压着不放人。两边都给你打了电话。",
  'options': [
    {
        'label': "去国家队",
        'hint': "征召稳固，队内地"+"位受损",
        'apply': function(){
return{'guanxi':0xc,'roleDelta':-0x1,'fame':0xa,'text':"你自己买了机票飞过去。下一场的大名单上，你的名字被划掉了。"};
}
    },
    {
        'label': "留在俱乐部",
        'hint': "地位稳固，国字号"+"机会下降",
        'apply': function(){
return{'guanxi':-0xf,'roleDelta':0x1,'text':"你留下了。名单公布那天，评论区有人说你「心里没有国家」。"};
}
    }
  ]
},

// ---- idx:20 | injury_p | 最不该受伤的时候 ----
{
  'id': "injury_p"+"eak",
  'title': "最不该受伤的时候",
  'icon': '🩹',
  'weight': 0x23,
  'repeat': 0x2,
  'stage': "prime",
  'when': function(p){
return p["ovr"]>=0x48;
},
  'desc': "膝盖里积了水，队医说打一针就能上，可打完这一针，可能得歇半年。前面就是决赛。",
  'options': [
    {
        'label': "打针上场",
        'hint': "夺冠概率大增，能"+"力-4",
        'apply': function(){
return{'ovr':-0x4,'mult':{'league':2.5,'cup':0x3,'cont':2.5},'fame':0x12,'text':"你打完了那场比赛。捧杯的时候，你连蹲下都要人扶。"};
}
    },
    {
        'label': '养伤',
        'hint': "夺冠概率降低，能"+"力保住",
        'apply': function(){
return{'mult':{'league':0.4,'cup':0.4,'cont':0.4},'text':"你在看台上看完了那场决赛。膝盖是保住了，可别的，什么都没保住。"};
}
    }
  ]
},

// ---- idx:21 | tattoo | ? ----
{
  'id': "tattoo",
  'title': '纹身',
  'icon': "🖋️",
  'weight': 0x19,
  'desc': "你想在小臂上纹一整片图案。有人提醒你，有些场合会要你穿长袖。",
  'options': [
    {
        'label': "纹上",
        'hint': "名气+，关系-",
        'apply': function(){
return{'fame':0xc,'guanxi':-0x8,'text':"图案确实好看。可从那以后，每次电视转播，你都得贴上肉色胶布。"};
}
    },
    {
        'label': '算了',
        'hint': "无变化",
        'apply': function(){
return{'text':"你把那张图打印出来，贴在衣柜门上，一贴就是好几年。"};
}
    }
  ]
},

// ---- idx:22 | study | 把书念完 ----
{
  'id': "study",
  'title': "把书念完",
  'icon': '📚',
  'weight': 0x19,
  'stage': "youth",
  'desc': "俱乐部跟学校合开了一个班，可以边踢球边把学历念完，代价是挤占训练时间。",
  'options': [
    {
        'label': "读书",
        'hint': "能力-1，退役后"+"有出路",
        'apply': function(){
return{'ovr':-0x1,'clean':0x5,'degree':!0x0,'text':"你成了队里少数几个能读懂合同条款的人。这件事的价值，要很多年以后才显现。"};
}
    },
    {
        'label': "全力踢球",
        'hint': "能力+2",
        'apply': function(){
return{'ovr':0x2,'text':"你把所有时间都交给了足球。这个年纪，这是最容易做、也最难的选择。"};
}
    }
  ]
},

// ---- idx:23 | language | 语言关 ----
{
  'id': "language",
  'title': "语言关",
  'icon': "🗣️",
  'weight': 0x37,
  'when': function(p){
return!p["inChina"]&&p["seasonsA"+"broad"]<=0x3;
},
  'desc': "战术会上，教练讲了二十分钟，你只听懂了三句。翻译不在，所有人都在等你开口。",
  'options': [
    {
        'label': "下苦功学",
        'hint': "能力+3，地位提"+'升',
        'apply': function(){
return{'ovr':0x3,'roleDelta':0x1,'text':"半年后，你已能在更衣室里开玩笑了。融进去以后，球也踢开了。"};
}
    },
    {
        'label': "靠翻译",
        'hint': "地位下降",
        'apply': function(){
return{'roleDelta':-0x1,'text':"翻译不能替你上场。比赛里那几次跑位失误，都是因为没听见喊声。"};
}
    }
  ]
},

// ---- idx:24 | homesick | 一个人的除夕 ----
{
  'id': "homesick",
  'title': "一个人的除夕",
  'icon': '🥟',
  'weight': 0x28,
  'when': function(p){
return!p["inChina"];
},
  'desc': "除夕夜，队里照常训练。你在出租屋煮了一锅速冻饺子，视频那头，家里正热闹。",
  'options': [
    {
        'label': "熬过去",
        'hint': "能力+2",
        'apply': function(){
return{'ovr':0x2,'text':"第二天，你照常出现在训练场，比所有人都早。有些东西，是熬出来的。"};
}
    },
    {
        'label': "找中介安排回国",
        'hint': "回中超，收入增加",
        'apply': function(){
return{'returnHome':!0x0,'money':0x1c2,'text':"你回来了。机场接机的人，比你在欧洲三年里见过的还多。"};
}
    }
  ]
},

// ---- idx:52 | late | ? ----
{
  'id': "late",
  'title': '迟到',
  'icon': '⏰',
  'weight': 0x37,
  'repeat': 0x2,
  'desc': "冬训第一天，你迟到了四十分钟。全队站在寒风里等你，教练一句话没说。",
  'options': [
    {
        'label': "公开道歉",
        'hint': "名气-，队内关系"+'回暖',
        'apply': function(){
return{'fame':-0x8,'roleDelta':0x1,'text':"队会上，你站起来说了对不起。老队员拍了拍你的背，这事就算翻篇了。"};
}
    },
    {
        'p': function(p){return f(0.5,[[p["clean"],70,0.008]],0.2,0.9);
},
        'label': "找借口",
        'hint': function(p,q){return g(q,'蒙混','被停训');
},
        'apply': function(p,q,s){
return d(q,s)?{'text':"你说路上出了车祸。没人去核实，也没人相信。"}:{'roleDelta':-0x2,'clean':-0x5,'text':"监控调出来了：九点，你的车还停在酒店门口。停训两周。"};
}
    }
  ]
},

// ---- idx:53 | coach_cl | 跟教练顶起来了 ----
{
  'id': "coach_cl"+"ash",
  'title': "跟教练顶起来了",
  'icon': '😠',
  'weight': 0x37,
  'repeat': 0x2,
  'stage': "prime",
  'desc': "半场被换下时，你把球衣摔在地上。摄像机全程跟着你。",
  'options': [
    {
        'label': "私下认错",
        'hint': "地位保住，名气-",
        'apply': function(){
return{'fame':-0xa,'roleDelta':0x1,'text':"你在教练办公室待了二十分钟。出来后没人再提这事，你也再没在半场被换下。"};
}
    },
    {
        'label': '不认',
        'hint': "球迷买账，教练不"+'用你',
        'apply': function(){
return{'fame':0x10,'roleDelta':-0x2,'text':"球迷夸你有血性。接下来的六轮，你在替补席上，看完了每一场。"};
}
    }
  ]
},

// ---- idx:54 | worldie | 世界波 ----
{
  'id': "worldie",
  'title': "世界波",
  'icon': '🎯',
  'weight': 0x32,
  'repeat': 0x2,
  'when': function(p){
return p["roleRank"]>=0x2&&'gk'!==p["posGroup"];
},
  'desc': "禁区外四十米，你抬头，看了一眼门将的站位。",
  'options': [
    {
        'p': function(p){return f(0.6,[[p["talent"],1,0.4]],0.2,0.9);
},
        'label': '抡',
        'hint': function(p,q){return g(q,'载入集锦','打飞看台');
},
        'apply': function(p,q,s){
return d(q,s)?{'fame':0x16,'ovr':0x2,'text':"球砸进死角。这一脚，被剪进了整个赛季所有集锦的片头。"}:{'fame':-0x6,'text':"球飞进看台第七排。解说只说了句：「这个选择值得商榷。」"};
}
    },
    {
        'label': '回传',
        'hint': "无变化",
        'apply': function(){
return{'text':"你把球回给后腰。正确的选择，往往也是没人会记得的选择。"};
}
    }
  ]
},

// ---- idx:55 | own_goal | 乌龙球 ----
{
  'id': "own_goal",
  'title': "乌龙球",
  'icon': '😵',
  'weight': 0x2d,
  'when': function(p){
return'gk'!==p["posGroup"];
},
  'desc': "解围，一脚把球捅进自家球门——偏偏还是德比。",
  'options': [
    {
        'p': function(p){return f(0.5,[[p["ovr"],60,0.008]],0.2,0.9);
},
        'label': '扛住',
        'hint': function(p,q){return g(q,'扳回来','状态崩');
},
        'apply': function(p,q,s){
return d(q,s)?{'ovr':0x2,'fame':0xa,'text':"下半场，你把球送进对方球门。赛后你说：「我欠球队一个。」"}:{'ovr':-0x3,'fame':-0xe,'text':"那之后几个月，你不敢再往前压。那脚球，在你脑子里循环了一整个赛季。"};
}
    }
  ]
},

// ---- idx:56 | teammate | 更衣室动手了 ----
{
  'id': "teammate"+"_fight",
  'title': "更衣室动手了",
  'icon': '🥊',
  'weight': 0x2d,
  'stage': "prime",
  'desc': "一次对抗，先是推搡，最后你们在更衣室里扭作一团。",
  'options': [
    {
        'label': "各打五十大板",
        'hint': "都被罚，名气-",
        'apply': function(){
return{'money':-0x28,'fame':-0x8,'roleDelta':-0x1,'text':"俱乐部各罚了一个月工资。赛季末你们握了手，只是从此，再没坐过同一桌。"};
}
    },
    {
        'label': "把责任揽下来",
        'hint': "破财，队内地位+",
        'apply': function(){
return{'money':-0x50,'roleDelta':0x1,'fame':-0x4,'text':"你说，是自己先动的手。后来队友在采访里提到你，说：这个人靠得住。"};
}
    }
  ]
},

// ---- idx:57 | father_i | 父亲住院了 ----
{
  'id': "father_i"+'ll',
  'title': "父亲住院了",
  'icon': '🏥',
  'weight': 0x2d,
  'desc': "赛季中段，家里来了电话：父亲要做手术，需要人守着。",
  'options': [
    {
        'label': "请假回去",
        'hint': "错过比赛，能力-",
        'apply': function(){
return{'ovr':-0x3,'roleDelta':-0x1,'money':-0x3c,'guanxi':0x4,'text':"你在病房陪了三周。回来时，联赛已过五轮，你的号码穿在别人身上。"};
}
    },
    {
        'label': "留队踢完",
        'hint': "保住位置，心里过"+'不去',
        'apply': function(){
return{'roleDelta':0x1,'fame':0x4,'ovr':-0x1,'text':"你留下了，那几场也踢得不错。父亲手术那天，你把手机关了九十分钟。"};
}
    }
  ]
},

// ---- idx:58 | agent_sw | 换经纪人 ----
{
  'id': "agent_sw"+"itch",
  'title': "换经纪人",
  'icon': '🤝',
  'weight': 0x2d,
  'stage': "prime",
  'desc': "一家大牌经纪公司找上门：能把你的身价翻一倍，前提是，和跟了你多年的老经纪人解约。",
  'options': [
    {
        'label': '换',
        'hint': "转会机会+，赔违"+'约金',
        'apply': function(p){
return{'money':-Math["max"](0x3c,0.12*p["money"]|0x0),'fame':0xa,'text':"违约金掏得肉疼。新公司能力确实更强——同时也代理着二十个，跟你抢位置的人。"};
}
    },
    {
        'label': '不换',
        'hint': "关系+",
        'apply': function(){
return{'guanxi':0x8,'fame':-0x3,'text':"老经纪人，是你十六岁那年就跟的。能力一般，可从没骗过你。"};
}
    }
  ]
},

// ---- idx:59 | relapse | 老伤复发 ----
{
  'id': "relapse",
  'title': "老伤复发",
  'icon': '🦯',
  'weight': 0x32,
  'repeat': 0x2,
  'stage': "prime",
  'when': function(p){
return p["age"]>=0x1b;
},
  'desc': "那个地方又疼了。核磁结果：老伤。医生说，要么保守，要么开刀。",
  'options': [
    {
        'label': "打封闭继续踢",
        'hint': "本期能踢，能力持"+"续下滑",
        'apply': function(){
return{'ovr':-0x4,'roleDelta':0x1,'text':"你靠封闭踢完了这一期。每场比赛，你都提前四十分钟进更衣室。"};
}
    },
    {
        'label': '开刀',
        'hint': "缺席一期，之后恢"+'复',
        'apply': function(){
return{'ovr':0x2,'roleDelta':-0x3,'text':"手术很成功，你也就此错过半年。回来时，身体是好的，位置是别人的。"};
}
    }
  ]
},

// ---- idx:60 | leader | 更衣室的话事人 ----
{
  'id': "leader",
  'title': "更衣室的话事人",
  'icon': '🗣',
  'weight': 0x28,
  'stage': "vet",
  'when': function(p){
return p["roleRank"]>=0x2;
},
  'desc': "老队长退役了。训练结束后，年轻人开始凑到你身边，问这问那。",
  'options': [
    {
        'label': "带他们",
        'hint': "球队更强，自己出"+'场少',
        'apply': function(){
return{'roleDelta':-0x1,'mult':{'league':1.7,'cup':1.7},'fame':0x8,'text':"你成了赛后第一个开口说话的人。数据不好看，可队伍立住了。"};
}
    },
    {
        'label': "先顾自己",
        'hint': "保住出场，队内孤"+'立',
        'apply': function(){
return{'roleDelta':0x1,'fame':-0x6,'text':"你把精力收回到自己身上。那些年轻人，后来去问别人了。"};
}
    }
  ]
},

// ---- idx:69 | visa | 劳工证 ----
{
  'id': "visa",
  'title': "劳工证",
  'icon': '🛂',
  'weight': 0x32,
  'when': function(p){
return!p["inChina"]&&p["seasonsA"+"broad"]<=0x2;
},
  'desc': "转会敲定了，可劳工证卡在国家队的出场次数上——你差三场。",
  'options': [
    {
        'label': "等下一个窗口",
        'hint': "空转半年",
        'apply': function(){
return{'ovr':-0x2,'roleDelta':-0x2,'text':"你在异国公寓里住了半年，每天跟着预备队。窗口开的那天，你的状态没了。"};
}
    },
    {
        'label': "先去别处过渡",
        'hint': "转去次级联赛",
        'apply': function(p){
return{'leave':!0x0,'ovr':0x1,'text':"你先去了隔壁联赛，踢了一年半。这条路很多人走过，走通的不多。"};
}
    }
  ]
},

// ---- idx:70 | fitness_ | 私人体能师 ----
{
  'id': "fitness_"+"coach",
  'title': "私人体能师",
  'icon': '⏱️',
  'weight': 0x3c,
  'repeat': 0x2,
  'desc': "队友介绍来一个体能师。一个冬训的报价，顶得上你两个月工资。",
  'options': [
    {
        'p': function(p){return f(0.75,[[p["talent"],1,0.4]],0.2,0.9);
},
        'label': "请他来",
        'hint': function(p,q){return g(q,'能力+5','练岔了');
},
        'apply': function(p,q,s){
return d(q,s)?{'money':-0x3c,'ovr':0x5,'text':"他把你的跑动一帧一帧拆开来看。三个月后，你觉得自己跑起来省劲了。"}:{'money':-0x3c,'ovr':-0x1,'text':"他那套练法和队里的大课撞在一起。你两边都没跟住，开季两个月都在找感觉。"};
}
    },
    {
        'label': "跟队练",
        'hint': "省钱，无变化",
        'apply': function(){
return{'text':"你跟着队里的大课练完了整个冬训。省下的钱，还躺在卡里。"};
}
    }
  ]
},

// ---- idx:71 | video_ro | 录像室 ----
{
  'id': "video_ro"+'om',
  'title': "录像室",
  'icon': "🎞️",
  'weight': 0x3a,
  'repeat': 0x2,
  'desc': "分析师把你半年的比赛剪成四十分钟，问你要不要每周留下来看一遍。",
  'options': [
    {
        'label': "留下来看",
        'hint': "能力+3，饭局都"+'推了',
        'apply': function(){
return{'ovr':0x3,'guanxi':-0x6,'text':"你这才发现，自己每次接球前都不回头。改掉这个习惯，花了半年。"};
}
    },
    {
        'label': '回家',
        'hint': "无变化",
        'apply': function(){
return{'text':"你说踢球靠感觉。"+"分析师没再问过第"+"二次。"};
}
    }
  ]
},

// ---- idx:72 | weak_foo | 另一只脚 ----
{
  'id': "weak_foo"+'t',
  'title': "另一只脚",
  'icon': '🦶',
  'weight': 0x37,
  'stage': "youth",
  'desc': "教练说你这只脚只能用来站着。要改，得从最基础的动作重新来一遍。",
  'options': [
    {
        'p': function(p){return f(0.6,[[p["talent"],1,0.4]],0.2,0.9);
},
        'label': "从头练",
        'hint': function(p,q){return g(q,'能力+6','别扭一整年');
},
        'apply': function(p,q,s){
return d(q,s)?{'ovr':0x6,'text':"半年后，你在训练赛里用左脚把球推入远角。那天，你自己都愣了一下。"}:{'ovr':-0x1,'roleDelta':-0x1,'text':"整整一年，你踢得像个新手。教练一度把你放回了替补。"};
}
    },
    {
        'label': "扬长避短",
        'hint': "无变化",
        'apply': function(){
return{'text':"你把右脚练得更好了。对手也很快知道，该往哪边逼你。"};
}
    }
  ]
},

// ---- idx:73 | growth_s | 窜个子 ----
{
  'id': "growth_s"+"purt",
  'title': "窜个子",
  'icon': '📏',
  'weight': 0x34,
  'stage': "youth",
  'desc': "一个夏天，你长了七公分。裤子短了一截，脚下的球也不太听话了。",
  'options': [
    {
        'p': function(p){return f(0.7,[[p["talent"],1,0.4]],0.2,0.9);
},
        'label': "加练协调性",
        'hint': function(p,q){return g(q,'能力+5','拉伤');
},
        'apply': function(p,q,s){
return d(q,s)?{'ovr':0x5,'text':"身体重新长回你自己的了，比以前高，也比以前快。"}:{'ovr':-0x2,'text':"长得太快，膝盖先"+"扛不住。队医让你"+"歇了两个月。"};
}
    },
    {
        'label': "等身体自己适应",
        'hint': "能力+1",
        'apply': function(){
return{'ovr':0x1,'text':"你等了一年。它确实自己长好了，只是那一年，白过了。"};
}
    }
  ]
},

// ---- idx:74 | street_b | 野球场 ----
{
  'id': "street_b"+"all",
  'title': "野球场",
  'icon': "🏙️",
  'weight': 0x32,
  'stage': "youth",
  'repeat': 0x2,
  'desc': "周末，有人喊你去公园的水泥地踢五人制。队规不让。",
  'options': [
    {
        'p': function(p){return f(0.7,[[p["talent"],1,0.4]],0.2,0.9);
},
        'label': "就去",
        'hint': function(p,q){return g(q,'能力+3','崴了脚');
},
        'apply': function(p,q,s){
return d(q,s)?{'ovr':0x3,'fame':0x4,'text':"小场地逼着你一秒之内做决定。回到队里再看十一人制，节奏慢得像放录像。"}:{'ovr':-0x2,'roleDelta':-0x1,'text':"你在水泥地上崴了脚。队里问你怎么伤的，你说不出口。"};
}
    },
    {
        'label': "老实待着",
        'hint': "无变化",
        'apply': function(){
return{'text':"你在宿舍躺了一天。手机里那群人，后来没再叫过你。"};
}
    }
  ]
},

// ---- idx:75 | foreign_ | 队里的外援 ----
{
  'id': "foreign_"+"star",
  'title': "队里的外援",
  'icon': '🌍',
  'weight': 0x37,
  'when': function(p){
return p["inChina"]&&p["clubRep"]>=0x2;
},
  'desc': "球队新签的外援，拿过欧冠。他每天提前四十分钟到训练场，一个人练。",
  'options': [
    {
        'p': function(p){return f(0.7,[[p["talent"],1,0.4]],0.2,0.9);
},
        'label': "跟着他练",
        'hint': function(p,q){return g(q,'能力+5','人家没搭理你');
},
        'apply': function(p,q,s){
return d(q,s)?{'ovr':0x5,'text':"他不太说中文，只是把动作做给你看。一个赛季下来，你偷学了不少。"}:{'ovr':0x1,'text':"他大概觉得你跟不"+"上。练了三次以后"+"，他换了个时间来"+'。'};
}
    },
    {
        'label': "按点上下班",
        'hint': "无变化",
        'apply': function(){
return{'text':"你按时到，也按时走。他后来去了日本，走之前没人送。"};
}
    }
  ]
},

// ---- idx:76 | summer_c | 自费夏训 ----
{
  'id': "summer_c"+"amp",
  'title': "自费夏训",
  'icon': '✈️',
  'weight': 0x30,
  'when': function(p){
return p["inChina"]&&p["age"]<=0x1b;
},
  'desc': "有中介能安排你去欧洲，跟一支二级联赛球队合练两个月，费用自理。",
  'options': [
    {
        'p': function(p){return f(0.75,[[p["talent"],1,0.4]],0.2,0.9);
},
        'label': "就去",
        'hint': function(p,q){return g(q,'能力+7','水土不服');
},
        'apply': function(p,q,s){
return d(q,s)?{'money':-0x82,'ovr':0x7,'fame':0x6,'text':"那边的对抗强度，不是一个量级。回来再踢国内比赛，你觉得自己有的是时间。"}:{'money':-0x82,'ovr':-0x1,
'text':"语言不通，饮食不惯，一场正式比赛都没捞着。两个月，只换来几段视频。"};
}
    },
    {
        'label': '不去',
        'hint': "无变化",
        'apply': function(){
return{'text':"你算了算钱，把机票退了。那个夏天，你在家乡的球场跑圈。"};
}
    }
  ]
},

// ---- idx:77 | analyst | 数据不会骗人 ----
{
  'id': "analyst",
  'title': "数据不会骗人",
  'icon': '📊',
  'weight': 0x30,
  'stage': "prime",
  'when': function(p){
return "att"===p["posGroup"]||"mid"===p["posGroup"];
},
  'desc': "分析师拿着一张热图来找你。今年你在禁区里的触球，比去年少了四成。",
  'options': [
    {
        'label': "照着改",
        'hint': "能力+3，踢得别"+'扭',
        'apply': function(){
return{'ovr':0x3,'fame':-0x4,'text':"你照着图跑位，一开始很难受。数据慢慢好看了，观众说你变木了。"};
}
    },
    {
        'p': function(p){return f(0.5,[[p["talent"],1,0.4]],0.2,0.9);
},
        'label': "凭感觉踢",
        'hint': function(p,q){return g(q,'能力+2','能力-2');
},
        'apply': function(p,q,s){
return d(q,s)?{'ovr':0x2,'fame':0x6,'text':"你说球是踢给人看的，不是给表格看的。那个赛季你进了十二个。"}:{'ovr':-0x2,'roleDelta':-0x1,'text':"第二年，热图更难看了。教练把你换到了他更放心的位置。"};
}
    }
  ]
},

// ---- idx:78 | psych | 去看心理医生 ----
{
  'id': "psych",
  'title': "去看心理医生",
  'icon': '🧠',
  'weight': 0x2d,
  'stage': "prime",
  'when': function(p){
return p["roleRank"]<=0x2;
},
  'desc': "连着几场丢球都跟你有关。你开始在赛前一晚醒着，数天花板。",
  'options': [
    {
        'label': "去谈谈",
        'hint': "花钱，能力+3",
        'apply': function(){
return{'money':-0x19,'ovr':0x3,'text':"她让你把每次失误写下来，写满一页就撕掉。三个月后，你能睡整觉了。"};
}
    },
    {
        'p': function(p){return f(0.5,[[p["fame"],25,0.01]],0.2,0.9);
},
        'label': "自己扛",
        'hint': function(p,q){return g(q,'扛过去了','越陷越深');
},
        'apply': function(p,q,s){
return d(q,s)?{'ovr':0x1,'text':"某个早上醒来，忽然就没事了。你也说不清是怎么好的。"}:{'ovr':-0x3,'roleDelta':-0x1,'text':"你越想踢好，越踢不好。那一年，录像你一次都没敢回看。"};
}
    }
  ]
},

// ---- idx:79 | body_mai | 三十岁以后的身体 ----
{
  'id': "body_mai"+"ntain",
  'title': "三十岁以后的身体",
  'icon': '🩺',
  'weight': 0x37,
  'stage': "vet",
  'desc': "队医给了两套方案。一套是保养着踢，一套是当没这回事。",
  'options': [
    {
        'label': "按方案保养",
        'hint': "少踢一些，能力+"+'3',
        'apply': function(){
return{'money':-0x28,'ovr':0x3,'roleDelta':-0x1,'text':"冷疗、按摩、忌口，一样不落。你少打了七八场，但四十岁那年，还在场上。"};
}
    },
    {
        'p': function(p){return f(0.6,[[p["ovr"],60,0.008]],0.2,0.9);
},
        'label': "当没这回事",
        'hint': function(p,q){return g(q,'硬扛住','伤病找上门');
},
        'apply': function(p,q,s){
return d(q,s)?{'fame':0x8,'text':"你还是场场首发。解说说，你是这支队伍最后一个老派球员。"}:{'ovr':-0x4,'text':"跟腱出了问题。医生说，这不是意外，是欠下的账，早晚要还。"};
}
    }
  ]
},

// ---- idx:82 | hat_tric | 帽子戏法 ----
{
  'id': "hat_tric"+'k',
  'title': "帽子戏法",
  'icon': '🎩',
  'weight': 0x32,
  'stage': "prime",
  'when': function(p){
return "att"===p["posGroup"]&&p["roleRank"]>=0x2;
},
  'desc': "上半场你已经进了两个。第三个球，看起来只是时间问题。",
  'options': [
    {
        'label': "接着抢点",
        'p': function(p){
return f(0.6,[[p["ovr"],0x44,0.007],[p["roleRank"],0x3,0.05]],0.35,0.85);
},
        'hint': function(p,q){
return g(q,'戴帽',"越位越到心态崩");
},
        'apply': function(p,q,s){
return d(q,s)?{'ovr':0x2,'fame':0x14,'text':"第 78 分钟，你抢到了第三个。队友把球捡起来塞给你，让你签名。"}:{'fame':-0x5,'text':"下半场你六次越位。解说说，你眼里只剩下那个数字了。"};
}
    },
    {
        'label': "把球让出去",
        'hint': "队内关系+，名气"+'-',
        'apply': function(){
return{'roleDelta':0x1,'guanxi':0x8,'fame':-0x4,'text':"点球你让给了状态低迷的队长。更衣室里没人说话，但从那天起，没人再说你自私。"};
}
    }
  ]
},

// ---- idx:167 | buyout_c | 解约金条款 ----
{
  'id': "buyout_c"+"lause",
  'title': "解约金条款",
  'icon': '📝',
  'weight': 0x34,
  'stage': "prime",
  'desc': "续约文本里有一条解约金条款。经纪人说，数字写低些，将来好走。",
  'options': [
    {
        'label': '写低',
        'hint': "工资少些，好脱身",
        'apply': function(){
return{'money':-0x3c,'lockAbroad':0x0,'ovr':0x1,'text':"俱乐部答应了，代价是工资折了一截。两年后，真有人按那个数字把你买走了。"};
}
    },
    {
        'p': function(p){return f(0.6,[[p["ovr"],60,0.008]],0.2,0.9);
},
        'label': "要高工资",
        'hint': function(p,q){return g(q,'值','被卡死');
},
        'apply': function(p,q,s){
return d(q,s)?{'money':0xc8,'text':"你拿到了队里第二"+"高的工资，踏踏实"+"实踢了三年。"}:{'money':0xc8,'roleDelta':-0x1,'lockAbroad':0x2,'text':"工资是高，可那个天价解约金，让每个来问价的球队都掉头走了。"};
}
    }
  ]
},

// ---- idx:168 | media_tr | 媒体培训 ----
{
  'id': "media_tr"+"aining",
  'title': "媒体培训",
  'icon': "🎙️",
  'weight': 0x30,
  'stage': "prime",
  'desc': "俱乐部请了人来教球员面对镜头：少说话、说套话、别接情绪。",
  'options': [
    {
        'label': "认真学",
        'hint': "名气稳，人变闷",
        'apply': function(){
return{'fame':-0x4,'guanxi':0xa,'clean':0x4,'text':"从此，你的采访没一句能上标题。俱乐部很满意，记者见你就绕道走。"};
}
    },
    {
        'p': function(p){return f(0.55,[[p["fame"],25,0.01]],0.2,0.9);
},
        'label': "有话直说",
        'hint': function(p,q){return g(q,'圈粉','惹祸');
},
        'apply': function(p,q,s){
return d(q,s)?{'fame':0x14,'text':"你那句「我们踢得不配拿工资」，当晚被顶上了热门榜第七。球迷说，这队总算有个说人话的。"}:{'fame':0x8,'guanxi':-0xe,'money':-0x1e,'text':"俱乐部内部通报批评，罚了你三十万。领队说你不懂事。"};
}
    }
  ]
},

// ---- idx:169 | boot_dea | 球鞋合同 ----
{
  'id': "boot_dea"+'l',
  'title': "球鞋合同",
  'icon': '👞',
  'weight': 0x32,
  'stage': "prime",
  'desc': "两家品牌找上门：一家钱多，鞋却不合脚；一家钱少，但按你的脚做楦。",
  'options': [
    {
        'p': function(p){return f(0.6,[[p["fame"],25,0.01]],0.2,0.9);
},
        'label': '要钱',
        'hint': function(p,q){return g(q,'没事','脚伤');
},
        'odds': ["脚没事","脚废了"],
        'apply': function(p,q,s){
return d(q,s)?{'money':0xb4,'fame':0x8,'text':"你穿着那双不太跟脚的鞋踢了三年，钱进了账。"}:{'money':0xb4,'ovr':-0x3,'text':"跖骨疲劳性骨折。医生的第一句话，是问你的鞋码。"};
}
    },
    {
        'label': "要定制",
        'hint': "钱少，能力+2",
        'apply': function(){
return{'money':0x28,'ovr':0x2,'text':"他们给你做了六双楦头不同的鞋。那两年，你一次脚伤都没犯过。"};
}
    }
  ]
},

// ---- idx:170 | play_inj | 带伤上阵 ----
{
  'id': "play_inj"+"ured",
  'title': "带伤上阵",
  'icon': '💉',
  'weight': 0x37,
  'stage': "prime",
  'repeat': 0x2,
  'desc': "关键战前一天，队医说：打一针就能上，但赛季可能就交代了。",
  'options': [
    {
        'p': function(p){return f(0.6,[[p["ovr"],60,0.008]],0.2,0.9);
},
        'label': "打针上场",
        'hint': function(p,q){return g(q,'英雄','赛季报销');
},
        'apply': function(p,q,s){
return d(q,s)?{'fame':0x14,'roleDelta':0x1,'mult':{'league':1.4},'text':"你踢满九十分钟。赛后，被人架着走出更衣室。那场球，赢了。"}:{'ovr':-0x5,'roleDelta':-0x1,
'text':"第 26 分钟，你自己倒下了。半月板。赛季，到此为止。"};
}
    },
    {
        'label': '不上',
        'hint': "关系-，身体保住",
        'apply': function(){
return{'guanxi':-0xa,'roleDelta':-0x1,'ovr':0x1,'text':"你在看台上看完了那场球。队里输了，有人在群里说：「有些人，爱惜羽毛。」"};
}
    }
  ]
},

// ---- idx:171 | system_c | 体系换了 ----
{
  'id': "system_c"+"hange",
  'title': "体系换了",
  'icon': '♟️',
  'weight': 0x34,
  'stage': "prime",
  'repeat': 0x2,
  'desc': "新帅带来的踢法完全换了套。你练了多年的本事，在战术板上找不到一格。",
  'options': [
    {
        'label': "改自己",
        'p': function(p){
return f(0.7,[[p["age"],0x1b,-0.035],[p["ovr"],0x46,0.004]],0.3,0.88);
},
        'hint': function(p,q){
return g(q,"能力+4","四不像");
},
        'apply': function(p,q,s){
return d(q,s)?{'ovr':0x3,'roleDelta':0x1,'text':"花了大半年，你把自己拆开重装。回头看，那半年值。"}:{'ovr':-0x3,'roleDelta':-0x1,'text':"新的没学会，老的丢干净了。你成了人们口中「以前挺好的」那种球员。"};
}
    },
    {
        'p': function(p){return f(0.5,[[p["ovr"],60,0.008]],0.2,0.9);
},
        'label': "等他下课",
        'hint': function(p,q){return g(q,'熬走了','先被熬走');
},
        'apply': function(p,q,s){
return d(q,s)?{'roleDelta':0x1,'text':"他只撑了半年就离任。新来的教练，打法像是照着你写的。"}:{'roleDelta':-0x2,'leave':!0x0,'text':"他在位三年，你在第二年冬天，上了挂牌名单。"};
}
    }
  ]
},

// ---- idx:172 | family_m | 举家搬迁 ----
{
  'id': "family_m"+"ove",
  'title': "举家搬迁",
  'icon': '📦',
  'weight': 0x30,
  'when': function(p){
return p["age"]>=0x1c&&p["age"]<=0x22;
},
  'desc': "转会落地，离家两千公里。孩子刚上小学，老人不愿挪窝。",
  'options': [
    {
        'label': "都接过来",
        'hint': "花钱，心里踏实",
        'apply': function(){
return{'money':-0x96,'ovr':0x2,'guanxi':0x6,'text':"租房、转学、找医院，一个夏天全搭进去。可每天回家，门一开，都有人。"};
}
    },
    {
        'p': function(p){return f(0.55,[[p["guanxi"],45,0.008]],0.2,0.9);
},
        'label': "自己一个人去",
        'hint': function(p,q){return g(q,'专心踢球','熬不住');
},
        'apply': function(p,q,s){
return d(q,s)?{'ovr':0x3,'money':0x28,'text':"一个人住队里的公寓，除了训练没有别的事。那两年，你的数据是生涯最好的。"}:{'ovr':-0x2,'fame':-0x4,'text':"视频那头，孩子对着镜头喊你「叔叔」。那个赛季，你总是走神。"};
}
    }
  ]
},

// ---- idx:173 | career_i | 膝盖里那块软骨 ----
{
  'id': "career_i"+"njury",
  'title': "膝盖里那块软骨",
  'icon': '🦴',
  'weight': 0x16,
  'stage': "prime",
  'when': function(p){
return p["age"]>=0x18&&p["ovr"]>=0x46;
},
  'desc': "第三次手术后，医生把片子转过来对着你：这关节，走路没问题，踢球就免了。",
  'options': [
    {
        'label': "再试一次复出",
        'p': function(p){
return f(0.42,[[p["ovr"],0x4a,0.006],[p["age"],0x1b,-0.02]],0.18,0.6);
},
        'hint': function(p,q){
return g(q,"撑住了","彻底废了");
},
        'apply': function(p,q,s){
return d(q,s)?{'ovr':-0x4,'fame':0xc,'roleDelta':-0x1,'text':"你回来了，慢了半步，好在还在场上。看台某个角落，有人举着「欢迎回家」。"}:{'retire':!0x0,'money':-0x50,
'text':"复出第七场，同一个地方又响了一声。这次你站起来，自己走下场，没等担架。"};
}
    },
    {
        'label': "就到这里吧",
        'hint': "挂靴，身体留给以"+'后',
        'apply': function(){
return{'retire':!0x0,'money':0x28,'clean':0x4,'text':"那晚你在更衣室把球鞋装进包里，拉链拉得比往常慢。谁也没想到，那是最后一次。"};
}
    }
  ]
},

// ---- idx:174 | teammate | 队友出事了 ----
{
  'id': "teammate"+"_scandal",
  'title': "队友出事了",
  'icon': '🚨',
  'weight': 0x32,
  'stage': "prime",
  'desc': "跟你关系最好的队友被带走调查。第二天，记者堵在基地门口，见谁都问。",
  'options': [
    {
        'label': "公开说他是好人",
        'hint': "名气+，清白受牵"+'连',
        'apply': function(){
return{'fame':0x10,'clean':-0x8,'guanxi':-0x6,'text':"你在镜头前说，「我认识的他，不是那样的人」。半年后判决下来，这句旧话被人翻出来，嘲了很久。"};
}
    },
    {
        'label': "什么都不说",
        'hint': "干净，落个冷血",
        'apply': function(){
return{'clean':0x4,'fame':-0x6,'text':"你从头到尾没开过口。他出来那天发来消息，你回了两字：保重。"};
}
    }
  ]
},

// ---- idx:175 | loan_out | 被外租 ----
{
  'id': "loan_out",
  'title': "被外租",
  'icon': '📤',
  'weight': 0x34,
  'stage': "prime",
  'desc': "俱乐部不打算用你，又不肯放你走。折中的方案：租给一支保级队，半年。",
  'options': [
    {
        'label': "就去",
        'hint': "能力+3，落差大",
        'apply': function(){
return{'ovr':0x3,'fame':-0x6,'roleDelta':0x1,'text':"那支队更衣室没有空调。你场场首发，半年踢了十九场，一次没落下。"};
}
    },
    {
        'label': "拒绝，留下来耗",
        'p': function(p){
return f(0.45,[[p["roleRank"],0x2,0.12],[p["ovr"],0x46,0.008]],0.2,0.82);
},
        'hint': function(p,q){
return g(q,"等到机会","荒废一年");
},
        'apply': function(p,q,s){
return d(q,s)?{'roleDelta':0x1,'ovr':0x1,'text':"冬窗一开，队里走了两个人。机会没吭声，自己回来了。"}:{'ovr':-0x3,'roleDelta':-0x2,'text':"一年里你只出场四次，全是替补登场，每回十分钟。"};
}
    }
  ]
},

// ---- idx:176 | transfer | 转会传闻 ----
{
  'id': "transfer"+"_rumor",
  'title': "转会传闻",
  'icon': '📰',
  'weight': 0x30,
  'stage': "prime",
  'repeat': 0x2,
  'desc': "整个冬窗，你要走的传闻没断过。训练场上，有人开始绕着你走。",
  'options': [
    {
        'label': "公开表态留下",
        'hint': "关系+，将来难走",
        'apply': function(){
return{'guanxi':0xe,'fame':0xa,'lockAbroad':0x2,'roleDelta':0x1,'text':"你在采访里说，「我哪儿也不去」。那句话被印上围巾，也把你钉在了原地。"};
}
    },
    {
        'label': "不表态",
        'p': function(p){
return f(0.45,[[p["ovr"],0x46,0.012],[p["fame"],0x2d,0.003]],0.18,0.85);
},
        'hint': function(p,q){
return g(q,"转成了","两头落空");
},
        'apply': function(p,q,s){
return d(q,s)?{'leave':!0x0,'fame':0x8,'text':"窗口关闭前四小时"+"，你在体检室里签"+"了字。"}:{'roleDelta':-0x2,'guanxi':-0xc,'text':"转会没成，队里也没人再把你当自己人。那半个赛季，过得格外慢。"};
}
    }
  ]
},

// ---- idx:177 | win_bonu | 赢球奖金 ----
{
  'id': "win_bonu"+'s',
  'title': "赢球奖金",
  'icon': '💴',
  'weight': 0x32,
  'stage': "prime",
  'cn': !0x0,
  'when': function(p){
return p["clubRep"]<=0x2;
},
  'desc': "保级生死战前夜，老板发话：赢了，每人五十万，现金。队委会拿着张纸来问你，签不签个字确认。",
  'options': [
    {
        'label': "签字确认",
        'hint': "钱到手，留痕迹",
        'apply': function(){
return{'money':0x32,'clean':-0x6,'text':"钱是给了，纸箱装着。可你签过字的那张条子，后来出现在了别处。"};
}
    },
    {
        'p': function(p){return f(0.6,[[p["guanxi"],45,0.008]],0.2,0.9);
},
        'label': "不签，照常踢",
        'hint': function(p,q){return g(q,'照样给','一分没有');
},
        'apply': function(p,q,s){
return d(q,s)?{'money':0x32,'clean':0x4,'text':"球赢了，钱照发。从头到尾，你没在任何纸上留过名字。"}:{'clean':0x4,'guanxi':-0x8,'text':"球赢了，奖金拖到第二年，最后没了下文。有人笑你：活该。"};
}
    }
  ]
},

// ---- idx:178 | fan_club | 球迷会 ----
{
  'id': "fan_club",
  'title': "球迷会",
  'icon': '🧣',
  'weight': 0x2d,
  'stage': "prime",
  'desc': "一伙球迷想用你的名字注册个球迷会，说不为赚钱，就是想让大伙有个地方聚。",
  'options': [
    {
        'p': function(p){return f(0.6,[[p["clean"],70,0.008]],0.2,0.9);
},
        'label': '同意',
        'hint': "名气+，惹麻烦",
        'odds': ["一直是好事","被人拿去做生意"],
        'apply': function(p,q,s){
return d(q,s)?{'fame':0x12,'guanxi':0x6,'text':"每个客场，看台上都有一小群人举着你的名字。你私下出钱，替他们订过两回车票。"}:{'fame':0xa,'money':-0x28,'clean':-0x6,
'text':"有人借着这名头卖假球衣。你自掏腰包请律师，才把这事了断。"};
}
    },
    {
        'label': '婉拒',
        'hint': "无变化",
        'apply': function(){
return{'text':"你说，等踢出点名堂再说。那群人后来，把名字印在了另一个球员的围巾上。"};
}
    }
  ]
},

// ---- idx:179 | second_t | 下放二队 ----
{
  'id': "second_t"+"eam",
  'title': "下放二队",
  'icon': '🪜',
  'weight': 0x30,
  'stage': "prime",
  'when': function(p){
return p["roleRank"]<=0x1&&p["age"]<=0x18;
},
  'desc': "训练课上，教练把你分进黄背心那组。全场没人说话——这队里谁都懂，那是什么意思。",
  'options': [
    {
        'p': function(p){return f(0.65,[[p["ovr"],60,0.008]],0.2,0.9);
},
        'label': "在二队踢出来",
        'hint': function(p,q){return g(q,'打回去','从此消失');
},
        'apply': function(p,q,s){
return d(q,s)?{'ovr':0x3,'roleDelta':0x2,'text':"预备队联赛你场场"+"首发，"+('gk'===p["posGroup"]?"十一轮只丢了四个":"def"===p["posGroup"]?"整条后防线让人挑"+"不出毛病":"进了十一个")+("。三个月后你被叫"+"回了一队。")}:{'ovr':-0x3,
'roleDelta':-0x1,'text':"二队的场子在郊区，看台空着。一线队的教练，一次都没来过。"};
}
    },
    {
        'p': function(p){return f(0.5,[[p["guanxi"],45,0.008]],0.2,0.9);
},
        'label': "找人说情",
        'hint': function(p,q){return g(q,'回一队','更难看');
},
        'apply': function(p,q,s){
return d(q,s)?{'roleDelta':0x1,'guanxi':-0x8,'text':"一个电话打上去，你回了头一队。教练再用你，脸一直是冷的。"}:{'roleDelta':-0x2,'guanxi':-0xe,'clean':-0x6,
'text':"教练在全队面前扔下一句：「有些人路子挺野。」从那以后，没人敢主动跟你说话。"};
}
    }
  ]
},

// ---- idx:230 | light_fi | 游戏里的自己 ----
{
  'id': "light_fi"+'fa',
  'title': "游戏里的自己",
  'icon': '🎮',
  'weight': 0x32,
  'tone': "light",
  'when': function(p){
return p["fame"]>=0x14;
},
  'desc': "那款足球游戏出了新版本，你的数值被砍了三点。评论区有人说：「这已经是抬举他了。」",
  'options': [
    {
        'p': function(p){return f(0.6,[[p["fame"],25,0.01]],0.2,0.9);
},
        'label': "发条动态自嘲",
        'hint': function(p,q){return g(q,'名气+','被当成玻璃心');
},
        'apply': function(p,q,s){
return d(q,s)?{'fame':0x8,'text':"你截图配了一句"+h(p,{'gk':"「反应 68 我"+"认，出击 61 "+"是谁定的」",'other':"「速度 68 我"+"认，射门 61 "+"是谁定的」"})+("。这条转了三万，"+"官方账号还回复了"+'你。')}:{'fame':-0x4,
'text':"有人把你的动态解读成「输不起」。你隔了两个小时删掉——删之前，它已经被搬到了另外三个平台。"};
}
    },
    {
        'label': "私下截了张图",
        'hint': "无变化",
        'apply': function(){
return{'text':"你把那页数值截下来，存进相册，谁也没发。那个文件夹里，已经躺了好几张。"};
}
    }
  ]
},

// ---- idx:231 | light_nu | 十号球衣 ----
{
  'id': "light_nu"+"mber",
  'title': "十号球衣",
  'icon': '👕',
  'weight': 0x32,
  'tone': "light",
  'when': function(p){
return p["roleRank"]>=0x2&&p["seasonsA"+"tClub"]>=0x2;
},
  'desc': "队里那个穿十号的老队员离开了。号码空出来的第二天，装备经理来问你：要不要换。",
  'options': [
    {
        'label': '换',
        'hint': "名气+，关系-",
        'apply': function(){
return{'fame':0x9,'guanxi':-0x5,'text':"你换了。第一场穿十号的比赛，你踢得格外紧。赛后，一个小球迷举着写你名字的十号球衣，来找你签名。"};
}
    },
    {
        'label': "留着原来的号",
        'hint': "关系+",
        'apply': function(){
return{'guanxi':0x6,'text':"你说习惯了。更衣室里再没人提这事，但那天之后，大家看你的眼神里多了点别的东西。"};
}
    }
  ]
},

// ---- idx:232 | light_ho | 队内聚餐 ----
{
  'id': "light_ho"+"tpot",
  'title': "队内聚餐",
  'icon': "🍽️",
  'weight': 0x32,
  'tone': "light",
  'repeat': 0x2,
  'desc': "队友在群里组了个聚餐，说好了 AA。周一早上还有恢复训练。",
  'options': [
    {
        'label': "去，敞开了吃",
        'hint': "关系+，训练吃点亏",
        'apply': function(){
return{'guanxi':0x8,'ovr':-0x1,'money':-0x3,'text':"那顿吃到十一点半。第二天恢复训练你排在最后一组，体能教练看了你一眼，什么也没说。"};
}
    },
    {
        'label': "去，随便吃点",
        'hint': "关系+，无损失",
        'apply': function(){
return{'guanxi':0x4,'text':"你只点了杯水，陪坐了两个小时。队友笑了你一路，这事后来被写进了队内的段子库。"};
}
    },
    {
        'label': '不去',
        'hint': "无变化",
        'apply': function(){
return{'text':"你在宿舍点了份鸡胸肉。那晚群里两百多条消息，你一条都没回。"};
}
    }
  ]
},

// ---- idx:233 | light_do | 捡了只狗 ----
{
  'id': "light_do"+'g',
  'title': "捡了只狗",
  'icon': '🐕',
  'weight': 0x32,
  'tone': "light",
  'desc': "训练基地门口趴着只狗，跟了你三天。门卫说，没人认领。",
  'options': [
    {
        'label': "带回去养",
        'hint': "花点钱，心态好",
        'apply': function(){
return{'money':-0x6,'ovr':0x1,'text':"你给它取名叫「越位」。此后三年，无论那天赢还是输，回家推开门，都是同一张脸在等你。"};
}
    },
    {
        'label': "托人找领养",
        'hint': "无变化",
        'apply': function(){
return{'text':"队医的表妹把它领走了。你偶尔会在朋友圈刷到它，长胖了不少。"};
}
    }
  ]
},

// ---- idx:234 | light_we | 队友结婚 ----
{
  'id': "light_we"+"dding",
  'title': "队友结婚",
  'icon': '💒',
  'weight': 0x32,
  'tone': "light",
  'repeat': 0x2,
  'desc': "同屋那位要结婚了。队里传的随礼数目一个比一个离谱。",
  'options': [
    {
        'label': "送份大的",
        'hint': "花钱，关系+",
        'apply': function(){
return{'money':-0xc,'guanxi':0x9,'text':"你送了一份全队第二大的礼。他后来在球队最难的那年，替你说过一次话——你到现在都不知道。"};
}
    },
    {
        'label': "按行情来",
        'hint': "小花销",
        'apply': function(){
return{'money':-0x4,'guanxi':0x3,'text':"你送了个不出挑的数，人到得比谁都早，帮着搬了一下午椅子。"};
}
    }
  ]
},

// ---- idx:235 | light_ni | ? ----
{
  'id': "light_ni"+"ckname",
  'title': '外号',
  'icon': '📣',
  'weight': 0x32,
  'tone': "light",
  'when': function(p){
return p["fame"]>=0xf;
},
  'desc': "看台上那帮人给你起了个外号——不算难听，也绝对不好听。横幅已经做出来了。",
  'options': [
    {
        'label': "认下来",
        'hint': "名气+",
        'apply': function(){
return{'fame':0x7,'text':"你在采访里主动用了那个外号。第二周，看台上出现了两百件印着它的自制 T 恤。"};
}
    },
    {
        'label': "装作没看见",
        'hint': "无变化",
        'apply': function(){
return{'text':"你一次都没提过它。它还是跟了你一辈子，连退役新闻的标题里都是它。"};
}
    }
  ]
},

// ---- idx:236 | light_co | 自己做饭 ----
{
  'id': "light_co"+'ok',
  'title': "自己做饭",
  'icon': '🍳',
  'weight': 0x32,
  'tone': "light",
  'when': function(p){
return!p["inChina"]&&p["seasonsA"+"broad"]>=0x1;
},
  'desc': "外面那家中餐馆吃了三个月，你决定自己做。第一次买菜，在超市货架前站了四十分钟——标签上一个字都不认识。",
  'options': [
    {
        'label': "认真学",
        'hint': "身体状态+",
        'apply': function(){
return{'ovr':0x1,'money':-0x4,'text':"两个月后，你已经能给三个队友做一锅像样的番茄牛腩。营养师看了一眼配料表，只说了一句：少放盐。"};
}
    },
    {
        'label': "叫外卖凑合",
        'hint': "无变化",
        'apply': function(){
return{'money':-0x6,'text':"你把那家亚洲超市的电话存进收藏夹。手机相册里，那张写满拼音的采购清单一直留着。"};
}
    }
  ]
},

// ---- idx:237 | light_wi | 更衣室密码 ----
{
  'id': "light_wi"+'fi',
  'title': "更衣室密码",
  'icon': '📶',
  'weight': 0x32,
  'tone': "light",
  'when': function(p){
return p["roleRank"]>=0x3;
},
  'desc': "更衣室的 WiFi 换了密码——新密码是队长的生日。队长说，以后谁想改，先拿一场最佳。",
  'options': [
    {
        'p': function(p){return f(0.5,[[p["guanxi"],45,0.008]],0.2,0.9);
},
        'label': "赌一把",
        'hint': function(p,q){return g(q,'换成你的生日','白说一句');
},
        'apply': function(p,q,s){
return d(q,s)?{'guanxi':0x7,'fame':0x4,'text':"两周后你拿了最佳。密码改成你的生日，一直用到你离队那天，没人换过。"}:{'guanxi':-0x3,'text':"那个月，你一场最佳都没拿到。这事被念叨了整整一个赛季。"};
}
    },
    {
        'label': "记下来就行",
        'hint': "无变化",
        'apply': function(){
return{'text':"你把它存进备忘录，命名「别问」。三年后换了球队，你还背得出来。"};
}
    }
  ]
},

// ---- idx:280 | cap_room | 更衣室的那一拳 ----
{
  'id': "cap_room",
  'title': "更衣室的那一拳",
  'icon': '🥊',
  'weight': 0x3a,
  'repeat': 0x2,
  'when': function(p){return p["_captain"]===p["teamId"];
},
  'desc': "训练前，更衣室里的火药味比平时重。两个主力为一个丢球的事闹僵了，谁都不肯先开口。",
  'options': [
    {
        'label': "把两边叫到一起说开",
        'p': function(p){return f(0.6,[[p["guanxi"],45,0.008]],0.2,0.9);
},
        'hint': function(p,q){return g(q,"更衣室又活了","袖标劝不动");
},
        'apply': function(p,q,s){return d(q,s)?{'guanxi':0xe,'fame':0x6,'text':"你把他们摁在一张桌上，让他们把话说完。那天下午的训练，是全队最顺的一场。"}:{'guanxi':-0x8,
'ovr':-0x1,'text':"你刚开口，其中一个就摔门走了。那天更衣室里，谁都没再说话。"};
}
    },
    {
        'label': "让教练来处理",
        'hint': "清白+，稍微有点掉份",
        'apply': function(){return{'clean':0x4,'guanxi':-0x3,'text':"你把这个烫手山芋交给了教练。他处理得干净，可第二天有人在背后说，这个队长不管事。"};
}
    }
  ]
},

// ---- idx:281 | cap_money | 袖标下的邀约 ----
{
  'id': "cap_money",
  'title': "袖标下的邀约",
  'icon': '💼',
  'weight': 0x38,
  'repeat': 0x1,
  'when': function(p){return p["_captain"]===p["teamId"];
},
  'desc': "一家跟队里合作的赞助商想加一条广告，点名让你出镜。经纪人觉得是好事，可你听说这单不走俱乐部账。",
  'options': [
    {
        'label': "接下这单",
        'hint': "钱+，清白受损",
        'apply': function(){return{'money':0xc8,'clean':-0xa,'fame':-0x4,'text':"你去了，成片里你笑得挺自然。两个月后这单被人翻出来，你才知道它有多难解释。"};
}
    },
    {
        'label': "把消息递给俱乐部",
        'hint': "清白+，钱没了",
        'apply': function(){return{'clean':0x8,'money':-0x1e,'fame':0x4,'text':"你把话递给了俱乐部。几天后那家赞助商被换掉了，更衣室里有人嘀咕你难搞，可俱乐部再没提过这事。"};
}
    }
  ]
},

// ---- idx:282 | cap_pressure | 连败之后 ----
{
  'id': "cap_pressure",
  'title': "连败之后",
  'icon': '🎤',
  'weight': 0x3c,
  'repeat': 0x2,
  'when': function(p){return p["_captain"]===p["teamId"];
},
  'desc': "联赛三轮不胜，发布会门口堵满了记者。教练朝你看了一眼——按惯例，队长得先开口。",
  'options': [
    {
        'label': "自己先站上去",
        'p': function(p){return f(0.6,[[p["fame"],25,0.01]],0.2,0.9);
},
        'hint': function(p,q){return g(q,"扛住了","被追问到失语");
},
        'apply': function(p,q,s){return d(q,s)?{'fame':0xc,'clean':0x4,'guanxi':0x6,'text':"你承认失误，也替球队兜底。那天你的发言上了热搜，更衣室里没人再抱怨。"}:{'fame':-0x6,
'ovr':-0x1,'text':"你说了两句场面话就被打断了。那晚的标题是「队长只会道歉」。"};
}
    },
    {
        'label': "让教练挡在前面",
        'hint': "关系-，清白-",
        'apply': function(){return{'guanxi':-0x4,'clean':-0x4,'text':"你把话筒推给了教练。他面不改色替你扛完，可从那天起，你在他心里的分量轻了一点。"};
}
    }
  ]
},

// ---- idx:342 | injury_type_shift | 伤后的抉择 ----
{
  'id': "injury_type_shift",
  'title': "伤后的抉择",
  'icon': '🩹',
  'weight': 0x50,
  'repeat': 1,
  'when': function(p){return p["_severeInjury"]&&p["playerType"]!==11;},
  'desc': function(p){
    var TN=['射手','组织核心','全能','速度型','支点','影锋','B2B','铁腰','边后卫','自由人','铁卫','门将'];
    var cur=p["playerType"]!=null?p["playerType"]:11;
    var injuryTarget={
      'att':{0:0,1:0,2:0,3:0,4:0,5:0},
      'mid':{1:6,5:6,6:6,7:6},
      'def':{8:10,9:10,10:10}
    };
    var grp=p["posGroup"];
    var map=injuryTarget[grp];
    if(!map||map[cur]==null)return null;
    var tgt=map[cur];
    p._injTarget=tgt;
    return "严重的伤病让你不得不重新审视自己的踢法。身体恢复后，教练建议你换个方式踢——也许能延长你的职业生涯。";
  },
  'options': [
    {
      'label': "接受转型",
      'p': function(p){return f(0.55,[[p["talent"],1,0.2],[p["age"],28,-0.02]],0.25,0.85);},
      'hint': function(p,q){
        var TN=['射手','组织核心','全能','速度型','支点','影锋','B2B','铁腰','边后卫','自由人','铁卫','门将'];
        var tgt=p._injTarget!=null?p._injTarget:0;
        return g(q,"转型成功→"+TN[tgt],"转型失败");
      },
      'apply': function(p,q,s){
        var tgt=p._injTarget!=null?p._injTarget:0;
        return d(q,s)?{'playerType':tgt,'ovr':0x2,'_severeInjury':0,'text':"你接受了教练的建议，花了三个月适应新的位置和踢法。虽然过程痛苦，但你发现自己在这个新位置上反而活得更自在了。"}
        :{'playerType':tgt,'ovr':-0x2,'_severeInjury':0,'text':"你硬着头皮试了新位置，但身体记忆太顽固。转型没成功，反而因为不适应掉了状态。不过至少，你试过了。"};
      }
    },
    {
      'label': "不转，硬扛",
      'hint': "能力-3",
      'apply': function(){return{'ovr':-0x3,'_severeInjury':0,'text':"你拒绝了所有人的建议：我就是我，不需要变。伤愈后你回到了原来的位置，但身体已经不如从前。"}}
    }
  ]
},

// ---- idx:343 | vet_type_shift | 老将的转型 ----
{
  'id': "vet_type_shift",
  'title': "老将的转型",
  'icon': '🧓',
  'weight': 0x48,
  'repeat': 1,
  'when': function(p){return p["age"]>=32&&p["playerType"]!==11&&!p["_vetTypeShiftDone"];},
  'desc': function(p){
    var TN=['射手','组织核心','全能','速度型','支点','影锋','B2B','铁腰','边后卫','自由人','铁卫','门将'];
    var cur=p["playerType"]!=null?p["playerType"]:11;
    var vetTarget={
      'att':{0:0,1:0,2:0,3:0,4:0,5:0},
      'mid':{1:6,5:6,6:6,7:6},
      'def':{8:10,9:10,10:10}
    };
    var grp=p["posGroup"];
    var map=vetTarget[grp];
    if(!map||map[cur]==null)return null;
    var tgt=map[cur];
    if(tgt===cur)return null;
    p._vetTarget=tgt;
    return "年龄不饶人，你的速度和爆发力都在下降。教练找你谈话：是时候换个活法了——经验比身体更值钱。";
  },
  'options': [
    {
      'label': "主动转型",
      'p': function(p){return f(0.60,[[p["talent"],1,0.25],[p["age"],35,-0.03]],0.30,0.88);},
      'hint': function(p,q){
        var TN=['射手','组织核心','全能','速度型','支点','影锋','B2B','铁腰','边后卫','自由人','铁卫','门将'];
        var tgt=p._vetTarget!=null?p._vetTarget:0;
        return g(q,"转型成功→"+TN[tgt],"转型失败");
      },
      'apply': function(p,q,s){
        var tgt=p._vetTarget!=null?p._vetTarget:0;
        return d(q,s)?{'playerType':tgt,'ovr':0x2,'_vetTypeShiftDone':1,'text':"你花了整个夏天加练新位置的技术。新赛季开始，你用经验弥补了身体的退化——虽然不再是从前的你，但依然有用。"}
        :{'playerType':tgt,'ovr':-0x1,'_vetTypeShiftDone':1,'text':"转型比想象中难。旧的习惯根深蒂固，新的位置也学得磕磕绊绊。教练叹了口气：算了，还是按你习惯的来吧。"};
      }
    },
    {
      'label': "不转，拼到退役",
      'hint': "能力-4",
      'apply': function(){return{'ovr':-0x4,'_vetTypeShiftDone':1,'text':"你告诉教练：我的身体我自己清楚。接下来的赛季，你拼尽全力维持状态，但岁月终究不可逆。"}}
    }
  ]
}

];
