// auto-generated by split_events.py - edit events here, then run build_events.py

var EVT_nat=[

// ---- idx:240 | nat_firs | 国家队的电话 ----
{
  'id': "nat_firs"+"tcall",
  'title': "国家队的电话",
  'icon': '📞',
  'weight': 0x3c,
  'when': function(p){
return p["caps"]>=0x1;
},
  'desc': "训练完，手机上有条未接来电，区号是北京。拨回去，那头只说了一句：下周一，香河报到，行李按十天准备。",
  'options': [
    {
        'label': "先给家里打电话",
        'hint': "名气+，这通电话"+"打了四十分钟",
        'apply': function(){
return{'fame':0xc,'guanxi':0x5,'ovr':0x1,'text':"你妈在那头沉默了很久，最后问的是「衣服够不够穿」。你爸在旁边一直咳嗽，什么也没说。"};
}
    },
    {
        'label': "谁也不说，先去加练",
        'hint': "能力+3",
        'apply': function(){
return{'ovr':0x3,'text':"你怕这事是假的，也怕说出去就黄了。名单公布那天，你正跑第四组折返跑。"};
}
    }
  ]
},

// ---- idx:241 | nat_firs | 国家队的电话 ----
{
  'id': "nat_firs"+"tcall2",
  'title': "国家队的电话",
  'icon': '📞',
  'weight': 0x3c,
  'when': function(p){
return p["caps"]>=0x1;
},
  'desc': "更衣室手机震了三下，区号是北京。回过去，那头没报职位，先问了一句：「这几周膝盖怎么样？」你愣住——他连你上周的训练笔记都看过。",
  'options': [
    {
        'label': "如实说",
        'hint': "名气+，关系+",
        'apply': function(){
return{'fame':0xa,'guanxi':0x5,'text':"你说有一处老伤，但能踢。那头沉默两秒：「那正好，队里缺你这样的。」"};
}
    },
    {
        'label': "多讲两句最近的比赛",
        'hint': "能力+2，名气+",
        'apply': function(){
return{'ovr':0x2,'fame':0x6,'text':"你把自己最近两场的表现讲了讲，尽量说得平淡。挂电话时你才发现，手心全是汗。"};
}
    }
  ]
},

// ---- idx:242 | nat_firs | 名单上的名字 ----
{
  'id': "nat_firs"+"tcall3",
  'title': "名单上的名字",
  'icon': '📋',
  'weight': 0x3c,
  'when': function(p){
return p["caps"]>=0x1;
},
  'desc': "名单贴在基地公告栏上。你路过时前面围了一堆人，有人回头看了你一眼，说：「有你。」你站住，又看了一遍。",
  'options': [
    {
        'label': "把那行看了三遍",
        'hint': "名气+，能力+",
        'apply': function(){
return{'fame':0x8,'guanxi':0x4,'ovr':0x1,'text':"你确认了三遍，名字没写错。那晚你给家里打电话，你爸只说了一句：别丢人。"};
}
    },
    {
        'label': "悄悄走开，自己消化",
        'hint': "能力+3",
        'apply': function(){
return{'ovr':0x3,'text':"你没在人堆里多待，拐进训练场。跑起来的时候，嘴角压不住。"};
}
    }
  ]
},

// ---- idx:243 | nat_firs | 第一个国家队进球 ----
{
  'id': "nat_firs"+"tgoal",
  'title': "第一个国家队进球",
  'icon': "🇨🇳",
  'weight': 0x3c,
  'when': function(p){
return p["natGoals"]>=0x1;
},
  'desc': "球进的那一下你其实没看清。等反应过来，队友已经跑过了半场，正朝你冲来。",
  'options': [
    {
        'label': "跑向看台，对着那"+'面旗',
        'hint': "名气大涨",
        'apply': function(){
return{'fame':0x12,'ovr':0x1,'text':"那张照片后来印在很多地方。你自己留的那张是手机拍的——看台上一个举着旗的人，脸都糊了。"};
}
    },
    {
        'label': "捡球回中圈，比赛"+"还没完",
        'hint': "能力+3，队内威"+'望+',
        'apply': function(){
return{'ovr':0x3,'guanxi':0x8,'text':"解说说了一句「他没庆祝」。那场最后 1 比 1，你站在中圈等开球，始终没坐下。"};
}
    }
  ]
},

// ---- idx:244 | nat_firs | 那个进球 ----
{
  'id': "nat_firs"+"tgoal2",
  'title': "那个进球",
  'icon': '⚽',
  'weight': 0x3c,
  'when': function(p){
return p["natGoals"]>=0x1;
},
  'desc': "队友直塞，球在你左脚内侧垫了一下，滚进门将够不到的那个角。你还没反应过来，哨声和欢呼一起到了。",
  'options': [
    {
        'label': "跑去角旗区滑跪",
        'hint': "名气大涨",
        'apply': function(){
return{'fame':0xf,'ovr':0x1,'text':"草皮吃了一小口，膝盖有点疼，但值。那张图后来做成表情包，你自己也存了一张。"};
}
    },
    {
        'label': "走回中圈，朝队友点头",
        'hint': "能力+3，队内威"+'望+',
        'apply': function(){
return{'ovr':0x3,'guanxi':0x6,'text':"你指了指给你助攻的人。那场赛后，他主动把比赛用球塞给你：留个纪念。"};
}
    }
  ]
},

// ---- idx:245 | nat_firs | 主场的那一下 ----
{
  'id': "nat_firs"+"tgoal3",
  'title': "主场的那一下",
  'icon': "🇨🇳",
  'weight': 0x3c,
  'when': function(p){
return p["natGoals"]>=0x1;
},
  'desc': "主场，五万人。进球那一刻，声音像浪一样从身后卷过来，你整个人被按在原地，耳朵里只剩嗡嗡声。",
  'options': [
    {
        'label': "抬头，看台那面旗一直没停",
        'hint': "名气大涨",
        'apply': function(){
return{'fame':0x10,'text':"你知道那面旗举了很久了。赛后看台有人喊你的名字，你第一次没觉得不好意思。"};
}
    },
    {
        'label': "埋头跑回半场，比谁都镇定",
        'hint': "能力+3，队内威"+'望+',
        'apply': function(){
return{'ovr':0x3,'guanxi':0x5,'text':"老队员们笑你「面无表情」。只有你自己知道，回更衣室的路，你走了三遍才找到。"};
}
    }
  ]
},

// ---- idx:246 | nat_qual | 世预赛最后一轮 ----
{
  'id': "nat_qual"+"ifier",
  'title': "世预赛最后一轮",
  'icon': '🎫',
  'weight': 0x44,
  'repeat': 0x2,
  'when': function(p){
return p["caps"]>=0x5;
},
  'desc': "最后一轮。赢，还有一线机会；输，就是下一个四年。客场，八万人里坐着两千个中国球迷。",
  'options': [
    {
        'label': "全场压上去踢",
        'hint': "赌一把，国家队履"+"历跟着走",
        'apply': function(p,q){
return d(q,f(0.42,[[p["ovr"],0x48,0.012]],0.2,0.72))?{'caps':0x3,'fame':0x14,'ovr':0x2,'text':h(p,{'gk':"你在最后十分钟扑"+"出了一记必进球。"+"终场哨响时看台上"+"那两千人喊的是你"+"的名字。",'def':"你在最后十分钟把"+"对方前锋的那脚射"+"门挡了出去。终场"+"哨响时看台上那两"+"千人喊的是你的名"+'字。','other':"你在第 88 分"+"钟把球捅了进去。"+"终场哨响时看台上"+"那两千人喊的是你"+"的名字。"})}:{'fame':-0xa,
'caps':0x2,'text':"0 比 2。回程飞机上没人说话。落地，通道口有人喊「谢谢你们」，也有人喊了别的。"};
}
    },
    {
        'label': "先守住，别输太难"+'看',
        'hint': "稳，但这一届也就"+"到这儿了",
        'apply': function(){
return{'caps':0x2,'fame':-0x5,'guanxi':0x6,'text':"0 比 0。教练组称之为「务实的一分」。回国后，没有人再提这场球。"};
}
    }
  ]
},

// ---- idx:247 | nat_anth | ? ----
{
  'id': "nat_anth"+'em',
  'title': '国歌',
  'icon': '🎼',
  'weight': 0x3e,
  'when': function(p){
return p["caps"]>=0x8;
},
  'desc': "大赛第一场，中圈线上唱国歌。左边的队友唱到一半哭了；右边那个，一个字都没张嘴。",
  'options': [
    {
        'label': "跟着唱完",
        'hint': "能力+2，名气+",
        'apply': function(){
return{'ovr':0x2,'fame':0x8,'text':"转播镜头正好扫过你。那个画面第二天被做成了很多张图，配的字你后来都看过。"};
}
    },
    {
        'label': "只想着待会儿的第"+"一脚球",
        'hint': "能力+3",
        'apply': function(){
return{'ovr':0x3,'text':"你满脑子都是对面那个左后卫的转身速度。开场第七分钟，你从他那一侧过了人。"};
}
    }
  ]
},

// ---- idx:248 | nat_newc | 新国家队主帅 ----
{
  'id': "nat_newc"+"oach",
  'title': "新国家队主帅",
  'icon': '📋',
  'weight': 0x40,
  'repeat': 0x2,
  'when': function(p){
return p["caps"]>=0xa;
},
  'desc': "又换帅了，这次来的是个外教。他带的第一期名单里没有你。助理教练私下说：「他喜欢跑得多的。」",
  'options': [
    {
        'label': "按他的要求改",
        'hint': "能力+3，重回名"+'单',
        'apply': function(){
return{'ovr':0x3,'caps':0x3,'text':"你把冬训的量加了三成，跑动数据发给了助教。第三期名单上你的名字排在最后一个——但它在。"};
}
    },
    {
        'p': function(p){return f(0.55,[[p["guanxi"],45,0.008]],0.2,0.9);
},
        'label': "不改，等他下课",
        'hint': "赌他走得比你早",
        'odds': ["他先走","你先老"],
        'apply': function(p,q,s){
return d(q,s)?{'caps':0x4,'guanxi':0x8,'text':"他两年后就走了，走时战绩 3 胜 9 负。下一任的第一期名单，把你叫了回去。"}:{'fame':-0x8,'caps':0x0,'text':"他待了四年。四年里，你没在国家队上过一场。等他走的时候，你已经过了三十。"};
}
    }
  ]
},

// ---- idx:249 | nat_capt | 国家队队长 ----
{
  'id': "nat_capt"+"ain",
  'title': "国家队队长",
  'icon': "🎗️",
  'weight': 0x3a,
  'when': function(p){
return p["caps"]>=0x19&&p["ovr"]>=0x48&&!p["_ntCaptain"];
},
  'desc': "老队长退了。教练"+"组在赛前把袖标放"+"在你的柜子上，没"+"说话，也没问你愿"+"不愿意。",
  'options': [
    {
        'label': '戴上',
        'hint': "名气+，从此每场"+"输球都要你去说话",
        'apply': function(){
return{'fame':0x14,'caps':0x4,'guanxi':0xa,'ovr':0x1,'ntCaptain':!0x0,'text':"从那以后每场输球，混合采访区都是你去站。有一次你站了二十六分钟，回到更衣室，饭已经凉了。"};
}
    },
    {
        'label': "说给更合适的人",
        'hint': "能力+2，少一身"+'麻烦',
        'apply': function(){
return{'ovr':0x2,'guanxi':0x5,'text':"你说队里有人比你更会说话。那人戴了两年袖标，那些最难的问题，都由你来挡。"};
}
    }
  ]
},

// ---- idx:250 | nat_natu | 更衣室里的两种话 ----
{
  'id': "nat_natu"+"ralized",
  'title': "更衣室里的两种话",
  'icon': '🛬',
  'weight': 0x3c,
  'when': function(p){
return p["caps"]>=0x8;
},
  'desc': "国家队来了三个归化球员，战术会得配两个翻译。主教练布置定位球，讲一句，停一句。",
  'options': [
    {
        'label': "主动去跟他们练配"+'合',
        'hint': "能力+3，国家队"+"地位+",
        'apply': function(){
return{'ovr':0x3,'caps':0x3,'guanxi':0x6,'text':"每天训练后你多留半小时，跟他们跑那几条线路。三个月后，那套战术是全队唯一练熟的东西。"};
}
    },
    {
        'label': "各踢各的",
        'hint': "无变化，但那届大"+"赛踢得很散",
        'apply': function(){
return{'caps':0x2,'fame':-0x4,'text':"场上传球总是慢半拍。赛后媒体统计，那场全队的传球成功率，小组垫底。"};
}
    }
  ]
},

// ---- idx:251 | nat_west | 西亚客场 ----
{
  'id': "nat_west"+"asia",
  'title': "西亚客场",
  'icon': "🏜️",
  'weight': 0x3e,
  'repeat': 0x2,
  'when': function(p){
return p["caps"]>=0x5;
},
  'desc': "客场打西亚，开球是当地凌晨零点。整场有人拿激光笔照你们。第 70 分钟，主队球迷开始往场里扔东西。",
  'options': [
    {
        'label': "踢完它",
        'hint': "能力+2，名气+",
        'apply': function(p){
return{'ovr':0x2,'fame':0xa,'caps':0x2,'text':h(p,{'gk':"你被激光笔照了整"+"整四十分钟，还是"+"把那记远射按在了"+"地上。赛后你眼睛"+"红得睁不开。",'other':"你被激光笔照了整"+"整四十分钟。终场"+"哨响你第一个走向"+"客场看台，鞠了个"+'躬。'})};
}
    },
    {
        'p': function(p){return f(0.5,[[p["fame"],25,0.01]],0.2,0.9);
},
        'label': "带头去找裁判",
        'hint': function(p,q){return g(q,'中止比赛','一张黄牌');
},
        'apply': function(p,q,s){
return d(q,s)?{'fame':0xc,'caps':0x2,'text':"裁判把比赛中断了八分钟。那八分钟，你们全队站在中圈，谁也没坐下。"}:{'banGames':0x1,'fame':0x4,'text':"裁判给了你一张黄牌，理由是「异议」。下一场，你停赛。"};
}
    }
  ]
},

// ---- idx:252 | nat_derb | 那场球 ----
{
  'id': "nat_derb"+'y',
  'title': "那场球",
  'icon': '⚔️',
  'weight': 0x42,
  'repeat': 0x2,
  'when': function(p){
return p["caps"]>=0xa;
},
  'desc': "对日本还是对韩国，这些年已经没什么区别了——赛前所有人只说一句「至少别输太多」。",
  'options': [
    {
        'label': "把这场当决赛踢",
        'hint': "拼一场，赢了这辈"+"子都有人记得",
        'apply': function(p,q){
return d(q,f(0.3,[[p["ovr"],0x4a,0.011]],0.12,0.62))?{'fame':0x19,'ovr':0x2,'caps':0x3,'text':h(p,{'gk':"你扑掉了那记点球"+"。那一晚全国的社"+"交平台都在放同一"+"段十秒的视频。",'def':"你在最后一分钟把"+"对方那记必进的射"+"门封了下来。那一"+"晚全国的社交平台"+"都在放同一段十秒"+"的视频。",'other':"你打进了那个球。"+"那一晚全国的社交"+"平台都在放同一段"+"十秒的视频。"})}:{'fame':-0x8,
'caps':0x2,'ovr':0x1,'text':"0 比 3。你跑了 11.8 公里，全队最多。这个数字，第二天没人提。"};
}
    },
    {
        'label': "保存体力，还有联"+'赛',
        'hint': "俱乐部那头受益，"+"名气-",
        'apply': function(){
return{'roleDelta':0x1,'fame':-0xc,'caps':0x1,'text':"六十分钟你就被换下了。回俱乐部，你连着三场首发。没人再问你国家队的事。"};
}
    }
  ]
},

// ---- idx:253 | nat_hurt | 带着伤去报到 ----
{
  'id': "nat_hurt",
  'title': "带着伤去报到",
  'icon': '🩼',
  'weight': 0x3c,
  'repeat': 0x2,
  'when': function(p){
return p["caps"]>=0xa;
},
  'desc': "脚踝还肿着，队医说再养两周就好。国家队那边，这一期是大赛前最后一次集训。",
  'options': [
    {
        'p': function(p){return f(0.55,[[p["ovr"],60,0.008]],0.2,0.9);
},
        'label': "打封闭去",
        'hint': "国家队履历+，能"+"力有风险",
        'odds': ["扛过去了","伤上加伤"],
        'apply': function(p,q,s){
return d(q,s)?{'caps':0x5,'fame':0xc,'guanxi':0x8,'text':"你打了三针，两场都踢满。回俱乐部那天走路还有点跛，可大赛名单上有你。"}:{'ovr':-0x4,'caps':0x2,'roleDelta':-0x1,
'text':"第二场，三十分钟你就下来了。那只脚踝后来疼了整整一年，阴雨天尤其厉害。"};
}
    },
    {
        'label': "跟国家队请假",
        'hint': "养好了，但这一期"+"名单没你",
        'apply': function(){
return{'ovr':0x2,'guanxi':-0xa,'fame':-0x6,'text':"你在俱乐部养了两周。名单公布那天，你坐在电视前一个个看过去——没有你。"};
}
    }
  ]
},

// ---- idx:254 | nat_camp | 长期集训 ----
{
  'id': "nat_camp",
  'title': "长期集训",
  'icon': "🏕️",
  'weight': 0x3a,
  'when': function(p){
return p["caps"]>=0x5&&p["inChina"];
},
  'desc': "足协定了：大赛前封闭集训四个月，联赛为此让路。俱乐部的教练在电话里问你：「你是我的球员，还是他们的？」",
  'options': [
    {
        'label': "去集训",
        'hint': "国家队履历+，队"+"内地位受损",
        'apply': function(){
return{'caps':0x6,'roleDelta':-0x2,'fame':0x8,'text':"四个月里你打了十四场热身赛，对手大多没听说过。回俱乐部那天，你的号码已经归了别人。"};
}
    },
    {
        'label': "找理由留在俱乐部",
        'hint': "地位保住，国字号"+"的门关一半",
        'apply': function(){
return{'roleDelta':0x1,'guanxi':-0xc,'fame':-0x8,'text':"你交了一份体检报告。那一年的国家队名单上，再没有你的名字——直到换帅。"};
}
    }
  ]
},

// ---- idx:255 | nat_bus | 机场那道通道 ----
{
  'id': "nat_bus",
  'title': "机场那道通道",
  'icon': '🚌',
  'weight': 0x38,
  'repeat': 0x2,
  'when': function(p){
return p["caps"]>=0x8;
},
  'desc': "又输了一场不该输的球。凌晨落地，出口通道两边站满了人——有举横幅的，有只是站着看的。",
  'options': [
    {
        'p': function(p){return f(0.5,[[p["fame"],25,0.01]],0.2,0.9);
},
        'label': "摘掉耳机走过去",
        'hint': "名气有涨有跌",
        'apply': function(p,q,s){
return d(q,s)?{'fame':0xc,'ovr':0x1,'text':"你走得很慢，始终没低头。一个小孩隔着栏杆递过来一张纸，上面画着球场。"}:{'fame':-0xa,'text':"有人喊了一句很难听的话。你站住，看了他两秒。那两秒，后来被传了三百万次。"};
}
    },
    {
        'label': "跟着大巴从侧门走",
        'hint': "名气-，心里清净",
        'apply': function(){
return{'fame':-0x6,'ovr':0x1,'text':"俱乐部的车等在侧门。你在车上睡了四十分钟——那半个月，睡得最沉的一觉。"};
}
    }
  ]
},

// ---- idx:256 | nat_kid | 看台上那件球衣 ----
{
  'id': "nat_kid",
  'title': "看台上那件球衣",
  'icon': '👕',
  'weight': 0x36,
  'when': function(p){
return p["caps"]>=0xf&&p["fame"]>=0x23;
},
  'desc': "热身时，看台第一排坐着个孩子，穿着国家队球衣，背后印着你的号码和名字。",
  'options': [
    {
        'label': "赛后把球衣给他",
        'hint': "名气+",
        'apply': function(){
return{'fame':0xf,'ovr':0x1,'text':"他哭了。他爸妈在旁边一个劲儿道谢。那件球衣，是那个赛季你唯一没留下的。"};
}
    },
    {
        'label': "记住这件事",
        'hint': "能力+3",
        'apply': function(){
return{'ovr':0x3,'text':"从那以后，国家队的每一场你都跑到抽筋。为什么，你没跟任何人说过。"};
}
    }
  ]
},

// ---- idx:257 | nat_quit | 退出国家队 ----
{
  'id': "nat_quit",
  'title': "退出国家队",
  'icon': "🕊️",
  'weight': 0x3c,
  'stage': "vet",
  'when': function(p){
return p["caps"]>=0x14&&p["age"]>=0x20;
},
  'desc': "新一期名单里还有你，可你知道自己跟不上那个节奏了。训练里，年轻人一次次从你身边过去，一次比一次快。",
  'options': [
    {
        'label': "打完这一届再说",
        'hint': "国家队履历+，身"+"体吃不消",
        'apply': function(){
return{'caps':0x6,'fame':0xa,'ovr':-0x2,'text':"你又打了一年。最后一场，客场，输了。你踢满九十分钟，赛后一个人在场地中间站了很久。"};
}
    },
    {
        'label': "发一条声明",
        'hint': "把位置让出去，名"+'气+',
        'apply': function(){
return{'fame':0xe,'guanxi':0x6,'ovr':0x1,'text':"你写了三百来字，最后一句是「这件球衣我穿了很多年，现在该给别人穿了」。那条消息下面，有十万条评论。"};
}
    }
  ]
},

// ---- idx:285 | ntcap_row | 替补席的冷眼 ----
{
  'id': "ntcap_row",
  'title': "替补席的冷眼",
  'icon': '😤',
  'weight': 0x3a,
  'repeat': 0x2,
  'when': function(p){return p["_ntCaptain"];
},
  'desc': "一场友谊赛，老将没进大名单，在场边坐了一整场。赛后他堵住你：这事你得给个说法。",
  'options': [
    {
        'label': "替教练把话说圆",
        'p': function(p){return f(0.55,[[p["guanxi"],45,0.008]],0.2,0.9);
},
        'hint': function(p,q){return g(q,"压下去了","里外不是人");
},
        'apply': function(p,q,s){return d(q,s)?{'guanxi':0xc,'fame':0x6,'text':"你把教练的难处摊开讲，他听着听着，火气下去了半截。"}:{'guanxi':-0x8,'fame':-0x4,
'text':"他听完冷笑一声：你站谁的边。那晚上，更衣室分了两拨。"};
}
    },
    {
        'label': "直说让他自己找教练",
        'hint': "清白+，关系-",
        'apply': function(){return{'clean':0x6,'guanxi':-0x4,'text':"你说这事不该我替你转。他愣了一下，扭头走了。你是队长，不是传声筒。"};
}
    }
  ]
},

// ---- idx:286 | ntcap_young | 新人的首发 ----
{
  'id': "ntcap_young",
  'title': "新人的首发",
  'icon': '🌱',
  'weight': 0x38,
  'repeat': 0x2,
  'when': function(p){return p["_ntCaptain"];
},
  'desc': "淘汰赛前夜，教练说想用一个十八岁的小孩顶替停赛的队友，问他行不行，教练说：你点头，他就上。",
  'options': [
    {
        'label': "跟教练说他可以",
        'p': function(p){return f(0.55,[[p["talent"],1,0.3]],0.2,0.9);
},
        'hint': function(p,q){return g(q,"他踢出来了","他踢砸了");
},
        'apply': function(p,q,s){return d(q,s)?{'ovr':0x2,'fame':0x8,'guanxi':0x6,'text':"那小孩全场跑了十二公里，扑出一个险球。赛后他跟着你，喊了半天的队长。"}:{'ovr':-0x1,
'fame':-0x4,'text':"他上半场就犯了错，教练半场把他换下。有人问这锅谁来背，你没躲。"};
}
    },
    {
        'label': "建议按原阵容来",
        'hint': "关系+，稳一点",
        'apply': function(){return{'guanxi':0x4,'text':"你把稳妥的一面说了。教练最终没换人，那小孩在替补席坐了一整场，你看见他眼眶有点红。"};
}
    }
  ]
},

// ---- idx:287 | ntcap_press | 赢球之后的漩涡 ----
{
  'id': "ntcap_press",
  'title': "赢球之后的漩涡",
  'icon': '📷',
  'weight': 0x3c,
  'repeat': 0x2,
  'when': function(p){return p["_ntCaptain"];
},
  'desc': "世预赛赢球，回酒店的路上。有记者截住你：队里有人赛后在社交平台说了一句不该说的话，你作为队长怎么看。",
  'options': [
    {
        'label': "当场把话圆回来",
        'p': function(p){return f(0.55,[[p["fame"],25,0.01]],0.2,0.9);
},
        'hint': function(p,q){return g(q,"圆过去了","越描越黑");
},
        'apply': function(p,q,s){return d(q,s)?{'fame':0xc,'clean':0x4,'guanxi':0x6,'text':"你替他把话收了回来，还给对方留了台阶。第二天，那条动态被删了。"}:{'fame':-0x6,
'clean':-0x4,'text':"你越解释，记者越来劲。第二天标题变成了「国家队内讧，队长回应含混」。"};
}
    },
    {
        'label': "只回一句：下场见",
        'hint': "清白+，关系少一点",
        'apply': function(){return{'clean':0x4,'guanxi':-0x3,'text':"你说了句「下场见」就上了大巴。有人觉得你敷衍，可你知道，有些事不该由你替所有人解释。"};
}
    }
  ]
}

];
