// auto-generated by split_events.py - edit events here, then run build_events.py

var EVT_star=[

// ---- idx:217 | star_mar | ? ----
{
  'id': "star_mar"+"ker",
  'title': '对位',
  'icon': '🎯',
  'weight': 0x96,
  'when': function(p){
return!p["inChina"]&&p["leagueRe"+'p']>=0x4&&"def"===p["posGroup"];
},
  'desc': "赛前会上，教练把战术板转向你：整场跟着 7 号，他去哪儿你去哪儿。教练不喊名字，可那个 7 号是梅西。",
  'options': [
    {
        'label': "贴死他",
        'p': function(p){
return f(0.42,[[p["ovr"],0x4c,0.011],[p["roleRank"],0x3,0.03]],0.12,0.78);
},
        'hint': function(p,q){
return g(q,"他这场没进球","被他过成了集锦");
},
        'apply': function(p,q,s){
return d(q,s)?{'ovr':0x3,'fame':0x16,'roleDelta':0x1,'text':"九十分钟，他碰到球四十七次，没有一次是在你身后。终场哨响，他拍了拍你的后脑勺。那个画面被拍了下来，现在还挂在你老家客厅的墙上。"}:{'ovr':-0x1,
'fame':0x6,'text':"第 63 分钟，他往回收了一步，你跟了出去，然后就没有然后了。那段视频标题写着「他把一个中国后卫钉在了原地」，播放量两千万。"};
}
    },
    {
        'label': "退半步，别单防",
        'hint': "不丢人，也没人记"+'得你',
        'apply': function(){
return{'fame':0x2,'guanxi':0x4,'text':"你始终和他保持两米，把他往边路赶。他这场进了一个，但那一球从另一侧打进。赛后教练说：你至少没让他在中路拿球转身。"};
}
    }
  ]
},

// ---- idx:218 | star_def | 他这一侧 ----
{
  'id': "star_def"+"_side",
  'title': "他这一侧",
  'icon': '🎯',
  'weight': 0x96,
  'when': function(p){
return!p["inChina"]&&p["leagueRe"+'p']>=0x4&&"def"===p["posGroup"];
},
  'desc': "赛前会，教练把鼠标点在你这一侧的边路：今晚对面那个 7 号归你。他上半场连续两次从这一侧起速，看台都在等第三次。",
  'options': [
    {
        'label': "贴死他,不放一步",
        'p': function(p){
return f(0.42,[[p["ovr"],0x4c,0.011],[p["roleRank"],0x3,0.03]],0.12,0.78);
},
        'hint': function(p,q){
return g(q,"他一晚没从你这边过","他连过你两次,还进了一个");
},
        'apply': function(p,q,s){
return d(q,s)?{'ovr':0x3,'fame':0x16,'roleDelta':0x1,'text':"他这一侧七次尝试，两次成功，都被你堵在底线附近。赛后他把球衣扔给你，一句话没说。你把它叠好，打算过年带回去给侄子。"}:{'ovr':-0x1,
'fame':0x6,'text':"他第三次内切时你已经知道追不上，可还是伸了脚。球进了死角。中场休息时你听见他在通道里跟队友复述那一下是怎么过的你。"};
}
    },
    {
        'label': "让队友协防,不硬扛",
        'hint': "保全自己,也保全全队",
        'apply': function(){
return{'guanxi':0x8,'fame':0x2,'text':"你每次给他留出外侧，逼他往内线走，那儿站着你的后腰。他这晚一次漂亮突破都没有，数据上什么也看不出来——但教练知道，队里也都知道。"};
}
    }
  ]
},

// ---- idx:219 | star_pen | 点球点上的那个人 ----
{
  'id': "star_pen"+"_save",
  'title': "点球点上的那个人",
  'icon': '🧤',
  'weight': 0x96,
  'when': function(p){
return!p["inChina"]&&p["leagueRe"+'p']>=0x4&&'gk'===p["posGroup"];
},
  'desc': "第 88 分钟，主裁指了指点球点。C 罗把球摆好，退到罚球弧外，深吸了一口气。",
  'options': [
    {
        'label': "赌一边",
        'p': function(p){
return f(0.22,[[p["ovr"],0x4c,0.008]],0.08,0.42);
},
        'hint': function(p,q){
return g(q,"扑出来了","球进了");
},
        'apply': function(p,q,s){
return d(q,s)?{'ovr':0x3,'fame':0x1c,'roleDelta':0x1,'text':"你倒向左侧，指尖把球拨出了立柱。客场看台安静了两秒，然后炸了。赛后他走过来，把球衣递到你手里。"}:{'fame':0x8,
'text':"他把球打进了死角。你扑对了方向，够不着。他没有庆祝，只是抬手指了指你——「你动得不算晚」。"};
}
    },
    {
        'label': "站着不动，等他先"+'动脚',
        'p': function(p){
return f(0.13,[[p["ovr"],0x4c,0.006]],0.04,0.3);
},
        'hint': function(p,q){
return g(q,"他打中路，你抱住"+'了',"球进了");
},
        'apply': function(p,q,s){
return d(q,s)?{'ovr':0x4,'fame':0x22,'roleDelta':0x1,'text':"你站在门线中间，一动没动。球直直飞向你胸口，你把它抱住。解说员连说了三遍：「他根本没有动。」"}:{'ovr':-0x1,
'fame':0x4,'text':"他把球打进你身后的网窝，你连方向都没来得及选。回更衣室，门将教练什么也没说，只把那段录像回放了七遍。"};
}
    }
  ]
},

// ---- idx:220 | star_mid | 中圈那一圈 ----
{
  'id': "star_mid"+"field",
  'title': "中圈那一圈",
  'icon': '🔄',
  'weight': 0x96,
  'when': function(p){
return!p["inChina"]&&p["leagueRe"+'p']>=0x4&&"mid"===p["posGroup"];
},
  'desc': "对面中场是莫德里奇。上半场，他在你面前转了三次身，你三次都扑了空。",
  'options': [
    {
        'label': "下半场提前一步上"+'抢',
        'p': function(p){
return f(0.45,[[p["ovr"],0x4c,0.01],[p["age"],0x1b,-0.008]],0.15,0.8);
},
        'hint': function(p,q){
return g(q,"把他摁住了","被晃出一张黄牌");
},
        'apply': function(p,q,s){
return d(q,s)?{'ovr':0x3,'fame':0x12,'roleDelta':0x1,'text':"第 58 分钟，你在他接球前半秒把球捅走，直接打成反击。赛后他找到你，用英语说了句：「你下半场变了。」"}:{'ovr':-0x1,
'fame':0x4,'text':"你扑上去，他一个外脚背把球拨到另一侧，你在他身后犯规。黄牌。场边教练摊手的样子，被人拍成了表情包。"};
}
    },
    {
        'label': "退回去守阵型",
        'hint': "稳，但这场没你什"+'么事',
        'apply': function(){
return{'ovr':0x1,'text':"你不再单独追他，只守住身前那一块。他这场送出两次助攻，都不是从你这边过去的。赛后没人提起你——这也是一种赞美。"};
}
    }
  ]
},

// ---- idx:221 | star_mid | 绞肉机 ----
{
  'id': "star_mid"+"_rodri",
  'title': "绞肉机",
  'icon': '🔄',
  'weight': 0x96,
  'when': function(p){
return!p["inChina"]&&p["leagueRe"+'p']>=0x4&&"mid"===p["posGroup"];
},
  'desc': "对面后腰是罗德里。上半场，他十二次把球从你脚下拿走，你一次都没能碰到他伸出来的那只脚。",
  'options': [
    {
        'label': "主动撞他的持球节奏",
        'p': function(p){
return f(0.45,[[p["ovr"],0x4c,0.01]],0.15,0.8);
},
        'hint': function(p,q){
return g(q,"把节奏搅乱了","被他遛了九十分钟");
},
        'apply': function(p,q,s){
return d(q,s)?{'ovr':0x3,'fame':0x12,'roleDelta':0x1,'text':"下半场他从你这里丢了三脚球，脸上惯常的平静第一次有了波动。赛后他在通道里等你握手，说了句「你踢得越来越像样子了」。"}:{'ovr':-0x1,
'fame':0x4,'text':"他像一块会算步数的铁板，你每次上抢都扑空。终场哨响时你发现，自己这晚一次干净的铲断都没有。"};
}
    },
    {
        'label': "不跟他正面,站住位置",
        'hint': "稳,把活儿让给队友",
        'apply': function(){
return{'ovr':0x1,'text':"你退到两名中卫身前，他出球七十九次，没有一次穿过你这一层。赛后你的传球成功率是百分之九十八——没人注意，但你知道那很重要。"};
}
    }
  ]
},

// ---- idx:222 | star_mid | 那脚直塞 ----
{
  'id': "star_mid"+"_kevin",
  'title': "那脚直塞",
  'icon': '🎯',
  'weight': 0x96,
  'when': function(p){
return!p["inChina"]&&p["leagueRe"+'p']>=0x4&&"mid"===p["posGroup"];
},
  'desc': "对面中场是德布劳内。录像里他每脚直塞都贴着草皮穿过两名中卫，教练在战术板上圈了三次：别给他起脚的空间。",
  'options': [
    {
        'label': "赌他直塞的线路",
        'p': function(p){
return f(0.45,[[p["ovr"],0x4c,0.01],[p["age"],0x1b,-0.008]],0.15,0.8);
},
        'hint': function(p,q){
return g(q,"猜对了那条线","球从你腿间穿过");
},
        'apply': function(p,q,s){
return d(q,s)?{'ovr':0x3,'fame':0x12,'roleDelta':0x1,'text':"你提前两步卡住那条线路，球刚到就被你捅给边路。他朝你点了点头。赛后他的数据里多了一次失误——那一次，是你。"}:{'ovr':-0x1,
'fame':0x4,'text':"他观察到你的站位，反手把球推给套边的边后卫，你的重心已经扔了出去。解说笑出声：「他骗了全世界，包括那个中国人。」"};
}
    },
    {
        'label': "切断他接球的线路",
        'hint': "脏活,没人看得见",
        'apply': function(){
return{'guanxi':0xa,'ovr':0x1,'text':"你整场贴着他最习惯的接球位，他被迫回撤拿球十七次。赛后教练只跟你说了一句话：今天他踢得不舒服，是你的功劳。"};
}
    }
  ]
},

// ---- idx:223 | star_str | 另一头那个九号 ----
{
  'id': "star_str"+"iker",
  'title': "另一头那个九号",
  'icon': '⚡',
  'weight': 0x96,
  'when': function(p){
return!p["inChina"]&&p["leagueRe"+'p']>=0x4&&"att"===p["posGroup"];
},
  'desc': "赛前热身，你在球场这头拉伸，哈兰德在另一头。所有的摄像机，都对着那一头。",
  'options': [
    {
        'label': "今晚就跟他比进球",
        'p': function(p){
return f(0.3,[[p["ovr"],0x4e,0.018],[p["roleRank"],0x3,0.04]],0.08,0.7);
},
        'hint': function(p,q){
return g(q,"你进得比他多","他梅开二度，你零"+'射正');
},
        'apply': function(p,q,s){
return d(q,s)?{'ovr':0x4,'fame':0x1e,'roleDelta':0x1,'text':"你打进两个，他一个。第二天，所有标题里都有你的名字——后面都跟着括号：「（对手：哈兰德）」。"}:{'ovr':-0x2,
'roleDelta':-0x1,'fame':0x6,'text':"他进了两个，你一脚射正都没有。混合区里他被围了三十分钟，你从他身后走过，没有人回头。"};
}
    },
    {
        'label': "老老实实做自己的"+'球',
        'hint': "不冒进，队友也认",
        'apply': function(){
return{'ovr':0x1,'guanxi':0x8,'text':"你回撤了很多，跑了十一公里，送出一个助攻。他进了三个。队长赛后说：今天全队只有你一个人在踢球。"};
}
    }
  ]
},

// ---- idx:224 | star_att | 他起步的那一下 ----
{
  'id': "star_att"+"_kylian",
  'title': "他起步的那一下",
  'icon': '⚡',
  'weight': 0x96,
  'when': function(p){
return!p["inChina"]&&p["leagueRe"+'p']>=0x4&&"att"===p["posGroup"];
},
  'desc': "对面是姆巴佩。他热身时随便一趟，三十米只用了四秒出头。你偷偷试了一次自己的起跑，然后决定今晚不跟他拼任何直线。",
  'options': [
    {
        'label': "跟他拼第一步",
        'p': function(p){
return f(0.3,[[p["ovr"],0x4e,0.018],[p["roleRank"],0x3,0.04]],0.08,0.7);
},
        'hint': function(p,q){
return g(q,"前三十米压住他","他超你两个身位");
},
        'apply': function(p,q,s){
return d(q,s)?{'ovr':0x4,'fame':0x1e,'roleDelta':0x1,'text':"前三十米你始终压着他半肩，他回头看了你一眼。赛后他在走廊里问你跑的什么路线——你说是高中田径队练的。"}:{'ovr':-0x2,
'roleDelta':-0x1,'fame':0x6,'text':"他一步就把你过了，你伸手去拉，没拉住。看台上响起一片起哄声，有人在喊你的号码，问你是不是卧底。"};
}
    },
    {
        'label': "放他走,守住第二落点",
        'hint': "不丢人,也护得住",
        'apply': function(){
return{'fame':0x2,'guanxi':0x6,'text':"你只贴他两步，第三步就回中路。他这场冲刺九次，只有一次真正形成射门，被门将没收。赛后报纸说你的防守叫「聪明的放弃」。"};
}
    }
  ]
},

// ---- idx:225 | star_att | 他背身那一块 ----
{
  'id': "star_att"+"_kane",
  'title': "他背身那一块",
  'icon': '🛡️',
  'weight': 0x96,
  'when': function(p){
return!p["inChina"]&&p["leagueRe"+'p']>=0x4&&"att"===p["posGroup"];
},
  'desc': "对面中锋是凯恩。他背身拿球的那一下，你想起教练说的那句话：跟他对位的中卫，没有一个能完整踢满九十分钟的。",
  'options': [
    {
        'label': "从身后绞住他",
        'p': function(p){
return f(0.3,[[p["ovr"],0x4e,0.018],[p["roleRank"],0x3,0.04]],0.08,0.7);
},
        'hint': function(p,q){
return g(q,"他一脚出球都没做成","他转身把你扛开");
},
        'apply': function(p,q,s){
return d(q,s)?{'ovr':0x4,'fame':0x1e,'roleDelta':0x1,'text':"你从身后卡住他接球的左脚，他整场只有两次舒服转身。赛后他拍拍你的肩膀：「你比上一场那个后卫硬。」你不知道他记得你。"}:{'ovr':-0x2,
'roleDelta':-0x1,'fame':0x6,'text':"他把胸口停的球顺势一挑，从你头顶转了过去，你拉倒了他，吃到一张黄牌。他躺在地上朝你笑了笑，像什么都没发生。"};
}
    },
    {
        'label': "绕前,不让他起脚",
        'hint': "稳,把球放给对方",
        'apply': function(){
return{'clean':0x4,'ovr':0x1,'text':"你整场站在他身前，他拿到球的次数不多，但每次回做都让队友进了球。赛后没人夸你，因为比分不好看。你记得自己没有一次被他扛开。"};
}
    }
  ]
},

// ---- idx:226 | star_tea | 更衣室里那个位置 ----
{
  'id': "star_tea"+"mmate",
  'title': "更衣室里那个位置",
  'icon': '👕',
  'weight': 0x96,
  'when': function(p){
return!p["inChina"]&&p["leagueRe"+'p']>=0x4&&p["clubRep"]>=0x4;
},
  'desc': "球队官宣了一笔全欧洲都在谈的引援。介绍会那天，更衣室重新排了位置。你柜子旁边空着，管理员说那是留给他的。",
  'options': [
    {
        'label': "每天早到一小时，"+"跟着他练",
        'hint': "能力+4，钱-2"+'0',
        'apply': function(){
return{'ovr':0x4,'fame':0xa,'money':-0x14,'guanxi':0x6,'text':"他六点半到基地，你六点二十到。三个月，他只跟你说过两句完整的话，但你把他每次触球前的那半步都看会了。"};
}
    },
    {
        'label': "把位置和球权都让"+'出去',
        'hint': "地位-，但队里念"+"你的好",
        'apply': function(){
return{'roleDelta':-0x1,'guanxi':0xe,'clean':0x4,'text':"你主动改踢另一边，把最好的那块地方留给他。那个赛季你少进了六个球，球队多拿了一座奖杯。"};
}
    }
  ]
},

// ---- idx:227 | star_shi | 赛后换球衣 ----
{
  'id': "star_shi"+'rt',
  'title': "赛后换球衣",
  'icon': '🔁',
  'weight': 0x96,
  'when': function(p){
return!p["inChina"]&&p["leagueRe"+'p']>=0x4;
},
  'desc': "终场哨响，你朝中圈走去，想跟他换球衣。走到一半你发现，另外三个队友已经排在了前面。",
  'options': [
    {
        'label': "还是走过去",
        'hint': "名气+，被拍下来",
        'apply': function(){
return{'fame':0xc,'guanxi':0x4,'text':"他一眼认出你，把球衣先递了过来，说了句「中国来的那个」。那张照片在国内上了热搜第一，配文写着「他知道你」。"};
}
    },
    {
        'label': "转身回更衣室",
        'hint': "清白+，自己心里"+'有数',
        'apply': function(){
return{'clean':0x6,'ovr':0x1,'text':"你没有去。更衣室里，你把自己那件球衣塞进包里。下次见面，该是他先来找你换了。"};
}
    }
  ]
},

// ---- idx:228 | star_pre | 记者的那个问题 ----
{
  'id': "star_pre"+'ss',
  'title': "记者的那个问题",
  'icon': '🎤',
  'weight': 0x96,
  'when': function(p){
return!p["inChina"]&&p["leagueRe"+'p']>=0x4&&p["fame"]>=0x19;
},
  'desc': "赛后发布会，一个本地记者举手问：「你觉得自己有一天能踢到梅西那个级别吗？」整个房间都安静下来，等你开口。",
  'options': [
    {
        'label': "「我会努力」",
        'hint': "稳妥，谁也不得罪",
        'apply': function(){
return{'fame':0x4,'guanxi':0x6,'text':"你说了句标准答案。第二天，那段视频没有人转发。"};
}
    },
    {
        'label': "「我为什么不能」",
        'p': function(p){
return f(0.5,[[p["fame"],0x2d,0.006],[p["ovr"],0x4c,0.008]],0.2,0.82);
},
        'hint': function(p,q){
return g(q,"被当成硬气","被当成笑话");
},
        'apply': function(p,q,s){
return d(q,s)?{'fame':0x1a,'guanxi':0x4,'ovr':0x1,'text':"话一说完，全场安静了两秒，然后有人鼓掌。那句话被印上了当地报纸头版。从那以后，你每场都得踢得像是说过那句话的人。"}:{'fame':-0x8,
'guanxi':-0x6,'text':"那句话被剪成十五秒，配着他的过人集锦传遍全世界。你花了两个赛季，才让人们不再提起它。"};
}
    }
  ]
},

// ---- idx:229 | star_tra | 训练课上的一对一 ----
{
  'id': "star_tra"+"ining",
  'title': "训练课上的一对一",
  'icon': '🥅',
  'weight': 0x96,
  'when': function(p){
return!p["inChina"]&&p["leagueRe"+'p']>=0x4&&p["clubRep"]>=0x4;
},
  'desc': "小场对抗，分组分完，你发现自己这边站着莱万多夫斯基。教练吹哨前说：今天这块场地上，没有队友。",
  'options': [
    {
        'label': "往死里拼",
        'p': function(p){
return f(0.4,[[p["ovr"],0x4c,0.013]],0.12,0.75);
},
        'hint': function(p,q){
return g(q,"他记住了你","你受伤了");
},
        'apply': function(p,q,s){
return d(q,s)?{'ovr':0x3,'roleDelta':0x1,'guanxi':0x8,'text':"四十分钟，你一次都没让他舒服转身。收操时，他把手搭在你肩上，跟教练说了句什么。下一场，你首发。"}:{'ovr':-0x3,
'roleDelta':-0x1,'text':"最后一次拼抢，你落地的姿势不对，脚踝当场肿了起来。队医说三周，实际躺了七周。"};
}
    },
    {
        'label': "按训练量来",
        'hint': "不受伤，也不被记"+'住',
        'apply': function(){
return{'ovr':0x1,'text':"你跑完了教练要求的每一米，一次多余的拼抢都没有。收操时，他从你身边走过，没有停下来。"};
}
    }
  ]
},

// ---- idx:230 | star_ucl | 欧冠淘汰赛的那两 ----
{
  'id': "star_ucl",
  'title': "欧冠淘汰赛的那两"+'回合',
  'icon': '🌟',
  'weight': 0x96,
  'when': function(p){
return!p["inChina"]&&p["leagueRe"+'p']>=0x4&&p["hasCont"]&&p["roleRank"]>=0x3;
},
  'desc': "抽签结果出来，八分之一决赛的对手，是他所在的球队。国内转播在凌晨四点，所有人却说会熬夜看。",
  'options': [
    {
        'label': "把这两场当成自己"+"的决赛",
        'p': function(p){
return f(0.34,[[p["ovr"],0x4e,0.011],[p["fame"],0x2d,0.003]],0.1,0.72);
},
        'hint': function(p,q){
return g(q,"你成了那两回合的"+'主角',"被打成了背景板");
},
        'apply': function(p,q,s){
return d(q,s)?{'ovr':0x3,'fame':0x22,'roleDelta':0x1,'mult':{'cont':1.5},'text':h(p,{'gk':"两回合你扑了九次"+"，次回合终场前那"+"个单刀你用腿封住"+"了，保住了平局。",'def':"两回合他一次没进"+"，次回合终场前那"+"次回追解围保住了"+"平局。",'other':"两回合你一球一助"+"攻，次回合终场前"+"那次回追解围保住"+"了平局。"})+("赛后欧足联官方社"+"媒发了你的名字，"+"国内的热搜挂了整"+"整一天。")}:{'ovr':-0x2,
'fame':0xa,'text':"两回合，总比分 1-6。他一个人参与了四个球。"+h(p,{'gk':"第六个球进的时候"+"你还坐在门线上没"+"起来，镜头给了你"+"很久，",'other':"你被换下的时候镜"+"头给了你很久，"})+("第二天那张脸出现"+"在所有的赛后总结"+'里。')};
}
    },
    {
        'label': "照平时那样踢",
        'hint': "不出彩，也不难看",
        'apply': function(){
return{'fame':0x8,'guanxi':0x6,'text':"你守住了自己那块，球队总比分输了一个球。回到更衣室，没有人指责谁。教练说：下一次，我们还会来。"};
}
    }
  ]
},

// ---- idx:231 | star_sau | 沙漠里的那些名字 ----
{
  'id': "star_sau"+'di',
  'title': "沙漠里的那些名字",
  'icon': '🏜',
  'weight': 0x96,
  'when': function(p){
return!p["inChina"]&&"spl"===p["leagueId"];
},
  'desc': "转会到这里的第一周你就发现，这个联赛里，到处是小时候在电视上见过的人。下一轮对手阵中，有三个金球奖得主，年纪都比你大。",
  'options': [
    {
        'label': "把他们当偶像",
        'hint': "名气+，钱+",
        'apply': function(){
return{'fame':0x12,'money':0x3c,'guanxi':0x6,'text':"赛后，你跟每个人都合了影，发回国内的社交平台。有人骂你没出息，更多人说，这就是他们想过的人生。"};
}
    },
    {
        'label': "把他们当对手",
        'p': function(p){
return f(0.46,[[p["ovr"],0x4a,0.012],[p["age"],0x1c,-0.012]],0.15,0.8);
},
        'hint': function(p,q){
return g(q,"你赢了那一场","被上了一课");
},
        'apply': function(p,q,s){
return d(q,s)?{'ovr':0x3,'fame':0x14,'roleDelta':0x1,'text':h(p,{'gk':"你把他那记必进的"+"任意球托了出去，"+"没有喊，只是把球"+"门框拍了一下。",'def':"你贴了他整场，他"+"一次也没射正，赛"+"后你把球衣换给了"+'他。','other':"你在他们面前打进"+"了制胜球，没有庆"+"祝，只是走回中圈"+'。'})+("第二天当地媒体的"+"标题是「中国人不"+"给面子」。")}:{'ovr':-0x1,
'fame':0x6,'text':"三十九岁的他跑不动了，可每次拿球，都知道该往哪儿传。"+h(p,{'gk':"那三个球全是从你"+"没想到的角度来的"+"，每一个你都动了"+"，每一个都晚了半"+'拍。','other':"你追了九十分钟，"+"追到的全是他刚离"+"开的位置。"})};
}
    }
  ]
},

// ---- idx:306 | star_training2 | 大师的中场课 ----
{
  'id': "star_training2",
  'title': "大师的中场课",
  'icon': '🎯',
  'weight': 0x96,
  'when': function(p){return "mid"===p["posGroup"]&&!p["inChina"]&&p["leagueRep"]>=0x4&&p["clubRep"]>=0x4;},
  'desc': "俱乐部周年庆，请回了一位退役的中场大师给全队上课。分组对抗里，你和他分到了同一边。他看了你两眼，说：小伙子，敢不敢跟我比一脚出球？",
  'options': [
    {
        'label': "接下战书",
        'p': function(p){return f(0.42,[[p["ovr"],0x4c,0.012]],0.12,0.75);},
        'hint': function(p,q){return g(q,"大师点头","自取其辱");},
        'apply': function(p,q,s){return d(q,s)?{'ovr':0x3,'guanxi':0xa,'text':"二十分钟，你们俩没让球落地超过两次。收操时他把球踩住，对教练说：这孩子的眼睛是踢中场的眼睛。第二天，队内传球数据榜第一行换了名字。"}:{'ovr':-0x1,'text':"第三脚你就慢了半拍。他笑着摇摇头，把球挑到你身后。你没恼——那半天你一直盯着他的跑位看，笔记本上记满了字。"};}
    },
    {
        'label': "多看他怎么踢",
        'hint': "稳，学东西",
        'apply': function(){return{'ovr':0x2,'text':"你整个下午都在跟着他跑。他停球前的那半步、出球前的抬头，你都记在心里。训练结束他说：会看的孩子，比会踢的少，但走得远。"};}
    }
  ]
},

// ---- idx:307 | star_training3 | 门前的最后一课 ----
{
  'id': "star_training3",
  'title': "门前的最后一课",
  'icon': '⚽',
  'weight': 0x96,
  'when': function(p){return "att"===p["posGroup"]&&!p["inChina"]&&p["leagueRep"]>=0x4&&p["clubRep"]>=0x4;},
  'desc': "一位传奇射手受邀回俱乐部带一周射门特训。第一天他就叫住了你：我看你三场了，你跑位像在逛街。来，我教你什么叫「偷」。",
  'options': [
    {
        'label': "跟他学偷袭",
        'p': function(p){return f(0.42,[[p["ovr"],0x4c,0.012]],0.12,0.75);},
        'hint': function(p,q){return g(q,"开窍了","差点意思");},
        'apply': function(p,q,s){return d(q,s)?{'ovr':0x3,'text':"他让你蒙着眼在禁区里站了一下午，只听声音判断球的落点。周五的教学赛，你在两个人中间凭感觉插到了那个点。他在场边喊：就是这个！就是这一下！"}:{'ovr':-0x1,'text':"你按他说的跑了，队友的球却传去了别处。他拍拍你：急什么，我练了十年才有人懂往哪给我传。回去接着磨。"};}
    },
    {
        'label': "加练射门找状态",
        'hint': "稳妥",
        'apply': function(){return{'ovr':0x1,'text':"特训之外你自己加了五十脚。他路过看了几眼，没说话，只在临走时留下一句话：射门是练不完的，但脑子得先到位。"};}
    }
  ]
}

];
