// auto-generated by split_events.py - edit events here, then run build_events.py
// 转会邀约事件：复用 vet.ev.js 的邀约机制（window.SIM.vetInvitePool + rpick + _vetInviteTeam）。
// 受邀球队会在"合同到期后的本次转会窗"作为一份报价出现，并自动获得"正常年限 +2、至少 3 年"的合同；
// 若该队属于高价联赛（见 sim.js 的 _lgPay：沙特联/美职联/中超…），工资再抬 35%。

var EVT_transfer=[

// ---- idx:403 | vet_payday | 最后的肥约 ----
{
  'id': "vet_payday",
  'title': "最后的肥约",
  'icon': '💰',
  'weight': 0x50,
  'stage': "vet",
  'when': function(p){
    return p["age"]>=0x21&&!p["inAcademy"]&&p["leagueRep"]>=0x4&&p["contractFinal"]&&
      window["SIM"]["vetInvitePool"]({"lg":"spl","minRep":0x3})["length"]>0x0;
  },
  'desc': "经纪人的桌上摆着三份报价：沙特、美国，还有一份来自国内。每一份的年限都比你现在这份长，数字也都比现在这份厚。他们说的是同一句话——还来得及。",
  'options': [
    {'label': "去沙特联", 'hint': "三年合同，工资最高，联赛水平最低", 'apply': function(){
      var _p=window["SIM"]["vetInvitePool"]({"lg":"spl","minRep":0x3});
      if(!_p["length"])return{'text':"那边的人没有再打来电话。"};
      var _t=window["SIM"]["rpick"](_p);
      return{'_vetInviteTeam':_t['id'],'money':0x96,'fame':-0x4,'ovr':-0x2,'text':"你签了"+_t["name"]+"。数字大到你自己读了两遍。第一堂训练课，你在三十八度的太阳底下站了十分钟，才想起自己已经不是二十四岁了。"};
    }},
    {'label': "去美职联", 'hint': "三年合同，工资不错，日子清闲", 'apply': function(){
      var _p=window["SIM"]["vetInvitePool"]({"lg":"mls","minRep":0x2});
      if(!_p["length"])return{'text':"那边的名额满了，对方说下赛季再看看。"};
      var _t=window["SIM"]["rpick"](_p);
      return{'_vetInviteTeam':_t['id'],'money':0x6e,'fame':0x2,'ovr':-0x1,'text':"你去了"+_t["name"]+"。训练基地旁边就是海。第一次有人管你叫『经验老将』的时候，你在更衣室里笑了很久。"};
    }},
    {'label': "回中超", 'hint': "三年合同，钱多，离家近", 'apply': function(){
      var _p=window["SIM"]["vetInvitePool"]({"lg":"csl","minRep":0x2});
      if(!_p["length"])return{'text':"国内那家说，名额要留给年轻人。"};
      var _t=window["SIM"]["rpick"](_p);
      return{'_vetInviteTeam':_t['id'],'money':0xb4,'fame':0x6,'ovr':-0x2,'text':"你回到了"+_t["name"]+"。机场有人接机，横幅上写着你的名字。你妈在看台上，第一次看清了你胸前的号码。"};
    }},
    {'label': "再踢一年", 'hint': "地位+，关系+，收入不变", 'apply': function(){
      return{'roleDelta':0x1,'guanxi':0x6,'text':"你把三份报价都推了。你说你还想再听一次欧冠的开场哨。"};
    }}
  ]
},

// ---- idx:404 | bigclub_call | 那通来自豪门的电话 ----
{
  'id': "bigclub_call",
  'title': "那通来自豪门的电话",
  'icon': '📞',
  'weight': 0x50,
  'when': function(p){
    return p["age"]<=0x18&&p["ovr"]>=0x4e&&p["clubRep"]<=0x3&&!p["inAcademy"]&&p["contractFinal"]&&
      window["SIM"]["vetInvitePool"]({"lg":["epl","liga","bund","seri","l1"],"minRep":0x4})["length"]>0x0;
  },
  'desc': "赛季结束的第二天，一个陌生号码打进来。对方自报家门的时候，你下意识站直了——那是你小时候贴在墙上的那块队徽。",
  'options': [
    {'label': "去", 'hint': "更长合同，工资大涨，位置要重新抢", 'apply': function(){
      var _p=window["SIM"]["vetInvitePool"]({"lg":["epl","liga","bund","seri","l1"],"minRep":0x4});
      if(!_p["length"])return{'text':"电话那头说，再等等。"};
      var _t=window["SIM"]["rpick"](_p);
      return{'_vetInviteTeam':_t['id'],'fame':0xc,'roleDelta':-0x1,'text':"你签了"+_t["name"]+"。报到那天，训练场门口站着三家电视台。更衣室里坐着的人，你以前只在游戏里用过。"};
    }},
    {'label': "再留一年", 'hint': "能力+，地位+，关系+", 'apply': function(){
      return{'ovr':0x1,'roleDelta':0x1,'guanxi':0x6,'text':"你留下来了。教练拍着你的肩膀说：明年这个时候，他们还会打电话来。"};
    }}
  ]
}

];
