// auto-generated by split_events.py - edit events here, then run build_events.py
// 类型专属事件：每种球员类型（playerType）一条签名事件。
// 由 sim.js 赛季结算处的 forceQ 保证一生至少触发一次；也可被随机池抽到。
// 门将(11)已有 gk.ev.js 专属池，此处只覆盖 0..10。

var EVT_type=[

// ---- idx:387 | type_finisher | 禁区猎手 ----
{
  'id': "type_finisher",
  'title': "禁区猎手",
  'icon': '🎯',
  'weight': 0x50,
  'stage': "prime",
  'when': function(p){return "att"===p["posGroup"]&&0x0===p["playerType"];},
  'desc': "你这种前锋，一场可能只碰三次球。教练说：三次里，你得进一个。",
  'options': [
    {'label': "把抢点练成直觉", 'p': function(p){return f(0.65,[[p["talent"],1.2,0.35]],0.25,0.9);}, 'hint': function(p,q){return g(q,"射术精进","越练越独");}, 'apply': function(p,q,s){return d(q,s)?{'ovr':0x4,'fame':0x8,'text':"禁区里那半秒，别人还在判断，你已经把球捅进去了。这个赛季你的进球，有一半是门前一脚出球。"}:{'ovr':-0x1,'roleDelta':-0x1,'text':"你眼里只剩下球门。队友跑出空位你也不传，一个赛季下来，边路的人开始不给你喂球了。"};}},
    {'label': "也学着给队友做球", 'hint': "助攻涨，进球少", 'apply': function(){return{'ovr':0x2,'fame':-0x3,'text':"你多了六次助攻，进球数掉了三分之一。教练说这是进步，射手榜不这么看。"};}}
  ]
},

// ---- idx:388 | type_playmaker | 慢半拍的节拍器 ----
{
  'id': "type_playmaker",
  'title': "慢半拍的节拍器",
  'icon': '🎼',
  'weight': 0x50,
  'stage': "prime",
  'when': function(p){return ("att"===p["posGroup"]||"mid"===p["posGroup"])&&0x1===p["playerType"];},
  'desc': "球要先在你脚下过一次。有人嫌你慢，教练说：那不叫慢，那叫让人跟着你跑。",
  'options': [
    {'label': "把球权攥在手里", 'p': function(p){return f(0.62,[[p["talent"],1.2,0.35]],0.25,0.9);}, 'hint': function(p,q){return g(q,"球队大脑","被断反击");}, 'apply': function(p,q,s){return d(q,s)?{'ovr':0x3,'fame':0x8,'text':"全队的进攻都要从你脚下过一次。有解说开始叫你节拍器，虽然你一场也就传了六十脚球。"}:{'ovr':-0x2,'fame':-0x8,'roleDelta':-0x1,'text':"对手开始贴身抢你。你有三场丢球，都直接变成了对方的进球。教练让你少拿球。"};}},
    {'label': "提速，往身后塞", 'hint': "助攻+，失误多", 'apply': function(){return{'ovr':0x2,'fame':0x2,'text':"你把出球时间缩短了一半。助攻上去了，成功率下来了。数据表两边都在涨。"};}}
  ]
},

// ---- idx:389 | type_complete | 哪儿缺人往哪儿放 ----
{
  'id': "type_complete",
  'title': "哪儿缺人往哪儿放",
  'icon': '🧩',
  'weight': 0x50,
  'stage': "prime",
  'when': function(p){return "gk"!==p["posGroup"]&&0x2===p["playerType"];},
  'desc': "排阵的时候，教练先写下你的名字，再想你到底该站哪儿。",
  'options': [
    {'label': "什么位置都接", 'hint': "地位↑，专项一般", 'apply': function(){return{'ovr':0x2,'roleDelta':0x2,'text':"中场缺人你去中场，后防缺人你退回去。一个赛季你踢了四个位置，教练说，有你这样的球员，他敢打任何阵型。"};}},
    {'label': "只练一个位置", 'p': function(p){return f(0.55,[[p["ovr"],60,0.008]],0.25,0.9);}, 'hint': function(p,q){return g(q,"练出看家本事","位置被人占了");}, 'apply': function(p,q,s){return d(q,s)?{'ovr':0x4,'text':"你把一个位置练到了别人抢不走。教练再想让你客串时，你先看的是自己的数据，不是他的眼神。"}:{'ovr':0x1,'roleDelta':-0x1,'text':"你挑了位置，也丢掉了别的可能。那个位置后来来了个更年轻的人，你坐了两轮板凳。"};}}
  ]
},

// ---- idx:390 | type_pace | 前五米 ----
{
  'id': "type_pace",
  'title': "前五米",
  'icon': '⚡',
  'weight': 0x50,
  'stage': "prime",
  'when': function(p){return ("att"===p["posGroup"]||"def"===p["posGroup"])&&0x3===p["playerType"];},
  'desc': "你的球感一般，但前五米没几个人跟得上。教练说，那就把前五米练到极致。",
  'options': [
    {'label': "往死里练冲刺", 'p': function(p){return f(0.6,[[p["talent"],1.1,0.35]],0.25,0.9);}, 'hint': function(p,q){return g(q,"边路爆点","拉伤");}, 'apply': function(p,q,s){return d(q,s)?{'ovr':0x4,'fame':0x8,'text':"你成了球队最直接的那条路。对手的边后卫赛前看你的录像，看得最多。"}:{'ovr':-0x2,'health':1.15,'text':"大腿后侧那一下，你听见了声音。之后每次启动，你都先想半秒——那半秒，就没了。"};}},
    {'label': "学着省着用", 'hint': "少受伤，存在感低", 'apply': function(){return{'health':0.85,'ovr':0x1,'roleDelta':-0x1,'text':"你学会了一场只爆发五六次。身体是保住了，可教练开始说你不够积极。"};}}
  ]
},

// ---- idx:391 | type_target | 背身那一下 ----
{
  'id': "type_target",
  'title': "背身那一下",
  'icon': '🪨',
  'weight': 0x50,
  'stage': "prime",
  'when': function(p){return "att"===p["posGroup"]&&0x4===p["playerType"];},
  'desc': "你背对着球门要球，中卫整个人贴上来。全队都在等你把那口气顶住。",
  'options': [
    {'label': "硬扛，把球做出来", 'p': function(p){return f(0.62,[[p["talent"],1.1,0.35]],0.25,0.9);}, 'hint': function(p,q){return g(q,"支点作用","被撞散");}, 'apply': function(p,q,s){return d(q,s)?{'ovr':0x3,'fame':0x6,'text':"你一场要背身接二十次球，扛住十九次。队友开始习惯把球往你头上开，因为他们知道你能把它停下来。"}:{'ovr':-0x2,'health':1.1,'text':"那个中卫比你重十公斤。一个赛季下来，你的腰和膝盖都不是原来的了。"};}},
    {'label': "不再背身，改抢点", 'hint': "少挨撞，地位降", 'apply': function(){return{'ovr':0x2,'roleDelta':-0x1,'text':"你不再去当那个支点。球队的打法没变，可中锋的位置上，站了另一个人。"};}}
  ]
},

// ---- idx:392 | type_shadow | 没人盯你 ----
{
  'id': "type_shadow",
  'title': "没人盯你",
  'icon': '👤',
  'weight': 0x50,
  'stage': "prime",
  'when': function(p){return ("att"===p["posGroup"]||"mid"===p["posGroup"])&&0x5===p["playerType"];},
  'desc': "对手的后腰整场都在找一个人。而他，总在你身后。",
  'options': [
    {'label': "在两线之间游走", 'p': function(p){return f(0.6,[[p["talent"],1.2,0.35]],0.25,0.9);}, 'hint': function(p,q){return g(q,"防不胜防","被教练批评");}, 'apply': function(p,q,s){return d(q,s)?{'ovr':0x3,'fame':0x8,'text':"你总站在后卫和后腰之间那条缝里。这个赛季你进的球，有九个是在禁区弧顶附近等来的。"}:{'ovr':-0x1,'roleDelta':-0x1,'text':"你等球等得太多。教练说，我们要的是参与进攻的人，不是站在场上等机会的人。"};}},
    {'label': "回中场拿球", 'hint': "触球多，威胁少", 'apply': function(){return{'ovr':0x2,'guanxi':0x4,'text':"你回撤到中场接应，触球数涨了一倍。禁区里的人少了你一个，进球也少了几粒。"};}}
  ]
},

// ---- idx:393 | type_b2b | 两头都到 ----
{
  'id': "type_b2b",
  'title': "两头都到",
  'icon': '🔁',
  'weight': 0x50,
  'stage': "prime",
  'when': function(p){return "mid"===p["posGroup"]&&0x6===p["playerType"];},
  'desc': "数据显示你这季跑了一万三千米。教练说，跑得多不算本事，跑对了才算。",
  'options': [
    {'label': "两个禁区之间来回", 'hint': "能力+，磨损大", 'apply': function(){return{'ovr':0x3,'roleDelta':0x1,'health':1.15,'text':"你成了球队唯一一个既进禁区又回禁区的人。数据很好看，队医看着你的跑动图，摇了摇头。"};}},
    {'label': "守在中场，别乱跑", 'hint': "少受伤，上限低", 'apply': function(){return{'ovr':0x1,'health':0.85,'text':"你把自己钉在中圈附近。跑动数掉下来了，伤病也少了，可教练说，你不像原来那个你了。"};}}
  ]
},

// ---- idx:394 | type_anchor | 把他吃掉 ----
{
  'id': "type_anchor",
  'title': "把他吃掉",
  'icon': '⛓️',
  'weight': 0x50,
  'stage': "prime",
  'when': function(p){return "mid"===p["posGroup"]&&0x7===p["playerType"];},
  'desc': "教练给你的任务只有一句：对方那个十号去哪儿，你去哪儿。",
  'options': [
    {'label': "贴身死缠", 'p': function(p){return f(0.6,[[p["ovr"],60,0.008]],0.25,0.9);}, 'hint': function(p,q){return g(q,"对方哑火","吃牌停赛");}, 'apply': function(p,q,s){return d(q,s)?{'ovr':0x2,'fame':0x4,'guanxi':-0x4,'text':"那场对方核心全场只摸了二十次球。终场哨响，他没跟你握手。"}:{'banGames':0x2,'roleDelta':-0x1,'fame':-0x4,'text':"你把他铲翻在中圈。黄牌，累积停赛两场。教练没说你什么，只是那两场你只能看电视。"};}},
    {'label': "靠站位，不靠身体", 'hint': "稳，能力+3", 'apply': function(){return{'ovr':0x3,'clean':0x4,'text':"你不追人，只堵线路。一个赛季只吃了四张黄牌，抢断数却是全队第一。"};}}
  ]
},

// ---- idx:395 | type_fullback | 整条边都是你的 ----
{
  'id': "type_fullback",
  'title': "整条边都是你的",
  'icon': '🏃',
  'weight': 0x50,
  'stage': "prime",
  'when': function(p){return "def"===p["posGroup"]&&0x8===p["playerType"];},
  'desc': "教练要你从自己底线跑到对面底线，九十分钟，两趟。",
  'options': [
    {'label': "两头都要到", 'p': function(p){return f(0.6,[[p["talent"],1.1,0.35]],0.25,0.9);}, 'hint': function(p,q){return g(q,"攻防一体","身后被打穿");}, 'apply': function(p,q,s){return d(q,s)?{'ovr':0x3,'fame':0x6,'text':"你一个赛季送出十次助攻。有球探在报告里写：他一个人能踢一条边。"}:{'ovr':-0x1,'health':1.1,'roleDelta':-0x1,'text':"你上去了，身后那块地就空了。对手专打你这一侧，教练最后让你少压。"};}},
    {'label': "守好自己那侧", 'hint': "稳，能力+2", 'apply': function(){return{'ovr':0x2,'health':0.9,'text':"你不怎么过半场了。丢球少了，助攻也少了。这份工作，本来就不靠数据证明。"};}}
  ]
},

// ---- idx:396 | type_libero | 最后一道 ----
{
  'id': "type_libero",
  'title': "最后一道",
  'icon': '🧭',
  'weight': 0x50,
  'stage': "prime",
  'when': function(p){return "def"===p["posGroup"]&&0x9===p["playerType"];},
  'desc': "你拖在整条防线后面。他们每漏一个人，都得靠你兜住。",
  'options': [
    {'label': "拖后补位，顺便出球", 'p': function(p){return f(0.6,[[p["talent"],1.2,0.35]],0.25,0.9);}, 'hint': function(p,q){return g(q,"后场大脑","补不过来");}, 'apply': function(p,q,s){return d(q,s)?{'ovr':0x3,'fame':0x5,'text':"你一边补位一边出球，把后卫线往前推了五米。有人说你是这支球队最像教练的人。"}:{'ovr':-0x2,'fame':-0x8,'text':"你一个人补三个人的位置。有一场你慢了半步，全队被对手打了一个三打一。"};}},
    {'label': "往前压，当后腰用", 'hint': "参与进攻，后场空", 'apply': function(){return{'ovr':0x3,'roleDelta':-0x1,'text':"你不再老老实实待在最后。教练喜欢你的出球，可他不放心把身后那片地方交给你。"};}}
  ]
},

// ---- idx:397 | type_stopper | 禁区是他的 ----
{
  'id': "type_stopper",
  'title': "禁区是他的",
  'icon': '🛡️',
  'weight': 0x50,
  'stage': "prime",
  'when': function(p){return "def"===p["posGroup"]&&0xa===p["playerType"];},
  'desc': "你的防区里没有优雅。只有先碰到球，或者先碰到人。",
  'options': [
    {'label': "贴身肉搏", 'p': function(p){return f(0.6,[[p["ovr"],60,0.008]],0.25,0.9);}, 'hint': function(p,q){return g(q,"前锋怕你","送点停赛");}, 'apply': function(p,q,s){return d(q,s)?{'ovr':0x2,'fame':0x4,'roleDelta':0x1,'text':"那个赛季没有前锋愿意往你这边冲。你身上全是淤青，队里没人比你更让人放心。"}:{'banGames':0x2,'clean':-0x4,'fame':-0x4,'text':"你又一次在禁区里把人放倒了。这次主裁吹了点球，还给了你第二张黄牌。"};}},
    {'label': "靠预判站着防", 'hint': "干净，能力+3", 'apply': function(){return{'ovr':0x3,'clean':0x4,'text':"你开始用站位代替身体。犯规数掉了一半，可队友说，你好像没那么狠了。"};}}
  ]
}

];
