// auto-generated by split_events.py - edit events here, then run build_events.py

var EVT_vet=[

// ---- idx:80 | vet_drop | 往回撤 ----
{
  'id': "vet_drop"+"back",
  'title': "往回撤",
  'icon': '🔙',
  'weight': 0x32,
  'stage': "vet",
  'when': function(p){
return "att"===p["posGroup"]||"mid"===p["posGroup"];
},
  'desc': "教练说你跑不动前场了，但脑子还在。他想让你后撤一条线。",
  'options': [
    {
        'label': "往后撤",
        'hint': "能力+3，地位回"+'升',
        'apply': function(){
return{'ovr':0x3,'roleDelta':0x1,'text':"你从抢点的人变成"+"了传球的人。数据"+"不好看了，球队赢"+"球多了。"};
}
    },
    {
        'p': function(p){return f(0.5,[[p["ovr"],60,0.008]],0.2,0.9);
},
        'label': "我还能冲",
        'hint': function(p,q){return g(q,'再战两年','彻底掉队');
},
        'apply': function(p,q,s){
return d(q,s)?{'ovr':0x1,'fame':0x6,'text':"你用两个赛季证明了自己还行。看台上，有人举着「别退」的牌子。"}:{'ovr':-0x4,'roleDelta':-0x2,'text':"你和二十四岁的人抢一个位置，抢了半年，输得很干净。"};
}
    }
  ]
},

// ---- idx:180 | vet_last | 最后一份合同 ----
{
  'id': "vet_last"+"_contrac"+'t',
  'title': "最后一份合同",
  'icon': "🖊️",
  'weight': 0x37,
  'stage': "vet",
  'desc': "俱乐部只肯签一年，工资砍掉六成，附加条款只有一条：带好那几个年轻人。",
  'options': [
    {
        'label': "签字",
        'hint': "钱少，踢得久",
        'apply': function(){
return{'money':0x1e,'guanxi':0xc,'roleDelta':-0x1,'text':"更衣室里，你说的话越来越有分量；工资单上，你的名字却越来越靠下。"};
}
    },
    {
        'p': function(p){return f(0.5,[[p["ovr"],60,0.008]],0.2,0.9);
},
        'label': "去别处找主力位置",
        'hint': function(p,q){return g(q,'找到了','没人要');
},
        'apply': function(p,q,s){
return d(q,s)?{'leave':!0x0,'ovr':0x1,'fame':0x6,'text':"低一级的球队递来两年合同和十号球衣。你在那儿，一路踢到三十九岁。"}:{'roleDelta':-0x2,'money':-0x28,
'text':"整个冬窗，手机没响过一次。一直熬到三月，才有一支队愿意让你试训。"};
}
    }
  ]
},

// ---- idx:181 | vet_benc | 板凳上的一年 ----
{
  'id': "vet_benc"+"h_year",
  'title': "板凳上的一年",
  'icon': '🪑',
  'weight': 0x34,
  'stage': "vet",
  'desc': "一个赛季你只上场四次，全在补时。汗还没出，哨就响了。",
  'options': [
    {
        'label': "留下带队",
        'hint': "关系+，能力继续"+'掉',
        'apply': function(){
return{'guanxi':0x10,'ovr':-0x2,'fame':0x4,'text':"你成了队里半个教练。年轻人有事总来问你；主帅，从不问你。"};
}
    },
    {
        'label': "降级去踢主力",
        'hint': "能力+2，名气-",
        'apply': function(){
return{'leave':!0x0,'ovr':0x2,'fame':-0x8,'text':"你往下走了一级，领回十号球衣。新看台上，不少人专程为你而来。"};
}
    }
  ]
},

// ---- idx:182 | vet_coac | 教练组的位置 ----
{
  'id': "vet_coac"+"h_offer",
  'title': "教练组的位置",
  'icon': '📋',
  'weight': 0x30,
  'stage': "vet",
  'desc': "俱乐部递来一个位置：退役后进教练组。前提是，这个赛季打完就挂靴。",
  'options': [
    {
        'label': '答应',
        'hint': "提前退役，退路有"+'了',
        'apply': function(){
return{'retire':!0x0,'money':0x3c,'coachCert':!0x0,'guanxi':0x10,'text':"最后一个主场，全场起立送你。第二周，你换了身队服，站到教练席后面。"};
}
    },
    {
        'p': function(p){return f(0.5,[[p["ovr"],60,0.008]],0.2,0.9);
},
        'label': "我还能踢",
        'hint': function(p,q){return g(q,'又踢了三年','位置也没了');
},
        'apply': function(p,q,s){
return d(q,s)?{'ovr':0x1,'fame':0x8,'text':"你又踢了三年。教练席上那个位置，也一直给你留着。"}:{'roleDelta':-0x2,'guanxi':-0xa,'text':"第二年，你踢不动了，教练组也换了人。这一头，那一头，都没赶上。"};
}
    }
  ]
},

// ---- idx:183 | vet_assi | 留下来带年轻人 ----
{
  'id': "vet_assi"+"stant",
  'title': "留下来带年轻人",
  'icon': '🧤',
  'weight': 0x2e,
  'stage': "vet",
  'when': function(p){
return p["seasonsA"+"tClub"]>=0x3;
},
  'desc': "青训总监找你喝茶：踢不动了，就留下来，一线队助教的位置给你留着，带那批十八九岁的孩子。",
  'options': [
    {
        'label': "答应下来",
        'hint': "退役后留在队里，"+"收入一般",
        'apply': function(){
return{'money':-0x14,'guanxi':0x12,'assistant':!0x0,'text':"你说，好。那天下午照常训练，只是你看年轻人的眼神，和以前不一样了。"};
}
    },
    {
        'label': "先不想这些",
        'hint': "专心踢球，能力+"+'2',
        'apply': function(){
return{'ovr':0x2,'text':"你说，等踢不动了再说。他笑了笑：这话，每个退役的人都讲过。"};
}
    }
  ]
},

// ---- idx:184 | vet_scou | 球探的差事 ----
{
  'id': "vet_scou"+'t',
  'title': "球探的差事",
  'icon': '🔎',
  'weight': 0x2c,
  'stage': "vet",
  'when': function(p){
return p["age"]>=0x22;
},
  'desc': "有家俱乐部想请你退役后当球探：一年三万公里，看的全是没人愿意看的比赛。",
  'options': [
    {
        'label': '接了',
        'hint': "退役后有事做，钱"+'不多',
        'apply': function(){
return{'money':0x1e,'guanxi':0xa,'scout':!0x0,'text':"你翻了翻行程表：小镇，雨天，再小镇。你合上本子说，这活儿，我干得来。"};
}
    },
    {
        'p': function(p){return f(0.5,[[p["guanxi"],45,0.008]],0.2,0.9);
},
        'label': '不去',
        'hint': "名气+，退路少一"+'条',
        'apply': function(p,q,s){
return d(q,s)?{'fame':0xa,'money':0x28,'text':"你去跑商业活动，穿得体面，笑得很职业。说的话，没几个人记得。"}:{'fame':-0x4,'text':"谁的电话你都没接。那一年，日子过得很慢。"};
}
    }
  ]
},

// ---- idx:185 | vet_test | 告别赛 ----
{
  'id': "vet_test"+"imonial",
  'title': "告别赛",
  'icon': '🎆',
  'weight': 0x2d,
  'stage': "vet",
  'when': function(p){
return p["seasonsA"+"tClub"]>=0x4;
},
  'desc': "俱乐部想给你办场告别赛，票房全归你。也有人劝：别办，太像作秀。",
  'options': [
    {
        'label': "办一下",
        'hint': "钱+名气+",
        'apply': function(){
return{'money':0xdc,'fame':0x18,'guanxi':0xa,'text':"来了两万人。上半场你踢了二十分钟，下半场坐回替补席，看年轻人踢。"};
}
    },
    {
        'label': '不办',
        'hint': "清白+，安静退场",
        'apply': function(){
return{'clean':0x6,'fame':-0x4,'text':"最后一场哨响，你自己走到中圈，鞠了一躬，转身回更衣室。没有仪式。"};
}
    }
  ]
},

// ---- idx:186 | vet_drop | 往下走一级 ----
{
  'id': "vet_drop"+"_league",
  'title': "往下走一级",
  'icon': '⬇️',
  'weight': 0x32,
  'stage': "vet",
  'desc': "{league}已经没有球队要你了。往低走一级，倒有两支队伍，愿意给你主力位置。",
  'options': [
    {
        'label': "往下走",
        'hint': "能力+2，联赛降"+'级',
        'apply': function(){
return{'leave':!0x0,'ovr':0x2,'money':-0x14,'text':"客场大巴、水泥看台、拖欠的奖金，一样不少地回来了。可你每周，都能踢满九十分钟。"};
}
    },
    {
        'p': function(p){return f(0.5,[[p["ovr"],60,0.008]],0.2,0.9);
},
        'label': "耗到没人要为止",
        'hint': function(p,q){return g(q,'有人捡漏','直接退役');
},
        'apply': function(p,q,s){
return d(q,s)?{'roleDelta':-0x1,'text':"三月份，一支保级队伤了人，临时把你签下。你替他们踢了十一场。"}:{'retire':!0x0,'text':"你一直等到六月。手机，没响过。"};
}
    }
  ]
},

// ---- idx:187 | vet_medi | 体检没过 ----
{
  'id': "vet_medi"+"cal_fail",
  'title': "体检没过",
  'icon': '🩻',
  'weight': 0x2d,
  'stage': "vet",
  'desc': "转会都谈妥了。体检报告出来的那天，对方打来电话，只说了句「很遗憾」。",
  'options': [
    {
        'p': function(p){return f(0.55,[[p["ovr"],60,0.008]],0.2,0.9);
},
        'label': "去别的医院再查",
        'hint': function(p,q){return g(q,'翻案','坐实');
},
        'apply': function(p,q,s){
return d(q,s)?{'money':-0x14,'ovr':0x1,'text':"另一家医院给出完全相反的结论。合同最终照签，只是晚了十天。"}:{'money':-0x14,'ovr':-0x3,'roleDelta':-0x1,
'text':"三家医院，口径一致。你这才知道，那块软骨已经磨了很多年。"};
}
    },
    {
        'label': "认了，找个不体检"+'的队',
        'hint': "能力-，有球踢",
        'apply': function(){
return{'leave':!0x0,'ovr':-0x2,'money':-0x1e,'text':"一支低一级的球队，没让你体检就签了字。后来他们知道了，也没多问。"};
}
    }
  ]
},

// ---- idx:188 | vet_comm | 解说席的邀请 ----
{
  'id': "vet_comm"+"entary",
  'title': "解说席的邀请",
  'icon': '🎧',
  'weight': 0x2d,
  'stage': "vet",
  'desc': "电视台想请现役球员当嘉宾解说，一场两万，代价是得评点同行。",
  'options': [
    {
        'label': '去说',
        'hint': "钱+名气+，得罪"+'人',
        'apply': function(){
return{'money':0x3c,'fame':0x12,'guanxi':-0xc,'text':"你对着麦克风说了句：「这个球，换我不会那么处理。」第二天，那个球员退了共同所在的群。"};
}
    },
    {
        'label': '不去',
        'hint': "无变化",
        'apply': function(){
return{'text':"你说自己还在踢，不合适。电视台转头，找了个刚退役的。"};
}
    }
  ]
},

// ---- idx:189 | vet_acad | 合伙办个班 ----
{
  'id': "vet_acad"+"emy",
  'title': "合伙办个班",
  'icon': "🏟️",
  'weight': 0x2c,
  'stage': "vet",
  'when': function(p){
return p["money"]>=0x12c;
},
  'desc': "退役两年的老队友找上门来：租块场地办个青训班，他跑手续、带训练，就差一个肯把名字挂在门口的人。",
  'options': [
    {
        'p': function(p){return f(0.55,[[p["guanxi"],45,0.008]],0.2,0.9);
},
        'label': "出钱，名字也挂上",
        'hint': function(p,q){return g(q,'招得满','砸手里');
},
        'apply': function(p,q,s){
return d(q,s)?{'money':-0x3c,'fame':0x8,'academy':!0x0,'text':"第一批来了三十几个孩子，家长是冲着门口那块牌子来的。你每周去两趟，站在场边，不说话。"}:{'money':-0x104,
'fame':-0x6,'text':"招生只来了九个。退场地那天，你去帮忙搬球门。老队友说下次再找你，你说，好。"};
}
    },
    {
        'p': function(p){return f(0.5,[[p["clean"],70,0.008]],0.2,0.9);
},
        'label': "只借名字，不出钱",
        'hint': function(p,q){return g(q,'相安无事','出事算你的');
},
        'apply': function(p,q,s){
return d(q,s)?{'money':0x5a,'text':"你签了张授权书，每年分一笔。那个班后来办得如何，你再没问过。"}:{'money':0x5a,'fame':-0x14,'clean':-0x8,'text':"有家长把收费单晒到网上，落款是你的名字。你这才知道，一年收两万四。"};
}
    },
    {
        'label': "不掺和",
        'hint': "无变化",
        'apply': function(){
return{'text':"你说自己不懂经营。他点了点头，走的时候，把那包烟留在了桌上。"};
}
    }
  ]
},

// ---- idx:296 | vet_wall | 撞上体能墙 ----
{
  'id': "vet_wall",
  'title': "撞上体能墙",
  'icon': '🧱',
  'weight': 0x3c,
  'stage': "vet",
  'when': function(p){return p["age"]>=0x22&&p["age"]<=0x24&&p["posGroup"]!=='gk';},
  'desc': "冬歇期后的队内体能测试，你第一次跑不过队里两个二十岁的小将。教练没说话，只是在训练表上把你从「全勤」那一栏圈了出来。",
  'options': [
    {
        'label': "调整训练，学着省着踢",
        'p': function(p){return f(0.7,[[p["talent"],1,0.3]],0.3,0.9);},
        'hint': function(p,q){return g(q,"延长职业生涯","状态下滑");},
        'apply': function(p,q,s){return d(q,s)?{'ovr':0x2,'health':0.95,'roleDelta':-0x1,'text':"你开始少跑那些没用的距离，把力气留给最关键的时刻。教练嘴上不说，季末总结时把你排进了「贡献榜」前三。"}:{'ovr':-0x2,'roleDelta':-0x2,'text':"你想省着踢，可节奏一降就回不来了。首发位置，让给了比你小十岁的孩子。"};}
    },
    {
        'label': "加练，拼一把",
        'p': function(p){return f(0.4,[[p["clean"],60,0.005]],0.2,0.8);},
        'hint': function(p,q){return g(q,"找回状态","膝盖先报警");},
        'apply': function(p,q,s){return d(q,s)?{'ovr':0x3,'text':"你比别人早到两小时，把体能的账一笔一笔还回去。第二次测试，你排回了队内前五。"}:{'ovr':-0x3,'health':1.15,'roleDelta':-0x1,'text':"量太大了。第三周，你的膝盖先提了抗议，队医说，这个年纪不该这么练。"};}
    }
  ]
},

// ---- idx:297 | vet_mentor | 把绝活传下去 ----
{
  'id': "vet_mentor",
  'title': "把绝活传下去",
  'icon': '📖',
  'weight': 0x3e,
  'stage': "vet",
  'when': function(p){return p["age"]>=0x21&&p["roleRank"]>=0x3;},
  'desc': "队里来了个十八岁的小将，位置和你一模一样。他每天加练后都会站在场边看你，眼睛亮得像刚踢球时的你。",
  'options': [
    {
        'label': "多带他，传点真东西",
        'p': function(p){return f(0.65,[[p["guanxi"],45,0.008]],0.3,0.9);},
        'hint': function(p,q){return g(q,"后继有人","教出个抢班夺权的");},
        'apply': function(p,q,s){return d(q,s)?{'guanxi':0xa,'roleDelta':-0x1,'fame':0x6,'text':"你教他停球，教他跑位，教他怎么在禁区里「借力」。几个月后他在预备队戴了帽子，新闻里说「师承XXX」。"}:{'guanxi':0x4,'roleDelta':-0x2,'text':"你倾囊相授。年底他进了首发，你的名字，渐渐只在新闻的「历任」里出现。"};}
    },
    {
        'label': "留一手",
        'hint': "保住位置",
        'apply': function(){return{'roleDelta':0x1,'guanxi':-0x3,'text':"你嘴上应着，练的时候总留一手。他球技长得快，可看你的眼神，慢慢就淡了。"};}
    }
  ]
},

// ---- idx:298 | vet_planning | 退役后的路 ----
{
  'id': "vet_planning",
  'title': "退役后的路",
  'icon': '🧭',
  'weight': 0x3a,
  'stage': "vet",
  'when': function(p){return p["age"]>=0x23;},
  'desc': "经纪人问你，挂靴之后想干什么。他说现在开始铺路，五年后退役那天就有一份新身份等着你。",
  'options': [
    {
        'label': "考教练证",
        'p': function(p){return f(0.6,[[p["fame"],30,0.006]],0.3,0.9);},
        'hint': function(p,q){return g(q,"退役即上岗","证没考下来");},
        'apply': function(p,q,s){return d(q,s)?{'clean':0x3,'fame':0x4,'text':"你报了教练班，和一群刚退役的老家伙当同学。结业那天，你拿着证拍了张照，背景是训练场。"}:{'money':-0x32,'text':"课程费交了，可你实在腾不出时间。那张报名表，最后被夹进了旧杂志里。"};}
    },
    {
        'label': "做点生意",
        'p': function(p){return f(0.5,[[p["money"],300,0.004]],0.2,0.8);},
        'hint': function(p,q){return g(q,"有份副业","亏了钱");},
        'apply': function(p,q,s){return d(q,s)?{'money':0x96,'fame':0x2,'text':"你投了一家青训机构，挂你的名字招生，生源不错。你偶尔去露个面，教孩子们踩单车。"}:{'money':-0x78,'text':"合伙人的账越算越糊涂。你退了股，那笔钱够你再踢三年。"};}
    },
    {
        'label': "先不想，踢到踢不动",
        'hint': "专心踢球",
        'apply': function(){return{'roleDelta':0x1,'text':"你把电话挂了。现在你脑子里只有下一场比赛，退役的事，等最后一场踢完再说。"};}
    }
  ]
},

// ---- idx:299 | vet_swan | 最后一舞 ----
{
  'id': "vet_swan",
  'title': "最后一舞",
  'icon': '💃',
  'weight': 0x40,
  'stage': "vet",
  'when': function(p){return p["age"]>=0x25;},
  'desc': "俱乐部宣布，下一场主场是你的「告别演出」——球衣印着纪念字样，看台上有人举着你的号码牌。",
  'options': [
    {
        'label': "拼尽全力",
        'p': function(p){return f(0.5,[[p["ovr"],60,0.006]],0.2,0.85);},
        'hint': function(p,q){return g(q,"再进一球","遗憾收场");},
        'apply': function(p,q,s){return d(q,s)?{'fame':0x14,'ovr':0x2,'text':"补时第93分钟，你在大禁区外轰出一脚世界波。全场的手机闪光灯对着你，像一片星海。赛后他们说，这是最好的告别。"}:{'fame':0x6,'text':"你拼到了抽筋。哨响时你跪在中圈，看台上的掌声，比你想象中响。"};}
    },
    {
        'label': "给年轻人让路",
        'hint': "队内地位降，关系升",
        'apply': function(){return{'roleDelta':-0x2,'guanxi':0x8,'text':"你把最后一次首发让给了队里的小将。你坐在替补席看完了整场，年轻人进了球，朝你的方向跑来。"};}
    }
  ]
},

// ---- idx:300 | vet_benchwarmer | 年轻人的替补 ----
{
  'id': "vet_benchwarmer",
  'title': "年轻人的替补",
  'icon': '🪑',
  'weight': 0x3a,
  'stage': "vet",
  'when': function(p){return p["age"]>=0x22&&p["roleRank"]<=0x2;},
  'desc': "更衣室的储物柜贴上了新名字。队里买了个比你小十二岁的年轻人，教练说他需要「比赛时间」。",
  'options': [
    {
        'label': "找教练谈，要个说法",
        'p': function(p){return f(0.45,[[p["guanxi"],45,0.008]],0.2,0.85);},
        'hint': function(p,q){return g(q,"争回出场","撕破脸");},
        'apply': function(p,q,s){return d(q,s)?{'roleDelta':0x2,'guanxi':-0x5,'text':"你把话摆到了明面上。教练给了你三场机会，你抓回了两场。可从那以后，更衣室里的气氛，就怪怪的。"}:{'roleDelta':-0x3,'text':"谈话不欢而散。接下来两个月，你连大名单都没进过。"};}
    },
    {
        'label': "接受现实，当好榜样",
        'hint': "关系+，地位-",
        'apply': function(){return{'guanxi':0x6,'roleDelta':-0x1,'fame':0x2,'text':"你开始以过来人的身份教他：怎么盯人，什么时候该上抢。他进步很快，教练说，队里需要你这种老将。"};}
    }
  ]
}

];
