// auto-generated by split_events.py - edit events here, then run build_events.py





var EVT_youth=[






// ---- idx:338 | youth_route_technique | 技术流转型 ----



{
  'id': "youth_route_technique",
  'title': "技术流转型",
  'icon': '🎯',
  'weight': 0x38,
  'stage': "youth",
  'repeat': 1,
  'when': function(p){
    if(!p["inAcademy"]||p["_typeShiftDone"]||p["playerType"]===11)return false;
    return p["playerType"]===0x0||p["playerType"]===0x1;
  },
  'desc': function(p){
    if(p["playerType"]===0x0)return "你在禁区里一直用速度和跑位找机会，但教练把你叫住：「你的脚下技术比你以为的要好。试试背身拿球，做支点，让队友也参与进来。」他画了一套以你为轴心的进攻套路。";
    return "你习惯在中场组织调度，但训练赛里教练突然把你推到前腰更靠前的位置：「你的传球视野不该只用在中场。往前走一步，用影锋的方式去连接中场和锋线。」";
  },
  'options': [
    {
      'label': "试试看",
      'p': function(p){return f(0.55,[[p["talent"],1,0.25],[p["ovr"],40,0.005]],0.25,0.85);},
      'hint': function(p,q){
        var TN=['射手','组织核心','全能','速度型','支点','影锋'];
        var tgt=p["playerType"]===0x0?0x4:0x5;
        return g(q,"转型成功→"+TN[tgt],"转型失败");
      },
      'apply': function(p,q,s){
        var tgt=p["playerType"]===0x0?0x4:0x5;
        return d(q,s)
          ? {'playerType':tgt,'ovr':0x2,'_typeShiftDone':1,'text':p["playerType"]===0x0
            ?"你试了支点踢法，发现自己背身护球的能力出奇地好。几周后训练赛，你连续扛住两个后卫做球给队友，教练笑着点了点头。"
            :"你往前挪了一步，用影锋的方式拿球、跑位、接应。那种介于前锋和中场之间的自由感，让你踢出了不一样的节奏。"}
          : {'ovr':-0x1,'_typeShiftDone':1,'text':p["playerType"]===0x0
            ?"你试着背身拿球，但身体总是习惯性转身面对球门。教练说：也许时机不对，先放一放。"
            :"你在新位置上站了十分钟，却不知道该往前插还是往回接。教练说：没关系，知道自己不适合什么，也是一种进步。"};
      }
    },
    {
      'label': "坚持自己的风格",
      'hint': "稳一点",
      'apply': function(){return{'ovr':0x1,'_typeShiftDone':1,'text':"你礼貌地告诉教练：谢谢，但我想先把现在的位置踢到极致。教练没说什么，只是在下次训练里多看了你几眼。"};}
    }
  ]
},



// ---- idx:339 | youth_route_speed | 速度型转型 ----



{
  'id': "youth_route_speed",
  'title': "速度型转型",
  'icon': '⚡',
  'weight': 0x38,
  'stage': "youth",
  'repeat': 1,
  'when': function(p){
    if(!p["inAcademy"]||p["_typeShiftDone"]||p["playerType"]===11)return false;
    return p["playerType"]===0x3;
  },
  'desc': function(p){
    return "你一直靠速度生吃对手，但最近几场比赛后卫开始提前卡你身后的空间。教练找你聊：「速度是你的武器，但足球不只有一条路。你要不要试试把速度用在别的地方？」";
  },
  'options': [
    {
      'label': "练射门，当终结者",
      'p': function(p){return f(0.52,[[p["talent"],1,0.3],[p["clean"],50,0.004]],0.22,0.83);},
      'hint': function(p,q){return g(q,"转型成功→射手","转型失败");},
      'apply': function(p,q,s){
        return d(q,s)
          ? {'playerType':0x0,'ovr':0x2,'_typeShiftDone':1,'text':"你开始在训练里加练射门——正脚背、外脚背、凌空。一个月后的队内赛，你接到直塞后没有选择下底，而是内切抽射破门。教练在场边喊：这就对了！"}
          : {'ovr':-0x1,'_typeShiftDone':1,'text':"你练了两周射门，但总是在该射门的时候本能地选择再带一步。教练说：速度型球员转型射门需要时间，也许以后再说。"};
      }
    },
    {
      'label': "练全能，走技术路线",
      'p': function(p){return f(0.48,[[p["talent"],1,0.25],[p["ovr"],45,0.004]],0.20,0.80);},
      'hint': function(p,q){return g(q,"转型成功→全能","转型失败");},
      'apply': function(p,q,s){
        return d(q,s)
          ? {'playerType':0x2,'ovr':0x3,'_typeShiftDone':1,'text':"你开始有意识地放慢节奏，练习在狭小空间里做技术动作。队友惊讶地发现你不只会冲刺了——你开始会用身体护球、用节奏变化过人。教练说：这才是真正的全面。"}
          : {'ovr':0x0,'_typeShiftDone':1,'text':"你试了几次技术动作，但身体总是比脑子快。速度是你的本能，技术需要时间。教练说：先把速度优势发挥到极致，以后再考虑。"};
      }
    }
  ]
},



// ---- idx:340 | youth_route_midfield | 中场转型 ----



{
  'id': "youth_route_midfield",
  'title': "中场转型",
  'icon': '🔄',
  'weight': 0x35,
  'stage': "youth",
  'repeat': 1,
  'when': function(p){
    if(!p["inAcademy"]||p["_typeShiftDone"]||p["playerType"]===11)return false;
    if(p["playerType"]===0x1&&p["posGroup"]==="mid")return true;
    if(p["playerType"]===0x6)return true;
    if(p["playerType"]===0x2&&p["posGroup"]==="mid")return true;
    return false;
  },
  'desc': function(p){
    if(p["playerType"]===0x1)return "你习惯在前场组织进攻，但教练觉得你的防守意识被浪费了：「你的阅读比赛能力很强，如果退后一步踢B2B，覆盖整个中场，你的价值会更大。」";
    if(p["playerType"]===0x6)return "你满场飞奔覆盖两个禁区，但教练觉得你可以更专注：「与其到处补位，不如退一步当铁腰。把防守做到极致，让队友放心往前冲。」";
    return "你在中场踢得四平八稳，但教练觉得你有更大的潜力：「你的能力很全面，但全面有时候意味着没有特点。试试组织核心，把你的视野和传球用到极致。」";
  },
  'options': [
    {
      'label': "试试看",
      'p': function(p){
        var base=p["playerType"]===0x7?0.50:0.52;
        return f(base,[[p["talent"],1,0.28],[p["ovr"],45,0.004]],0.22,0.84);
      },
      'hint': function(p,q){
        var TN=['射手','组织核心','全能','速度型','支点','影锋','B2B','铁腰','边后卫','自由人','铁卫','门将'];
        var tgt=p["playerType"]===0x1?0x6:p["playerType"]===0x6?0x7:0x1;
        return g(q,"转型成功→"+TN[tgt],"转型失败");
      },
      'apply': function(p,q,s){
        var tgt=p["playerType"]===0x1?0x6:p["playerType"]===0x6?0x7:0x1;
        return d(q,s)
          ? {'playerType':tgt,'ovr':0x2,'_typeShiftDone':1,'text':p["playerType"]===0x1
            ?"你退后一步，开始用防守球员的方式思考。以前你只想着怎么传最后一传，现在你先想怎么断球再组织反击。几场比赛后，教练说：你让我想起了年轻时的皮尔洛。"
            :p["playerType"]===0x6
            ?"你站在后卫线前面，像一道屏障。以前你满场飞奔，现在你专注一件事：把球断下来，交给该交的人。三场比赛零失球，教练说：这才叫铁腰。"
            :"你开始用组织核心的方式踢球——拿球、观察、分球。队友渐渐习惯了在你脚下等球，因为他们知道你能看到他们看不到的空当。"}
          : {'ovr':-0x1,'_typeShiftDone':1,'text':"你试了新位置，但身体总是往原来的位置跑。教练说：也许时机不对，先放一放。"};
      }
    },
    {
      'label': "坚持自己的风格",
      'hint': "稳一点",
      'apply': function(){return{'ovr':0x1,'_typeShiftDone':1,'text':"你告诉教练：我现在的位置还没踢明白，不想分心。教练点点头，没再提。"};}
    }
  ]
},



// ---- idx:349 | youth_route_defender | 防守线转型 ----



{
  'id': "youth_route_defender",
  'title': "防守线转型",
  'icon': '🛡️',
  'weight': 0x35,
  'stage': "youth",
  'repeat': 1,
  'when': function(p){
    if(!p["inAcademy"]||p["_typeShiftDone"]||p["playerType"]===11)return false;
    return p["playerType"]===0x8||p["playerType"]===0x9||p["playerType"]===0x10||(p["playerType"]===0x3&&p["posGroup"]==="def");
  },
  'desc': function(p){
    if(p["playerType"]===0x8)return "你在边路攻防两端都很活跃，但教练觉得你的身体条件更适合踢中卫：「你有速度、有对抗、有阅读比赛的能力。站到中间来，当一道墙。」";
    if(p["playerType"]===0x9)return "你踢自由人习惯拖后扫荡，但教练觉得你可以更激进：「你有传球能力，为什么不试试铁卫？带球往前走，从后场组织进攻。」";
    if(p["playerType"]===0x10)return "你是中卫线上最稳的一环，但教练觉得你可以换个思路：「你的位置感很好，但速度也不差。试试自由人，给自己更多自由。」";
    return "你踢防守位置靠速度补位，但教练觉得你的全面性可以发挥在中卫：「边后卫是你的起点，但不是终点。到中间来，成为后防核心。」";
  },
  'options': [
    {
      'label': "试试看",
      'p': function(p){return f(0.50,[[p["talent"],1,0.3],[p["ovr"],45,0.004]],0.20,0.82);},
      'hint': function(p,q){
        var TN=['射手','组织核心','全能','速度型','支点','影锋','B2B','铁腰','边后卫','自由人','铁卫','门将'];
        var tgt=p["playerType"]===0x8?0x10:p["playerType"]===0x9?0x10:p["playerType"]===0x10?0x9:0x10;
        return g(q,"转型成功→"+TN[tgt],"转型失败");
      },
      'apply': function(p,q,s){
        var tgt=p["playerType"]===0x8?0x10:p["playerType"]===0x9?0x10:p["playerType"]===0x10?0x9:0x10;
        return d(q,s)
          ? {'playerType':tgt,'ovr':0x2,'_typeShiftDone':1,'text':p["playerType"]===0x8
            ?"你站到了中卫的位置上，第一次感受到和边路完全不同的节奏——没有边线可以依靠，背后就是球门。但你很快适应了，用速度和对抗守护禁区。教练说：你天生就是踢中卫的料。"
            :p["playerType"]===0x9
            ?"你开始带球往前走，用自由人的视野组织后场进攻。第一次长传精准找到前锋脚下时，全场都安静了一秒——然后教练在场边鼓掌。"
            :p["playerType"]===0x10
            ?"你退后一步，站在后卫线最后面。以前你贴身盯人，现在你扫荡、预判、指挥。那种掌控全局的感觉，让你踢得比以前从容。"
            :"你站到了中卫的位置，用速度弥补经验的不足。几次关键时刻的回追铲断，让教练对你刮目相看。"}
          : {'ovr':-0x1,'_typeShiftDone':1,'text':"你试了新位置，但总是不自觉地跑到原来的位置上。教练说：也许时机不对，先放一放。"};
      }
    },
    {
      'label': "坚持自己的风格",
      'hint': "稳一点",
      'apply': function(){return{'ovr':0x1,'_typeShiftDone':1,'text':"你告诉教练：我现在的位置还没踢明白，不想分心。教练点点头，没再提。"};}
    }
  ]
},



// ---- idx:350 | youth_route_playmaker | 组织核心深化 ----



{
  'id': "youth_route_playmaker",
  'title': "组织核心深化",
  'icon': '🧠',
  'weight': 0x32,
  'stage': "youth",
  'repeat': 1,
  'when': function(p){
    if(!p["inAcademy"]||p["_typeShiftDone"]||p["playerType"]===11)return false;
    return p["playerType"]===0x1&&p["posGroup"]==="att";
  },
  'desc': function(p){
    return "你在前场组织进攻，但教练觉得你的射门能力被浪费了：「你的传球视野是一流的，但你站在影锋的位置上却不射门，等于浪费了一半的威胁。往前挪一步，学会在关键时刻自己来。」";
  },
  'options': [
    {
      'label': "练射门，当影锋",
      'p': function(p){return f(0.52,[[p["talent"],1,0.28],[p["clean"],50,0.004]],0.22,0.83);},
      'hint': function(p,q){return g(q,"转型成功→影锋","转型失败");},
      'apply': function(p,q,s){
        return d(q,s)
          ? {'playerType':0x5,'ovr':0x3,'_typeShiftDone':1,'text':"你开始在训练里加练射门——禁区前沿的抽射、禁区里的抢点。几周后的比赛，你接到直塞后没有选择传球，而是晃过门将推射空门。教练在场边喊：这就是影锋！"}
          : {'ovr':0x1,'_typeShiftDone':1,'text':"你试了几次射门，但总是在该射门的时候选择传球。教练说：射门需要本能，不是技术问题，是心态问题。也许以后再说。"};
      }
    },
    {
      'label': "坚持组织者角色",
      'hint': "稳一点",
      'apply': function(){return{'ovr':0x1,'_typeShiftDone':1,'text':"你告诉教练：我的价值在于传球，不是射门。教练说：好吧，那你把传球练到极致。"};}
    }
  ]
},



// ---- idx:343 | youth_route_late | 最后机会 ----



{
  'id': "youth_route_late",
  'title': "最后机会",
  'icon': '⏰',
  'weight': 0x30,
  'stage': "youth",
  'repeat': 1,
  'when': function(p){
    if(!p["inAcademy"]||p["_typeShiftDone"]||p["playerType"]===11||p["age"]<17)return false;
    var pool={'att':[0x0,0x1,0x2,0x3,0x4,0x5],'mid':[0x1,0x2,0x5,0x6,0x7],'def':[0x2,0x3,0x8,0x9,0xa]};
    var pp=pool[p["posGroup"]];
    return pp&&pp["indexOf"](p["playerType"])>=0;
  },
  'desc': function(p){
    return "离毕业考核只剩最后几个月。你偶然看到一线队的比赛录像，某个球员的踢法让你心动了——也许你也能那样踢。";
  },
  'options': [
    {
      'label': "大胆改变",
      'p': function(p){return f(0.45,[[p["talent"],1,0.35],[p["age"],18,-0.04]],0.18,0.80);},
      'hint': function(p,q){
        var TN=['射手','组织核心','全能','速度型','支点','影锋','B2B','铁腰','边后卫','自由人','铁卫','门将'];
        var endgame={0x0:0x4,0x1:0x5,0x2:0x9,0x3:0x0,0x4:0x0,0x5:0x1,0x6:0x7,0x7:0x6,0x8:0xa,0x9:0xa,0xa:0x9};
        var tgt=endgame[p["playerType"]];
        return tgt!=null?g(q,"涅槃重生→"+TN[tgt],"为时已晚"):g(q,"涅槃重生","为时已晚");
      },
      'apply': function(p,q,s){
        var endgame={0x0:0x4,0x1:0x5,0x2:0x9,0x3:0x0,0x4:0x0,0x5:0x1,0x6:0x7,0x7:0x6,0x8:0xa,0x9:0xa,0xa:0x9};
        var tgt=endgame[p["playerType"]];
        if(tgt==null)return{'ovr':0x1,'_typeShiftDone':1,'text':"你想改变，但不知道该往哪个方向走。最后几个月就这样过去了。"};
        return d(q,s)
          ? {'playerType':tgt,'ovr':0x3,'_typeShiftDone':1,'text':"最后几个月你像变了个人，每天加练到最晚。毕业考核那天，你用全新的方式完成了一次教科书般的进球/防守/组织。教练在评估表上写下：此人上限不止于此。"}
          : {'ovr':-0x2,'_typeShiftDone':1,'text':"改变来得太晚了。身体习惯已经定型，新学的东西和旧的互相打架。考核日你表现平平，教练叹了口气：可惜了，早点下决心就好了。"};
      }
    },
    {
      'label': "留到职业赛场再说",
      'hint': "以后再变",
      'apply': function(){return{'ovr':0x1,'_typeShiftDone':1,'text':"你把那个念头压了下去。也许等到了职业赛场，有了更好的教练和队友，再做改变也不迟。至少现在，先把基础打牢。"};}
    }
  ]
},

// ---- idx:146 | youth_do | 宿舍熄灯以后 ----




{
  'id': "youth_do"+'rm',
  'title': "宿舍熄灯以后",
  'icon': "🛏️",
  'weight': 0x37,
  'stage': "youth",
  'repeat': 1,
  'when': function(p){
return p["inAcadem"+'y'];
},




  'desc': "同屋的几个人，每晚打游戏到凌晨两点。你六点半要出早操。",
  'options': [
    {
        'label': "自己去走廊睡",
        'hint': "能力+3，被叫怪"+'人',
        'apply': function(){
return{'ovr':0x3,'guanxi':-0x8,'text':"你抱着被子，在走廊尽头睡了三个月。他们叫你「圣人」，语气不太友善。"};
}
    },
    {
        'p': function(p){return f(0.5,[[p["guanxi"],45,0.008]],0.2,0.9);
},
        'label': "跟着熬",
        'hint': function(p,q){return g(q,'合群','早操废了');
},
        'apply': function(p,q,s){
return d(q,s)?{'guanxi':0x8,'fame':0x3,'text':"那几个，后来成了你在这行最铁的朋友。有两个，第二年就回家了。"}:{'ovr':-0x2,'roleDelta':-0x1,'text':"连着两个月，早操你都垫底。教练说你眼睛里没有光。"};
}
    }
  ]
},










// ---- idx:147 | youth_ex | ? ----




{
  'id': "youth_ex"+'am',
  'title': '中考',
  'icon': '📚',
  'weight': 0x34,
  'stage': "youth",
  'cn': !0x0,
  'when': function(p){
return p["inAcadem"+'y'];
},




  'desc': "文化课老师说，你还有希望考上普高。教练说，这个节骨眼上请假，就是放弃。",
  'options': [
    {
        'label': "回去考",
        'hint': "能力-2，多一条"+'路',
        'apply': function(){
return{'ovr':-0x2,'degree':!0x0,'clean':0x4,'text':"你请了六周假。考上了，也确确实实落下了一个夏天的训练。"};
}
    },
    {
        'label': "不考了",
        'hint': "能力+3，没有退"+'路',
        'apply': function(){
return{'ovr':0x3,'text':"那个夏天，你是在训练场上过完的。班主任后来发来一条短信，你没有回。"};
}
    }
  ]
},










// ---- idx:148 | youth_co | 教练的心头肉 ----




{
  'id': "youth_co"+"ach_fav",
  'title': "教练的心头肉",
  'icon': '🫶',
  'weight': 0x32,
  'stage': "youth",
  'when': function(p){
return p["inAcadem"+'y'];
},




  'desc': "梯队教练明显偏爱另一个孩子：新位置先让他试，输了球从不挨骂。",
  'options': [
    {
        'p': function(p){return f(0.5,[[p["guanxi"],45,0.008]],0.2,0.9);
},
        'label': "找教练谈",
        'hint': function(p,q){return g(q,'被看见','被记恨');
},
        'apply': function(p,q,s){
return d(q,s)?{'roleDelta':0x2,'ovr':0x2,'text':"他愣了一下，说没想到你会来说这个。下一场，你首发。"}:{'roleDelta':-0x2,'guanxi':-0xa,'text':"他说，年轻人要沉住气。从那以后，你连替补名单都进得少了。"};
}
    },
    {
        'label': "用球说话",
        'hint': "能力+3，慢",
        'apply': function(){
return{'ovr':0x3,'text':"整整两年，你把训练赛当正赛踢。教练换人的那天，你的名字排在第一个。"};
}
    }
  ]
},










// ---- idx:149 | youth_fi | 第一份职业合同 ----




{
  'id': "youth_fi"+"rst_cont"+"ract",
  'title': "第一份职业合同",
  'icon': '✒️',
  'weight': 0x3a,
  'stage': "youth",
  'when': function(p){
return p["inAcadem"+'y'];
},




  'desc': "俱乐部把合同放在"+"桌上：五年，工资"+"很低，违约金写得"+"很高。",
  'options': [
    {
        'label': "签字",
        'hint': "钱少，位置稳",
        'apply': function(){
return{'money':0x1e,'roleDelta':0x1,'text':"你爸妈坐在旁边，一直点头。你后来才知道，那个违约金意味着什么。"};
}
    },
    {
        'p': function(p){return f(0.6,[[p["guanxi"],45,0.008]],0.2,0.9);
},
        'label': "让家里找人看看",
        'hint': function(p,q){return g(q,'改好了','俱乐部翻脸');
},
        'apply': function(p,q,s){
return d(q,s)?{'money':0x3c,'clean':0x4,'text':"违约金砍掉一半，年限缩到三年。经理签字的时候，脸色不好看。"}:{'roleDelta':-0x2,'guanxi':-0xa,'text':"俱乐部说，不签就先下二队。你在二队待了一年半。"};
}
    }
  ]
},










// ---- idx:150 | youth_ag | 第一个经纪人 ----




{
  'id': "youth_ag"+"ent",
  'title': "第一个经纪人",
  'icon': '🤝',
  'weight': 0x34,
  'stage': "youth",
  'when': function(p){
return p["inChina"];
},




  'desc': "有人在训练场外等你，说能把你送出国，条件是先签五年的独家。",
  'options': [
    {
        'p': function(p){return f(0.5,[[p["guanxi"],45,0.008]],0.2,0.9);
},
        'label': "签字",
        'hint': function(p,q){return g(q,'真有门路','被套牢');
},
        'apply': function(p,q,s){
return d(q,s)?{'ovr':0x2,'fame':0x8,'text':"他确实带你去了两次海外试训。虽然没成，可你知道了差距在哪里。"}:{'money':-0x28,'roleDelta':-0x1,'text':"五年里，他只做了一件事：拦下所有别人递给你的机会。"};
}
    },
    {
        'label': '不签',
        'hint': "无变化",
        'apply': function(){
return{'text':"你说要先问问家里。他留下张名片，后来再没出现过。"};
}
    }
  ]
},










// ---- idx:151 | youth_lo | 借去中乙 ----




{
  'id': "youth_lo"+"an_lower",
  'title': "借去中乙",
  'icon': '🚌',
  'weight': 0x32,
  'stage': "youth",
  'when': function(p){
return p["inChina"];
},




  'desc': "俱乐部想把你租到中乙踢一年。那边条件差得可以，但一整年你都能有球踢。",
  'options': [
    {
        'label': "就去",
        'hint': "能力+5，苦",
        'apply': function(){
return{'ovr':0x3,'money':-0xa,'fame':0x4,'text':"客场十小时大巴，看台是水泥台阶。二十八场踢完，成人比赛的节奏，已经长在了你身上。"};
}
    },
    {
        'p': function(p){return f(0.5,[[p["ovr"],60,0.008]],0.2,0.9);
},
        'label': "留在梯队",
        'hint': function(p,q){return g(q,'熬出头','白熬');
},
        'apply': function(p,q,s){
return d(q,s)?{'ovr':0x2,'roleDelta':0x1,'text':"你在预备队联赛打满一整年。年底，一线队的名单里有了你的名字。"}:{'ovr':-0x1,'roleDelta':-0x1,'text':"预备队一年到头，打不了十场球。二十岁那年，你还没踢过一场正式比赛。"};
}
    }
  ]
},










// ---- idx:152 | youth_tr | 海外试训 ----




{
  'id': "youth_tr"+"ial_abro"+'ad',
  'title': "海外试训",
  'icon': '🎫',
  'weight': 0x30,
  'stage': "youth",
  'when': function(p){
return p["inChina"]&&p["inAcadem"+'y'];
},




  'desc': "有个去欧洲试训的机会：中游俱乐部，两周。机票和食宿，自己掏。",
  'options': [
    {
        'p': function(p){return f(0.6,[[p["talent"],1,0.4]],0.2,0.9);
},
        'label': "砸锅卖铁去",
        'hint': function(p,q){return g(q,'眼界大开','白跑');
},
        'apply': function(p,q,s){
return d(q,s)?{'money':-0x32,'ovr':0x4,'fame':0x6,'text':"两周过去，一份合同没拿到。可你第一次看清，同龄人能把球跑成什么样。回来以后，你练得像换了个人。"}:{'money':-0x32,
'ovr':-0x1,'text':"两周里你只上了三次分组对抗，其余时间都泡在健身房。回程的飞机上，你一路没说话。"};
}
    },
    {
        'label': '不去',
        'hint': "无变化",
        'apply': function(){
return{'text':"这笔钱，家里凑不出来。同去的那个孩子，后来去了荷兰。"};
}
    }
  ]
},










// ---- idx:153 | youth_he | 身高不够 ----




{
  'id': "youth_he"+"ight",
  'title': "身高不够",
  'icon': '📐',
  'weight': 0x2d,
  'stage': "youth",
  'when': function(p){
return p["inAcadem"+'y'];
},




  'desc': "选材表上，你的名字被划了一道：身高预测不达标。有人建议打生长激素。",
  'options': [
    {
        'p': function(p){return f(0.5,[[p["clean"],70,0.008]],0.2,0.9);
},
        'label': "打激素",
        'hint': function(p,q){return g(q,'长起来了','出问题');
},
        'apply': function(p,q,s){
return d(q,s)?{'ovr':0x4,'clean':-0xa,'money':-0x28,'text':"两年后，你长到了一米八三。那两年的每一针，你都记得当时的疼。"}:{'ovr':-0x3,'clean':-0xe,'money':-0x28,
'text':"个子没怎么长，体检倒查出了别的问题。那盒药，你后来自己扔了。"};
}
    },
    {
        'label': '不打',
        'hint': "能力+2，靠别的"+'吃饭',
        'apply': function(){
return{'ovr':0x2,'clean':0x4,'text':"你把重心、启动和"+"脑子练到了极致。"+"教练说你是队里最"+"不像小个子的小个"+'子。'};
}
    }
  ]
},










// ---- idx:272 | youth_night | 熄灯后的球场 ----




{
  'id': "youth_night",
  'title': "熄灯后的球场",
  'icon': '🌙',
  'weight': 0x34,
  'repeat': 1,
  'stage': "youth",
  'when': function(p){return p["inAcademy"];
},




  'desc': "熄灯前十分钟，你抱着球溜回训练场。路灯刚好照到禁区线——够练一百脚。",
  'options': [
    {
        'label': "加练到门卫来赶",
        'p': function(p){return f(0.35,[[p["talent"],1,0.25]],0.2,0.65);
},
        'hint': function(p,q){return g(q,"球感大涨","白练一夜");
},
        'apply': function(p,q,s){return d(q,s)?{'talent':0.05,'text':"第一百脚，落点终于贴地。门卫的脚步声响起时，你刚好收球。"}:{'text':"第二天晨训你站着都想睡。教练盯着你看了三秒，什么也没说。"};
}
    },
    {
        'label': "早点睡",
        'hint': "能力+1",
        'apply': function(){return{'ovr':0x1,'text':"睡眠也是训练的一部分。第二天状态正好，教练多给了你一组对抗。"};
}
    }
  ]
},










// ---- idx:273 | youth_watch | 高手的慢动作 ----




{
  'id': "youth_watch",
  'title': "高手的慢动作",
  'icon': '🎬',
  'weight': 0x30,
  'repeat': 1,
  'stage': "youth",
  'when': function(p){return p["inAcademy"];
},




  'desc': "录像室循环放着一球：接球、转身、抹过两个人。教练说，看懂这一下，比练十脚有用。",
  'options': [
    {
        'label': "重看二十遍",
        'p': function(p){return f(0.4,[[p["talent"],1,0.25]],0.2,0.7);
},
        'hint': function(p,q){return g(q,"悟到了","走神了");
},
        'apply': function(p,q,s){return d(q,s)?{'talent':0.05,'ovr':0x1,'text':"第二十遍，你终于看清那只脚是怎么踩的。第二天训练你照着来了一次，教练没说话，但点了点头。"}:{'ovr':-0x1,
'text':"看到第十遍你就走了神。第二天教练抽查，你一句话答不上来。"};
}
    },
    {
        'label': "去操场练",
        'hint': "能力+2",
        'apply': function(){return{'ovr':0x2,'text':"看不如练。你把录像时间换成了两组变向，教练没拦。"};
}
    }
  ]
},










// ---- idx:274 | youth_ballfeel | 睡前颠球 ----




{
  'id': "youth_ballfeel",
  'title': "睡前颠球",
  'icon': '⚽',
  'weight': 0x2e,
  'repeat': 1,
  'stage': "youth",
  'when': function(p){return p["inAcademy"];
},




  'desc': "宿舍熄灯，你枕边放着一只球。室友翻身时，你悄悄下了床。",
  'options': [
    {
        'label': "下床颠两百个",
        'p': function(p){return f(0.3,[[p["talent"],1,0.3]],0.15,0.6);
},
        'hint': function(p,q){return g(q,"球感大涨","差点吵醒室友");
},
        'apply': function(p,q,s){return d(q,s)?{'talent':0.06,'text':"两百个后你停住了。那种球贴着脚的感觉，你第一次不靠蒙。"}:{'text':"第一百零三个，球滚进了床底。你趴着捞球，被室友的夜灯照了个正着。"};
}
    },
    {
        'label': "躺平",
        'hint': "没有变化",
        'apply': function(){return{'text':"你选择好好睡觉。梦里，你在决赛补时打进了致胜球。"};
}
    }
  ]
},










// ---- idx:275 | youth_skills | 基本功补课 ----




{
  'id': "youth_skills",
  'title': "基本功补课",
  'icon': '🦶',
  'weight': 0x38,
  'repeat': 1,
  'stage': "youth",
  'when': function(p){return p["inAcademy"];
},




  'desc': "青训教练把你划进了补课名单：左脚传球、一脚出球、护球转身，每周三次。",
  'options': [
    {
        'label': "全部按要求来",
        'p': function(p){return f(0.5,[[p["talent"],1,0.3]],0.3,0.75);
},
        'hint': function(p,q){return g(q,"能力+3","越练越别扭");
},
        'apply': function(p,q,s){return d(q,s)?{'ovr':0x3,'text':"补课结束那周，对抗赛你被放进了首发。一脚出球，全队节奏都顺了。"}:{'ovr':-0x1,'text':"越练越别扭，左脚那一脚至今还是歪的。你把这归咎于补课时间不够。"};
}
    },
    {
        'label': "找教练改单练",
        'hint': "能力+1",
        'apply': function(){return{'ovr':0x1,'text':"你提了意见，教练改了单子。一对一的那几天，你进步明显。"};
}
    }
  ]
},










// ---- idx:276 | youth_rainshoot | 雨后的球场 ----




{
  'id': "youth_rainshoot",
  'title': "雨后的球场",
  'icon': '🌧️',
  'weight': 0x34,
  'repeat': 1,
  'stage': "youth",
  'when': function(p){return p["inAcademy"];
},




  'desc': "雨停了，训练场积水还没干。管理员刚关灯，你又翻了过去。没人跟你抢空门，只有水面上自己的倒影。",
  'options': [
    {
        'label': "练到看不清倒影",
        'p': function(p){return f(0.3,[[p["talent"],1,0.3]],0.15,0.6);
},
        'hint': function(p,q){return g(q,"天赋+","感冒一场");
},
        'apply': function(p,q,s){return d(q,s)?{'talent':0.06,'text':"湿球比干球难控，你就专挑它练。半年后教练说，你脚下比同龄人多一点东西。"}:{'ovr':-0x1,'text':"第二天你开始发烧，队医给你开了三天的药。积水的草地，到底还是凉。"};
}
    },
    {
        'label': "回去泡个热水澡",
        'hint': "没有变化",
        'apply': function(){return{'text':"你站在窗边看了一会儿雨，转身回了宿舍。第二天训练，你状态正好。"};
}
    }
  ]
},










// ---- idx:277 | youth_turnaround | 转身那一课 ----




{
  'id': "youth_turnaround",
  'title': "转身那一课",
  'icon': '🔄',
  'weight': 0x36,
  'repeat': 1,
  'stage': "youth",
  'when': function(p){return p["inAcademy"];
},




  'desc': "教练给你单独开小灶：背身拿球，怎么把防守队员晃开。他管它叫「转身那一课」。",
  'options': [
    {
        'label': "课后自己加量",
        'p': function(p){return f(0.5,[[p["talent"],1,0.3]],0.3,0.75);
},
        'hint': function(p,q){return g(q,"能力+4","练岔了");
},
        'apply': function(p,q,s){return d(q,s)?{'ovr':0x4,'text':"那阵子你连吃饭都在想转身的时机。期末评语里，教练写了一句：会自己加量。"}:{'ovr':-0x1,'text':"加量加到用力过猛，那两天转身总是慢半拍。教练让你先歇够了再来。"};
}
    },
    {
        'label': "按时下课",
        'hint': "能力+1",
        'apply': function(){return{'ovr':0x1,'text':"你把时间留给比赛。周末的队内对抗里，你试着用了一下，居然成了。"};
}
    }
  ]
},










// ---- idx:278 | youth_vice | 熄灯以后的烟火 ----




{
  'id': "youth_vice",
  'title': "熄灯以后的烟火",
  'icon': '🚬',
  'weight': 0x32,
  'repeat': 1,
  'stage': "youth",
  'when': function(p){return p["inAcademy"];
},




  'desc': "熄灯后，同屋的孩子翻下床，掏出一包烟，挨个递。轮到你时，他停了一下，看你。",
  'options': [
    {
        'label': "摇头",
        'hint': "清白+，跟他们有点远了",
        'apply': function(){return{'clean':0x6,'guanxi':-0x3,'text':"你摇头，他没再劝。往后那半年，分组对抗你总被分到另一个组。"};
}
    },
    {
        'label': "接过来，没点",
        'hint': "关系没变，心里那关自己过",
        'apply': function(){return{'guanxi':0x5,'clean':-0x3,'text':"你接过来放在床头，谁也没逼你点。可你知道，这条线是你自己划的。"};
}
    },
    {
        'label': "陪他们出去抽",
        'hint': "关系+，清白受损",
        'apply': function(){return{'guanxi':0x8,'clean':-0x6,'text':"你跟着去了阳台。烟味呛得你直咳嗽，他们笑，你也笑。"};
}
    }
  ]
},










// ---- idx:279 | youth_selfdrill | 一个人练到天黑 ----




{
  'id': "youth_selfdrill",
  'title': "一个人练到天黑",
  'icon': '🌆',
  'weight': 0x32,
  'repeat': 1,
  'stage': "youth",

  'when': function(p){return p["inAcademy"];
},



  'desc': "下午的课结束得早。别人去冲凉，你拎着一袋球又回了场。管理员把钥匙给你时，多看了你一眼。",
  'options': [
    {
        'label': "练到天黑",
        'p': function(p){return f(0.25,[[p["talent"],1,0.35]],0.12,0.6);
},
        'hint': function(p,q){return g(q,"天赋+","白练，但心里踏实");
},
        'apply': function(p,q,s){return d(q,s)?{'talent':0.07,'text':"天色暗下来，你反而更准了。管理员来催第三次的时候，你已经能闭着眼找到球门。"}:{'text':"天黑了，球都看不清，你只靠感觉踢。没进步，但也不亏。"};
}
    },
    {
        'label': "跟着大家去冲凉",
        'hint': "能力+1",
        'apply': function(){return{'ovr':0x1,'text':"你把球放回筐里，去冲凉了。热水冲下来那一下，你觉得明天再练也一样。"};
}
    }
  ]
},


// ---- idx:344 | youth_elite | 顶级青训的洗礼 ----




{
  'id': "youth_elite",
  'title': "顶级青训的洗礼",
  'icon': '🏆',
  'weight': 0x38,
  'repeat': 1,
  'stage': "youth",
  'when': function(p){
return p["inAcadem"+'y']&&p["clubRep"]>=5;
},




  'desc': "你站在全世界最贵的青训基地门口，旁边是未来可能身价过亿的同龄人。这里的每个人都是各自国家的天才，但最终能进一线队的，整个梯队不超过三个人。",
  'options': [
    {
        'label': "和天才们拼一把",
        'p': function(p){return f(0.35,[[p["talent"],1,0.4],[p["ovr"],55,0.008]],0.15,0.80);},
        'hint': function(p,q){return g(q,"站稳脚跟","被淹没了");},
        'apply': function(p,q,s){return d(q,s)?{'ovr':0x4,'talent':0.04,'text':"训练赛你连过两人送出助攻，旁边的球探在本子上写下你的名字。教练说：你证明了自己配得上这个基地。"}:{'ovr':-0x2,'text':"第一周你就意识到差距——这里的替补都比你见过的主力强。你在对抗赛里被断了七次，晚上躺在宿舍想：天才和天才之间，也隔着一道墙。"};}
    },
    {
        'label': "先扎实基本功",
        'hint': "能力+2，稳",
        'apply': function(){return{'ovr':0x2,'text':"你没急着表现，先花三个月把每一项基础数据都练到位。教练在报告里写：此人态度端正，潜力待开发。"};}
    }
  ]
},










// ---- idx:345 | youth_topclub | 豪门梯队的日常 ----




{
  'id': "youth_topclub",
  'title': "豪门梯队的日常",
  'icon': '⭐',
  'weight': 0x36,
  'repeat': 1,
  'stage': "youth",
  'when': function(p){
return p["inAcadem"+'y']&&p["clubRep"]>=4&&p["clubRep"]<5;
},




  'desc': "每周三下午，一线队教练会来看梯队训练。他站在场边的时候，所有人的跑动距离都会多出半公里。你知道，被他记住名字，可能比进十个球都重要。",
  'options': [
    {
        'label': "抓住每次曝光机会",
        'p': function(p){return f(0.45,[[p["talent"],1,0.3],[p["ovr"],50,0.006]],0.22,0.82);},
        'hint': function(p,q){return g(q,"被一线队注意到","太紧张了");},
        'apply': function(p,q,s){return d(q,s)?{'ovr':0x3,'fame':0x3,'text':"那天训练赛你打进一粒倒钩，一线队教练走过来拍了拍你肩膀。第二天，你出现在了一线队合练名单上。"}:{'ovr':-0x1,'text':"你太想表现，动作全变形了。教练看完就走了，连名单都没抄。晚上你想：机会来了，但没接住。"};}
    },
    {
        'label': "按自己节奏踢",
        'hint': "能力+1，稳",
        'apply': function(){return{'ovr':0x1,'text':"你没刻意表现，只是做了该做的事。一周后教练在报告里加了一行：此人沉稳，可观察。"};}
    }
  ]
},










// ---- idx:346 | youth_contender | 争冠队的青训氛围 ----




{
  'id': "youth_contender",
  'title': "争冠队的青训氛围",
  'icon': '🔥',
  'weight': 0x34,
  'repeat': 1,
  'stage': "youth",


  'when': function(p){
return p["inAcadem"+'y']&&p["clubRep"]>=3&&p["clubRep"]<4;
},


  'desc': "这支球队每年都在争冠，梯队的压力也不小：每月一次的内部考核，排名末位的直接降级到更低的梯队。你不想成为那个被刷下去的人。",


  'options': [
    {
        'label': "用训练赛成绩说话",
        'p': function(p){return f(0.5,[[p["talent"],1,0.3],[p["ovr"],48,0.005]],0.28,0.82);},
        'hint': function(p,q){return g(q,"排名上升","原地踏步");},
        'apply': function(p,q,s){return d(q,s)?{'ovr':0x3,'text':"连续五场训练赛你都有进球或助攻，月度考核从第十二升到第三。教练说：这就是竞争的意义。"}:{'ovr':-0x1,'text':"你拼了命，但对手也在拼。考核排名从第十二掉到第十五，再差一步就要去B队了。那种压力，让你第一次失眠。"};}
    },
    {
        'label': "和队友搞好关系",
        'hint': "关系+，稳",
        'apply': function(){return{'guanxi':0x6,'text':"你帮队友捡球、递水、主动加练配合。大家觉得你这人不错，训练赛里也愿意给你传球。"};}
    }
  ]
},










// ---- idx:347 | youth_midtable | 中游球队的青训日子 ----




{
  'id': "youth_midtable",
  'title': "中游球队的青训日子",
  'icon': '🌱',
  'weight': 0x32,
  'repeat': 1,
  'stage': "youth",


  'when': function(p){
return p["inAcadem"+'y']&&p["clubRep"]>=2&&p["clubRep"]<3;
},


  'desc': "这里没有顶级的设施，也没有一线队的聚光灯。但教练说了一句话让你记住：中游球队的青训，靠的是自己给自己加戏。没人盯着你，所以你要自己盯着自己。",


  'options': [
    {
        'label': "每天多练一小时",
        'p': function(p){return f(0.55,[[p["talent"],1,0.25],[p["ovr"],45,0.004]],0.3,0.82);},
        'hint': function(p,q){return g(q,"能力见长","没太大变化");},
        'apply': function(p,q,s){return d(q,s)?{'ovr':0x3,'text':"三个月后你的体测数据排进了梯队前五。教练在周会上表扬了你，虽然只有一句话，但你知道那是真的。"}:{'ovr':0x1,'text':"你多练了一小时，但效果不明显。教练说：方向对了，量也够了，再等等。"};}
    },
    {
        'label': "多看比赛录像",
        'hint': "天赋+",
        'apply': function(){return{'talent':0.03,'text':"你把每周的训练录像看了三遍，笔记记了厚厚一本。虽然身体进步不大，但脑子比以前清楚多了。"};}
    }
  ]
},










// ---- idx:348 | youth_grassroots | 小球会的青训路 ----




{
  'id': "youth_grassroots",
  'title': "小球会的青训路",
  'icon': '💪',
  'weight': 0x30,
  'repeat': 1,
  'stage': "youth",


  'when': function(p){
return p["inAcadem"+'y']&&p["clubRep"]<=1;
},


  'desc': "训练场是公共的，周末还有市民来踢野球。教练身兼三职，梯队就二十来人。但正因如此，你几乎每场训练赛都能踢满全场——在大俱乐部，这不可能。",


  'options': [
    {
        'label': "珍惜每次上场机会",
        'p': function(p){return f(0.6,[[p["talent"],1,0.2],[p["ovr"],42,0.003]],0.35,0.85);},
        'hint': function(p,q){return g(q,"实力提升","机会太少");},
        'apply': function(p,q,s){return d(q,s)?{'ovr':0x4,'text':"一个赛季你打了三十场全场，这在大俱乐部的梯队根本不敢想。教练说：你是这里最努力的孩子，别小看自己。"}:{'ovr':0x2,'text':"训练赛你表现不错，但正式比赛的机会太少了。教练说：别急，你的水平会被人看到的。"};}
    },
    {
        'label': "加练个人技术",
        'hint': "天赋+",
        'apply': function(){return{'talent':0.04,'text':"每天训练结束后你对着墙练传球，虽然条件简陋，但你比任何人都珍惜每一脚球。"};}
    }
  ]
}

];




